ROSE: RangeMapNumeric< R, T > Class Template Reference
RangeMapNumeric< R, T > Class Template Reference
Description
template<class R, class T>
class RangeMapNumeric< R, T >
Scalar value type for a RangeMap.
Values can be merged if they compare equal; splitting a value is done by copying it. The removing() and truncate() methods are no-ops. See the RangeMapVoid class for full documentation.
Definition at line 607 of file rangemap.h.
#include <roseSupport/rangemap.h>
Public Types
typedef R Range
typedef T Value
Public Member Functions
RangeMapNumeric ()
Constructor creates object whose underlying value is zero.
RangeMapNumeric (Value v)
Constructor creates object with specified value.
void removing (const Range &my_range)
Called when this value is being removed from a RangeMap.
void truncate (const Range &my_range, const typename Range::Value &new_end)
Called when removing part of a value from a RangeMap.
bool merge (const Range &my_range, const Range &other_range, RangeMapNumeric other_value)
Called to merge two RangeMap values.
RangeMapNumeric split (const Range &my_range, typename Range::Value new_end)
Split a RangeMap value into two parts.
void set (Value v)
Accessor for the value actually stored here.
virtual Value get () const
Accessor for the value actually stored here.
void print (std::ostream &o) const
Print a RangeMap value.
Member Typedef Documentation
Range
template<class R , class T > typedef R RangeMapNumeric< R, T >::Range
Definition at line 609 of file rangemap.h.
Value
template<class R , class T > typedef T RangeMapNumeric< R, T >::Value
Definition at line 610 of file rangemap.h.
Constructor & Destructor Documentation
RangeMapNumeric() [1/2]
template<class R , class T > RangeMapNumeric< R, T >::RangeMapNumeric () inline
Constructor creates object whose underlying value is zero.
Definition at line 613 of file rangemap.h.
RangeMapNumeric() [2/2]
template<class R , class T > RangeMapNumeric< R, T >::RangeMapNumeric (Value v) inline
Constructor creates object with specified value.
Definition at line 616 of file rangemap.h.
Member Function Documentation
set()
template<class R , class T > void RangeMapNumeric< R, T >::set (Value v) inline
Accessor for the value actually stored here.
Definition at line 620 of file rangemap.h.
get()
template<class R , class T > virtual Value RangeMapNumeric< R, T >::get () const inline virtual
Accessor for the value actually stored here.
Definition at line 623 of file rangemap.h.
Referenced by RangeMapNumeric< R, T >::merge().
removing()
template<class R , class T > void RangeMapNumeric< R, T >::removing (const Range & my_range) inline
Called when this value is being removed from a RangeMap.
Definition at line 630 of file rangemap.h.
References Range< T >::empty().
truncate()
template<class R , class T > void RangeMapNumeric< R, T >::truncate (const Range & my_range, const typename Range::Value & new_end) inline
Called when removing part of a value from a RangeMap.
Definition at line 635 of file rangemap.h.
References Range< T >::first(), and Range< T >::last().
merge()
template<class R , class T > bool RangeMapNumeric< R, T >::merge (const Range & my_range, const Range & other_range, RangeMapNumeric< R, T > other_value) inline
Called to merge two RangeMap values.
The values can be merged only if they compare equal.
Definition at line 640 of file rangemap.h.
References Range< T >::empty(), and RangeMapNumeric< R, T >::get().
split()
template<class R , class T > RangeMapNumeric RangeMapNumeric< R, T >::split (const Range & my_range, typename Range::Value new_end) inline
Split a RangeMap value into two parts.
Definition at line 646 of file rangemap.h.
References Range< T >::contains().
print()
template<class R , class T > void RangeMapNumeric< R, T >::print (std::ostream & o) const inline
Print a RangeMap value.
Definition at line 653 of file rangemap.h.
The documentation for this class was generated from the following file:
rangemap.h