ROSE: SgSymbol Class Reference
SgSymbol Class Reference abstract
Description
This class represents the concept of a name within the compiler.
Symbols are a simpler way for the compiler to quickly associate types, declarations and names. It is also more compact than carrying around names as strings. The SgSymbol can contain many references and is a shared IR node.
A "symbol" within the compiler is a concept of a name. The simplest example is a variable name, the variable most often has a name but internally within the compiler the variable is referenced as a symbol, the symbol data struction contains a name, type, and declaration (where the name was first associated with the type). Each variable has an associated symbol and each variable reference internally stores a pointer to the single symbol representing that variable. this avoids the compiler internally relying upon string processing to compile variable (different symbols can be trivially compared to either have the same address on not). Each named entity within the language's translation within the AST has a unique symbol. Mappings from names to symbols are held in the "Symbol Table" which provides for a quick (hashed) lookup on the symbol for any name. Mappings from the symbol to the name are held through pointers to the declaration (stored within the symbol).
To organize the symbols, they are differentiated by type, each symbol is derived from the SgSymbol class and defines a specialized interface for that specific kind of IR node. For example, there are symbol objects specific to classes, templates, variable, enums, functions, member functions, lables, function types, namespaces, typedefs, etc. In each case these symbols contain a name (or method for generating a name when it is located elsewhere), and a declaration, and often a reference to a type (or function to returning the type if not held in the symbol directly).
Each SgSymbol has a get_name() member function which gets the associated name of the symbol, usually from the stored declaration. A few symbols have an explicitly stored name (SgName), this is done where the name is derived from a named type (SgNamedType).
IMPORTANT: Declarations in Symbols
Indepedent of the different kinds of declarations (declarations are statements), declarations can be considered to be definind and non-defining. See SgDeclarationStatement for details. where there exist defining and non-defining declarations symbols within Sage III always reference non-defining declarations (only non-defining declarations are shared within the AST).
There are no uses of this IR node anywhere. All expressions and statements are derived from this IR node to build either SgExpression or SgStatement derived classes.
Definition at line 691127 of file Cxx_Grammar.h.
Public Types
enum { static_variant = V_SgSymbol }
static variant value
typedef SgNode base_node_type
Public Types inherited from SgNode
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
virtual SgName get_name () const =0
Access function for getting name from declarations or types internally.
virtual SgType * get_type () const =0
This function returns the type associated with the named entity.
virtual SgNode * get_symbol_basis () const
virtual SgScopeStatement * get_scope () const
SgName get_mangled_name () const
virtual void addNewAttribute (std::string s, AstAttribute *a) override
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const override
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a) override
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a) override
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s) override
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const override
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const override
Returns the number of attributes on this IR node.
virtual std::string class_name () const override
returns a string representing the class name
virtual VariantT variantT () const override
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer () override
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer () override
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors () override
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx) override
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child) override
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI () override
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const override
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor) override
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const override
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const override
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgSymbol (const SgSymbolStorageClass &source)
IR node constructor to support AST File I/O.
SgSymbol * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
AstAttributeMechanism * get_attributeMechanism () const override
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
void set_attributeMechanism (AstAttributeMechanism *attributeMechanism) override
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
virtual ~SgSymbol ()
This is the destructor.
SgSymbol ()
This is the default constructor.
Public Member Functions inherited from SgNode
virtual SgNode * copy (SgCopyHelp &help) const
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const
virtual Sg_File_Info * get_file_info (void) const
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
virtual Sg_File_Info * get_startOfConstruct (void) const
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
virtual Sg_File_Info * get_endOfConstruct (void) const
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
virtual unsigned int cfgIndexForEnd () const
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n)
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n)
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index=false)
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index=false)
Find the in edges of a CFG node – internal version.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
virtual SgNode * copy (SgCopyHelp &help) const
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const
virtual Sg_File_Info * get_file_info (void) const
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
virtual Sg_File_Info * get_startOfConstruct (void) const
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
virtual Sg_File_Info * get_endOfConstruct (void) const
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
virtual unsigned int cfgIndexForEnd () const
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n)
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n)
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index=false)
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index=false)
Find the in edges of a CFG node – internal version.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
Static Public Member Functions
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgSymbol * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgSymbol *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgSymbol *sgnode)
Static Public Member Functions inherited from SgNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Protected Attributes
AstAttributeMechanism * p_attributeMechanism
Protected Attributes inherited from SgNode
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Additional Inherited Members
Protected Member Functions inherited from SgNode
virtual void post_construction_initialization ()
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void post_construction_initialization ()
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Static Protected Attributes inherited from SgNode
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Member Typedef Documentation
base_node_type
typedef SgNode SgSymbol::base_node_type
Definition at line 691623 of file Cxx_Grammar.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
static variant value
Definition at line 691244 of file Cxx_Grammar.h.
Constructor & Destructor Documentation
SgSymbol()
SgSymbol::SgSymbol ()
This is the default constructor.
This constructor builds the SgSymbol base class.
See also
Example:create an SgSymbol object
Member Function Documentation
get_name()
SgSymbol::get_name () const pure virtual
Access function for getting name from declarations or types internally.
Implemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
Referenced by SageInterface::findDeclarationStatement(), SageInterface::get_name(), and SageInterface::getClassTypeChainForMemberReference().
get_type()
SgSymbol::get_type () const pure virtual
This function returns the type associated with the named entity.
Implemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
Referenced by SageInterface::lookupNamedTypeInParentScopes().
get_scope()
virtual SgScopeStatement * SgSymbol::get_scope () const virtual
Reimplemented in SgAdaInheritedFunctionSymbol.
addNewAttribute()
virtual void SgSymbol::addNewAttribute (std::string s, AstAttribute * a) override virtual
Add a new attribute represented by the named string.
Reimplemented from SgNode.
getAttribute()
virtual AstAttribute * SgSymbol::getAttribute (std::string s) const override virtual
Returns attribute of name 's'.
Reimplemented from SgNode.
updateAttribute()
virtual void SgSymbol::updateAttribute (std::string s, AstAttribute * a) override virtual
Replace existing attribute of name 's' with new AstAttribute.
Reimplemented from SgNode.
setAttribute()
virtual void SgSymbol::setAttribute (std::string s, AstAttribute * a) override virtual
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
Reimplemented from SgNode.
removeAttribute()
virtual void SgSymbol::removeAttribute (std::string s) override virtual
Remove attribute of name 's' if present.
Reimplemented from SgNode.
attributeExists()
virtual bool SgSymbol::attributeExists (std::string s) const override virtual
Tests if attribute of name 's' is present.
Reimplemented from SgNode.
numberOfAttributes()
virtual int SgSymbol::numberOfAttributes () const override virtual
Returns the number of attributes on this IR node.
Reimplemented from SgNode.
class_name()
virtual std::string SgSymbol::class_name () const override virtual
returns a string representing the class name
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
Referenced by SageInterface::getClassTypeChainForMemberReference(), SageInterface::lookupSymbolInParentScopesIgnoringAliasSymbols(), and SageInterface::set_name().
variantT()
virtual VariantT SgSymbol::variantT () const override virtual
returns new style SageIII enum values
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
Referenced by SageInterface::fixupReferencesToSymbols().
operator delete()
void SgSymbol::operator delete (void * pointer) inline
Definition at line 691299 of file Cxx_Grammar.h.
get_traversalSuccessorContainer()
virtual std::vector< SgNode * > SgSymbol::get_traversalSuccessorContainer () override virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
get_traversalSuccessorNamesContainer()
virtual std::vector< std::string > SgSymbol::get_traversalSuccessorNamesContainer () override virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
get_numberOfTraversalSuccessors()
virtual size_t SgSymbol::get_numberOfTraversalSuccessors () override virtual
return number of children in the traversal successor list
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
get_traversalSuccessorByIndex()
virtual SgNode * SgSymbol::get_traversalSuccessorByIndex (size_t idx) override virtual
index-based access to traversal successors by index number
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
get_childIndex()
virtual size_t SgSymbol::get_childIndex (SgNode * child) override virtual
index-based access to traversal successors by child node
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
roseRTI()
virtual RTIReturnType SgSymbol::roseRTI () override virtual
return C++ Runtime-Time-Information
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
sage_class_name()
virtual const char * SgSymbol::sage_class_name () const override virtual
returns a C style string (char*) representing the class name
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
accept()
virtual void SgSymbol::accept (ROSE_VisitorPattern & visitor) override virtual
support for the classic visitor pattern done in GoF
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
isInMemoryPool()
virtual bool SgSymbol::isInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
checkDataMemberPointersIfInMemoryPool()
virtual void SgSymbol::checkDataMemberPointersIfInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
returnDataMemberPointers()
virtual std::vector< std::pair< SgNode *, std::string > > SgSymbol::returnDataMemberPointers () const override virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
processDataMemberReferenceToPointers()
virtual void SgSymbol::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
getChildIndex()
virtual long SgSymbol::getChildIndex (SgNode * childNode) const override virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented from SgNode.
Reimplemented in SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
addRegExpAttribute()
SgSymbol * SgSymbol::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
get_attributeMechanism()
AstAttributeMechanism * SgSymbol::get_attributeMechanism () const override virtual
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
This is an access function used for getting the interally held pointer to a valid AstAttributeMechanism. It provides access to lower level functionality of the AstAttributeMechanism, put is mostly of use to internal tools.
Reimplemented from SgNode.
set_attributeMechanism()
void SgSymbol::set_attributeMechanism (AstAttributeMechanism * a) override virtual
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
This is an access function used for setting the interally held pointer to a valid AstAttributeMechanism.
Reimplemented from SgNode.
Member Data Documentation
p_attributeMechanism
AstAttributeMechanism* SgSymbol::p_attributeMechanism protected
Definition at line 691642 of file Cxx_Grammar.h.
The documentation for this class was generated from the following files:
Cxx_Grammar.h
SgSymbol.docs