ROSE: SgNode Class Reference
SgNode Class Reference
Description
This class represents the base class for all IR nodes within Sage III.
This class is used as a base class for all IR nodes in Sage III.
Note
AST attributes should not be used for the following IR nodes:
SgName
SgModifier (and all derived modifier IR nodes)
SgUnparse_Info
SgSymbolTable
Definition at line 119 of file Cxx_Grammar.h.
Public Types
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
virtual SgNode * copy (SgCopyHelp &help) const
virtual std::string class_name () const
returns a string representing the class name
virtual VariantT variantT () const
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual size_t get_numberOfTraversalSuccessors ()
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx)
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child)
index-based access to traversal successors by child node
virtual const char * sage_class_name () const
generates string representing the class name: (e.g. for SgNode returns "SgNode").
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor)
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool ()
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool ()
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *)
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
virtual void addNewAttribute (std::string s, AstAttribute *a)
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a)
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a)
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s)
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const
Returns the number of attributes on this IR node.
virtual AstAttributeMechanism * get_attributeMechanism () const
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
virtual void set_attributeMechanism (AstAttributeMechanism *a)
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const
virtual Sg_File_Info * get_file_info (void) const
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
virtual Sg_File_Info * get_startOfConstruct (void) const
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
virtual Sg_File_Info * get_endOfConstruct (void) const
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
virtual unsigned int cfgIndexForEnd () const
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n)
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n)
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index=false)
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index=false)
Find the in edges of a CFG node – internal version.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
virtual SgNode * copy (SgCopyHelp &help) const
virtual std::string class_name () const
returns a string representing the class name
virtual VariantT variantT () const
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer ()
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer ()
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors ()
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx)
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child)
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI ()
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor)
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool ()
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool ()
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *)
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
virtual void addNewAttribute (std::string s, AstAttribute *a)
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a)
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a)
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s)
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const
Returns the number of attributes on this IR node.
virtual AstAttributeMechanism * get_attributeMechanism () const
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
virtual void set_attributeMechanism (AstAttributeMechanism *a)
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const
virtual Sg_File_Info * get_file_info (void) const
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
virtual Sg_File_Info * get_startOfConstruct (void) const
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
virtual Sg_File_Info * get_endOfConstruct (void) const
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
virtual unsigned int cfgIndexForEnd () const
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n)
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n)
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index=false)
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index=false)
Find the in edges of a CFG node – internal version.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
Static Public Member Functions
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Protected Member Functions
virtual void post_construction_initialization ()
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void post_construction_initialization ()
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
Protected Attributes
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Static Protected Attributes
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Traversal Support
virtual std::vector< SgNode * > get_traversalSuccessorContainer ()
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer ()
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual RTIReturnType roseRTI ()
return C++ Runtime-Time-Information
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Member Enumeration Documentation
anonymous enum
anonymous enum
static variant value
Definition at line 150 of file Cxx_Grammar.h.
anonymous enum
anonymous enum
static variant value
Definition at line 127 of file SgNode.h.
Constructor & Destructor Documentation
~SgNode()
SgNode::~SgNode () virtual
This is the destructor.
There is nothing to delete in this object.
SgNode()
SgNode::SgNode ()
This is the constructor.
This constructor builds a SgNode, always used as a base class. All Sage III IR nodes are derived from this class.
See also
Example:create an SgNode object
Member Function Documentation
copy() [1/2]
virtual SgNode * SgNode::copy (SgCopyHelp & help) const virtual
Reimplemented in SgInitializedName, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, and SgPythonGlobalStmt.
class_name() [1/2]
string SgNode::class_name () const virtual
returns a string representing the class name
generates string representing the class name: (e.g. for SgNode returns "SgNode").
This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
a C++ string object.
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
Referenced by SageInterface::addMangledNameToCache(), SageInterface::appendStatementWithDependentDeclaration(), SageBuilder::buildClassDeclaration_nfi(), SageBuilder::buildVariableDeclaration_nfi(), SageInterface::changeAllBodiesToBlocks(), SageInterface::collectModifiedLocatedNodes(), SageInterface::collectModifiedStatements(), SageInterface::convertRefToInitializedName(), SageInterface::deleteAllNodes(), SageInterface::deleteAST(), SageInterface::dumpInfo(), SageBuilder::errorCheckingTargetAST(), SageInterface::findFirstSgCastExpMarkedAsTransformation(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageBuilder::fixupSharingSourcePosition(), SageBuilder::fixupSourcePositionFileSpecification(), SageInterface::functionCallExpressionPreceedsDeclarationWhichAssociatesScope(), SageInterface::get_name(), SageInterface::getClassTypeChainForMemberReference(), SageInterface::getDefaultDestructor(), SageInterface::getEnclosingFileNode(), SageInterface::getEnclosingNode(), SageInterface::getScope(), SageInterface::isEquivalentType(), SageInterface::listHeaderFiles(), SageInterface::markNodeToBeUnparsed(), SageInterface::markSubtreeToBeUnparsedTreeTraversal(), SageInterface::moveDeclarationToAssociatedNamespace(), SageInterface::outputFileIds(), SageInterface::outputSharedNodes(), SageInterface::recursivePrintCurrentAndParent(), SageInterface::replaceExpression(), SageInterface::serialize(), SageInterface::setLoopLowerBound(), SageInterface::setLoopStride(), SageInterface::setLoopUpperBound(), SageInterface::setSourcePosition(), SageBuilder::setTemplateArgumentParents(), SageBuilder::testTemplateParameterParents(), SageInterface::translateToUseCppDeclarations(), CollectDependentDeclarationsTraversal::visit(), and SageInterface::whereAmI().
variantT() [1/2]
SgNode::variantT () const virtual
returns new style SageIII enum values
returns enum value "V_SgNode"
This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
an enum value (type: VariantT).
This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
an enum value (type: VariantT).
This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
an enum value (type: VariantT).
This function is useful for debugging and error reporting. It returns the name of the IR node.
\implementation Once the variant() function is removed this function will be deprecated and replaced by a new function named "variant()". The new "variant()" function will return the new enum type (with consistant naming convention in place). The name of the enum type might be changed to make it more clear.
Returns
an enum value (type: VariantT).
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
Referenced by SageInterface::buildForwardFunctionDeclaration(), SageInterface::changeAllBodiesToBlocks(), SageInterface::checkTypesAreEqual(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), and ssa_private::DataflowCfgFilter::operator()().
operator delete() [1/2]
void SgNode::operator delete (void * pointer) inline
Definition at line 205 of file Cxx_Grammar.h.
get_traversalSuccessorContainer() [1/2]
SgNode::get_traversalSuccessorContainer () virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
FOR INTERNAL USE within ROSE traverals mechanism only.
This function builds and returns a copy of ordered container holding pointers to children of this node in a traversal. It is associated with the definition of a tree that is travered by the AST traversal mechanism; a tree that is embeded in the AST (which is a more general graph). This function is used within the implementation of the AST traversal and has a semantics may change in subtle ways that makes it difficult to use in user code. It can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
Returns ordered STL Container of pointers to children nodes in AST.
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
Referenced by SageInterface::findDeclarationStatement(), SageInterface::findMain(), SageInterface::preOrderCollectPreprocessingInfo(), and SageInterface::serialize().
get_traversalSuccessorNamesContainer() [1/2]
SgNode::get_traversalSuccessorNamesContainer () virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
FOR INTERNAL USE within ROSE traverals mechanism only.
This function builds and returns a copy of ordered container holding strings used to name data members that are traversed in the IR node. It is associated with the definition of a tree that is travered by the AST traversal mechanism; a tree that is embeded in the AST (which is a more general graph). This function is used within the implementation of the AST traversal and has a semantics may change in subtle ways that makes it difficult to use in user code. It can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Each string is a name of a member variable holding a pointer to a child in the AST. The names are the same as used in the generated enums for accessing attributes in a traversal. The order is the same in which they are traversed and the same in which the access enums are defined. Therefore this method can be used to get the corresponding name (string) of an access enum which allows to produce more meaningful messages for attribute computations.
Returns
Returns ordered STL container of names (strings) of access names to children nodes in AST.
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
Referenced by SageInterface::serialize().
get_numberOfTraversalSuccessors() [1/2]
virtual size_t SgNode::get_numberOfTraversalSuccessors () virtual
return number of children in the traversal successor list
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
get_traversalSuccessorByIndex() [1/2]
virtual SgNode * SgNode::get_traversalSuccessorByIndex (size_t idx) virtual
index-based access to traversal successors by index number
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
get_childIndex() [1/2]
virtual size_t SgNode::get_childIndex (SgNode * child) virtual
index-based access to traversal successors by child node
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
roseRTI() [1/2]
SgNode::roseRTI () virtual
return C++ Runtime-Time-Information
FOR INTERNAL USE Access to Runtime Type Information (RTI) for this IR nodes.
This function provides runtime type information for accessing the structure of the current node. It is useful for generating code which would dump out or rebuild IR nodes.
Returns
Returns a RTIReturnType object (runtime type information).
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
sage_class_name() [1/2]
SgNode::sage_class_name () const virtual
generates string representing the class name: (e.g. for SgNode returns "SgNode").
returns a C style string (char*) representing the class name
This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
a char* pointer to a C style string.
This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
a char* pointer to a C style string.
This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
a char* pointer to a C style string.
This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
a char* pointer to a C style string.
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
accept() [1/2]
virtual void SgNode::accept (ROSE_VisitorPattern & visitor) virtual
support for the classic visitor pattern done in GoF
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
isInMemoryPool() [1/2]
virtual bool SgNode::isInMemoryPool () virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
checkDataMemberPointersIfInMemoryPool() [1/2]
virtual void SgNode::checkDataMemberPointersIfInMemoryPool () virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
returnDataMemberPointers() [1/2]
virtual std::vector< std::pair< SgNode *, std::string > > SgNode::returnDataMemberPointers () const virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
Referenced by SageInterface::getFrontendSpecificNodes().
processDataMemberReferenceToPointers() [1/2]
virtual void SgNode::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
getChildIndex() [1/2]
virtual long SgNode::getChildIndex (SgNode * childNode) const virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
addRegExpAttribute() [1/2]
SgNode * SgNode::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
set_isModified() [1/2]
SgNode::set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
Acess function for isModified flag.
This flag can be set but this is typically an internal function used to track the modifications to AST. Within future unparsing this flag will control where the token stream is used alternatively to the code generation from the AST.
This flag records if the current IR node has been modified. It is set to false after and ROSE front-end processing.
Referenced by SageBuilder::buildFile(), SageBuilder::buildSourceFile(), SageInterface::changeAllBodiesToBlocks(), SageInterface::cleanupNontransformedBasicBlockNode(), SageInterface::movePreprocessingInfo(), SageInterface::resetModifiedLocatedNodes(), and SageInterface::set_name().
set_containsTransformation() [1/2]
void SgNode::set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
This flag is required to support the unparsing using the token stream.
get_isModified() [1/2]
SgNode::get_isModified () const
Acess function for isModified flag.
FOR INTERNAL USE All nodes in the AST contain a isModified flag.
This flag records if the current IR node has been modified. It is set to false after and ROSE front-end processing.
This flag can be set but this is typically an internal function used to track the updates to AST.
Returns
Returns bool; true if IR node has been modified.
Referenced by SageBuilder::buildFile(), SageBuilder::buildSourceFile(), SageInterface::changeAllBodiesToBlocks(), SageInterface::cleanupNontransformedBasicBlockNode(), SageInterface::collectModifiedLocatedNodes(), SageInterface::collectModifiedStatements(), SageInterface::movePreprocessingInfo(), and SageInterface::outputFileIds().
get_containsTransformation() [1/2]
bool SgNode::get_containsTransformation () const
Acess function for containsTransformation flag.
This flag records if the current IR node has a nested AST node that is marked as being modified.
set_parent()
SgNode::set_parent (SgNode * parent)
All nodes in the AST contain a reference to a parent node.
Sets parent node for any IR node. The parent node in the AST can be set but this is typically an internal function used to build the AST.
Parameters
parent - Pointer to parent node to store within the current IR node.
Returns
returns void.
Referenced by SageInterface::appendExpression(), SageInterface::appendStatement(), SageInterface::appendStatementWithDependentDeclaration(), SageBuilder::buildActualArgumentExpression(), SageBuilder::buildActualArgumentExpression_nfi(), SageBuilder::buildAggregateInitializer(), SageBuilder::buildAggregateInitializer_nfi(), SageBuilder::buildAlignOfOp(), SageBuilder::buildAlignOfOp_nfi(), SageBuilder::buildArrayType(), SageBuilder::buildArrayType(), SageBuilder::buildAssertStmt(), SageBuilder::buildAssertStmt(), SageBuilder::buildAssertStmt_nfi(), SageBuilder::buildAssignInitializer(), SageBuilder::buildAssignInitializer_nfi(), SageBuilder::buildAssignStatement(), SageBuilder::buildAssignStatement_ast_translate(), SageBuilder::buildAsyncStmt(), SageBuilder::buildAtExp(), SageBuilder::buildAtomicStmt(), SageBuilder::buildAtStmt(), SageBuilder::buildBaseClass(), SageBuilder::buildBasicBlock_nfi(), SageBuilder::buildBinaryExpression(), SageBuilder::buildBinaryExpression_nfi(), SageBuilder::buildBoolType(), SageBuilder::buildBracedInitializer(), SageBuilder::buildBracedInitializer_nfi(), SageBuilder::buildCaseOptionStmt(), SageBuilder::buildCaseOptionStmt_nfi(), SageBuilder::buildCastExp(), SageBuilder::buildCastExp_nfi(), SageBuilder::buildCatchOptionStmt(), SageBuilder::buildComplexVal(), SageBuilder::buildComplexVal_nfi(), SageBuilder::buildCompoundInitializer(), SageBuilder::buildCompoundInitializer_nfi(), SageBuilder::buildComprehension(), SageBuilder::buildComprehension_nfi(), SageBuilder::buildConditionalExp(), SageBuilder::buildConditionalExp_nfi(), SageBuilder::buildConstructorInitializer(), SageBuilder::buildConstructorInitializer_nfi(), SageBuilder::buildCudaKernelCallExp_nfi(), SageBuilder::buildCudaKernelExecConfig_nfi(), SageBuilder::buildDeclType(), SageBuilder::buildDefaultOptionStmt(), SageBuilder::buildDefaultOptionStmt_nfi(), SageBuilder::buildDefiningFunctionDeclaration_T(), SageBuilder::buildDictionaryComprehension(), SageBuilder::buildDictionaryComprehension_nfi(), SageBuilder::buildDoWhileStatement_nfi(), SageBuilder::buildDoWhileStmt(), SageBuilder::buildDoWhileStmt_nfi(), SageBuilder::buildEmptyDeclaration(), SageBuilder::buildEnumDeclaration_nfi(), SageBuilder::buildExecStatement(), SageBuilder::buildExecStatement_nfi(), SageBuilder::buildExprStatement(), SageBuilder::buildExprStatement_nfi(), SageBuilder::buildFile(), SageBuilder::buildFinishExp(), SageBuilder::buildFinishStmt(), SageBuilder::buildFixedType(), SageBuilder::buildFloatType(), SageBuilder::buildForStatement(), SageBuilder::buildForStatement_nfi(), SageBuilder::buildForStatement_nfi(), SageBuilder::buildFortranDo(), SageBuilder::buildFortranDo_nfi(), SageBuilder::buildFunctionCallExp(), SageBuilder::buildFunctionCallExp(), SageBuilder::buildFunctionCallExp(), SageBuilder::buildFunctionCallExp_nfi(), SageBuilder::buildFunctionType(), SageBuilder::buildGotoStatement(), SageBuilder::buildIfStmt(), SageBuilder::buildImaginaryVal(), SageBuilder::buildImaginaryVal(), SageBuilder::buildImaginaryVal_nfi(), SageBuilder::buildIntType(), SageBuilder::buildJavaInstanceOfOp(), SageBuilder::buildJavaSynchronizedStatement(), SageBuilder::buildJavaThrowStatement(), SageBuilder::buildJovialBitType(), SageBuilder::buildJovialDefineDeclaration_nfi(), SageBuilder::buildJovialForThenStatement_nfi(), SageBuilder::buildJovialTableType(), SageBuilder::buildKeyDatumPair(), SageBuilder::buildKeyDatumPair_nfi(), SageBuilder::buildLabelStatement(), SageBuilder::buildLabelStatement_nfi(), SageBuilder::buildLambdaExp(), SageBuilder::buildLambdaExp_nfi(), SageBuilder::buildLambdaRefExp(), SageBuilder::buildListComprehension(), SageBuilder::buildListComprehension_nfi(), SageBuilder::buildMatlabForStatement(), SageBuilder::buildMemberFunctionType(), SageBuilder::buildNamespaceAliasDeclarationStatement(), SageBuilder::buildNamespaceDeclaration_nfi(), SageBuilder::buildNamespaceDefinition(), SageBuilder::buildNaryBooleanOp(), SageBuilder::buildNaryBooleanOp_nfi(), SageBuilder::buildNaryComparisonOp(), SageBuilder::buildNaryComparisonOp_nfi(), SageBuilder::buildNoexceptOp(), SageBuilder::buildNoexceptOp_nfi(), SageBuilder::buildNondefiningClassDeclaration_nfi(), SageBuilder::buildNondefiningEnumDeclaration_nfi(), SageBuilder::buildNondefiningTemplateClassDeclaration_nfi(), SageBuilder::buildNonrealBaseClass(), SageBuilder::buildNonrealDecl(), SageBuilder::buildNonrealType(), SageBuilder::buildOpaqueVarRefExp(), SageBuilder::buildPragmaDeclaration(), SageBuilder::buildPythonPrintStmt(), SageBuilder::buildPythonPrintStmt_nfi(), SageBuilder::buildRangeBasedForStatement_nfi(), SageBuilder::buildReturnStmt(), SageBuilder::buildReturnStmt_nfi(), SageBuilder::buildSetComprehension(), SageBuilder::buildSetComprehension_nfi(), SageBuilder::buildSizeOfOp(), SageBuilder::buildSizeOfOp_nfi(), SageBuilder::buildStatementExpression(), SageBuilder::buildStatementExpression_nfi(), SageBuilder::buildStmtDeclarationStatement(), SageBuilder::buildStmtDeclarationStatement_nfi(), SageBuilder::buildStringConversion(), SageBuilder::buildStringConversion_nfi(), SageBuilder::buildSubscriptExpression_nfi(), SageBuilder::buildSwitchStatement(), SageBuilder::buildSwitchStatement_nfi(), SageBuilder::buildTemplateClassDeclaration_nfi(), SageBuilder::buildTemplateInstantiationTypedefDeclaration_nfi(), SageBuilder::buildTemplateTypedefDeclaration_nfi(), SageBuilder::buildTryStmt(), SageBuilder::buildTypedefDeclaration_nfi(), SageBuilder::buildTypeOfType(), SageBuilder::buildUnaryExpression(), SageBuilder::buildUnaryExpression_nfi(), SageBuilder::buildUnsignedIntType(), SageBuilder::buildUpcBarrierStatement_nfi(), SageBuilder::buildUpcForAllStatement_nfi(), SageBuilder::buildUpcForAllStatement_nfi(), SageBuilder::buildUpcNotifyStatement_nfi(), SageBuilder::buildUpcWaitStatement_nfi(), SageBuilder::buildVarArgOp_nfi(), SageBuilder::buildVariableDeclaration(), SageBuilder::buildVariableDeclaration_nfi(), SageBuilder::buildVariableDefinition_nfi(), SageBuilder::buildVarRefExp(), SageBuilder::buildWhenStmt(), SageBuilder::buildWhileStmt(), SageBuilder::buildWhileStmt_nfi(), SageBuilder::buildWithStatement(), SageBuilder::buildWithStatement_nfi(), SageBuilder::buildYieldExpression(), SageBuilder::buildYieldExpression_nfi(), SageInterface::changeBreakStatementsToGotos(), SageInterface::cleanupNontransformedBasicBlockNode(), SageInterface::doLoopNormalization(), SageInterface::ensureBasicBlockAsBodyOfCaseOption(), SageInterface::ensureBasicBlockAsBodyOfCatch(), SageInterface::ensureBasicBlockAsBodyOfDefaultOption(), SageInterface::ensureBasicBlockAsBodyOfDoWhile(), SageInterface::ensureBasicBlockAsBodyOfFor(), SageInterface::ensureBasicBlockAsBodyOfOmpBodyStmt(), SageInterface::ensureBasicBlockAsBodyOfSwitch(), SageInterface::ensureBasicBlockAsBodyOfWhile(), SageInterface::ensureBasicBlockAsFalseBodyOfIf(), SageInterface::ensureBasicBlockAsTrueBodyOfIf(), SageInterface::fixFunctionDeclaration(), SageInterface::fixNamespaceDeclaration(), SageInterface::fixStatement(), SageInterface::fixStructDeclaration(), SageInterface::fixVariableDeclaration(), SageInterface::initializeIfStmt(), SageInterface::initializeSwitchStatement(), SageInterface::initializeWhileStatement(), SageInterface::insertBeforeUsingCommaOp(), SageInterface::insertStatement(), SageInterface::loopCollapsing(), SageInterface::loopInterchange(), SageInterface::mergeAssignmentWithDeclaration(), SageInterface::mergeDeclarationWithAssignment(), SageInterface::moveForStatementIncrementIntoBody(), SageInterface::moveToSubdirectory(), SageInterface::moveVariableDeclaration(), SageInterface::normalizeForLoopInitDeclaration(), SageInterface::prependStatement(), SageInterface::rebuildSymbolTable(), SageInterface::replaceExpression(), SageInterface::replaceExpressionWithStatement(), SageInterface::replaceStatement(), SageInterface::replaceSubexpressionWithStatement(), SageInterface::setBaseTypeDefiningDeclaration(), SageInterface::setFortranNumericLabel(), SageInterface::setLhsOperand(), SageInterface::setLoopBody(), SageInterface::setLoopCondition(), SageInterface::setLoopLowerBound(), SageInterface::setLoopStride(), SageInterface::setLoopUpperBound(), SageInterface::setOperand(), SageInterface::setParameterList(), SageInterface::setPragma(), SageInterface::setRhsOperand(), SageInterface::setSourcePositionAsTransformation(), SageBuilder::setTemplateArgumentParents(), SageBuilder::setTemplateParameterParents(), SageInterface::splitExpression(), and SageInterface::unnormalizeForLoopInitDeclaration().
get_parent()
SgNode::get_parent () const
Access function for parent node.
Access function for parent node in AST.
The parent node in the AST can be accessed, in general only the project node, symbols and types should be NULL. Since parent nodes are set within post processing (and using the ROSE AST traveral mechanism) the parents are guarenteed to match the traversal, and no other concept of what could be a parent within the AST (e.g a parent concept based on scope). Because the traversal is based on the source code layout, what is a parent is similarly based on the source code layout and not any concept of scope. Note that the scope of relavant IR nodes is stored explicitly in the AST, precisely because it is not always related to the layout of the source code (and thus not related to the concept of parent in the AST).
Returns
Returns pointer to SgNode
Referenced by SageInterface::addDefaultConstructorIfRequired(), SageInterface::addMangledNameToCache(), SageInterface::appendStatement(), SageInterface::appendStatementWithDependentDeclaration(), SageBuilder::buildClassDeclaration_nfi(), SageBuilder::buildComplexVal(), SageBuilder::buildComplexVal_nfi(), SageBuilder::buildDefiningClassDeclaration(), SageBuilder::buildDoWhileStatement_nfi(), SageBuilder::buildEmptyDeclaration(), SageBuilder::buildEnumDeclaration(), SageBuilder::buildEnumDeclaration_nfi(), SageInterface::buildFunctionPrototype(), SageBuilder::buildImaginaryVal(), SageBuilder::buildImaginaryVal(), SageBuilder::buildImaginaryVal_nfi(), SageBuilder::buildMemberFunctionType(), SageBuilder::buildNamespaceDeclaration_nfi(), SageBuilder::buildNondefiningClassDeclaration_nfi(), SageBuilder::buildNondefiningTemplateClassDeclaration_nfi(), SageBuilder::buildPragmaDeclaration(), SageBuilder::buildTemplateClassDeclaration_nfi(), SageBuilder::buildTemplateInstantiationTypedefDeclaration_nfi(), SageBuilder::buildTemplateParameterVal(), SageBuilder::buildTemplateParameterVal_nfi(), SageBuilder::buildTemplateTypedefDeclaration_nfi(), SageBuilder::buildTypedefDeclaration_nfi(), SageBuilder::buildUpcBarrierStatement_nfi(), SageBuilder::buildUpcNotifyStatement_nfi(), SageBuilder::buildUpcWaitStatement_nfi(), SageBuilder::buildVariableDeclaration(), SageBuilder::buildVariableDeclaration_nfi(), SageInterface::changeBreakStatementsToGotos(), SageInterface::cleanupNontransformedBasicBlockNode(), SageInterface::collectUseByAddressVariableRefs(), SageInterface::convertForToWhile(), SageInterface::convertRefToInitializedName(), SageInterface::deleteAST(), SageInterface::findEnclosingLoop(), SageInterface::findEnclosingOmpClauseBodyStatement(), SageInterface::findEnclosingSwitch(), SageInterface::findFirstSgCastExpMarkedAsTransformation(), SageInterface::fixFunctionDeclaration(), SageInterface::fixNamespaceDeclaration(), SageInterface::fixStatement(), SageInterface::fixStructDeclaration(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::fixVariableDeclaration(), SageInterface::fixVariableReferences(), SageInterface::functionCallExpressionPreceedsDeclarationWhichAssociatesScope(), SageInterface::generateFunctionDefinitionsList(), SageInterface::get_name(), SageInterface::getClassTypeChainForMemberReference(), SageInterface::getDefaultDestructor(), SageInterface::getEnclosingFileNode(), SageInterface::getEnclosingNode(), SageInterface::getEnclosingScope(), SageInterface::getEnclosingStatement(), SageInterface::getInitializerOfExpression(), SageInterface::getMangledNameFromCache(), SageInterface::getNonInstantiatonDeclarationForClass(), SageInterface::getScope(), SageInterface::hasSameGlobalScope(), SageInterface::insertAfterUsingCommaOp(), SageInterface::insertBeforeUsingCommaOp(), SageInterface::insertStatement(), SageInterface::isAddressTaken(), SageInterface::isAncestor(), SageInterface::isBodyStatement(), SageInterface::isDataMemberReference(), SageInterface::isEquivalentType(), SageInterface::isLambdaCapturedVariable(), SageInterface::isLambdaFunction(), SageInterface::isLoopIndexVariable(), SageInterface::isMemberFunctionMemberReference(), SageInterface::isUseByAddressVariableRef(), SageInterface::lookupClassSymbolInParentScopes(), SageInterface::lookupEnumSymbolInParentScopes(), SageInterface::lookupFunctionSymbolInParentScopes(), SageInterface::lookupFunctionSymbolInParentScopes(), SageInterface::lookupNamespaceSymbolInParentScopes(), SageInterface::lookupNonrealSymbolInParentScopes(), SageInterface::lookupSymbolInParentScopes(), SageInterface::lookupSymbolInParentScopesIgnoringAliasSymbols(), SageInterface::lookupTemplateClassSymbolInParentScopes(), SageInterface::lookupTemplateFunctionSymbolInParentScopes(), SageInterface::lookupTemplateMemberFunctionSymbolInParentScopes(), SageInterface::lookupTemplateVariableSymbolInParentScopes(), SageInterface::lookupTypedefSymbolInParentScopes(), SageInterface::lookupVariableSymbolInParentScopes(), SageInterface::loopCollapsing(), SageInterface::loopTiling(), SageInterface::loopUnrolling(), SageInterface::makeSingleStatementBodyToBlock(), SageInterface::moveDeclarationToAssociatedNamespace(), SageInterface::moveStatementsBetweenBlocks(), SageInterface::moveStatementsBetweenBlocks(), SageInterface::moveToSubdirectory(), SageInterface::myRemoveStatement(), SageInterface::rebuildSymbolTable(), SageInterface::recursivePrintCurrentAndParent(), SageInterface::removeConsecutiveLabels(), SageInterface::removeLabeledGotos(), SageInterface::removeStatement(), SageInterface::replaceDefiningFunctionDeclarationWithFunctionPrototype(), SageInterface::replaceExpression(), SageInterface::replaceExpressionWithStatement(), SageInterface::replaceStatement(), SageInterface::replaceSubexpressionWithStatement(), SageInterface::reportModifiedLocatedNodes(), SageInterface::reportModifiedStatements(), SageInterface::set_name(), SageInterface::setBaseTypeDefiningDeclaration(), SageInterface::setLoopStride(), SageInterface::setParameterList(), SageBuilder::setTemplateArgumentParents(), SageBuilder::setTemplateParameterParents(), SageInterface::splitExpression(), SageInterface::templateDefinitionIsInClass(), SageBuilder::testTemplateArgumentParents(), SageBuilder::testTemplateParameterParents(), and SageInterface::whereAmI().
unparseToCompleteString()
SgNode::unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
This function is a complement to the unparseToString() function and includes any associated comments and preprocessor control directives. Because C preprocessor control directive can be included string generated using this function may or may not be appropriate for use as input to the AST rewrite mechanism.
Returns
Returns std::string
This function is a complement to the unparseToString() function and includes any associated comments and preprocessor control directives. Because C preprocessor control directive can be included string generated using this function may or may not be appropriate for use as input to the AST rewrite mechanism.
Returns
Returns std::string
This function is a complement to the unparseToString() function and includes any associated comments and preprocessor control directives. Because C preprocessor control directive can be included string generated using this function may or may not be appropriate for use as input to the AST rewrite mechanism.
Returns
Returns std::string
This function is a complement to the unparseToString() function and includes any associated comments and preprocessor control directives. Because C preprocessor control directive can be included string generated using this function may or may not be appropriate for use as input to the AST rewrite mechanism.
Returns
Returns std::string
buildCommandLineToSubstituteTransformationFile() [1/2]
static std::vector< std::string > SgNode::buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > & argv, std::string newFileName) static
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
Parameters
argv - vector of strings holding command line arguments
newFileName - current file name being used (part of support for multiple files on command line).
Returns
returns vector of strings.
variant() [1/2]
SgNode::variant () const inline
Older version function returns enum value "NODE".
This function is an older version of the variant function. This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
an int value.
This function is an older version of the variant function. This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
an int value.
This function is an older version of the variant function. This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
an int value.
This function is an older version of the variant function. This function is useful for debugging and error reporting. It returns the name of the IR node.
Returns
an int value.
Definition at line 609 of file Cxx_Grammar.h.
get_isVisited() [1/2]
SgNode::get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
DOCS IN SgNode.docs: Access function for p_isVisited flag used previously by the AST traversals.
Returns
Returns bool; true if previously visited within current AST traversal.
Returns bool; true if previously visited within current AST traversal.
Returns bool; true if previously visited within current AST traversal.
Returns bool; true if previously visited within current AST traversal.
Returns bool; true if previously visited within current AST traversal.
set_isVisited() [1/2]
SgNode::set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
DOCS IN SgNode.docs: Access function for p_isVisited flag used previously by the AST traversals.
get_globalMangledNameMap() [1/2]
static std::map< SgNode *, std::string > & SgNode::get_globalMangledNameMap () static
Access function for performance optimizing global mangled name map.
This mangle name caching is implemented to support better performance.
Referenced by SageInterface::addMangledNameToCache(), SageBuilder::buildFile(), and SageInterface::getMangledNameFromCache().
get_shortMangledNameCache() [1/2]
static std::map< std::string, uint64_t > & SgNode::get_shortMangledNameCache () static
Access function for lower level optimizing of global mangled name map.
This mangle name caching is implemented to shorter strings used in the globalMangledNameMap mechanism.
Referenced by SageInterface::addMangledNameToCache().
get_globalQualifiedNameMapForNames() [1/2]
static std::map< SgNode *, std::string > & SgNode::get_globalQualifiedNameMapForNames () static
Access function for name qualification support (for names).
This qualified name is stored with reference to where the name is used (as required) instead of with the IR node of what is names (e.g. function declaration, variable declaration, etc.).
set_globalQualifiedNameMapForNames() [1/2]
static void SgNode::set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > & X) static
Access function for name qualification support (for names).
This qualified name is stored with reference to where the name is used (as required) instead of with the IR node of what is names (e.g. function declaration, variable declaration, etc.).
get_globalQualifiedNameMapForTypes() [1/2]
static std::map< SgNode *, std::string > & SgNode::get_globalQualifiedNameMapForTypes () static
Access function for name qualification support (for type).
This qualified name is stored with reference to where the type is used (as required) instead of with the IR node representing the type (which are typically shared) (e.g. function return type, variable type, etc.).
set_globalQualifiedNameMapForTypes() [1/2]
static void SgNode::set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > & X) static
Access function for name qualification support (for type).
This qualified name is stored with reference to where the type is used (as required) instead of with the IR node representing the type (which are typically shared) (e.g. function return type, variable type, etc.).
get_globalQualifiedNameMapForMapsOfTypes() [1/2]
static std::map< SgNode *, std::map< SgNode *, std::string > > & SgNode::get_globalQualifiedNameMapForMapsOfTypes () static
Access function for name qualification support (for maps of types).
This qualified name is stored with reference to where the type is used (as required) instead of with the IR node representing the type (which are typically shared) (e.g. function return type, variable type, etc.).
set_globalQualifiedNameMapForMapsOfTypes() [1/2]
static void SgNode::set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > & X) static
Access function for name qualification support (for maps of types).
This qualified name is stored with reference to where the type is used (as required) instead of with the IR node representing the type (which are typically shared) (e.g. function return type, variable type, etc.).
get_globalQualifiedNameMapForTemplateHeaders() [1/2]
static std::map< SgNode *, std::string > & SgNode::get_globalQualifiedNameMapForTemplateHeaders () static
Access function for name qualification support (for template headers in template declarations).
This name is stored with reference to where the template declaration is used (as required) instead of with the IR node (where it could be incorrect). This design allows it to be computed as needed. Note that template headers are the substrings "template<typename T>" that apepar in header declarations. These can be repeated as required for deeply nested templated classes and thus are associated with name qualification of template declarations (along with the more common form of name qualication that also applies to template declarations).
set_globalQualifiedNameMapForTemplateHeaders() [1/2]
static void SgNode::set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > & X) static
Access function for name qualification support (for template headers in template declarations).
See documentation in get_globalQualifiedNameMapForTemplateHeaders() (above).
get_globalTypeNameMap() [1/2]
static std::map< SgNode *, std::string > & SgNode::get_globalTypeNameMap () static
Access function for name qualification support (for names of types).
This type name is stored with reference to where the type is used (as required) instead of with the IR node representing the type (which are typically shared) (e.g. function return type, variable type, etc.).
set_globalTypeNameMap() [1/2]
static void SgNode::set_globalTypeNameMap (const std::map< SgNode *, std::string > & X) static
Access function for name qualification support (for names of types).
This qualified name is stored with reference to where the name is used (as required) instead of with the IR node of what is names (e.g. function declaration, variable declaration, etc.).
addNewAttribute() [1/2]
virtual void SgNode::addNewAttribute (std::string s, AstAttribute * a) virtual
Add a new attribute represented by the named string.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
Referenced by SageInterface::addTextForUnparser().
getAttribute() [1/2]
virtual AstAttribute * SgNode::getAttribute (std::string s) const virtual
Returns attribute of name 's'.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
Referenced by SageInterface::addTextForUnparser().
updateAttribute() [1/2]
virtual void SgNode::updateAttribute (std::string s, AstAttribute * a) virtual
Replace existing attribute of name 's' with new AstAttribute.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
setAttribute() [1/2]
virtual void SgNode::setAttribute (std::string s, AstAttribute * a) virtual
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
removeAttribute() [1/2]
virtual void SgNode::removeAttribute (std::string s) virtual
Remove attribute of name 's' if present.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
attributeExists() [1/2]
virtual bool SgNode::attributeExists (std::string s) const virtual
Tests if attribute of name 's' is present.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
Referenced by SageInterface::addTextForUnparser().
numberOfAttributes() [1/2]
virtual int SgNode::numberOfAttributes () const virtual
Returns the number of attributes on this IR node.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
get_attributeMechanism() [1/2]
virtual AstAttributeMechanism * SgNode::get_attributeMechanism () const virtual
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
This is an access function used for getting the interally held pointer to a valid AstAttributeMechanism. It provides access to lower level functionality of the AstAttributeMechanism, put is mostly of use to internal tools.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, and SgSymbol.
set_attributeMechanism() [1/2]
virtual void SgNode::set_attributeMechanism (AstAttributeMechanism * a) virtual
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
This is an access function used for setting the interally held pointer to a valid AstAttributeMechanism.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, and SgSymbol.
get_file_info() [1/2]
virtual Sg_File_Info * SgNode::get_file_info (void) const inline virtual
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
Reimplemented in SgPragma, SgFile, SgLocatedNode, and SgExpression.
Definition at line 813 of file Cxx_Grammar.h.
Referenced by SageInterface::convertRefToInitializedName(), SageInterface::findFirstDefiningFunctionDecl(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::getEnclosingNode(), SageInterface::getFirstStatement(), SageInterface::getFrontendSpecificNodes(), SageInterface::markNodeToBeUnparsed(), SageInterface::outputFileIds(), SageInterface::outputSharedNodes(), SageInterface::setSourcePosition(), CollectDependentDeclarationsTraversal::visit(), CollectSourceSequenceNumbers::visit(), and SageInterface::whereAmI().
get_startOfConstruct() [1/2]
virtual Sg_File_Info * SgNode::get_startOfConstruct (void) const inline virtual
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
Reimplemented in SgPragma, SgFile, and SgLocatedNode.
Definition at line 818 of file Cxx_Grammar.h.
get_endOfConstruct() [1/2]
virtual Sg_File_Info * SgNode::get_endOfConstruct (void) const inline virtual
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
Reimplemented in SgPragma, and SgLocatedNode.
Definition at line 823 of file Cxx_Grammar.h.
Referenced by SageBuilder::fixupSourcePositionFileSpecification().
cfgIndexForEnd() [1/2]
virtual unsigned int SgNode::cfgIndexForEnd () const virtual
Determine the CFG index for the end of this construct.
Reimplemented in SgInitializedName, SgStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgAssociateStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgFunctionParameterList, SgVariableDeclaration, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgUseStatement, SgEquivalenceStatement, SgInterfaceStatement, SgCommonBlock, SgTypedefDeclaration, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgModuleStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgContainsStatement, SgStaticAssertionDeclaration, SgEmptyDeclaration, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgNullStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgWhereStatement, SgElseWhereStatement, SgArithmeticIfStatement, SgComputedGotoStatement, SgOmpBodyStatement, SgOmpClauseBodyStatement, SgAssertStmt, SgJavaSynchronizedStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgExpression, SgUnaryOp, SgThrowOp, SgBinaryOp, SgExprListExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgFunctionCallExp, SgSizeOfOp, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgInitializer, SgConstructorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgNullExpression, SgSubscriptExpression, SgAsteriskShapeExp, SgImpliedDo, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgPseudoDestructorRefExp, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgNoexceptOp, and SgNonrealRefExp.
cfgIsIndexInteresting() [1/2]
virtual bool SgNode::cfgIsIndexInteresting (unsigned int index) const virtual
Determine whether a particular CFG node index is "interesting" for this kind of node.
Reimplemented in SgGlobal, SgJavaForEachStatement, SgJavaLabelStatement, SgInitializedName, SgStatement, SgExpression, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgStaticAssertionDeclaration, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgGotoStatement, SgCatchStatementSeq, SgComputedGotoStatement, SgJavaSynchronizedStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAndOp, SgOrOp, and SgConditionalExp.
cfgFindChildIndex() [1/2]
virtual unsigned int SgNode::cfgFindChildIndex (SgNode * n) virtual
Find the index of n in this node's CFG children.
Reimplemented in SgInitializedName, SgStatement, SgIfStmt, SgForStatement, SgFunctionDefinition, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgRangeBasedForStatement, SgVariableDeclaration, SgLabelStatement, SgCaseOptionStmt, SgComputedGotoStatement, SgJavaSynchronizedStatement, SgExpression, SgCastExp, SgConditionalExp, SgNewExp, and SgDesignatedInitializer.
cfgFindNextChildIndex() [1/2]
virtual unsigned int SgNode::cfgFindNextChildIndex (SgNode * n) virtual
Find the index just after n in this node's CFG children.
Reimplemented in SgInitializedName, SgStatement, SgForStatement, SgWhileStmt, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgRangeBasedForStatement, and SgExpression.
cfgOutEdges() [1/2]
virtual std::vector< VirtualCFG::CFGEdge > SgNode::cfgOutEdges (unsigned int index = false) virtual
Find the out edges of a CFG node – internal version.
Reimplemented in SgInitializedName, SgStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgAssociateStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgFunctionParameterList, SgVariableDeclaration, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgUseStatement, SgEquivalenceStatement, SgInterfaceStatement, SgCommonBlock, SgTypedefDeclaration, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgModuleStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgContainsStatement, SgStaticAssertionDeclaration, SgEmptyDeclaration, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgNullStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgWhereStatement, SgElseWhereStatement, SgArithmeticIfStatement, SgComputedGotoStatement, SgOmpBodyStatement, SgOmpClauseBodyStatement, SgAssertStmt, SgJavaSynchronizedStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgExpression, SgUnaryOp, SgThrowOp, SgBinaryOp, SgAndOp, SgOrOp, SgExprListExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgFunctionCallExp, SgSizeOfOp, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgNullExpression, SgSubscriptExpression, SgAsteriskShapeExp, SgImpliedDo, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgPseudoDestructorRefExp, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgNoexceptOp, SgNonrealRefExp, and SgAdaAttributeExp.
cfgInEdges() [1/2]
virtual std::vector< VirtualCFG::CFGEdge > SgNode::cfgInEdges (unsigned int index = false) virtual
Find the in edges of a CFG node – internal version.
Reimplemented in SgInitializedName, SgStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgAssociateStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgFunctionParameterList, SgVariableDeclaration, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgUseStatement, SgEquivalenceStatement, SgInterfaceStatement, SgCommonBlock, SgTypedefDeclaration, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgModuleStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgContainsStatement, SgStaticAssertionDeclaration, SgEmptyDeclaration, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgNullStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgWhereStatement, SgElseWhereStatement, SgArithmeticIfStatement, SgComputedGotoStatement, SgOmpBodyStatement, SgOmpClauseBodyStatement, SgAssertStmt, SgJavaSynchronizedStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgExpression, SgUnaryOp, SgThrowOp, SgBinaryOp, SgAndOp, SgOrOp, SgExprListExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgFunctionCallExp, SgSizeOfOp, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgNullExpression, SgSubscriptExpression, SgAsteriskShapeExp, SgImpliedDo, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgPseudoDestructorRefExp, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgNoexceptOp, SgNonrealRefExp, and SgAdaAttributeExp.
numberOfNodesInSubtree() [1/2]
int SgNode::numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
This function is used as a basis for steps in AST isomophism tests. The implementation uses a traversal of the AST subtree to count the number of IR nodes. So the complexity if order N in the size of the subtree.
depthOfSubtree() [1/2]
int SgNode::depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
This function is used as a basis for steps in AST isomophism tests. The implementation uses a traversal of the AST subtree to count the depth of the AST traversal. So the complexity if order N in the size of the subtree.
post_construction_initialization() [1/2]
virtual void SgNode::post_construction_initialization () protected virtual
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
Reimplemented in SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgPragma, Sg_File_Info, SgBinaryComposite, SgJvmComposite, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgGraph, SgIncidenceDirectedGraph, SgGraphNode, SgGraphEdge, SgDataStatementValue, SgTypeString, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgLocatedNode, SgInitializedName, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgNamespaceSymbol, and SgAliasSymbol.
createAndParent() [1/2]
template<class T > static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type SgNode::createAndParent (SgNode * parent) inline static
Allocate and return a new node after setting its parent.
ROSE's AST has this annoying, error-prone process for adding a node to the tree. One has to not only add the downward edge from parent to child, but also explicitly add the upward edge from child to parent. This two-step process makes it difficult to create child nodes and link them into the parent while the parent is being constructed. This function attempts to make this easier by doing everything in one step.
Use it like this:
Parent::Parent(int foo, int bar)
    : p_child(createAndParent<Child>(this), p_foo(foo), p_bar(bar) {}
Definition at line 948 of file Cxx_Grammar.h.
initParentPointer() [1/2]
template<class T > T * SgNode::initParentPointer (T * child, SgNode * parent) inline
Generated for tree edge data member initializations.
When initializing a data member that's an edge in the tree, this sets the nodes parent pointer to this object and then returns the node. It is used in generated code for constructors, like this:
Foo::Foo(Bar *bar)
    : p_bar(adjustParent(bar, this)) {}
Definition at line 964 of file Cxx_Grammar.h.
changeChildPointer() [1/4]
template<class T > std::enable_if< std::is_pointer< T >::value, void >::type SgNode::changeChildPointer (T & edge, T const & child) inline
Set a child edge in a tree to point to a specific child.
Normally one has to remember to set the parent pointer when adding a child to a tree, and also be careful that the result is still a tree. This helper function tries to make that easier by checking some things and setting the parent pointer automatically.
For instance, this should work:
SgAsmBinaryExpression *parent = ...;
SgAsmBinaryExpression *child1 = ...;
SgAsmBinaryExpression *child2 = ...;
parent->set_lhs(child1);
ASSERT_require(child1->get_parent() == parent);
parent->set_lhs(child2);
ASSERT_require(child1->get_parent() == nullptr);
ASSERT_require(child2->get_parent() == parent);
parent->set_lhs(nullptr);
ASSERT_require(child2->get_parent() == nullptr);
The following should not work when assertions are enabled:
SgAsmBinaryExpression *parent = ...;
SgAsmBinaryExpression *child1 = ...;
SgAsmBinaryExpression *child2 = ...;
parent->set_lhs(child1);
parent->set_rhs(child1); // no longer a tree, but still acyclic
Definition at line 1026 of file Cxx_Grammar.h.
changeChildPointer() [2/4]
template<class T > std::enable_if<!std::is_pointer< T >::value, void >::type SgNode::changeChildPointer (T & edge, T const & child) inline
Set a child edge in a tree to point to a specific child.
Normally one has to remember to set the parent pointer when adding a child to a tree, and also be careful that the result is still a tree. This helper function tries to make that easier by checking some things and setting the parent pointer automatically.
For instance, this should work:
SgAsmBinaryExpression *parent = ...;
SgAsmBinaryExpression *child1 = ...;
SgAsmBinaryExpression *child2 = ...;
parent->set_lhs(child1);
ASSERT_require(child1->get_parent() == parent);
parent->set_lhs(child2);
ASSERT_require(child1->get_parent() == nullptr);
ASSERT_require(child2->get_parent() == parent);
parent->set_lhs(nullptr);
ASSERT_require(child2->get_parent() == nullptr);
The following should not work when assertions are enabled:
SgAsmBinaryExpression *parent = ...;
SgAsmBinaryExpression *child1 = ...;
SgAsmBinaryExpression *child2 = ...;
parent->set_lhs(child1);
parent->set_rhs(child1); // no longer a tree, but still acyclic
Definition at line 1072 of file Cxx_Grammar.h.
destructorHelper() [1/2]
virtual void SgNode::destructorHelper () inline protected virtual
This gets called by all Rosebud-generated destructors.
Rosebud generates a call to destructorHelper from every destructor implementation. This gives the user a chance to do something special. There are some things to be aware of when reimplementing this function, and you should be well versed in the C++ rules about calling virtual functions from destructors.
The implementation must not attempt to access any data members of derived classes. These data members have already been destroyed by time this function is called.
Any calls you make to virtual functions declared in this class will dispatch only to implementations in this class or its base classes, not any derived classes.
Your implementation must expect to be called multiple times for the same object. This occurs when this class implements this function but its derived class does not. During destruction of a derived object, the derived class's Rosebud-generated destructor will call destructorHelper, which will dispatch to the implementation in this class. Then, when the part of the object corresponding to this class is being destroyed, the destructor will call destructorHelper again, which will dispatch to this implementation again. This may happen recursively mutliple times.
Your implementation should not destroy anything that a subclass might need during its destruction. This follows from the rule above, but is generally not a problem in practice. The reason it's not a problem is that the derived classes are usually Rosebud-generated and thus their destructors only call destructorHelper. Therefore, in order for any derived class to any work, it must be done in its destructorHelper, which would be called before the implementation of destructorHelper in this class is called.
All attempts should be made to avoid having to implement a destructorHelper in any class but the most base class (and that one does nothing). Instead, use data members whose own destructors do their cleanup. For instance, if this class needs a pointer to data allocated on the stack, then instead of using a raw pointer which needs to be deleted in this class's destructor, use a smart pointer whose own destructor deletes the data. If you follow this advice, then you don't need to be well-versed in the details of C++ object destruction.
Reimplemented in SgAsmJvmFileHeader, SgAsmJvmConstantPool, SgAsmGenericFile, SgAsmElfStrtab, SgAsmCoffStrtab, and SgAsmGenericSection.
Definition at line 1140 of file Cxx_Grammar.h.
debugSerializationBegin() [1/2]
virtual void SgNode::debugSerializationBegin (const char * className) inline protected virtual
Called by generated serializers.
All generated serialization functions call this function as the first or last thing they do. This is a convenient place to put temporary debugging code or breakpoints if you're trying to figure out what went wrong. You can also it in particular derived classes if you need to debug just one class.
Definition at line 1150 of file Cxx_Grammar.h.
debugSerializationEnd() [1/2]
virtual void SgNode::debugSerializationEnd (const char * className) inline protected virtual
Called by generated serializers.
All generated serialization functions call this function as the first or last thing they do. This is a convenient place to put temporary debugging code or breakpoints if you're trying to figure out what went wrong. You can also it in particular derived classes if you need to debug just one class.
Definition at line 1153 of file Cxx_Grammar.h.
copy() [2/2]
virtual SgNode * SgNode::copy (SgCopyHelp & help) const virtual
Reimplemented in SgInitializedName, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, and SgPythonGlobalStmt.
class_name() [2/2]
virtual std::string SgNode::class_name () const virtual
returns a string representing the class name
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
variantT() [2/2]
virtual VariantT SgNode::variantT () const virtual
returns new style SageIII enum values
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
operator delete() [2/2]
void SgNode::operator delete (void * pointer) inline
Definition at line 182 of file SgNode.h.
get_traversalSuccessorContainer() [2/2]
virtual std::vector< SgNode * > SgNode::get_traversalSuccessorContainer () virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
get_traversalSuccessorNamesContainer() [2/2]
virtual std::vector< std::string > SgNode::get_traversalSuccessorNamesContainer () virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
get_numberOfTraversalSuccessors() [2/2]
virtual size_t SgNode::get_numberOfTraversalSuccessors () virtual
return number of children in the traversal successor list
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
get_traversalSuccessorByIndex() [2/2]
virtual SgNode * SgNode::get_traversalSuccessorByIndex (size_t idx) virtual
index-based access to traversal successors by index number
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
get_childIndex() [2/2]
virtual size_t SgNode::get_childIndex (SgNode * child) virtual
index-based access to traversal successors by child node
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
roseRTI() [2/2]
virtual RTIReturnType SgNode::roseRTI () virtual
return C++ Runtime-Time-Information
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
sage_class_name() [2/2]
virtual const char * SgNode::sage_class_name () const virtual
returns a C style string (char*) representing the class name
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
accept() [2/2]
virtual void SgNode::accept (ROSE_VisitorPattern & visitor) virtual
support for the classic visitor pattern done in GoF
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
isInMemoryPool() [2/2]
virtual bool SgNode::isInMemoryPool () virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
checkDataMemberPointersIfInMemoryPool() [2/2]
virtual void SgNode::checkDataMemberPointersIfInMemoryPool () virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
returnDataMemberPointers() [2/2]
virtual std::vector< std::pair< SgNode *, std::string > > SgNode::returnDataMemberPointers () const virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
processDataMemberReferenceToPointers() [2/2]
virtual void SgNode::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
getChildIndex() [2/2]
virtual long SgNode::getChildIndex (SgNode * childNode) const virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented in SgSupport, SgModifier, SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgName, SgSymbolTable, SgAttribute, SgPragma, SgBitAttribute, SgFuncDecl_attr, SgClassDecl_attr, Sg_File_Info, SgFile, SgSourceFile, SgUnknownFile, SgBinaryComposite, SgJvmComposite, SgProject, SgOptions, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTypedefSeq, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgFileList, SgDirectoryList, SgFunctionParameterTypeList, SgQualifiedName, SgTemplateArgumentList, SgTemplateParameterList, SgGraph, SgIncidenceDirectedGraph, SgBidirectionalGraph, SgStringKeyedBidirectionalGraph, SgIntKeyedBidirectionalGraph, SgIncidenceUndirectedGraph, SgGraphNode, SgGraphEdge, SgDirectedGraphEdge, SgUndirectedGraphEdge, SgGraphNodeList, SgGraphEdgeList, SgTypeTable, SgNameGroup, SgDimensionObject, SgFormatItem, SgFormatItemList, SgDataStatementGroup, SgDataStatementObject, SgIncludeFile, SgDataStatementValue, SgJavaImportStatementList, SgJavaClassDeclarationList, SgHeaderFileReport, SgType, SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, SgRangeType, SgLocatedNode, SgToken, SgLocatedNodeSupport, SgCommonBlockObject, SgInitializedName, SgInterfaceBody, SgHeaderFileBody, SgRenamePair, SgJavaMemberValuePair, SgOmpClause, SgOmpNowaitClause, SgOmpBeginClause, SgOmpEndClause, SgOmpUntiedClause, SgOmpDefaultClause, SgOmpAtomicClause, SgOmpProcBindClause, SgOmpExpressionClause, SgOmpOrderedClause, SgOmpCollapseClause, SgOmpIfClause, SgOmpNumThreadsClause, SgOmpDeviceClause, SgOmpSafelenClause, SgOmpSimdlenClause, SgOmpFinalClause, SgOmpPriorityClause, SgOmpInbranchClause, SgOmpNotinbranchClause, SgOmpVariablesClause, SgOmpCopyprivateClause, SgOmpPrivateClause, SgOmpFirstprivateClause, SgOmpSharedClause, SgOmpCopyinClause, SgOmpLastprivateClause, SgOmpReductionClause, SgOmpMapClause, SgOmpUniformClause, SgOmpAlignedClause, SgOmpLinearClause, SgOmpDependClause, SgOmpScheduleClause, SgOmpMergeableClause, SgLambdaCapture, SgLambdaCaptureList, SgAdaTypeConstraint, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgSymbol, SgVariableSymbol, SgTemplateVariableSymbol, SgNonrealSymbol, SgFunctionSymbol, SgMemberFunctionSymbol, SgTemplateMemberFunctionSymbol, SgTemplateFunctionSymbol, SgRenameSymbol, SgAdaInheritedFunctionSymbol, SgFunctionTypeSymbol, SgClassSymbol, SgTemplateClassSymbol, SgTemplateSymbol, SgEnumSymbol, SgEnumFieldSymbol, SgTypedefSymbol, SgTemplateTypedefSymbol, SgLabelSymbol, SgDefaultSymbol, SgNamespaceSymbol, SgIntrinsicSymbol, SgModuleSymbol, SgInterfaceSymbol, SgCommonSymbol, SgAliasSymbol, SgAsmBinaryAddressSymbol, SgAsmBinaryDataSymbol, SgJavaLabelSymbol, SgAdaPackageSymbol, SgAdaTaskSymbol, SgAdaProtectedSymbol, SgAdaRenamingSymbol, SgAdaGenericSymbol, SgAdaGenericInstanceSymbol, and SgAdaFormalPackageSymbol.
addRegExpAttribute() [2/2]
SgNode * SgNode::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
set_isModified() [2/2]
void SgNode::set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
This flag can be set but this is typically an internal function used to track the modifications to AST. Within future unparsing this flag will control where the token stream is used alternatively to the code generation from the AST.
set_containsTransformation() [2/2]
void SgNode::set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
This flag is required to support the unparsing using the token stream.
get_isModified() [2/2]
bool SgNode::get_isModified () const
Acess function for isModified flag.
This flag records if the current IR node has been modified. It is set to false after and ROSE front-end processing.
get_containsTransformation() [2/2]
bool SgNode::get_containsTransformation () const
Acess function for containsTransformation flag.
This flag records if the current IR node has a nested AST node that is marked as being modified.
buildCommandLineToSubstituteTransformationFile() [2/2]
static std::vector< std::string > SgNode::buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > & argv, std::string newFileName) static
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
Parameters
argv - vector of strings holding command line arguments
newFileName - current file name being used (part of support for multiple files on command line).
Returns
returns vector of strings.
variant() [2/2]
int SgNode::variant () const inline
Definition at line 586 of file SgNode.h.
get_isVisited() [2/2]
bool SgNode::get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
Returns
Returns bool; true if previously visited within current AST traversal.
set_isVisited() [2/2]
void SgNode::set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
get_globalMangledNameMap() [2/2]
static std::map< SgNode *, std::string > & SgNode::get_globalMangledNameMap () static
Access function for performance optimizing global mangled name map.
This mangle name caching is implemented to support better performance.
get_shortMangledNameCache() [2/2]
static std::map< std::string, uint64_t > & SgNode::get_shortMangledNameCache () static
Access function for lower level optimizing of global mangled name map.
This mangle name caching is implemented to shorter strings used in the globalMangledNameMap mechanism.
get_globalQualifiedNameMapForNames() [2/2]
static std::map< SgNode *, std::string > & SgNode::get_globalQualifiedNameMapForNames () static
Access function for name qualification support (for names).
This qualified name is stored with reference to where the name is used (as required) instead of with the IR node of what is names (e.g. function declaration, variable declaration, etc.).
set_globalQualifiedNameMapForNames() [2/2]
static void SgNode::set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > & X) static
Access function for name qualification support (for names).
This qualified name is stored with reference to where the name is used (as required) instead of with the IR node of what is names (e.g. function declaration, variable declaration, etc.).
get_globalQualifiedNameMapForTypes() [2/2]
static std::map< SgNode *, std::string > & SgNode::get_globalQualifiedNameMapForTypes () static
Access function for name qualification support (for type).
This qualified name is stored with reference to where the type is used (as required) instead of with the IR node representing the type (which are typically shared) (e.g. function return type, variable type, etc.).
set_globalQualifiedNameMapForTypes() [2/2]
static void SgNode::set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > & X) static
Access function for name qualification support (for type).
This qualified name is stored with reference to where the type is used (as required) instead of with the IR node representing the type (which are typically shared) (e.g. function return type, variable type, etc.).
get_globalQualifiedNameMapForMapsOfTypes() [2/2]
static std::map< SgNode *, std::map< SgNode *, std::string > > & SgNode::get_globalQualifiedNameMapForMapsOfTypes () static
Access function for name qualification support (for maps of types).
This qualified name is stored with reference to where the type is used (as required) instead of with the IR node representing the type (which are typically shared) (e.g. function return type, variable type, etc.).
set_globalQualifiedNameMapForMapsOfTypes() [2/2]
static void SgNode::set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > & X) static
Access function for name qualification support (for maps of types).
This qualified name is stored with reference to where the type is used (as required) instead of with the IR node representing the type (which are typically shared) (e.g. function return type, variable type, etc.).
get_globalQualifiedNameMapForTemplateHeaders() [2/2]
static std::map< SgNode *, std::string > & SgNode::get_globalQualifiedNameMapForTemplateHeaders () static
Access function for name qualification support (for template headers in template declarations).
This name is stored with reference to where the template declaration is used (as required) instead of with the IR node (where it could be incorrect). This design allows it to be computed as needed. Note that template headers are the substrings "template<typename T>" that apepar in header declarations. These can be repeated as required for deeply nested templated classes and thus are associated with name qualification of template declarations (along with the more common form of name qualication that also applies to template declarations).
set_globalQualifiedNameMapForTemplateHeaders() [2/2]
static void SgNode::set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > & X) static
Access function for name qualification support (for template headers in template declarations).
See documentation in get_globalQualifiedNameMapForTemplateHeaders() (above).
get_globalTypeNameMap() [2/2]
static std::map< SgNode *, std::string > & SgNode::get_globalTypeNameMap () static
Access function for name qualification support (for names of types).
This type name is stored with reference to where the type is used (as required) instead of with the IR node representing the type (which are typically shared) (e.g. function return type, variable type, etc.).
set_globalTypeNameMap() [2/2]
static void SgNode::set_globalTypeNameMap (const std::map< SgNode *, std::string > & X) static
Access function for name qualification support (for names of types).
This qualified name is stored with reference to where the name is used (as required) instead of with the IR node of what is names (e.g. function declaration, variable declaration, etc.).
addNewAttribute() [2/2]
virtual void SgNode::addNewAttribute (std::string s, AstAttribute * a) virtual
Add a new attribute represented by the named string.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
getAttribute() [2/2]
virtual AstAttribute * SgNode::getAttribute (std::string s) const virtual
Returns attribute of name 's'.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
updateAttribute() [2/2]
virtual void SgNode::updateAttribute (std::string s, AstAttribute * a) virtual
Replace existing attribute of name 's' with new AstAttribute.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
setAttribute() [2/2]
virtual void SgNode::setAttribute (std::string s, AstAttribute * a) virtual
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
removeAttribute() [2/2]
virtual void SgNode::removeAttribute (std::string s) virtual
Remove attribute of name 's' if present.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
attributeExists() [2/2]
virtual bool SgNode::attributeExists (std::string s) const virtual
Tests if attribute of name 's' is present.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
numberOfAttributes() [2/2]
virtual int SgNode::numberOfAttributes () const virtual
Returns the number of attributes on this IR node.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, SgInitializedName, and SgSymbol.
get_attributeMechanism() [2/2]
virtual AstAttributeMechanism * SgNode::get_attributeMechanism () const virtual
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
This is an access function used for getting the interally held pointer to a valid AstAttributeMechanism. It provides access to lower level functionality of the AstAttributeMechanism, put is mostly of use to internal tools.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, and SgSymbol.
set_attributeMechanism() [2/2]
virtual void SgNode::set_attributeMechanism (AstAttributeMechanism * a) virtual
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
This is an access function used for setting the interally held pointer to a valid AstAttributeMechanism.
Reimplemented in SgPragma, SgFile, SgProject, SgDirectory, SgFileList, SgGraph, SgGraphNode, SgGraphEdge, SgType, SgLocatedNode, and SgSymbol.
get_file_info() [2/2]
virtual Sg_File_Info * SgNode::get_file_info (void) const inline virtual
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
Reimplemented in SgPragma, SgFile, SgLocatedNode, and SgExpression.
Definition at line 790 of file SgNode.h.
get_startOfConstruct() [2/2]
virtual Sg_File_Info * SgNode::get_startOfConstruct (void) const inline virtual
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
Reimplemented in SgPragma, SgFile, and SgLocatedNode.
Definition at line 795 of file SgNode.h.
get_endOfConstruct() [2/2]
virtual Sg_File_Info * SgNode::get_endOfConstruct (void) const inline virtual
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
Reimplemented in SgPragma, and SgLocatedNode.
Definition at line 800 of file SgNode.h.
cfgIndexForEnd() [2/2]
virtual unsigned int SgNode::cfgIndexForEnd () const virtual
Determine the CFG index for the end of this construct.
Reimplemented in SgInitializedName, SgStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgAssociateStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgFunctionParameterList, SgVariableDeclaration, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgUseStatement, SgEquivalenceStatement, SgInterfaceStatement, SgCommonBlock, SgTypedefDeclaration, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgModuleStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgContainsStatement, SgStaticAssertionDeclaration, SgEmptyDeclaration, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgNullStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgWhereStatement, SgElseWhereStatement, SgArithmeticIfStatement, SgComputedGotoStatement, SgOmpBodyStatement, SgOmpClauseBodyStatement, SgAssertStmt, SgJavaSynchronizedStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgExpression, SgUnaryOp, SgThrowOp, SgBinaryOp, SgExprListExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgFunctionCallExp, SgSizeOfOp, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgInitializer, SgConstructorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgNullExpression, SgSubscriptExpression, SgAsteriskShapeExp, SgImpliedDo, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgPseudoDestructorRefExp, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgNoexceptOp, and SgNonrealRefExp.
cfgIsIndexInteresting() [2/2]
virtual bool SgNode::cfgIsIndexInteresting (unsigned int index) const virtual
Determine whether a particular CFG node index is "interesting" for this kind of node.
Reimplemented in SgGlobal, SgJavaForEachStatement, SgJavaLabelStatement, SgInitializedName, SgStatement, SgExpression, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgStaticAssertionDeclaration, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgGotoStatement, SgCatchStatementSeq, SgComputedGotoStatement, SgJavaSynchronizedStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAndOp, SgOrOp, and SgConditionalExp.
cfgFindChildIndex() [2/2]
virtual unsigned int SgNode::cfgFindChildIndex (SgNode * n) virtual
Find the index of n in this node's CFG children.
Reimplemented in SgInitializedName, SgStatement, SgIfStmt, SgForStatement, SgFunctionDefinition, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgRangeBasedForStatement, SgVariableDeclaration, SgLabelStatement, SgCaseOptionStmt, SgComputedGotoStatement, SgJavaSynchronizedStatement, SgExpression, SgCastExp, SgConditionalExp, SgNewExp, and SgDesignatedInitializer.
cfgFindNextChildIndex() [2/2]
virtual unsigned int SgNode::cfgFindNextChildIndex (SgNode * n) virtual
Find the index just after n in this node's CFG children.
Reimplemented in SgInitializedName, SgStatement, SgForStatement, SgWhileStmt, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgRangeBasedForStatement, and SgExpression.
cfgOutEdges() [2/2]
virtual std::vector< VirtualCFG::CFGEdge > SgNode::cfgOutEdges (unsigned int index = false) virtual
Find the out edges of a CFG node – internal version.
Reimplemented in SgInitializedName, SgStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgAssociateStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgFunctionParameterList, SgVariableDeclaration, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgUseStatement, SgEquivalenceStatement, SgInterfaceStatement, SgCommonBlock, SgTypedefDeclaration, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgModuleStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgContainsStatement, SgStaticAssertionDeclaration, SgEmptyDeclaration, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgNullStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgWhereStatement, SgElseWhereStatement, SgArithmeticIfStatement, SgComputedGotoStatement, SgOmpBodyStatement, SgOmpClauseBodyStatement, SgAssertStmt, SgJavaSynchronizedStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgExpression, SgUnaryOp, SgThrowOp, SgBinaryOp, SgAndOp, SgOrOp, SgExprListExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgFunctionCallExp, SgSizeOfOp, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgNullExpression, SgSubscriptExpression, SgAsteriskShapeExp, SgImpliedDo, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgPseudoDestructorRefExp, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgNoexceptOp, SgNonrealRefExp, and SgAdaAttributeExp.
cfgInEdges() [2/2]
virtual std::vector< VirtualCFG::CFGEdge > SgNode::cfgInEdges (unsigned int index = false) virtual
Find the in edges of a CFG node – internal version.
Reimplemented in SgInitializedName, SgStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgAssociateStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgFunctionParameterList, SgVariableDeclaration, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgUseStatement, SgEquivalenceStatement, SgInterfaceStatement, SgCommonBlock, SgTypedefDeclaration, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgModuleStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgContainsStatement, SgStaticAssertionDeclaration, SgEmptyDeclaration, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgNullStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgWhereStatement, SgElseWhereStatement, SgArithmeticIfStatement, SgComputedGotoStatement, SgOmpBodyStatement, SgOmpClauseBodyStatement, SgAssertStmt, SgJavaSynchronizedStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgExpression, SgUnaryOp, SgThrowOp, SgBinaryOp, SgAndOp, SgOrOp, SgExprListExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgFunctionCallExp, SgSizeOfOp, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgNullExpression, SgSubscriptExpression, SgAsteriskShapeExp, SgImpliedDo, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgPseudoDestructorRefExp, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgNoexceptOp, SgNonrealRefExp, and SgAdaAttributeExp.
numberOfNodesInSubtree() [2/2]
int SgNode::numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
This function is used as a basis for steps in AST isomophism tests. The implementation uses a traversal of the AST subtree to count the number of IR nodes. So the complexity if order N in the size of the subtree.
depthOfSubtree() [2/2]
int SgNode::depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
This function is used as a basis for steps in AST isomophism tests. The implementation uses a traversal of the AST subtree to count the depth of the AST traversal. So the complexity if order N in the size of the subtree.
post_construction_initialization() [2/2]
virtual void SgNode::post_construction_initialization () protected virtual
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
Reimplemented in SgModifierNodes, SgConstVolatileModifier, SgStorageModifier, SgAccessModifier, SgFunctionModifier, SgUPC_AccessModifier, SgSpecialFunctionModifier, SgElaboratedTypeModifier, SgLinkageModifier, SgBaseClassModifier, SgStructureModifier, SgTypeModifier, SgDeclarationModifier, SgOpenclAccessModeModifier, SgPragma, Sg_File_Info, SgBinaryComposite, SgJvmComposite, SgUnparse_Info, SgBaseClass, SgExpBaseClass, SgNonrealBaseClass, SgTemplateParameter, SgTemplateArgument, SgDirectory, SgGraph, SgIncidenceDirectedGraph, SgGraphNode, SgGraphEdge, SgDataStatementValue, SgTypeString, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgLocatedNode, SgInitializedName, SgAdaRangeConstraint, SgAdaIndexConstraint, SgAdaDigitsConstraint, SgAdaDeltaConstraint, SgAdaDiscriminantConstraint, SgAdaNullConstraint, SgStatement, SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, SgAdaVariantWhenStmt, SgExpression, SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, SgAdaUnitRefExp, SgNamespaceSymbol, and SgAliasSymbol.
createAndParent() [2/2]
template<class T > static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type SgNode::createAndParent (SgNode * parent) inline static
Allocate and return a new node after setting its parent.
ROSE's AST has this annoying, error-prone process for adding a node to the tree. One has to not only add the downward edge from parent to child, but also explicitly add the upward edge from child to parent. This two-step process makes it difficult to create child nodes and link them into the parent while the parent is being constructed. This function attempts to make this easier by doing everything in one step.
Use it like this:
Parent::Parent(int foo, int bar)
    : p_child(createAndParent<Child>(this), p_foo(foo), p_bar(bar) {}
Definition at line 925 of file SgNode.h.
initParentPointer() [2/2]
template<class T > T * SgNode::initParentPointer (T * child, SgNode * parent) inline
Generated for tree edge data member initializations.
When initializing a data member that's an edge in the tree, this sets the nodes parent pointer to this object and then returns the node. It is used in generated code for constructors, like this:
Foo::Foo(Bar *bar)
    : p_bar(adjustParent(bar, this)) {}
Definition at line 941 of file SgNode.h.
changeChildPointer() [3/4]
template<class T > std::enable_if< std::is_pointer< T >::value, void >::type SgNode::changeChildPointer (T & edge, T const & child) inline
Set a child edge in a tree to point to a specific child.
Normally one has to remember to set the parent pointer when adding a child to a tree, and also be careful that the result is still a tree. This helper function tries to make that easier by checking some things and setting the parent pointer automatically.
For instance, this should work:
SgAsmBinaryExpression *parent = ...;
SgAsmBinaryExpression *child1 = ...;
SgAsmBinaryExpression *child2 = ...;
parent->set_lhs(child1);
ASSERT_require(child1->get_parent() == parent);
parent->set_lhs(child2);
ASSERT_require(child1->get_parent() == nullptr);
ASSERT_require(child2->get_parent() == parent);
parent->set_lhs(nullptr);
ASSERT_require(child2->get_parent() == nullptr);
The following should not work when assertions are enabled:
SgAsmBinaryExpression *parent = ...;
SgAsmBinaryExpression *child1 = ...;
SgAsmBinaryExpression *child2 = ...;
parent->set_lhs(child1);
parent->set_rhs(child1); // no longer a tree, but still acyclic
Definition at line 1003 of file SgNode.h.
changeChildPointer() [4/4]
template<class T > std::enable_if<!std::is_pointer< T >::value, void >::type SgNode::changeChildPointer (T & edge, T const & child) inline
Set a child edge in a tree to point to a specific child.
Normally one has to remember to set the parent pointer when adding a child to a tree, and also be careful that the result is still a tree. This helper function tries to make that easier by checking some things and setting the parent pointer automatically.
For instance, this should work:
SgAsmBinaryExpression *parent = ...;
SgAsmBinaryExpression *child1 = ...;
SgAsmBinaryExpression *child2 = ...;
parent->set_lhs(child1);
ASSERT_require(child1->get_parent() == parent);
parent->set_lhs(child2);
ASSERT_require(child1->get_parent() == nullptr);
ASSERT_require(child2->get_parent() == parent);
parent->set_lhs(nullptr);
ASSERT_require(child2->get_parent() == nullptr);
The following should not work when assertions are enabled:
SgAsmBinaryExpression *parent = ...;
SgAsmBinaryExpression *child1 = ...;
SgAsmBinaryExpression *child2 = ...;
parent->set_lhs(child1);
parent->set_rhs(child1); // no longer a tree, but still acyclic
Definition at line 1049 of file SgNode.h.
destructorHelper() [2/2]
virtual void SgNode::destructorHelper () inline protected virtual
This gets called by all Rosebud-generated destructors.
Rosebud generates a call to destructorHelper from every destructor implementation. This gives the user a chance to do something special. There are some things to be aware of when reimplementing this function, and you should be well versed in the C++ rules about calling virtual functions from destructors.
The implementation must not attempt to access any data members of derived classes. These data members have already been destroyed by time this function is called.
Any calls you make to virtual functions declared in this class will dispatch only to implementations in this class or its base classes, not any derived classes.
Your implementation must expect to be called multiple times for the same object. This occurs when this class implements this function but its derived class does not. During destruction of a derived object, the derived class's Rosebud-generated destructor will call destructorHelper, which will dispatch to the implementation in this class. Then, when the part of the object corresponding to this class is being destroyed, the destructor will call destructorHelper again, which will dispatch to this implementation again. This may happen recursively mutliple times.
Your implementation should not destroy anything that a subclass might need during its destruction. This follows from the rule above, but is generally not a problem in practice. The reason it's not a problem is that the derived classes are usually Rosebud-generated and thus their destructors only call destructorHelper. Therefore, in order for any derived class to any work, it must be done in its destructorHelper, which would be called before the implementation of destructorHelper in this class is called.
All attempts should be made to avoid having to implement a destructorHelper in any class but the most base class (and that one does nothing). Instead, use data members whose own destructors do their cleanup. For instance, if this class needs a pointer to data allocated on the stack, then instead of using a raw pointer which needs to be deleted in this class's destructor, use a smart pointer whose own destructor deletes the data. If you follow this advice, then you don't need to be well-versed in the details of C++ object destruction.
Reimplemented in SgAsmJvmFileHeader, SgAsmJvmConstantPool, SgAsmGenericFile, SgAsmElfStrtab, SgAsmCoffStrtab, and SgAsmGenericSection.
Definition at line 1117 of file SgNode.h.
debugSerializationBegin() [2/2]
virtual void SgNode::debugSerializationBegin (const char * className) inline protected virtual
Called by generated serializers.
All generated serialization functions call this function as the first or last thing they do. This is a convenient place to put temporary debugging code or breakpoints if you're trying to figure out what went wrong. You can also it in particular derived classes if you need to debug just one class.
Definition at line 1127 of file SgNode.h.
debugSerializationEnd() [2/2]
virtual void SgNode::debugSerializationEnd (const char * className) inline protected virtual
Called by generated serializers.
All generated serialization functions call this function as the first or last thing they do. This is a convenient place to put temporary debugging code or breakpoints if you're trying to figure out what went wrong. You can also it in particular derived classes if you need to debug just one class.
Definition at line 1130 of file SgNode.h.
Member Data Documentation
all_pools
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > SgNode::all_pools static protected
Definition at line 886 of file Cxx_Grammar.h.
p_parent
SgNode::p_parent protected
This is the pointer to the parent IR node in the AST.
This is the pointer to the parent IR node in the AST. This is the pointer to the parent IR node. It is a valid pointer on all nodes that are traversed (SgExpressions, SgStatements, SgInitializedName, etc.) However it is not set on SgTypes and SgSymbols,both of which are shared internally. This pointer is mostly set in post processing of the Sage III AST, until this point it is not reliable.
This is the pointer to the parent IR node. It is a valid pointer on all nodes that are traversed (SgExpressions, SgStatements, SgInitializedName, etc.) However it is not set on SgTypes and SgSymbols,both of which are shared internally. This pointer is mostly set in post processing of the Sage III AST, until this point it is not reliable.
Definition at line 1190 of file Cxx_Grammar.h.
p_isModified
SgNode::p_isModified protected
Records if IR node has been modified (data members reset).
This is part of an internal mechanism that records if IR nodes have been modified, either by a transformation or a access function to set a value on the IR node. All access functions that set IR node data members are automatically generated (except the ones for this data member) and include code to set this boolean flag to true. This is also part of the support for copy based code generation where source file is copied except where the AST was modified an for these subtrees new code is generated from the AST.
Definition at line 1194 of file Cxx_Grammar.h.
p_containsTransformation
bool SgNode::p_containsTransformation protected
Definition at line 1198 of file Cxx_Grammar.h.
p_freepointer
SgNode::p_freepointer protected
This is the pointer to the chain of previously freed objects.
Definition at line 1202 of file Cxx_Grammar.h.
p_globalFunctionTypeTable
SgNode::p_globalFunctionTypeTable static protected
Pointer to symbol table specific to function types.
Definition at line 1206 of file Cxx_Grammar.h.
p_globalTypeTable
static SgTypeTable * SgNode::p_globalTypeTable static protected
Definition at line 1210 of file Cxx_Grammar.h.
p_globalMangledNameMap
SgNode::p_globalMangledNameMap static protected
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
Definition at line 1214 of file Cxx_Grammar.h.
p_shortMangledNameCache
SgNode::p_shortMangledNameCache static protected
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
Definition at line 1218 of file Cxx_Grammar.h.
p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > SgNode::p_globalQualifiedNameMapForNames static protected
Definition at line 1222 of file Cxx_Grammar.h.
p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > SgNode::p_globalQualifiedNameMapForTypes static protected
Definition at line 1226 of file Cxx_Grammar.h.
p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > SgNode::p_globalQualifiedNameMapForTemplateHeaders static protected
Definition at line 1230 of file Cxx_Grammar.h.
p_globalTypeNameMap
static std::map< SgNode *, std::string > SgNode::p_globalTypeNameMap static protected
Definition at line 1234 of file Cxx_Grammar.h.
p_globalQualifiedNameMapForMapsOfTypes
static std::map< SgNode *, std::map< SgNode *, std::string > > SgNode::p_globalQualifiedNameMapForMapsOfTypes static protected
Definition at line 1238 of file Cxx_Grammar.h.
The documentation for this class was generated from the following files:
Cxx_Grammar.h
SgNode.h
SgBinaryNode.docs
SgIsNotOp.docs
SgIsOp.docs
SgNode.docs