ROSE: SgStatement Class Reference
SgStatement Class Reference
Description
This class represents the notion of a statement.
There are no uses of this IR node anywhere. All statements are derived from this SgStatement class.
Definition at line 224723 of file Cxx_Grammar.h.
Public Types
enum { static_variant = V_SgStatement }
static variant value
typedef SgLocatedNode base_node_type
Public Types inherited from SgLocatedNode
enum { static_variant = V_SgLocatedNode }
static variant value
typedef SgNode base_node_type
Public Types inherited from SgNode
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
virtual SgNode * copy (SgCopyHelp &help) const override
virtual SgScopeStatement * get_scope (void) const
Returns scope of current statement.
virtual void setExtern ()
This function sets "extern" status for the current statement.
virtual void setStatic ()
This function sets "static" status for the current statement.
void insert_statement (SgStatement *target, SgStatement *newstmt, bool inFront=true)
This function inserts a single statement at the position indicated by target.
void insert_statement (SgStatement *target, const SgStatementPtrList &newstmtList, bool inFront=true)
This function inserts a list of statements at the position indicated by target.
void replace_statement (SgStatement *target, SgStatement *newstmt)
This function replaces the target statement with a single statement.
void replace_statement (SgStatement *target, const SgStatementPtrList &newstmtList)
This function replaces the target statement with a list of statements.
void remove_statement (SgStatement *)
This function removes the target statement from the AST.
void insert_statement_from_basicBlock (SgStatement *target, SgStatement *newstmt, bool inFront=true)
This function inserts a statement at the position indicated by target. If newstmt is a basicBlock, statements inside newstmt are extracted and then inserted.
void replace_statement_from_basicBlock (SgStatement *target, SgStatement *newstmt)
This function replaces the target statement with a new statement. If newstmt is a basicBlock, statements inside newstmt are extracted and then inserted.
virtual int replace_expression (SgExpression *original_expression, SgExpression *new_expression)
support general replace functions, used in statements that directly contain SgExpression IR nodes.
virtual void set_scope (SgScopeStatement *newScope)
Support for setting scopes (only meaningful on IR statements that store the scope explicitly).
virtual bool hasExplicitScope () const
Support for where the scope is explicitly required.
virtual SgSymbol * get_symbol_from_symbol_table () const
Get the associated symbol from the symbol table in the stored scope.
virtual unsigned int cfgIndexForEnd () const override
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const override
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n) override
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n) override
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index) override
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index) override
Find the in edges of a CFG node – internal version.
virtual bool isChildUsedAsLValue (const SgExpression *child) const
Virtual function to determine if the provided expression is used as an l-value within the cotext of this statement.
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const override
virtual void set_end_numeric_label (SgLabelRefExp *end_numeric_label)
virtual bool has_end_numeric_label () const
bool hasExplicitType ()
Some statement store internal SgType pointers explicitly. This function is true if it has a data member that is a type (only applies to SgTypedefDeclaration).
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
virtual std::string class_name () const override
returns a string representing the class name
virtual VariantT variantT () const override
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer () override
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer () override
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors () override
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx) override
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child) override
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI () override
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const override
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor) override
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const override
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const override
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgStatement (const SgStatementStorageClass &source)
IR node constructor to support AST File I/O.
SgStatement * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
SgLabelRefExp * get_numeric_label () const
void set_numeric_label (SgLabelRefExp *numeric_label)
int get_source_sequence_value () const
void set_source_sequence_value (int source_sequence_value)
virtual ~SgStatement ()
This is the destructor.
SgStatement (Sg_File_Info *startOfConstruct)
This is the constructor.
Public Member Functions inherited from SgLocatedNode
const std::string & getFilenameString () const
void addToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo::RelativePositionType locationInList=PreprocessingInfo::after)
This function adds comment or CPP directives to the current IR node.
void insertToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo *anchorInfoPtr, bool insertAfter=true)
Insert prepInfo After (or before if last parameter is false) an anchor info ptr in the list of preprocessing info attached to the current node. This is useful to insert things in the middle.
virtual Sg_File_Info * get_file_info () const override
Interface function to implement original SAGE interface to SgFile_Info objects.
virtual void set_file_info (Sg_File_Info *X)
Access function calls set_startingConstruct(Sg_File_Info*) member function.
void setCompilerGenerated ()
Allow IR nodes (mostly SgLocatedNode) to be marked as compiler generated.
void unsetCompilerGenerated ()
bool isCompilerGenerated () const
Simple test for if this is a compiler generated node.
void setTransformation ()
Allow IR nodes (mostly SgLocatedNode) to be marked as a transformation.
void unsetTransformation ()
bool isTransformation () const
Simple test for if this is a part of a transformation.
void setFrontendSpecific ()
Allow IR nodes (mostly SgLocatedNode) to be marked as front-end specific (generated by the front-end to support a specific backend compiler; e.g. GNU gcc and g++).
void unsetFrontendSpecific ()
bool isFrontendSpecific () const
Simple test for if this is a frontend specific IR node.
void setShared ()
Allow IR nodes (mostly SgLocatedNode) to be marked as shared.
void unsetShared ()
bool isShared () const
Simple test for if this is a shared IR node.
void setSourcePositionUnavailableInFrontend ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetSourcePositionUnavailableInFrontend ()
void setOutputInCodeGeneration ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetOutputInCodeGeneration ()
bool isOutputInCodeGeneration () const
int get_physical_file_id ()
Allow IR nodes (mostly SgLocatedNode) to be queried for there physical file ID.
AttachedPreprocessingInfoType *& getAttachedPreprocessingInfo (void)
Computes the number of nodes in the defined subtree of the AST.
Sg_File_Info * generateMatchingFileInfo ()
virtual void addNewAttribute (std::string s, AstAttribute *a) override
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const override
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a) override
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a) override
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s) override
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const override
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const override
Returns the number of attributes on this IR node.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgLocatedNode (const SgLocatedNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgLocatedNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
Sg_File_Info * get_startOfConstruct () const override
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
void set_startOfConstruct (Sg_File_Info *startOfConstruct)
This function sets the current source location position of the start of the current construct.
Sg_File_Info * get_endOfConstruct () const override
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
void set_endOfConstruct (Sg_File_Info *endOfConstruct)
This function sets the current source location position of the end of the current construct.
AttachedPreprocessingInfoType * get_attachedPreprocessingInfoPtr () const
void set_attachedPreprocessingInfoPtr (AttachedPreprocessingInfoType *attachedPreprocessingInfoPtr)
AstAttributeMechanism * get_attributeMechanism () const override
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
void set_attributeMechanism (AstAttributeMechanism *attributeMechanism) override
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
bool get_containsTransformationToSurroundingWhitespace () const
void set_containsTransformationToSurroundingWhitespace (bool containsTransformationToSurroundingWhitespace)
virtual ~SgLocatedNode ()
This is the destructor.
SgLocatedNode (Sg_File_Info *startOfConstruct=NULL)
This is the constructor.
Public Member Functions inherited from SgNode
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
Static Public Member Functions
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgStatement * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgStatement *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgStatement *sgnode)
Static Public Member Functions inherited from SgLocatedNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgLocatedNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgLocatedNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgLocatedNode *sgnode)
Static Public Member Functions inherited from SgNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Protected Member Functions
Private Supporting Functions for Low-Level Rewrite Interface
Low-level Support for mutation of the AST.
This is the lowest level of support for the mutation of the AST.
virtual bool replace_child (SgStatement *target, SgStatement *newStmt, bool extractListFromBasicBlock=false)
Private supporting function for low level SageIII rewrite interface.
virtual bool insert_child (SgStatement *, SgStatement *, bool inFront=true, bool extractListFromBasicBlock=false)
Private supporting function for low level SageIII rewrite interface.
Protected Member Functions inherited from SgNode
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Protected Attributes
SgLabelRefExp * p_numeric_label
int p_source_sequence_value
Protected Attributes inherited from SgLocatedNode
Sg_File_Info * p_startOfConstruct
This pointer is always valid and stores the source position of the start of the current construct.
Sg_File_Info * p_endOfConstruct
This pointer is always valid and stores the source position of the end of the current construct.
AttachedPreprocessingInfoType * p_attachedPreprocessingInfoPtr
Holds comments and/or preprocessor directives located before or after the current statement of expression.
AstAttributeMechanism * p_attributeMechanism
bool p_containsTransformationToSurroundingWhitespace
Protected Attributes inherited from SgNode
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Additional Inherited Members
Static Protected Attributes inherited from SgNode
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Member Typedef Documentation
base_node_type
typedef SgLocatedNode SgStatement::base_node_type
Definition at line 225358 of file Cxx_Grammar.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
static variant value
Definition at line 224979 of file Cxx_Grammar.h.
Constructor & Destructor Documentation
~SgStatement()
SgStatement::~SgStatement () virtual
This is the destructor.
There is nothing to delete in this object.
SgStatement()
SgStatement::SgStatement (Sg_File_Info * startOfConstruct = NULL)
This is the constructor.
This constructor builds the SgStatement base class.
Parameters
startOfConstruct represents the position in the source code
See also
Example:create an SgStatement object
Member Function Documentation
copy()
virtual SgNode * SgStatement::copy (SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, and SgPythonGlobalStmt.
get_scope()
SgStatement::get_scope (void) const virtual
Returns scope of current statement.
This functions returns a pointer to the inner most SgScopeStatement where the current statement is located. This is a function called after the parents have been set. It is not called by the EDG/SAGE interface and is only called after the SAGE AST has been built and the parent pointers set within a separate phase. Improtant exception: The SgFunctionParameterList should have as it's scope the SgFunctionDefinition, but it is a sibling of the SgFunctionDefinition (both the SgFunctionParameterList and the SgFunctionDefinition have the SgFunctionDeclaration as a parent. Thus the scope of the SgFunctionParameterList is computed to be the SgGlobal (global scope) most often; which is an error). So we handle this case explicitly.
Returns
Returns valid pointer to SgScopeStatement.
Reimplemented in SgEnumDeclaration, SgTemplateDeclaration, SgTypedefDeclaration, SgClassDeclaration, SgFunctionDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaGenericDecl, SgAdaGenericInstanceDecl, and SgLabelStatement.
Referenced by SageInterface::addMangledNameToCache(), SageInterface::appendStatementWithDependentDeclaration(), SageInterface::enclosingNamespaceScope(), SageBuilder::errorCheckingTargetAST(), SageBuilder::findAssociatedDeclarationInTargetAST(), SageBuilder::findAssociatedSymbolInTargetAST(), SageInterface::fixNamespaceDeclaration(), SageInterface::fixStatement(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::generateUniqueNameForUseAsIdentifier_support(), SageInterface::getClassTypeChainForMemberReference(), SageInterface::getNonInstantiatonDeclarationForClass(), SageInterface::getScope(), SageInterface::insertAfterUsingCommaOp(), SageInterface::insertStatement(), SageInterface::isLastStatement(), SageInterface::isMain(), SageInterface::lookupClassSymbolInParentScopes(), SageInterface::lookupEnumSymbolInParentScopes(), SageInterface::lookupFunctionSymbolInParentScopes(), SageInterface::lookupFunctionSymbolInParentScopes(), SageInterface::lookupNamespaceSymbolInParentScopes(), SageInterface::lookupNonrealSymbolInParentScopes(), SageInterface::lookupSymbolInParentScopes(), SageInterface::lookupSymbolInParentScopesIgnoringAliasSymbols(), SageInterface::lookupTemplateClassSymbolInParentScopes(), SageInterface::lookupTemplateFunctionSymbolInParentScopes(), SageInterface::lookupTemplateMemberFunctionSymbolInParentScopes(), SageInterface::lookupTemplateVariableSymbolInParentScopes(), SageInterface::lookupTypedefSymbolInParentScopes(), SageInterface::lookupVariableSymbolInParentScopes(), SageInterface::loopCollapsing(), SageInterface::loopTiling(), SageInterface::loopUnrolling(), SageInterface::moveDeclarationToAssociatedNamespace(), SageInterface::moveVariableDeclaration(), SageInterface::setBaseTypeDefiningDeclaration(), SageInterface::splitVariableDeclaration(), and SageInterface::updateDefiningNondefiningLinks().
setExtern()
SgStatement::setExtern () virtual
This function sets "extern" status for the current statement.
The new modifier mechanism makes this older function interface redundent.
Reimplemented in SgVariableDeclaration.
setStatic()
SgStatement::setStatic () virtual
This function sets "static" status for the current statement.
The new modifier mechanism makes this older function interface redundent.
Reimplemented in SgVariableDeclaration.
replace_child()
SgStatement::replace_child (SgStatement * target, SgStatement * newStmt, bool extractListFromBasicBlock = false) protected virtual
Private supporting function for low level SageIII rewrite interface.
This function implements special semantics for the insertion of a collection of statements in a block. If extractListFromBasicBlock is true then the statements in the block are extracts and placed into the same scope as the target position.
Returns
Returns bool.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgUpcForAllStatement, SgFunctionParameterScope, SgRangeBasedForStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgTypedefDeclaration, SgClassDeclaration, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgProgramHeaderStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgGotoStatement, SgForInitStatement, SgOmpBodyStatement, SgAdaExitStmt, and SgAdaLoopStmt.
insert_child()
SgStatement::insert_child (SgStatement * , SgStatement * , bool inFront = true, bool extractListFromBasicBlock = false) protected virtual
Private supporting function for low level SageIII rewrite interface.
 This function implements special semantics for the insertion of a collection of
statements in a block. If extractListFromBasicBlock is true then the statements in the block are extracts and placed into the same scope as the target position.
Returns
Returns bool.
Reimplemented in SgGlobal, SgBasicBlock, SgClassDefinition, SgNamespaceDefinitionStatement, SgFunctionParameterScope, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, and SgForInitStatement.
insert_statement() [1/2]
void SgStatement::insert_statement (SgStatement * target, SgStatement * newstmt, bool inFront = true)
This function inserts a single statement at the position indicated by target.
This function handles the insertion of the specified statement at the target location. The boolean variable specifies if the new statement is inserted before or after the target statement.
Parameters
target - location in the AST where new statement is to be inserted.
newstmt - New statement to be placed into the AST.
inFront - if true the new statement is inserted before the target statement, else the new statement is inserted after the target statement (default = true).
Returns
Function returns void.
Referenced by SageInterface::appendStatementWithDependentDeclaration(), SageInterface::insertHeader(), SageInterface::insertStatement(), and SageInterface::translateScopeToUseCppDeclarations().
insert_statement() [2/2]
void SgStatement::insert_statement (SgStatement * target, const SgStatementPtrList & newstmtList, bool inFront = true)
This function inserts a list of statements at the position indicated by target.
This function handles the insertion of a list of statements at the target location. The boolean variable specifies if the new statements are inserted before or after the target statement.
Parameters
target - location in the AST where new statements are to be inserted.
newstmt - List of new statements to be placed into the AST.
inFront - if true the new statements are inserted before the target statement, else the new statements are inserted after the target statement (default = true).
Returns
Function returns void.
replace_statement() [1/2]
void SgStatement::replace_statement (SgStatement * target, SgStatement * newstmt)
This function replaces the target statement with a single statement.
This function handles the replacement of the specified target statement with a new statement.
Parameters
target - location of the statement to be replaced.
newstmt - New statement to replace target statement in the AST.
Returns
Function returns void.
Referenced by SageInterface::changeBreakStatementsToGotos(), SageInterface::convertForToWhile(), SageInterface::myRemoveStatement(), SageInterface::replaceStatement(), and SageInterface::replaceSubexpressionWithStatement().
replace_statement() [2/2]
void SgStatement::replace_statement (SgStatement * target, const SgStatementPtrList & newstmtList)
This function replaces the target statement with a list of statements.
This function handles the replacement of the specified target statement with a list of statements at the target location.
Parameters
target - location of the statement to be replaced.
newstmt - List of new statements to replace the target statement in the AST.
Returns
Function returns void.
remove_statement()
void SgStatement::remove_statement (SgStatement *)
This function removes the target statement from the AST.
This function handles the removal of the target statement from the AST. Any comments or C preprocessor directives associated with the statement are also removed. This is a low level primitive for higher level functions (in the higher level interfaces) which take care to preserve such attributes.
Parameters
target - location of the statement to be removed.
Returns
Function returns void.
Referenced by SageInterface::removeStatement().
insert_statement_from_basicBlock()
void SgStatement::insert_statement_from_basicBlock (SgStatement * target, SgStatement * newstmt, bool inFront = true)
This function inserts a statement at the position indicated by target. If newstmt is a basicBlock, statements inside newstmt are extracted and then inserted.
This function handles the insertion of the specified statement at the target location. The boolean variable specifies if the new statement is inserted before or after the target statement. This function has somewhat unusual semantics.
replace_statement_from_basicBlock()
void SgStatement::replace_statement_from_basicBlock (SgStatement * target, SgStatement * newstmt)
This function replaces the target statement with a new statement. If newstmt is a basicBlock, statements inside newstmt are extracted and then inserted.
This function handles the replacement of the target statement with the new statement. This function has somewhat unusual semantics.
replace_expression()
virtual int SgStatement::replace_expression (SgExpression * original_expression, SgExpression * new_expression) virtual
support general replace functions, used in statements that directly contain SgExpression IR nodes.
Reimplemented in SgExprStatement, SgForStatement, SgUpcForAllStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgReturnStmt, SgAdaExitStmt, and SgAdaDelayStmt.
set_scope()
virtual void SgStatement::set_scope (SgScopeStatement * newScope) virtual
Support for setting scopes (only meaningful on IR statements that store the scope explicitly).
Reimplemented in SgAdaTaskBodyDecl, SgAdaProtectedBodyDecl, SgEnumDeclaration, SgTemplateDeclaration, SgTypedefDeclaration, SgClassDeclaration, SgFunctionDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaTaskTypeDecl, SgAdaProtectedTypeDecl, SgAdaGenericDecl, SgAdaGenericInstanceDecl, and SgLabelStatement.
Referenced by SageInterface::fixNamespaceDeclaration(), SageInterface::fixStatement(), and SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst().
hasExplicitScope()
virtual bool SgStatement::hasExplicitScope () const virtual
Support for where the scope is explicitly required.
Reimplemented in SgEnumDeclaration, SgTemplateDeclaration, SgTypedefDeclaration, SgClassDeclaration, SgFunctionDeclaration, SgStaticAssertionDeclaration, SgMicrosoftAttributeDeclaration, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaTaskTypeDecl, SgAdaProtectedTypeDecl, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaGenericInstanceDecl, and SgLabelStatement.
Referenced by SageInterface::addMangledNameToCache(), SageBuilder::errorCheckingTargetAST(), SageInterface::fixStatement(), and SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst().
get_symbol_from_symbol_table()
SgStatement::get_symbol_from_symbol_table () const virtual
Get the associated symbol from the symbol table in the stored scope.
Virtual function to obtain the SgSymbol from the scope's symbol table.
 This function permits retrival of the associated SgSymbol, where it exists
for that IR node, where is is associated with this exact declaration. If no symbol is found in the symbol table the function returns NULL. If it is not implemented for the associated statement or declaration it is an error (assertion failure). This fucntion is ONLY defined for those IR nodes for which symbols can be constructed.
Returns
Returns SgSymbol pointer.
Reimplemented in SgJavaLabelStatement, SgDeclarationStatement, SgEnumDeclaration, SgTemplateDeclaration, SgNamespaceDeclarationStatement, SgNamespaceAliasDeclarationStatement, SgTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgClassDeclaration, SgTemplateInstantiationDecl, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgNonrealDecl, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaVariantDecl, and SgLabelStatement.
Referenced by SageInterface::deleteAST().
cfgIndexForEnd()
virtual unsigned int SgStatement::cfgIndexForEnd () const override virtual
Determine the CFG index for the end of this construct.
Reimplemented from SgNode.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgAssociateStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgFunctionParameterList, SgVariableDeclaration, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgUseStatement, SgEquivalenceStatement, SgInterfaceStatement, SgCommonBlock, SgTypedefDeclaration, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgModuleStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgContainsStatement, SgStaticAssertionDeclaration, SgEmptyDeclaration, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgNullStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgWhereStatement, SgElseWhereStatement, SgArithmeticIfStatement, SgComputedGotoStatement, SgOmpBodyStatement, SgOmpClauseBodyStatement, SgAssertStmt, SgJavaSynchronizedStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, and SgAdaLoopStmt.
cfgIsIndexInteresting()
virtual bool SgStatement::cfgIsIndexInteresting (unsigned int index) const override virtual
Determine whether a particular CFG node index is "interesting" for this kind of node.
Reimplemented from SgNode.
Reimplemented in SgGlobal, SgJavaForEachStatement, SgJavaLabelStatement, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgStaticAssertionDeclaration, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgGotoStatement, SgCatchStatementSeq, SgComputedGotoStatement, SgJavaSynchronizedStatement, SgAdaExitStmt, SgAdaDelayStmt, and SgAdaLoopStmt.
cfgFindChildIndex()
virtual unsigned int SgStatement::cfgFindChildIndex (SgNode * n) override virtual
Find the index of n in this node's CFG children.
Reimplemented from SgNode.
Reimplemented in SgIfStmt, SgForStatement, SgFunctionDefinition, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgRangeBasedForStatement, SgVariableDeclaration, SgLabelStatement, SgCaseOptionStmt, SgComputedGotoStatement, and SgJavaSynchronizedStatement.
cfgFindNextChildIndex()
virtual unsigned int SgStatement::cfgFindNextChildIndex (SgNode * n) override virtual
Find the index just after n in this node's CFG children.
Reimplemented from SgNode.
Reimplemented in SgForStatement, SgWhileStmt, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, and SgRangeBasedForStatement.
cfgOutEdges()
virtual std::vector< VirtualCFG::CFGEdge > SgStatement::cfgOutEdges (unsigned int index) override virtual
Find the out edges of a CFG node – internal version.
Reimplemented from SgNode.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgAssociateStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgFunctionParameterList, SgVariableDeclaration, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgUseStatement, SgEquivalenceStatement, SgInterfaceStatement, SgCommonBlock, SgTypedefDeclaration, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgModuleStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgContainsStatement, SgStaticAssertionDeclaration, SgEmptyDeclaration, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgNullStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgWhereStatement, SgElseWhereStatement, SgArithmeticIfStatement, SgComputedGotoStatement, SgOmpBodyStatement, SgOmpClauseBodyStatement, SgAssertStmt, SgJavaSynchronizedStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, and SgAdaLoopStmt.
cfgInEdges()
virtual std::vector< VirtualCFG::CFGEdge > SgStatement::cfgInEdges (unsigned int index) override virtual
Find the in edges of a CFG node – internal version.
Reimplemented from SgNode.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgAssociateStatement, SgFortranDo, SgForAllStatement, SgUpcForAllStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgRangeBasedForStatement, SgAdaAcceptStmt, SgFunctionParameterList, SgVariableDeclaration, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgUseStatement, SgEquivalenceStatement, SgInterfaceStatement, SgCommonBlock, SgTypedefDeclaration, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgModuleStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgContainsStatement, SgStaticAssertionDeclaration, SgEmptyDeclaration, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgNullStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgWhereStatement, SgElseWhereStatement, SgArithmeticIfStatement, SgComputedGotoStatement, SgOmpBodyStatement, SgOmpClauseBodyStatement, SgAssertStmt, SgJavaSynchronizedStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, and SgAdaLoopStmt.
isChildUsedAsLValue()
SgStatement::isChildUsedAsLValue (const SgExpression * child) const virtual
Virtual function to determine if the provided expression is used as an l-value within the cotext of this statement.
Returns
True if the expression is used within this statement as an l-value.
Reimplemented in SgReturnStmt.
fixupCopy_scopes()
virtual void SgStatement::fixupCopy_scopes (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
fixupCopy_symbols()
virtual void SgStatement::fixupCopy_symbols (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
fixupCopy_references()
virtual void SgStatement::fixupCopy_references (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
set_end_numeric_label()
virtual void SgStatement::set_end_numeric_label (SgLabelRefExp * end_numeric_label) virtual
Reimplemented in SgIfStmt.
hasExplicitType()
bool SgStatement::hasExplicitType ()
Some statement store internal SgType pointers explicitly. This function is true if it has a data member that is a type (only applies to SgTypedefDeclaration).
Result is true if it stores a type explicitly as a data member, else false.
post_construction_initialization()
void SgStatement::post_construction_initialization () override virtual
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
Reimplemented from SgLocatedNode.
Reimplemented in SgTemplateFunctionDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgSwitchStatement, SgUpcForAllStatement, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgUsingDirectiveStatement, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgUsingDeclarationStatement, SgTemplateFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgUndefDirectiveStatement, SgWarningDirectiveStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgTryStmt, SgVariantStatement, SgWriteStatement, SgWaitStatement, SgWhereStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgWithStatement, SgWhenStmt, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, and SgUnlockStatement.
class_name()
virtual std::string SgStatement::class_name () const override virtual
returns a string representing the class name
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
Referenced by SageInterface::addMangledNameToCache(), SageInterface::appendStatement(), SageInterface::appendStatement(), SageInterface::cleanupNontransformedBasicBlockNode(), SageInterface::displayScope(), SageInterface::findSurroundingStatementFromSameFile(), SageInterface::fixStatement(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageBuilder::fixupSharingSourcePosition(), SageInterface::get_name(), SageInterface::getDependentDeclarations(), SageInterface::getLoopIndexVariable(), SageInterface::hasSameGlobalScope(), SageInterface::insertStatement(), SageInterface::lastFrontEndSpecificStatement(), SageInterface::lastStatementOfScopeWithTokenInfo(), SageInterface::moveCommentsToNewStatement(), SageInterface::moveDeclarationToAssociatedNamespace(), SageInterface::movePreprocessingInfo(), SageInterface::prependStatement(), SageInterface::prependStatement(), SageInterface::removeStatement(), SageInterface::resetInternalMapsForTargetStatement(), and SageInterface::translateScopeToUseCppDeclarations().
variantT()
virtual VariantT SgStatement::variantT () const override virtual
returns new style SageIII enum values
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
Referenced by SageInterface::cleanupNontransformedBasicBlockNode(), SageInterface::findEnclosingLoop(), SageInterface::fixStatement(), and SageInterface::get_name().
operator delete()
void SgStatement::operator delete (void * pointer) inline
Definition at line 225034 of file Cxx_Grammar.h.
get_traversalSuccessorContainer()
virtual std::vector< SgNode * > SgStatement::get_traversalSuccessorContainer () override virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
get_traversalSuccessorNamesContainer()
virtual std::vector< std::string > SgStatement::get_traversalSuccessorNamesContainer () override virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
get_numberOfTraversalSuccessors()
virtual size_t SgStatement::get_numberOfTraversalSuccessors () override virtual
return number of children in the traversal successor list
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
get_traversalSuccessorByIndex()
virtual SgNode * SgStatement::get_traversalSuccessorByIndex (size_t idx) override virtual
index-based access to traversal successors by index number
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
get_childIndex()
virtual size_t SgStatement::get_childIndex (SgNode * child) override virtual
index-based access to traversal successors by child node
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
roseRTI()
virtual RTIReturnType SgStatement::roseRTI () override virtual
return C++ Runtime-Time-Information
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
sage_class_name()
virtual const char * SgStatement::sage_class_name () const override virtual
returns a C style string (char*) representing the class name
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
accept()
virtual void SgStatement::accept (ROSE_VisitorPattern & visitor) override virtual
support for the classic visitor pattern done in GoF
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
isInMemoryPool()
virtual bool SgStatement::isInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
checkDataMemberPointersIfInMemoryPool()
virtual void SgStatement::checkDataMemberPointersIfInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
returnDataMemberPointers()
virtual std::vector< std::pair< SgNode *, std::string > > SgStatement::returnDataMemberPointers () const override virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
processDataMemberReferenceToPointers()
virtual void SgStatement::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
getChildIndex()
virtual long SgStatement::getChildIndex (SgNode * childNode) const override virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented from SgLocatedNode.
Reimplemented in SgScopeStatement, SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, SgAdaGenericDefn, SgFunctionTypeTable, SgDeclarationStatement, SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, SgAdaVariantDecl, SgExprStatement, SgLabelStatement, SgCaseOptionStmt, SgTryStmt, SgDefaultOptionStmt, SgBreakStmt, SgContinueStmt, SgReturnStmt, SgGotoStatement, SgSpawnStmt, SgNullStatement, SgVariantStatement, SgForInitStatement, SgCatchStatementSeq, SgProcessControlStatement, SgIOStatement, SgPrintStatement, SgReadStatement, SgWriteStatement, SgOpenStatement, SgCloseStatement, SgInquireStatement, SgFlushStatement, SgBackspaceStatement, SgRewindStatement, SgEndfileStatement, SgWaitStatement, SgFortranContinueStmt, SgWhereStatement, SgElseWhereStatement, SgNullifyStatement, SgArithmeticIfStatement, SgAssignStatement, SgComputedGotoStatement, SgAssignedGotoStatement, SgAllocateStatement, SgDeallocateStatement, SgUpcNotifyStatement, SgUpcWaitStatement, SgUpcBarrierStatement, SgUpcFenceStatement, SgOmpBarrierStatement, SgOmpTaskwaitStatement, SgOmpFlushStatement, SgOmpBodyStatement, SgOmpMasterStatement, SgOmpOrderedStatement, SgOmpCriticalStatement, SgOmpSectionStatement, SgOmpWorkshareStatement, SgOmpClauseBodyStatement, SgOmpParallelStatement, SgOmpSingleStatement, SgOmpAtomicStatement, SgOmpTaskStatement, SgOmpForStatement, SgOmpDoStatement, SgOmpSectionsStatement, SgOmpTargetStatement, SgOmpTargetDataStatement, SgOmpSimdStatement, SgOmpForSimdStatement, SgSequenceStatement, SgWithStatement, SgPythonPrintStmt, SgPassStatement, SgAssertStmt, SgExecStatement, SgPythonGlobalStmt, SgJavaThrowStatement, SgJavaSynchronizedStatement, SgAsyncStmt, SgFinishStmt, SgAtStmt, SgAtomicStmt, SgWhenStmt, SgImageControlStatement, SgSyncAllStatement, SgSyncImagesStatement, SgSyncMemoryStatement, SgSyncTeamStatement, SgLockStatement, SgUnlockStatement, SgAdaExitStmt, SgAdaDelayStmt, SgAdaLoopStmt, SgAdaSelectStmt, SgAdaSelectAlternativeStmt, SgAdaTerminateStmt, SgAdaUnscopedBlock, and SgAdaVariantWhenStmt.
addRegExpAttribute()
SgStatement * SgStatement::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
Member Data Documentation
p_numeric_label
SgLabelRefExp* SgStatement::p_numeric_label protected
Definition at line 225382 of file Cxx_Grammar.h.
p_source_sequence_value
int SgStatement::p_source_sequence_value protected
Definition at line 225386 of file Cxx_Grammar.h.
The documentation for this class was generated from the following files:
Cxx_Grammar.h
SgStatement.docs