ROSE: SgDeclarationStatement Class Reference
SgDeclarationStatement Class Reference
Description
This class represents the concept of a declaration statement.
Declaration statements are where variables and types are defined and become available for use within a program. Declarations are strored in symbols (SgSymbol) and used to associate the symbol with a location within a scope within the application source code. There are many different types of declarations, within Sage III the SgDeclaration forms a base class for numerous IR nodes such as: class declarations (including structs and unions), enum declarations, function declarations, namespace declarations, pragma declarations, template declarations, typedef declarations, using declarations, using directives, variable declarations, etc.
An important concept for a few types fo declarations is that of defining vs. non-defining. Defining declarations are associated with definitions, for example a class definition or function definition. A class declaration where a class is defined (instead of a forward declaration) is a defining declaration. A forward declaration is a non-defining declaration. Some declarations are not explicitly forward declarations, they are non-defining declarations. Only declarations where there is a definition are defining declarations. Because definitions can at most appear once within a translation unit (a source file and it included header files), there is at most one defining declaration. The defining declaration is never shared, however the non-defining declaration can be shared and is required to be shared if there is more than one location in the AST where a non-defining declaration is required. There is at most one defining and one non-defining declaration (at some point they will also share their name, but this is not implemented yet). If a variable is defined to be extern or only defined through a refererence or pointer, then there would be no defining declaration (only a non-defining declaration).
The following code contains no defining declaration for the type "foobar":
typedef struct foobar *((FunctionPointer)(void);
foobar* foobar_pointer = NULL;
and yet is valid code (even though there is no explicit forward declaration of "foobar" as a class (or struct). In this case foobar is represented using a non-defining declaration internally and that declaration is reference multiple types (once within each statement). Note that the code above is valid C++, and not valid C code (to make it valid C code we would have to add "struct" the pointer declaration, for example:
struct foobar* foobar_pointer = NULL;
So C++ is not always a super set of C :-).
Different types of declarations explained: C and C++ declarations can come in several forms, for example:
typedef struct { int A; } A; // unnamed class declaration (which gets a name from the typedef)
struct A { int i; };         // autonomous declaration
struct B { int i; } b;       // non autonomous declaration
In these cases "struct" and "class" can be used interchangablily. Internally "struct" and "class" are he same (but with a different enum to classify them, see SgNameType and SgClassType). Clearly most C++ code uses autonomous declarations.
There are no uses of this IR node anywhere. All statements are derived from this SgDeclarationStatement class.
Definition at line 268250 of file Cxx_Grammar.h.
Public Types
enum template_specialization_enum {
e_unknown = 0 ,
e_no_specialization = 1 ,
e_partial_specialization = 2 ,
e_specialization = 3 ,
e_template_specialization_last = 4
}
Template Specialization Support.
enum gnu_extension_visability_attribute_enum {
e_gnu_attribute_visability_unknown = 0 ,
e_gnu_attribute_visability_unspecified = 1 ,
e_gnu_attribute_visability_hidden = 2 ,
e_gnu_attribute_visability_protected = 3 ,
e_gnu_attribute_visability_internal = 4 ,
e_last_gnu_visability_attribute
}
GNU extension for visibility modifier (only one value can be specified)
enum { static_variant = V_SgDeclarationStatement }
static variant value
typedef SgStatement base_node_type
Public Types inherited from SgStatement
enum { static_variant = V_SgStatement }
static variant value
typedef SgLocatedNode base_node_type
Public Types inherited from SgLocatedNode
enum { static_variant = V_SgLocatedNode }
static variant value
typedef SgNode base_node_type
Public Types inherited from SgNode
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
virtual SgNode * copy (SgCopyHelp &help) const override
bool isForward () const
Returns boolean value indicating if this is a forward declaration.
void setForward ()
Marks a declaration as a forward declaration.
void unsetForward ()
Marks a forward declaration as a non-forward declaration.
bool isNameOnly () const
void setNameOnly ()
void unsetNameOnly ()
bool isExternBrace () const
void setExternBrace ()
void unsetExternBrace ()
bool skipElaborateType () const
void setSkipElaborateType ()
void unsetSkipElaborateType ()
virtual SgName get_mangled_name (void) const
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const override
SgQualifiedNamePtrList & get_qualifiedNameList ()
const SgQualifiedNamePtrList & get_qualifiedNameList () const
void set_qualifiedNameList (const SgQualifiedNamePtrList &x)
virtual SgSymbol * get_symbol_from_symbol_table () const override
FOR INTERNAL USE Get the associated symbol from the symbol table in the stored scope. Users should use the SgDeclarationStatement::search_for_symbol_from_symbol_table() instead.
SgDeclarationStatement * get_declaration_associated_with_symbol () const
SgSymbol * search_for_symbol_from_symbol_table () const
User interface for retrieving the associated symbol from the declaration.
bool hasAssociatedSymbol () const
Returns boolean value true of this type of declaration has an associated sysmbol.
SgName get_qualified_name_prefix () const
This function generates the qualified name prefix to be used with the named declaration (only applied to restricted set of declarations where name qualification can be used).
SgName get_template_name () const
This function returns the template name (taken from the template declaration for the class, function, member function, or variable template declaration).
SgDeclarationStatement * get_definingDeclaration () const
This is an access function for the SgDeclarationStatement::p_definingDeclaration data member (see that variable's documentation for details).
void set_definingDeclaration (SgDeclarationStatement *definingDeclaration)
This is an access function for the SgDeclarationStatement::p_definingDeclaration data member (see that variable's documentation for details).
SgDeclarationStatement * get_firstNondefiningDeclaration () const
This is an access function for the SgDeclarationStatement::p_firstNondefiningDeclaration data member (see that variable's documentation for details).
void set_firstNondefiningDeclaration (SgDeclarationStatement *firstNondefiningDeclaration)
This is an access function for the SgDeclarationStatement::p_firstNondefiningDeclaration data member (see that variable's documentation for details).
SgType * get_type () const
std::string unparseNameToString ()
virtual std::string class_name () const override
returns a string representing the class name
virtual VariantT variantT () const override
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer () override
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer () override
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors () override
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx) override
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child) override
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI () override
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const override
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor) override
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const override
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const override
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgDeclarationStatement (const SgDeclarationStatementStorageClass &source)
IR node constructor to support AST File I/O.
SgDeclarationStatement * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
unsigned int get_decl_attributes () const
void set_decl_attributes (unsigned int decl_attributes)
std::string get_linkage () const
void set_linkage (std::string linkage)
const SgDeclarationModifier & get_declarationModifier () const
SgDeclarationModifier & get_declarationModifier ()
Returns SgDeclarationModifier object by reference (so that it can be set).
bool get_nameOnly () const
void set_nameOnly (bool nameOnly)
bool get_forward () const
void set_forward (bool forward)
bool get_externBrace () const
void set_externBrace (bool externBrace)
bool get_skipElaborateType () const
void set_skipElaborateType (bool skipElaborateType)
std::string get_binding_label () const
void set_binding_label (std::string binding_label)
SgDeclarationScope * get_declarationScope () const
void set_declarationScope (SgDeclarationScope *declarationScope)
bool get_unparse_template_ast () const
void set_unparse_template_ast (bool unparse_template_ast)
SgExprListExp * get_adaAspects () const
void set_adaAspects (SgExprListExp *adaAspects)
virtual ~SgDeclarationStatement ()
This is the destructor.
SgDeclarationStatement (Sg_File_Info *startOfConstruct)
This is the constructor.
Public Member Functions inherited from SgStatement
virtual SgScopeStatement * get_scope (void) const
Returns scope of current statement.
virtual void setExtern ()
This function sets "extern" status for the current statement.
virtual void setStatic ()
This function sets "static" status for the current statement.
void insert_statement (SgStatement *target, SgStatement *newstmt, bool inFront=true)
This function inserts a single statement at the position indicated by target.
void insert_statement (SgStatement *target, const SgStatementPtrList &newstmtList, bool inFront=true)
This function inserts a list of statements at the position indicated by target.
void replace_statement (SgStatement *target, SgStatement *newstmt)
This function replaces the target statement with a single statement.
void replace_statement (SgStatement *target, const SgStatementPtrList &newstmtList)
This function replaces the target statement with a list of statements.
void remove_statement (SgStatement *)
This function removes the target statement from the AST.
void insert_statement_from_basicBlock (SgStatement *target, SgStatement *newstmt, bool inFront=true)
This function inserts a statement at the position indicated by target. If newstmt is a basicBlock, statements inside newstmt are extracted and then inserted.
void replace_statement_from_basicBlock (SgStatement *target, SgStatement *newstmt)
This function replaces the target statement with a new statement. If newstmt is a basicBlock, statements inside newstmt are extracted and then inserted.
virtual int replace_expression (SgExpression *original_expression, SgExpression *new_expression)
support general replace functions, used in statements that directly contain SgExpression IR nodes.
virtual void set_scope (SgScopeStatement *newScope)
Support for setting scopes (only meaningful on IR statements that store the scope explicitly).
virtual bool hasExplicitScope () const
Support for where the scope is explicitly required.
virtual unsigned int cfgIndexForEnd () const override
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const override
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n) override
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n) override
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index) override
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index) override
Find the in edges of a CFG node – internal version.
virtual bool isChildUsedAsLValue (const SgExpression *child) const
Virtual function to determine if the provided expression is used as an l-value within the cotext of this statement.
virtual void set_end_numeric_label (SgLabelRefExp *end_numeric_label)
virtual bool has_end_numeric_label () const
bool hasExplicitType ()
Some statement store internal SgType pointers explicitly. This function is true if it has a data member that is a type (only applies to SgTypedefDeclaration).
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgStatement (const SgStatementStorageClass &source)
IR node constructor to support AST File I/O.
SgStatement * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
SgLabelRefExp * get_numeric_label () const
void set_numeric_label (SgLabelRefExp *numeric_label)
int get_source_sequence_value () const
void set_source_sequence_value (int source_sequence_value)
virtual ~SgStatement ()
This is the destructor.
SgStatement (Sg_File_Info *startOfConstruct)
This is the constructor.
Public Member Functions inherited from SgLocatedNode
const std::string & getFilenameString () const
void addToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo::RelativePositionType locationInList=PreprocessingInfo::after)
This function adds comment or CPP directives to the current IR node.
void insertToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo *anchorInfoPtr, bool insertAfter=true)
Insert prepInfo After (or before if last parameter is false) an anchor info ptr in the list of preprocessing info attached to the current node. This is useful to insert things in the middle.
virtual Sg_File_Info * get_file_info () const override
Interface function to implement original SAGE interface to SgFile_Info objects.
virtual void set_file_info (Sg_File_Info *X)
Access function calls set_startingConstruct(Sg_File_Info*) member function.
void setCompilerGenerated ()
Allow IR nodes (mostly SgLocatedNode) to be marked as compiler generated.
void unsetCompilerGenerated ()
bool isCompilerGenerated () const
Simple test for if this is a compiler generated node.
void setTransformation ()
Allow IR nodes (mostly SgLocatedNode) to be marked as a transformation.
void unsetTransformation ()
bool isTransformation () const
Simple test for if this is a part of a transformation.
void setFrontendSpecific ()
Allow IR nodes (mostly SgLocatedNode) to be marked as front-end specific (generated by the front-end to support a specific backend compiler; e.g. GNU gcc and g++).
void unsetFrontendSpecific ()
bool isFrontendSpecific () const
Simple test for if this is a frontend specific IR node.
void setShared ()
Allow IR nodes (mostly SgLocatedNode) to be marked as shared.
void unsetShared ()
bool isShared () const
Simple test for if this is a shared IR node.
void setSourcePositionUnavailableInFrontend ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetSourcePositionUnavailableInFrontend ()
void setOutputInCodeGeneration ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetOutputInCodeGeneration ()
bool isOutputInCodeGeneration () const
int get_physical_file_id ()
Allow IR nodes (mostly SgLocatedNode) to be queried for there physical file ID.
AttachedPreprocessingInfoType *& getAttachedPreprocessingInfo (void)
Computes the number of nodes in the defined subtree of the AST.
Sg_File_Info * generateMatchingFileInfo ()
virtual void addNewAttribute (std::string s, AstAttribute *a) override
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const override
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a) override
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a) override
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s) override
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const override
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const override
Returns the number of attributes on this IR node.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgLocatedNode (const SgLocatedNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgLocatedNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
Sg_File_Info * get_startOfConstruct () const override
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
void set_startOfConstruct (Sg_File_Info *startOfConstruct)
This function sets the current source location position of the start of the current construct.
Sg_File_Info * get_endOfConstruct () const override
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
void set_endOfConstruct (Sg_File_Info *endOfConstruct)
This function sets the current source location position of the end of the current construct.
AttachedPreprocessingInfoType * get_attachedPreprocessingInfoPtr () const
void set_attachedPreprocessingInfoPtr (AttachedPreprocessingInfoType *attachedPreprocessingInfoPtr)
AstAttributeMechanism * get_attributeMechanism () const override
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
void set_attributeMechanism (AstAttributeMechanism *attributeMechanism) override
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
bool get_containsTransformationToSurroundingWhitespace () const
void set_containsTransformationToSurroundingWhitespace (bool containsTransformationToSurroundingWhitespace)
virtual ~SgLocatedNode ()
This is the destructor.
SgLocatedNode (Sg_File_Info *startOfConstruct=NULL)
This is the constructor.
Public Member Functions inherited from SgNode
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
Static Public Member Functions
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgDeclarationStatement * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgDeclarationStatement *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgDeclarationStatement *sgnode)
Static Public Member Functions inherited from SgStatement
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgStatement * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgStatement *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgStatement *sgnode)
Static Public Member Functions inherited from SgLocatedNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgLocatedNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgLocatedNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgLocatedNode *sgnode)
Static Public Member Functions inherited from SgNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Protected Member Functions
void resetTemplateNameSupport (bool &nameResetFromMangledForm, SgName &name)
void testForBadGenerateTemplateName (const std::string &name)
bool skipEmptyTemplateArgumentListTest (SgFunctionDeclaration *functionDeclaration)
SgName fixupTemplateNameForMangledNameSupport (const SgName &s) const
SgName generate_alternative_name_for_unnamed_declaration (SgNode *parent) const
SgName generate_alternative_name_for_unnamed_declaration_in_scope (SgScopeStatement *scope) const
Protected Member Functions inherited from SgStatement
virtual bool replace_child (SgStatement *target, SgStatement *newStmt, bool extractListFromBasicBlock=false)
Private supporting function for low level SageIII rewrite interface.
virtual bool insert_child (SgStatement *, SgStatement *, bool inFront=true, bool extractListFromBasicBlock=false)
Private supporting function for low level SageIII rewrite interface.
Protected Member Functions inherited from SgNode
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Protected Attributes
unsigned int p_decl_attributes
This is old and used to be used to hold modifiers.
std::string p_linkage
This string stores the value "C", "C++", or "fortran" to define the external linkage for generating linkable names.
SgDeclarationModifier p_declarationModifier
This is the mechanism to handle declaration modifiers.
bool p_nameOnly
I think this is somewhat redundant with the purpose of specifying a forward declaration. Either that or it is information used by the unparser (Oh, I hope not!).
bool p_forward
This marks a declaration as being an explicit forward declaration.
bool p_externBrace
This marks that the declaration appeared with "extern".
bool p_skipElaborateType
This marks "type elaboration" which is the use of the keyword "class" before variables of type class.
SgDeclarationStatement * p_definingDeclaration
This pointer is valid only if a defining declaration exists, and stores the defining declaration where the declaration was defined.
SgDeclarationStatement * p_firstNondefiningDeclaration
This pointer is valid if there is a non-defining declaration, and stores the first non-defining declaration where a declaration was made explicitly (as in forward declaration) or implicitly as in the case of a few IR nodes (e.g. SgClassDeclaration). See description of SgDeclarationStatement.
SgQualifiedNamePtrList p_qualifiedNameList
std::string p_binding_label
SgDeclarationScope * p_declarationScope
bool p_unparse_template_ast
SgExprListExp * p_adaAspects
Protected Attributes inherited from SgStatement
SgLabelRefExp * p_numeric_label
int p_source_sequence_value
Protected Attributes inherited from SgLocatedNode
Sg_File_Info * p_startOfConstruct
This pointer is always valid and stores the source position of the start of the current construct.
Sg_File_Info * p_endOfConstruct
This pointer is always valid and stores the source position of the end of the current construct.
AttachedPreprocessingInfoType * p_attachedPreprocessingInfoPtr
Holds comments and/or preprocessor directives located before or after the current statement of expression.
AstAttributeMechanism * p_attributeMechanism
bool p_containsTransformationToSurroundingWhitespace
Protected Attributes inherited from SgNode
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Additional Inherited Members
Static Protected Attributes inherited from SgNode
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Member Typedef Documentation
base_node_type
typedef SgStatement SgDeclarationStatement::base_node_type
Definition at line 268820 of file Cxx_Grammar.h.
Member Enumeration Documentation
template_specialization_enum
enum SgDeclarationStatement::template_specialization_enum
Template Specialization Support.
different forms of template specialization for - classes, functions, and variable declarations
Enumerator
e_unknown
unknown value (error value)
e_no_specialization
not a specialization (default value)
e_partial_specialization
partial specialization
e_specialization
specialization
e_template_specialization_last
last value (unused)
Definition at line 268267 of file Cxx_Grammar.h.
gnu_extension_visability_attribute_enum
enum SgDeclarationStatement::gnu_extension_visability_attribute_enum
GNU extension for visibility modifier (only one value can be specified)
Visibility modifier information about (unspecified, hidden, protected, internal).
Enumerator
e_gnu_attribute_visability_unknown
Unknown value (error)
e_gnu_attribute_visability_unspecified
Default value
e_gnu_attribute_visability_hidden
hidden visibility attribute
e_gnu_attribute_visability_protected
protected visibility attribute
e_gnu_attribute_visability_internal
internal visibility attribute
e_last_gnu_visability_attribute
last visibility attribute value (upper bound on range of values, used in error checking)
Definition at line 268282 of file Cxx_Grammar.h.
anonymous enum
anonymous enum
static variant value
Definition at line 268441 of file Cxx_Grammar.h.
Constructor & Destructor Documentation
~SgDeclarationStatement()
SgDeclarationStatement::~SgDeclarationStatement () virtual
This is the destructor.
There are a lot of things to delete, but nothing is deleted in this destructor.
SgDeclarationStatement()
SgDeclarationStatement::SgDeclarationStatement (Sg_File_Info * startOfConstruct = NULL)
This is the constructor.
This constructor builds the SgDeclarationStatement base class.
Parameters
startOfConstruct represents the position in the source code
Member Function Documentation
copy()
virtual SgNode * SgDeclarationStatement::copy (SgCopyHelp & help) const override virtual
Reimplemented from SgStatement.
isForward()
SgDeclarationStatement::isForward () const
Returns boolean value indicating if this is a forward declaration.
Returns
Returns bool.
Referenced by SageInterface::buildForwardFunctionDeclaration(), SageInterface::isPrototypeInScope(), and SageInterface::rebuildSymbolTable().
setForward()
SgDeclarationStatement::setForward ()
Marks a declaration as a forward declaration.
Returns
Returns void.
Referenced by SageBuilder::buildNamespaceDeclaration_nfi(), SageBuilder::buildNondefiningClassDeclaration(), SageBuilder::buildNondefiningClassDeclaration_nfi(), SageBuilder::buildNondefiningEnumDeclaration_nfi(), SageBuilder::buildNondefiningTemplateClassDeclaration_nfi(), SageBuilder::buildStructDeclaration(), and SageBuilder::buildTemplateClassDeclaration_nfi().
unsetForward()
SgDeclarationStatement::unsetForward ()
Marks a forward declaration as a non-forward declaration.
Returns
Returns void.
get_mangled_name()
virtual SgName SgDeclarationStatement::get_mangled_name (void) const virtual
Reimplemented in SgTemplateInstantiationMemberFunctionDecl, SgOmpThreadprivateStatement, and SgOmpDeclareSimdStatement.
fixupCopy_scopes()
virtual void SgDeclarationStatement::fixupCopy_scopes (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgStatement.
fixupCopy_symbols()
virtual void SgDeclarationStatement::fixupCopy_symbols (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgStatement.
fixupCopy_references()
virtual void SgDeclarationStatement::fixupCopy_references (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgStatement.
get_symbol_from_symbol_table()
SgDeclarationStatement::get_symbol_from_symbol_table () const override virtual
FOR INTERNAL USE Get the associated symbol from the symbol table in the stored scope. Users should use the SgDeclarationStatement::search_for_symbol_from_symbol_table() instead.
Reimplemented from SgStatement.
Reimplemented in SgEnumDeclaration, SgTemplateDeclaration, SgNamespaceDeclarationStatement, SgNamespaceAliasDeclarationStatement, SgTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgClassDeclaration, SgTemplateInstantiationDecl, SgFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgNonrealDecl, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, and SgAdaVariantDecl.
Referenced by SageInterface::appendStatementWithDependentDeclaration(), SageBuilder::buildFunctionRefExp(), SageBuilder::buildNondefiningTemplateFunctionDeclaration(), SageBuilder::buildNondefiningTemplateMemberFunctionDeclaration(), and CollectDependentDeclarationsTraversal::visit().
search_for_symbol_from_symbol_table()
SgDeclarationStatement::search_for_symbol_from_symbol_table () const
User interface for retrieving the associated symbol from the declaration.
Returns
Returns SgSymbol pointer.
Referenced by SageBuilder::buildTemplateInstantiationTypedefDeclaration_nfi(), SageBuilder::buildTemplateTypedefDeclaration_nfi(), SageBuilder::buildTypedefDeclaration_nfi(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), and CollectDependentDeclarationsTraversal::visit().
hasAssociatedSymbol()
SgDeclarationStatement::hasAssociatedSymbol () const
Returns boolean value true of this type of declaration has an associated sysmbol.
Returns
Returns bool.
Referenced by CollectDependentDeclarationsTraversal::visit().
class_name()
virtual std::string SgDeclarationStatement::class_name () const override virtual
returns a string representing the class name
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
Referenced by SageInterface::appendStatementWithDependentDeclaration(), SageBuilder::appendTemplateArgumentsToName(), SageBuilder::buildClassDeclaration_nfi(), SageBuilder::buildFile(), SageBuilder::buildTypedefDeclaration_nfi(), SageInterface::checkAccessPermissions(), SageInterface::declarationPreceedsDefinition(), SageBuilder::findAssociatedDeclarationInTargetAST(), SageBuilder::findAssociatedSymbolInTargetAST(), SageInterface::fixStructDeclaration(), SageInterface::generateUniqueNameForUseAsIdentifier(), SageInterface::generateUniqueNameForUseAsIdentifier_support(), SageInterface::get_name(), SageInterface::getClassTypeChainForMemberReference(), SageBuilder::getTargetFileType(), SageBuilder::getTargetFileTypeSupport(), SageBuilder::getTemplateArgumentList(), SageBuilder::getTemplateParameterList(), SageInterface::insertHeader(), SageInterface::moveDeclarationToAssociatedNamespace(), SageInterface::rebuildSymbolTable(), SageBuilder::setTemplateArgumentParents(), SageBuilder::testTemplateArgumentParents(), SageBuilder::testTemplateParameterParents(), and SageInterface::updateDefiningNondefiningLinks().
variantT()
virtual VariantT SgDeclarationStatement::variantT () const override virtual
returns new style SageIII enum values
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
Referenced by SageInterface::appendStatementWithDependentDeclaration(), SageBuilder::appendTemplateArgumentsToName(), SageBuilder::findAssociatedDeclarationInTargetAST(), SageBuilder::findAssociatedSymbolInTargetAST(), SageInterface::generateUniqueNameForUseAsIdentifier_support(), SageInterface::get_name(), SageBuilder::getTemplateArgumentList(), SageBuilder::getTemplateParameterList(), SageInterface::rebuildSymbolTable(), SageInterface::set_name(), SageBuilder::setTemplateArgumentsInDeclaration(), SageBuilder::setTemplateParametersInDeclaration(), and SageBuilder::setTemplateSpecializationArgumentsInDeclaration().
operator delete()
void SgDeclarationStatement::operator delete (void * pointer) inline
Definition at line 268496 of file Cxx_Grammar.h.
get_traversalSuccessorContainer()
virtual std::vector< SgNode * > SgDeclarationStatement::get_traversalSuccessorContainer () override virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
get_traversalSuccessorNamesContainer()
virtual std::vector< std::string > SgDeclarationStatement::get_traversalSuccessorNamesContainer () override virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
get_numberOfTraversalSuccessors()
virtual size_t SgDeclarationStatement::get_numberOfTraversalSuccessors () override virtual
return number of children in the traversal successor list
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
get_traversalSuccessorByIndex()
virtual SgNode * SgDeclarationStatement::get_traversalSuccessorByIndex (size_t idx) override virtual
index-based access to traversal successors by index number
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
get_childIndex()
virtual size_t SgDeclarationStatement::get_childIndex (SgNode * child) override virtual
index-based access to traversal successors by child node
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
roseRTI()
virtual RTIReturnType SgDeclarationStatement::roseRTI () override virtual
return C++ Runtime-Time-Information
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
sage_class_name()
virtual const char * SgDeclarationStatement::sage_class_name () const override virtual
returns a C style string (char*) representing the class name
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
accept()
virtual void SgDeclarationStatement::accept (ROSE_VisitorPattern & visitor) override virtual
support for the classic visitor pattern done in GoF
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
isInMemoryPool()
virtual bool SgDeclarationStatement::isInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
checkDataMemberPointersIfInMemoryPool()
virtual void SgDeclarationStatement::checkDataMemberPointersIfInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
returnDataMemberPointers()
virtual std::vector< std::pair< SgNode *, std::string > > SgDeclarationStatement::returnDataMemberPointers () const override virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
processDataMemberReferenceToPointers()
virtual void SgDeclarationStatement::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
getChildIndex()
virtual long SgDeclarationStatement::getChildIndex (SgNode * childNode) const override virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented from SgStatement.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgClinkageDeclarationStatement, SgClinkageStartStatement, SgClinkageEndStatement, SgEnumDeclaration, SgAsmStmt, SgAttributeSpecificationStatement, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgCommonBlock, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgCtorInitializerList, SgPragmaDeclaration, SgUsingDirectiveStatement, SgClassDeclaration, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgAdaEntryDecl, SgAdaFunctionRenamingDecl, SgContainsStatement, SgC_PreprocessorDirectiveStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgDeadIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, SgEmptyDeclaration, SgAdaPackageBodyDecl, SgAdaPackageSpecDecl, SgAdaRenamingDecl, SgAdaTaskSpecDecl, SgAdaTaskBodyDecl, SgAdaTaskTypeDecl, SgAdaProtectedSpecDecl, SgAdaProtectedBodyDecl, SgAdaProtectedTypeDecl, SgAdaRepresentationClause, SgAdaComponentClause, SgAdaAttributeClause, SgAdaEnumRepresentationClause, SgAdaGenericDecl, SgAdaFormalTypeDecl, SgAdaDiscriminatedTypeDecl, SgAdaGenericInstanceDecl, SgAdaFormalPackageDecl, SgAdaParameterList, and SgAdaVariantDecl.
addRegExpAttribute()
SgDeclarationStatement * SgDeclarationStatement::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
post_construction_initialization()
void SgDeclarationStatement::post_construction_initialization () override virtual
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
Reimplemented from SgNode.
Reimplemented in SgFunctionParameterList, SgVariableDeclaration, SgTemplateVariableDeclaration, SgVariableDefinition, SgEnumDeclaration, SgFormatStatement, SgTemplateDeclaration, SgTemplateInstantiationDirectiveStatement, SgUseStatement, SgParameterStatement, SgNamespaceDeclarationStatement, SgEquivalenceStatement, SgInterfaceStatement, SgNamespaceAliasDeclarationStatement, SgTypedefDeclaration, SgTemplateTypedefDeclaration, SgTemplateInstantiationTypedefDeclaration, SgStatementFunctionStatement, SgPragmaDeclaration, SgUsingDirectiveStatement, SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, SgJovialTableStatement, SgImplicitStatement, SgUsingDeclarationStatement, SgNamelistStatement, SgImportStatement, SgFunctionDeclaration, SgTemplateFunctionDeclaration, SgMemberFunctionDeclaration, SgTemplateMemberFunctionDeclaration, SgTemplateInstantiationMemberFunctionDecl, SgTemplateInstantiationFunctionDecl, SgProgramHeaderStatement, SgProcedureHeaderStatement, SgEntryStatement, SgIncludeDirectiveStatement, SgDefineDirectiveStatement, SgUndefDirectiveStatement, SgIfdefDirectiveStatement, SgIfndefDirectiveStatement, SgIfDirectiveStatement, SgElseDirectiveStatement, SgElseifDirectiveStatement, SgEndifDirectiveStatement, SgLineDirectiveStatement, SgWarningDirectiveStatement, SgErrorDirectiveStatement, SgEmptyDirectiveStatement, SgIncludeNextDirectiveStatement, SgIdentDirectiveStatement, SgLinemarkerDirectiveStatement, SgOmpThreadprivateStatement, SgFortranIncludeLine, SgJavaImportStatement, SgJavaPackageStatement, SgStmtDeclarationStatement, SgStaticAssertionDeclaration, SgOmpDeclareSimdStatement, SgMicrosoftAttributeDeclaration, SgJovialCompoolStatement, SgJovialDirectiveStatement, SgJovialDefineDeclaration, SgJovialLabelDeclaration, SgJovialOverlayDeclaration, SgNonrealDecl, and SgEmptyDeclaration.
get_declarationModifier()
SgDeclarationStatement::get_declarationModifier ()
Returns SgDeclarationModifier object by reference (so that it can be set).
Returns
Returns SgDeclarationModifier by reference.
Member Data Documentation
p_decl_attributes
SgDeclarationStatement::p_decl_attributes protected
This is old and used to be used to hold modifiers.
Definition at line 268890 of file Cxx_Grammar.h.
p_linkage
SgDeclarationStatement::p_linkage protected
This string stores the value "C", "C++", or "fortran" to define the external linkage for generating linkable names.
The only values that make sense here are "C", "C++" is the assumed default and requires a NULL pointer value. And the use of "fortran" would be backend specific (may be rejected by some backend vendor compilers).
Definition at line 268894 of file Cxx_Grammar.h.
p_declarationModifier
SgDeclarationStatement::p_declarationModifier protected
This is the mechanism to handle declaration modifiers.
See Stroustrup 3rd edition, Appendix A, for details of how modifiers are represented in ROSE.
Definition at line 268898 of file Cxx_Grammar.h.
p_nameOnly
SgDeclarationStatement::p_nameOnly protected
I think this is somewhat redundant with the purpose of specifying a forward declaration. Either that or it is information used by the unparser (Oh, I hope not!).
Definition at line 268902 of file Cxx_Grammar.h.
p_forward
SgDeclarationStatement::p_forward protected
This marks a declaration as being an explicit forward declaration.
All non-defining declaations are marked as forward declarations, while a defining declaration is NOT a marked as a forward declaration.
Definition at line 268906 of file Cxx_Grammar.h.
p_externBrace
SgDeclarationStatement::p_externBrace protected
This marks that the declaration appeared with "extern".
Note that I think this is also set even if it appears between "extern {" and "}". It might be that this is a way to specify the first "extern {", but I don't think it is used interanlly and it is not clear if attaching the "extern {" to a declaration is a great way to handle this problem generally (appears to be overlly sensative to transformations that would add, remove, or move declarations (e.g in inlining and outlining transformations).
Currently the lex pass saves all "extern \"C\" {" declarations and treats them as CPP directive (along with comments), they are then woven back into the AST as a separate pass.
Definition at line 268910 of file Cxx_Grammar.h.
p_skipElaborateType
SgDeclarationStatement::p_skipElaborateType protected
This marks "type elaboration" which is the use of the keyword "class" before variables of type class.
This is not often required, but is routinely output by the unparser to be conservative. The support for hidden lists allows the unparser to more precisely output the type elaboration, and so this variable is redundant.
Definition at line 268914 of file Cxx_Grammar.h.
p_definingDeclaration
SgDeclarationStatement::p_definingDeclaration protected
This pointer is valid only if a defining declaration exists, and stores the defining declaration where the declaration was defined.
It is important to note that this is the only defining declaration as opposed to the non-defining declarations (where there can, depending on IR node, often be many).
Definition at line 268918 of file Cxx_Grammar.h.
p_firstNondefiningDeclaration
SgDeclarationStatement::p_firstNondefiningDeclaration protected
This pointer is valid if there is a non-defining declaration, and stores the first non-defining declaration where a declaration was made explicitly (as in forward declaration) or implicitly as in the case of a few IR nodes (e.g. SgClassDeclaration). See description of SgDeclarationStatement.
It is important to note that this is the first non-defining declaration as opposed to the defining declaration. Thus it is usually the first forward declaration.
Definition at line 268922 of file Cxx_Grammar.h.
p_qualifiedNameList
SgQualifiedNamePtrList SgDeclarationStatement::p_qualifiedNameList protected
Definition at line 268926 of file Cxx_Grammar.h.
p_binding_label
std::string SgDeclarationStatement::p_binding_label protected
Definition at line 268930 of file Cxx_Grammar.h.
p_declarationScope
SgDeclarationScope* SgDeclarationStatement::p_declarationScope protected
Definition at line 268934 of file Cxx_Grammar.h.
p_unparse_template_ast
bool SgDeclarationStatement::p_unparse_template_ast protected
Definition at line 268938 of file Cxx_Grammar.h.
p_adaAspects
SgExprListExp* SgDeclarationStatement::p_adaAspects protected
Definition at line 268942 of file Cxx_Grammar.h.
The documentation for this class was generated from the following files:
Cxx_Grammar.h
SgDeclarationStatement.docs