ROSE: CallGraphBuilder Class Reference
CallGraphBuilder Class Reference
Description
Definition at line 145 of file CallGraph.h.
Public Member Functions
CallGraphBuilder (SgProject *proj)
void buildCallGraph ()
Default builder filtering nothing in the call graph.
template<typename Predicate >
void buildCallGraph (Predicate pred)
Builder accepting user defined predicate to filter certain functions.
SgIncidenceDirectedGraph * getGraph ()
Grab the call graph built.
boost::unordered_map< SgFunctionDeclaration *, SgGraphNode * > & getGraphNodesMapping ()
SgGraphNode * hasGraphNodeFor (SgFunctionDeclaration *fdecl) const
Retrieve the node matching a function declaration using firstNondefiningDeclaration (does not work across translation units)
SgGraphNode * getGraphNodeFor (SgFunctionDeclaration *fdecl) const
Retrieve the node matching a function declaration (using mangled name to resolve across translation units)
Member Function Documentation
buildCallGraph()
template<typename Predicate > void CallGraphBuilder::buildCallGraph (Predicate pred)
Builder accepting user defined predicate to filter certain functions.
Definition at line 187 of file CallGraph.h.
References SgIncidenceDirectedGraph::addDirectedEdge(), SgGraph::addNode(), SgFunctionDeclaration::class_name(), FunctionData::functionList, SgDeclarationStatement::get_firstNondefiningDeclaration(), getGraphNodeFor(), and hasGraphNodeFor().
getGraphNodesMapping()
boost::unordered_map< SgFunctionDeclaration *, SgGraphNode * > & CallGraphBuilder::getGraphNodesMapping () inline
Definition at line 159 of file CallGraph.h.
The documentation for this class was generated from the following file:
CallGraph.h