ROSE: SgScopeStatement Class Reference
SgScopeStatement Class Reference
Description
This class represents the concept of a scope in C++ (e.g. global scope, fuction scope, etc.).
Scopes are an important aspect of language design. They allow declarations to have a local context and so promote good programming style. Scope statments in C++ include a number of different kinds of statements; the SgScopeStatement is a base class for these. Each scope statement contains a symbol table and the SgScopeStatements role is mostly to provide this symbol table and an interface to accessing it.
Definition at line 226300 of file Cxx_Grammar.h.
Public Types
enum { static_variant = V_SgScopeStatement }
static variant value
typedef SgStatement base_node_type
Public Types inherited from SgStatement
enum { static_variant = V_SgStatement }
static variant value
typedef SgLocatedNode base_node_type
Public Types inherited from SgLocatedNode
enum { static_variant = V_SgLocatedNode }
static variant value
typedef SgNode base_node_type
Public Types inherited from SgNode
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
virtual SgNode * copy (SgCopyHelp &help) const override
Makes a copy (deap of shallow depending on SgCopyHelp).
SgScopeStatement (Sg_File_Info *file_info=NULL)
This is the constructor.
virtual SgName get_qualified_name () const
Returns SgName (a string) representing the name of the current scope.
virtual SgName get_mangled_name () const
size_t count_symbol (const SgName &n)
return number of entries in symbol table for the specified name (note that it is sometime OK for there to be more than 1).
size_t count_alias_symbol (const SgName &n)
Count for alias symbols of a specific name, used in name qualification support.
size_t symbol_table_size ()
Return the size of the symbol table.
void insert_symbol (const SgName &n, SgSymbol *s)
Puts a SgSymbol object into the local symbol table.
int lookup_symbol (const SgName &n, SgSymbol *s) const
bool symbol_exists (const SgName &, SgSymbol *sp) const
bool symbol_exists (const SgName &name) const
bool symbol_exists (const SgSymbol *sp) const
void remove_symbol (SgSymbol *s)
SgSymbol * lookup_symbol (const SgName &n, SgTemplateParameterPtrList *templateParameterList=NULL, SgTemplateArgumentPtrList *templateArgumentList=NULL) const
get the first symbol with name (note that "" is a valid name and is used for unnamed declarations) the input name is stored as internal state to support the use of next_XXX_symbol() member function.
SgVariableSymbol * lookup_var_symbol (const SgName &n) const
SgVariableSymbol * lookup_variable_symbol (const SgName &n) const
SgClassSymbol * lookup_class_symbol (const SgName &n, SgTemplateArgumentPtrList *templateArgumentsList=NULL) const
SgNonrealSymbol * lookup_nonreal_symbol (const SgName &n, SgTemplateParameterPtrList *templateParameterList=NULL, SgTemplateArgumentPtrList *templateArgumentsList=NULL) const
SgFunctionSymbol * lookup_function_symbol (const SgName &n) const
SgFunctionSymbol * lookup_function_symbol (const SgName &n, const SgType *t, SgTemplateArgumentPtrList *templateArgumentsList=NULL) const
SgTypedefSymbol * lookup_typedef_symbol (const SgName &n) const
SgEnumSymbol * lookup_enum_symbol (const SgName &n) const
SgEnumFieldSymbol * lookup_enum_field_symbol (const SgName &n) const
SgLabelSymbol * lookup_label_symbol (const SgName &n) const
SgJavaLabelSymbol * lookup_java_label_symbol (const SgName &n) const
SgNamespaceSymbol * lookup_namespace_symbol (const SgName &n) const
SgTemplateClassSymbol * lookup_template_class_symbol (const SgName &n, SgTemplateParameterPtrList *templateParameterList, SgTemplateArgumentPtrList *templateSpecializationArgumentList) const
SgTemplateTypedefSymbol * lookup_template_typedef_symbol (const SgName &n) const
SgClassSymbol * lookup_nontemplate_class_symbol (const SgName &n, SgTemplateArgumentPtrList *templateArgumentsList) const
SgTemplateFunctionSymbol * lookup_template_function_symbol (const SgName &n, const SgType *t, SgTemplateParameterPtrList *templateParameterList) const
SgTemplateVariableSymbol * lookup_template_variable_symbol (const SgName &n, SgTemplateParameterPtrList *templateParameterList, SgTemplateArgumentPtrList *templateArgumentsList) const
SgFunctionSymbol * lookup_nontemplate_function_symbol (const SgName &n, const SgType *t, SgTemplateArgumentPtrList *templateArgumentsList=NULL) const
SgTemplateMemberFunctionSymbol * lookup_template_member_function_symbol (const SgName &n, const SgType *t, SgTemplateParameterPtrList *templateParameterList) const
SgMemberFunctionSymbol * lookup_nontemplate_member_function_symbol (const SgName &n, const SgType *t, SgTemplateArgumentPtrList *templateArgumentsList=NULL) const
SgAliasSymbol * lookup_alias_symbol (const SgName &n, SgSymbol *sp) const
bool hasAmbiguity (SgName &name, SgSymbol *symbol)
SgSymbol * first_any_symbol () const
get the first symbol independent of name (lack of name is stored as internal state)
SgVariableSymbol * first_variable_symbol () const
SgClassSymbol * first_class_symbol () const
SgFunctionSymbol * first_function_symbol () const
SgTypedefSymbol * first_typedef_symbol () const
SgEnumSymbol * first_enum_symbol () const
SgEnumFieldSymbol * first_enum_field_symbol () const
SgLabelSymbol * first_label_symbol () const
SgNamespaceSymbol * first_namespace_symbol () const
SgTemplateSymbol * first_template_symbol () const
SgSymbol * next_any_symbol () const
Only use after lookup_XXX_symbol(const SgName&) or after first_XXX_symbol() These functions use the stored state of the name or lack of name (from the lookup_XXX_symbol(const SgName&) or after first_XXX_symbol() member function) and return the next symbol.
SgVariableSymbol * next_variable_symbol () const
SgClassSymbol * next_class_symbol () const
SgFunctionSymbol * next_function_symbol () const
SgTypedefSymbol * next_typedef_symbol () const
SgEnumSymbol * next_enum_symbol () const
SgEnumFieldSymbol * next_enum_field_symbol () const
SgLabelSymbol * next_label_symbol () const
SgNamespaceSymbol * next_namespace_symbol () const
SgTemplateSymbol * next_template_symbol () const
void print_symboltable (const std::string &str, std::ostream &os)
void print_symboltable (const std::string &label, VariantT nodeType)
void print_symboltable (const std::string &str)
bool containsOnlyDeclarations () const
This function is used to indicate if either the getDeclarationList() or getStatementList() can be called to return a reference to the list of IR nodes (manipulation of the list is then possible).
void insertStatementInScope (SgStatement *newTransformationStatement, bool atTop)
SgDeclarationStatementPtrList & getDeclarationList ()
Gets reference to internal STL list of pointers to SgDeclarationStatement objects (only defined for scopes containing declarations, see bool containsOnlyDeclarations()).
SgStatementPtrList & getStatementList ()
Gets reference to internal STL list of pointers to SgStatement objects (only defined for scopes containing declarations, see bool containsOnlyDeclarations()).
const SgDeclarationStatementPtrList & getDeclarationList () const
const SgStatementPtrList & getStatementList () const
const SgStatementPtrList generateStatementList () const
Generate s list of statements from either the existing list of statements or the list of declarations.
bool statementExistsInScope (SgStatement *statement)
Test for existence of statement is scope.
bool supportsDefiningFunctionDeclaration ()
Reports if scope can support defining function declarations. Not all scopes permit function declarations. Any function prototype in a scope appropriate for a function definition triggers requirements for name qualification. This function returns true if the scope is appropriate for the definition of a function or member function (i.e. is a SgGlobal, SgClassDefinition, or SgNamespaceDefinitionStatement).
unsigned int generateUniqueStatementNumberForScope (SgStatement *statement)
Generate a unique number for the statement in the scope.
bool generateUniqueStatementNumberForScopeHelper (unsigned int &counter, SgStatement *statement)
Helper for generateUniqueStatementNumberForScope: return true if the element is found, incrementing the counter once for each element of tree up to either the element of the end of the sub-statements in the current statement.
std::set< SgSymbol * > & get_type_elaboration_list ()
This list of symbols represent types that will require type elaboration when source code is generated.
std::set< SgSymbol * > & get_hidden_type_list ()
This list of symbols represent types that will require name qualification when the type name is output.
std::set< SgSymbol * > & get_hidden_declaration_list ()
This list of symbols represent declarations that will require name qualification when the identifier name is output.
void set_type_elaboration_list (const std::set< SgSymbol * > &type_elaboration_list)
void set_hidden_type_list (const std::set< SgSymbol * > &hidden_type_list)
void set_hidden_declaration_list (const std::set< SgSymbol * > &hidden_declaration_list)
void append_statement (SgStatement *stmt)
Higher level function to handle statements and declarations is scopes.
void prepend_statement (SgStatement *stmt)
SgStatement * firstStatement () const
SgStatement * lastStatement () const
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const override
bool isCaseInsensitive () const
Query of scope symbol table behavior (is symbol table behavior case sensitive (C/C++) or case insensitive (Fortran).
void setCaseInsensitive (bool b)
bool isNamedScope ()
Some scopes have associated names for purposed of name qualification. This returns true if the scope has a name, false if not.
SgName associatedScopeName ()
Some scopes have associated names for purposed of name qualification. This generates the associated name.
SgSymbolTable * get_symbol_table () const
Returns a pointer to the locally strored SgSymbolTable.
void set_symbol_table (SgSymbolTable *symbol_table)
Sets the pointer to the locally strored SgSymbolTable.
template<class T >
SgFunctionSymbol * find_symbol_by_type_of_function (const SgName &name, const SgType *func_type, SgTemplateParameterPtrList *templateParameterList, SgTemplateArgumentPtrList *templateArgumentList)
template<class T >
SgSymbol * find_symbol_from_declaration (const T *node) const
virtual std::string class_name () const override
returns a string representing the class name
virtual VariantT variantT () const override
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer () override
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer () override
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors () override
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx) override
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child) override
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI () override
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const override
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor) override
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const override
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const override
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgScopeStatement (const SgScopeStatementStorageClass &source)
IR node constructor to support AST File I/O.
SgScopeStatement * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
SgTypeTable * get_type_table () const
void set_type_table (SgTypeTable *type_table)
SgPragma * get_pragma () const
void set_pragma (SgPragma *pragma)
virtual ~SgScopeStatement ()
This is the destructor.
Public Member Functions inherited from SgStatement
virtual SgScopeStatement * get_scope (void) const
Returns scope of current statement.
virtual void setExtern ()
This function sets "extern" status for the current statement.
virtual void setStatic ()
This function sets "static" status for the current statement.
void insert_statement (SgStatement *target, SgStatement *newstmt, bool inFront=true)
This function inserts a single statement at the position indicated by target.
void insert_statement (SgStatement *target, const SgStatementPtrList &newstmtList, bool inFront=true)
This function inserts a list of statements at the position indicated by target.
void replace_statement (SgStatement *target, SgStatement *newstmt)
This function replaces the target statement with a single statement.
void replace_statement (SgStatement *target, const SgStatementPtrList &newstmtList)
This function replaces the target statement with a list of statements.
void remove_statement (SgStatement *)
This function removes the target statement from the AST.
void insert_statement_from_basicBlock (SgStatement *target, SgStatement *newstmt, bool inFront=true)
This function inserts a statement at the position indicated by target. If newstmt is a basicBlock, statements inside newstmt are extracted and then inserted.
void replace_statement_from_basicBlock (SgStatement *target, SgStatement *newstmt)
This function replaces the target statement with a new statement. If newstmt is a basicBlock, statements inside newstmt are extracted and then inserted.
virtual int replace_expression (SgExpression *original_expression, SgExpression *new_expression)
support general replace functions, used in statements that directly contain SgExpression IR nodes.
virtual void set_scope (SgScopeStatement *newScope)
Support for setting scopes (only meaningful on IR statements that store the scope explicitly).
virtual bool hasExplicitScope () const
Support for where the scope is explicitly required.
virtual SgSymbol * get_symbol_from_symbol_table () const
Get the associated symbol from the symbol table in the stored scope.
virtual unsigned int cfgIndexForEnd () const override
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const override
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n) override
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n) override
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index) override
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index) override
Find the in edges of a CFG node – internal version.
virtual bool isChildUsedAsLValue (const SgExpression *child) const
Virtual function to determine if the provided expression is used as an l-value within the cotext of this statement.
virtual void set_end_numeric_label (SgLabelRefExp *end_numeric_label)
virtual bool has_end_numeric_label () const
bool hasExplicitType ()
Some statement store internal SgType pointers explicitly. This function is true if it has a data member that is a type (only applies to SgTypedefDeclaration).
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgStatement (const SgStatementStorageClass &source)
IR node constructor to support AST File I/O.
SgStatement * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
SgLabelRefExp * get_numeric_label () const
void set_numeric_label (SgLabelRefExp *numeric_label)
int get_source_sequence_value () const
void set_source_sequence_value (int source_sequence_value)
virtual ~SgStatement ()
This is the destructor.
SgStatement (Sg_File_Info *startOfConstruct)
This is the constructor.
Public Member Functions inherited from SgLocatedNode
const std::string & getFilenameString () const
void addToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo::RelativePositionType locationInList=PreprocessingInfo::after)
This function adds comment or CPP directives to the current IR node.
void insertToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo *anchorInfoPtr, bool insertAfter=true)
Insert prepInfo After (or before if last parameter is false) an anchor info ptr in the list of preprocessing info attached to the current node. This is useful to insert things in the middle.
virtual Sg_File_Info * get_file_info () const override
Interface function to implement original SAGE interface to SgFile_Info objects.
virtual void set_file_info (Sg_File_Info *X)
Access function calls set_startingConstruct(Sg_File_Info*) member function.
void setCompilerGenerated ()
Allow IR nodes (mostly SgLocatedNode) to be marked as compiler generated.
void unsetCompilerGenerated ()
bool isCompilerGenerated () const
Simple test for if this is a compiler generated node.
void setTransformation ()
Allow IR nodes (mostly SgLocatedNode) to be marked as a transformation.
void unsetTransformation ()
bool isTransformation () const
Simple test for if this is a part of a transformation.
void setFrontendSpecific ()
Allow IR nodes (mostly SgLocatedNode) to be marked as front-end specific (generated by the front-end to support a specific backend compiler; e.g. GNU gcc and g++).
void unsetFrontendSpecific ()
bool isFrontendSpecific () const
Simple test for if this is a frontend specific IR node.
void setShared ()
Allow IR nodes (mostly SgLocatedNode) to be marked as shared.
void unsetShared ()
bool isShared () const
Simple test for if this is a shared IR node.
void setSourcePositionUnavailableInFrontend ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetSourcePositionUnavailableInFrontend ()
void setOutputInCodeGeneration ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetOutputInCodeGeneration ()
bool isOutputInCodeGeneration () const
int get_physical_file_id ()
Allow IR nodes (mostly SgLocatedNode) to be queried for there physical file ID.
AttachedPreprocessingInfoType *& getAttachedPreprocessingInfo (void)
Computes the number of nodes in the defined subtree of the AST.
Sg_File_Info * generateMatchingFileInfo ()
virtual void addNewAttribute (std::string s, AstAttribute *a) override
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const override
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a) override
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a) override
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s) override
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const override
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const override
Returns the number of attributes on this IR node.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgLocatedNode (const SgLocatedNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgLocatedNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
Sg_File_Info * get_startOfConstruct () const override
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
void set_startOfConstruct (Sg_File_Info *startOfConstruct)
This function sets the current source location position of the start of the current construct.
Sg_File_Info * get_endOfConstruct () const override
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
void set_endOfConstruct (Sg_File_Info *endOfConstruct)
This function sets the current source location position of the end of the current construct.
AttachedPreprocessingInfoType * get_attachedPreprocessingInfoPtr () const
void set_attachedPreprocessingInfoPtr (AttachedPreprocessingInfoType *attachedPreprocessingInfoPtr)
AstAttributeMechanism * get_attributeMechanism () const override
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
void set_attributeMechanism (AstAttributeMechanism *attributeMechanism) override
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
bool get_containsTransformationToSurroundingWhitespace () const
void set_containsTransformationToSurroundingWhitespace (bool containsTransformationToSurroundingWhitespace)
virtual ~SgLocatedNode ()
This is the destructor.
SgLocatedNode (Sg_File_Info *startOfConstruct=NULL)
This is the constructor.
Public Member Functions inherited from SgNode
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
Static Public Member Functions
static bool isEquivalentScope (SgScopeStatement *scope1, SgScopeStatement *scope2)
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgScopeStatement * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgScopeStatement *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgScopeStatement *sgnode)
Static Public Member Functions inherited from SgStatement
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgStatement * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgStatement *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgStatement *sgnode)
Static Public Member Functions inherited from SgLocatedNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgLocatedNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgLocatedNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgLocatedNode *sgnode)
Static Public Member Functions inherited from SgNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Protected Attributes
SgSymbolTable * p_symbol_table
This pointer is always valid and stores the symbl table.
SgTypeTable * p_type_table
std::set< SgSymbol * > p_type_elaboration_list
std::set< SgSymbol * > p_hidden_type_list
std::set< SgSymbol * > p_hidden_declaration_list
SgPragma * p_pragma
Protected Attributes inherited from SgStatement
SgLabelRefExp * p_numeric_label
int p_source_sequence_value
Protected Attributes inherited from SgLocatedNode
Sg_File_Info * p_startOfConstruct
This pointer is always valid and stores the source position of the start of the current construct.
Sg_File_Info * p_endOfConstruct
This pointer is always valid and stores the source position of the end of the current construct.
AttachedPreprocessingInfoType * p_attachedPreprocessingInfoPtr
Holds comments and/or preprocessor directives located before or after the current statement of expression.
AstAttributeMechanism * p_attributeMechanism
bool p_containsTransformationToSurroundingWhitespace
Protected Attributes inherited from SgNode
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Additional Inherited Members
Protected Member Functions inherited from SgStatement
virtual bool replace_child (SgStatement *target, SgStatement *newStmt, bool extractListFromBasicBlock=false)
Private supporting function for low level SageIII rewrite interface.
virtual bool insert_child (SgStatement *, SgStatement *, bool inFront=true, bool extractListFromBasicBlock=false)
Private supporting function for low level SageIII rewrite interface.
Protected Member Functions inherited from SgNode
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Static Protected Attributes inherited from SgNode
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Member Typedef Documentation
base_node_type
typedef SgStatement SgScopeStatement::base_node_type
Definition at line 227027 of file Cxx_Grammar.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
static variant value
Definition at line 226648 of file Cxx_Grammar.h.
Constructor & Destructor Documentation
SgScopeStatement()
SgScopeStatement::SgScopeStatement (Sg_File_Info * startOfConstruct = NULL)
This is the constructor.
This constructor builds the SgScopeStatement base class.
Parameters
startOfConstruct represents the position in the source code
~SgScopeStatement()
SgScopeStatement::~SgScopeStatement () virtual
This is the destructor.
There are a lot of things to delete, but nothing is deleted in this destructor.
Member Function Documentation
copy()
SgScopeStatement::copy (SgCopyHelp & help) const override virtual
Makes a copy (deap of shallow depending on SgCopyHelp).
Returns
Returns pointer to copy of SgScopeStatement.
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
get_qualified_name()
SgScopeStatement::get_qualified_name () const virtual
Returns SgName (a string) representing the name of the current scope.
See discussion of mangled names in the documentation.
Returns
Returns SgName (a string).
Reimplemented in SgGlobal, SgBasicBlock, SgFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgNamespaceDefinitionStatement, SgDeclarationScope, SgAdaPackageSpec, SgAdaPackageBody, and SgAdaGenericDefn.
Referenced by SageInterface::serialize().
insert_symbol()
SgScopeStatement::insert_symbol (const SgName & name, SgSymbol * symbol)
Puts a SgSymbol object into the local symbol table.
Returns
Returns void.
Referenced by SageBuilder::buildClassDeclaration_nfi(), SageBuilder::buildDefiningFunctionDeclaration_T(), SageBuilder::buildEnumDeclaration_nfi(), SageBuilder::buildNamespaceDeclaration_nfi(), SageBuilder::buildNondefiningClassDeclaration(), SageBuilder::buildNondefiningClassDeclaration_nfi(), SageBuilder::buildNondefiningEnumDeclaration_nfi(), SageBuilder::buildNondefiningTemplateClassDeclaration_nfi(), SageBuilder::buildNonrealDecl(), SageBuilder::buildOpaqueType(), SageBuilder::buildTemplateClassDeclaration_nfi(), SageBuilder::buildTemplateInstantiationTypedefDeclaration_nfi(), SageBuilder::buildTemplateTypedefDeclaration_nfi(), SageBuilder::buildTypedefDeclaration_nfi(), SageInterface::fixFunctionDeclaration(), SageInterface::fixLabelStatement(), SageInterface::fixNamespaceDeclaration(), SageInterface::fixStatement(), SageInterface::fixStructDeclaration(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::fixVariableDeclaration(), SageInterface::moveVariableDeclaration(), SageInterface::rebuildSymbolTable(), SageInterface::replaceExpressionWithStatement(), and SageInterface::setFortranNumericLabel().
containsOnlyDeclarations()
SgScopeStatement::containsOnlyDeclarations () const
This function is used to indicate if either the getDeclarationList() or getStatementList() can be called to return a reference to the list of IR nodes (manipulation of the list is then possible).
boolean member function to distinquish if getStatementList() or getDeclarationList() is appropriate for the SgScopeStatment IR node.
Returns
bool.
Referenced by SageInterface::appendStatement(), SageBuilder::buildDefiningFunctionDeclaration_T(), SageInterface::findFirstDefiningFunctionDecl(), SageInterface::getFirstStatement(), SageInterface::getLastStatement(), SageInterface::isLastStatement(), SageInterface::isPrototypeInScope(), SageInterface::scopeHasStatementsFromSameFile(), SageInterface::translateScopeToUseCppDeclarations(), and SageInterface::updateDefiningNondefiningLinks().
getDeclarationList()
SgScopeStatement::getDeclarationList ()
Gets reference to internal STL list of pointers to SgDeclarationStatement objects (only defined for scopes containing declarations, see bool containsOnlyDeclarations()).
This function is useful for SgScopeStatement objects that contain declarations, and is not defined (returns an error) if called on a SgClassDefinition, SgTemplateInstantiationDefn, SgGlobal, SgNamespaceDefinitionStatement. To test if a scope contains only declarations use "bool containsOnlyDeclarations()". Because this function returns a reference to the list (instead of a list of pointers to the declarations or statements) any modification of the list is a modification of the AST.
Returns
STL list of pointers to SgDeclarationStatement objects.
Referenced by SageInterface::appendStatementWithDependentDeclaration(), SageInterface::findFirstDefiningFunctionDecl(), SageInterface::getFirstStatement(), SageInterface::getLastStatement(), SageInterface::isLastStatement(), SageInterface::isPrototypeInScope(), SageInterface::scopeHasStatementsFromSameFile(), SageInterface::translateScopeToUseCppDeclarations(), and SageInterface::updateDefiningNondefiningLinks().
getStatementList()
SgScopeStatement::getStatementList ()
Gets reference to internal STL list of pointers to SgStatement objects (only defined for scopes containing declarations, see bool containsOnlyDeclarations()).
This function is useful for SgScopeStatement objects that contain non-declarations (lists of SgStatement instead of lists of SgDeclarationStatement IR nodes). Because this function returns a reference to the list (instead of a list of pointers to the declarations or statements) any modification of the list is a modification of the AST.
Returns
STL list of pointers to SgStatement objects.
Referenced by SageInterface::findFirstDefiningFunctionDecl(), SageInterface::getFirstStatement(), SageInterface::getLastStatement(), SageInterface::isLastStatement(), SageInterface::scopeHasStatementsFromSameFile(), SageInterface::translateScopeToUseCppDeclarations(), and SageInterface::updateDefiningNondefiningLinks().
generateStatementList()
SgScopeStatement::generateStatementList () const
Generate s list of statements from either the existing list of statements or the list of declarations.
Builds list of pointers to SgStatement objects (useful for all SgScopeStatement objects, independent of whether they contain lists of SgDeclarationStatements or lists of SgStatements).
This permits access via a common type (SgStatement). (this list is constructed and manipulation of it will not effect the scope's SgStatementPtrList or SgDeclarationStatementPtrList. So this should be considered to be a read only list.
This function is useful for any SgScopeStatement object, but since it returns by value any modification of the list is not reflected in the AST.
Returns
STL list of pointers to SgStatement objects (returns by value).
Referenced by SageInterface::displayScope(), SageInterface::findLastDeclarationStatement(), SageInterface::insertStatementBeforeFirstNonDeclaration(), SageInterface::insertStatementListBeforeFirstNonDeclaration(), SageInterface::isLastStatement(), SageInterface::lastStatementOfScopeWithTokenInfo(), SageInterface::rebuildSymbolTable(), and SageInterface::setBaseTypeDefiningDeclaration().
fixupCopy_scopes()
virtual void SgScopeStatement::fixupCopy_scopes (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgStatement.
fixupCopy_symbols()
virtual void SgScopeStatement::fixupCopy_symbols (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgStatement.
fixupCopy_references()
virtual void SgScopeStatement::fixupCopy_references (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgStatement.
get_symbol_table()
SgScopeStatement::get_symbol_table () const
Returns a pointer to the locally strored SgSymbolTable.
Returns
Returns a pointer.
Referenced by SageBuilder::buildClassDeclaration_nfi(), SageBuilder::buildFile(), SageBuilder::buildNondefiningTemplateMemberFunctionDeclaration(), SageInterface::checkSymbolTables(), SageInterface::clearSharedGlobalScopes(), SageInterface::deleteAST(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::fixupReferencesToSymbols(), SageBuilder::getTargetFileTypeSupport(), SageInterface::rebuildSymbolTable(), SageInterface::replaceExpressionWithStatement(), SageInterface::set_name(), and SageInterface::suggestNextNumericLabel().
set_symbol_table()
SgScopeStatement::set_symbol_table (SgSymbolTable * symbolTable)
Sets the pointer to the locally strored SgSymbolTable.
Returns
Returns void.
Referenced by SageInterface::rebuildSymbolTable().
find_symbol_by_type_of_function()
template<class T > template SgFunctionSymbol * SgScopeStatement::find_symbol_by_type_of_function< SgFunctionDeclaration > (const SgName & name, const SgType * func_type, SgTemplateParameterPtrList * templateParameterList, SgTemplateArgumentPtrList * templateArgumentList)
Definition at line 234 of file sageBuilder.C.
class_name()
virtual std::string SgScopeStatement::class_name () const override virtual
returns a string representing the class name
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
Referenced by SageInterface::appendStatement(), SageInterface::appendStatement(), SageBuilder::buildClassDeclaration_nfi(), SageBuilder::buildDefiningClassDeclaration(), SageBuilder::buildEnumDeclaration_nfi(), SageBuilder::buildMemberFunctionType(), SageBuilder::buildNamespaceDeclaration_nfi(), SageBuilder::buildNondefiningClassDeclaration(), SageBuilder::buildNondefiningClassDeclaration_nfi(), SageBuilder::buildNondefiningTemplateClassDeclaration_nfi(), SageBuilder::buildNondefiningTemplateMemberFunctionDeclaration(), SageBuilder::buildStatementFromString(), SageBuilder::buildTemplateClassDeclaration_nfi(), SageBuilder::buildTemplateInstantiationTypedefDeclaration_nfi(), SageBuilder::buildTemplateTypedefDeclaration_nfi(), SageBuilder::buildVariableDeclaration_nfi(), SageInterface::displayScope(), SageInterface::enclosingNamespaceScope(), SageBuilder::errorCheckingTargetAST(), SageBuilder::findAssociatedDeclarationInTargetAST(), SageBuilder::findAssociatedSymbolInTargetAST(), SageInterface::fixFunctionDeclaration(), SageInterface::fixNamespaceDeclaration(), SageInterface::fixStatement(), SageInterface::fixStructDeclaration(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::fixupReferencesToSymbols(), SageInterface::fixVariableDeclaration(), SageInterface::generateUniqueNameForUseAsIdentifier_support(), SageInterface::get_name(), SageInterface::getClassTypeChainForMemberReference(), SageInterface::insertStatement(), SageInterface::lastStatementOfScopeWithTokenInfo(), SageInterface::lookupFunctionSymbolInParentScopes(), SageInterface::lookupSymbolInParentScopesIgnoringAliasSymbols(), SageInterface::lookupTemplateClassSymbolInParentScopes(), SageInterface::lookupTemplateFunctionSymbolInParentScopes(), SageInterface::lookupTemplateMemberFunctionSymbolInParentScopes(), SageInterface::lookupTemplateVariableSymbolInParentScopes(), SageInterface::lookupTypedefSymbolInParentScopes(), SageInterface::moveDeclarationToAssociatedNamespace(), SageInterface::moveVariableDeclaration(), SageInterface::prependStatement(), SageInterface::prependStatement(), SageInterface::rebuildSymbolTable(), SageInterface::resetScopeNumbers(), SageInterface::set_name(), SageBuilder::topScopeStack(), SageInterface::translateScopeToUseCppDeclarations(), SageInterface::translateToUseCppDeclarations(), and SageInterface::updateDefiningNondefiningLinks().
variantT()
virtual VariantT SgScopeStatement::variantT () const override virtual
returns new style SageIII enum values
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
Referenced by SageInterface::get_name(), SageInterface::hasSimpleChildrenList(), SageInterface::moveVariableDeclaration(), and SageInterface::rebuildSymbolTable().
operator delete()
void SgScopeStatement::operator delete (void * pointer) inline
Definition at line 226703 of file Cxx_Grammar.h.
get_traversalSuccessorContainer()
virtual std::vector< SgNode * > SgScopeStatement::get_traversalSuccessorContainer () override virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
get_traversalSuccessorNamesContainer()
virtual std::vector< std::string > SgScopeStatement::get_traversalSuccessorNamesContainer () override virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
get_numberOfTraversalSuccessors()
virtual size_t SgScopeStatement::get_numberOfTraversalSuccessors () override virtual
return number of children in the traversal successor list
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
get_traversalSuccessorByIndex()
virtual SgNode * SgScopeStatement::get_traversalSuccessorByIndex (size_t idx) override virtual
index-based access to traversal successors by index number
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
get_childIndex()
virtual size_t SgScopeStatement::get_childIndex (SgNode * child) override virtual
index-based access to traversal successors by child node
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
roseRTI()
virtual RTIReturnType SgScopeStatement::roseRTI () override virtual
return C++ Runtime-Time-Information
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
sage_class_name()
virtual const char * SgScopeStatement::sage_class_name () const override virtual
returns a C style string (char*) representing the class name
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
Referenced by SageInterface::OutputLocalSymbolTables::visit().
accept()
virtual void SgScopeStatement::accept (ROSE_VisitorPattern & visitor) override virtual
support for the classic visitor pattern done in GoF
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
isInMemoryPool()
virtual bool SgScopeStatement::isInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
checkDataMemberPointersIfInMemoryPool()
virtual void SgScopeStatement::checkDataMemberPointersIfInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
returnDataMemberPointers()
virtual std::vector< std::pair< SgNode *, std::string > > SgScopeStatement::returnDataMemberPointers () const override virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
processDataMemberReferenceToPointers()
virtual void SgScopeStatement::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
getChildIndex()
virtual long SgScopeStatement::getChildIndex (SgNode * childNode) const override virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented from SgStatement.
Reimplemented in SgGlobal, SgBasicBlock, SgIfStmt, SgForStatement, SgFunctionDefinition, SgTemplateFunctionDefinition, SgClassDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgDoWhileStmt, SgSwitchStatement, SgCatchOptionStmt, SgNamespaceDefinitionStatement, SgBlockDataStatement, SgAssociateStatement, SgFortranDo, SgFortranNonblockedDo, SgForAllStatement, SgUpcForAllStatement, SgCAFWithTeamStatement, SgJavaForEachStatement, SgJavaLabelStatement, SgMatlabForStatement, SgFunctionParameterScope, SgDeclarationScope, SgRangeBasedForStatement, SgJovialForThenStatement, SgAdaAcceptStmt, SgAdaPackageSpec, SgAdaPackageBody, SgAdaTaskSpec, SgAdaTaskBody, SgAdaProtectedBody, SgAdaProtectedSpec, and SgAdaGenericDefn.
addRegExpAttribute()
SgScopeStatement * SgScopeStatement::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
post_construction_initialization()
void SgScopeStatement::post_construction_initialization () override virtual
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
Reimplemented from SgLocatedNode.
Reimplemented in SgTemplateFunctionDefinition, SgTemplateInstantiationDefn, SgTemplateClassDefinition, SgWhileStmt, SgSwitchStatement, and SgUpcForAllStatement.
Member Data Documentation
p_symbol_table
SgScopeStatement::p_symbol_table protected
This pointer is always valid and stores the symbl table.
Definition at line 227057 of file Cxx_Grammar.h.
p_type_table
SgTypeTable* SgScopeStatement::p_type_table protected
Definition at line 227061 of file Cxx_Grammar.h.
p_type_elaboration_list
std::set<SgSymbol*> SgScopeStatement::p_type_elaboration_list protected
Definition at line 227065 of file Cxx_Grammar.h.
p_hidden_type_list
std::set<SgSymbol*> SgScopeStatement::p_hidden_type_list protected
Definition at line 227069 of file Cxx_Grammar.h.
p_hidden_declaration_list
std::set<SgSymbol*> SgScopeStatement::p_hidden_declaration_list protected
Definition at line 227073 of file Cxx_Grammar.h.
p_pragma
SgPragma* SgScopeStatement::p_pragma protected
Definition at line 227077 of file Cxx_Grammar.h.
The documentation for this class was generated from the following files:
Cxx_Grammar.h
SgScopeStatement.docs
sageBuilder.C