ROSE: Sawyer::CommandLine::RealNumberParser< T > Class Template Reference
Sawyer::CommandLine::RealNumberParser< T > Class Template Reference
Description
template<typename T>
class Sawyer::CommandLine::RealNumberParser< T >
Parses a real number and converts it to numeric type T.
Matches a real number in the mathematical sense in C++ floating-point representation, and attempts to convert it to the type T. If the real number cannot be converted to type T then an std::range_error is thrown, which is most likely caught by higher layers of the library and converted to an std::runtime_error with additional information about the failure. The syntax is that which is recognized by the strtod function, plus trailing white space.
See also
realNumberParser factory, and Command line parser factories.
Definition at line 1126 of file Sawyer/CommandLine.h.
#include <Sawyer/CommandLine.h>
Public Types
typedef SharedPointer< RealNumberParser > Ptr
Reference counting pointer for this class.
Public Types inherited from Sawyer::CommandLine::ValueParser
typedef SharedPointer< ValueParser > Ptr
Reference counting pointer for this class.
Static Public Member Functions
static Ptr instance ()
Allocating constructor.
static Ptr instance (const ValueSaver::Ptr &valueSaver)
Allocating constructor.
Protected Member Functions
RealNumberParser ()
Constructor for derived classes.
RealNumberParser (const ValueSaver::Ptr &valueSaver)
Constructor for derived classes.
Protected Member Functions inherited from Sawyer::CommandLine::ValueParser
ValueParser ()
Constructor for derived classes.
ValueParser (const ValueSaver::Ptr &valueSaver)
Constructor for derived classes.
Additional Inherited Members
Public Member Functions inherited from Sawyer::CommandLine::ValueParser
ParsedValue matchString (const std::string &)
Parse the entire string and return a value.
ParsedValue match (Cursor &)
Parse a value from the beginning of the specified string.
Ptr valueSaver (const ValueSaver::Ptr &f)
Property: functor responsible for saving a parsed value in user storage.
const ValueSaver::Ptr valueSaver () const
Property: functor responsible for saving a parsed value in user storage.
Public Member Functions inherited from Sawyer::SharedObject
SharedObject ()
Default constructor.
SharedObject (const SharedObject &)
Copy constructor.
virtual ~SharedObject ()
Virtual destructor.
SharedObject & operator= (const SharedObject &)
Assignment.
Public Member Functions inherited from Sawyer::SharedFromThis< ValueParser >
SharedPointer< ValueParser > sharedFromThis ()
Create a shared pointer from this.
SharedPointer< const ValueParser > sharedFromThis () const
Create a shared pointer from this.
Member Typedef Documentation
Ptr
template<typename T > typedef SharedPointer<RealNumberParser> Sawyer::CommandLine::RealNumberParser< T >::Ptr
Reference counting pointer for this class.
Definition at line 1135 of file Sawyer/CommandLine.h.
Constructor & Destructor Documentation
RealNumberParser() [1/2]
template<typename T > Sawyer::CommandLine::RealNumberParser< T >::RealNumberParser () inline protected
Constructor for derived classes.
Non-subclass users should use instance instead.
Definition at line 1129 of file Sawyer/CommandLine.h.
Referenced by Sawyer::CommandLine::RealNumberParser< T >::instance().
RealNumberParser() [2/2]
template<typename T > Sawyer::CommandLine::RealNumberParser< T >::RealNumberParser (const ValueSaver::Ptr & valueSaver) inline protected
Constructor for derived classes.
Non-subclass users should use instance instead.
Definition at line 1132 of file Sawyer/CommandLine.h.
Member Function Documentation
instance() [1/2]
template<typename T > static Ptr Sawyer::CommandLine::RealNumberParser< T >::instance () inline static
Allocating constructor.
Returns a pointer to a new RealNumberParser object. Uses will most likely want to use the realNumberParser factory instead, which requires less typing.
See also
Command line parser factories
Definition at line 1140 of file Sawyer/CommandLine.h.
Referenced by Sawyer::CommandLine::realNumberParser(), and Sawyer::CommandLine::realNumberParser().
instance() [2/2]
template<typename T > static Ptr Sawyer::CommandLine::RealNumberParser< T >::instance (const ValueSaver::Ptr & valueSaver) inline static
Allocating constructor.
Returns a pointer to a new RealNumberParser object. Uses will most likely want to use the realNumberParser factory instead, which takes the same arguments, but requires less typing.
See also
Command line parser factories
Definition at line 1145 of file Sawyer/CommandLine.h.
References Sawyer::CommandLine::RealNumberParser< T >::RealNumberParser(), and Sawyer::CommandLine::ValueParser::valueSaver().
The documentation for this class was generated from the following file:
Sawyer/CommandLine.h