ROSE: Sawyer::Container::Map< K, T, Cmp, Alloc >::Node Class Reference
Sawyer::Container::Map< K, T, Cmp, Alloc >::Node Class Reference
Description
template<class K, class T, class Cmp = std::less<K>, class Alloc = std::allocator<std::pair<const K, T> >>
class Sawyer::Container::Map< K, T, Cmp, Alloc >::Node
Type for stored nodes.
A storage node contains the immutable key and its associated value.
Definition at line 107 of file Sawyer/Map.h.
#include <Sawyer/Map.h>
Public Member Functions
Node (const std::pair< const Key, Value > &pair)
Node (const Key &key, Value &value)
const Key & key () const
Key part of key/value node.
Value & value ()
Value part of key/value node.
const Value & value () const
Value part of key/value node.
Constructor & Destructor Documentation
Node() [1/2]
template<class K , class T , class Cmp = std::less<K>, class Alloc = std::allocator<std::pair<const K, T> >> Sawyer::Container::Map< K, T, Cmp, Alloc >::Node::Node (const std::pair< const Key, Value > & pair) inline explicit
Definition at line 110 of file Sawyer/Map.h.
Node() [2/2]
template<class K , class T , class Cmp = std::less<K>, class Alloc = std::allocator<std::pair<const K, T> >> Sawyer::Container::Map< K, T, Cmp, Alloc >::Node::Node (const Key & key, Value & value) inline
Definition at line 111 of file Sawyer/Map.h.
Member Function Documentation
key()
template<class K , class T , class Cmp = std::less<K>, class Alloc = std::allocator<std::pair<const K, T> >> const Key & Sawyer::Container::Map< K, T, Cmp, Alloc >::Node::key () const inline
Key part of key/value node.
Returns the key part of a key/value node. Keys are not mutable when they are part of a map.
Definition at line 116 of file Sawyer/Map.h.
Referenced by Sawyer::Container::IntervalMap< I, T, Policy >::erase(), Sawyer::Container::IntervalSetMap< I, S >::erase(), Sawyer::Container::IntervalMap< I, T, Policy >::findFirstOverlapImpl(), Sawyer::Container::IntervalSetMap< I, S >::getIntersection(), Sawyer::Container::IntervalMap< I, T, Policy >::greatest(), Sawyer::Container::IntervalSetMap< I, S >::insert(), Sawyer::Container::IntervalMap< I, T, Policy >::insert(), Sawyer::Container::IntervalMap< I, T, Policy >::least(), Sawyer::Container::IntervalMap< I, T, Policy >::upperBound(), and Sawyer::Container::IntervalMap< I, T, Policy >::upperBound().
value() [1/2]
template<class K , class T , class Cmp = std::less<K>, class Alloc = std::allocator<std::pair<const K, T> >> Value & Sawyer::Container::Map< K, T, Cmp, Alloc >::Node::value () inline
Value part of key/value node.
Returns a reference to the value part of a key/value node.
Definition at line 123 of file Sawyer/Map.h.
Referenced by Sawyer::Container::IntervalMap< I, T, Policy >::erase(), Sawyer::Container::DistinctList< T, Cmp >::erase(), Sawyer::Container::IntervalSetMap< I, S >::existsAnywhere(), Sawyer::Container::IntervalSetMap< I, S >::existsEverywhere(), Sawyer::Container::IntervalMap< I, T, Policy >::get(), Sawyer::Container::IntervalMap< I, T, Policy >::getOptional(), Sawyer::Container::IntervalMap< I, T, Policy >::getOrDefault(), Sawyer::Container::IntervalMap< I, T, Policy >::getOrElse(), Sawyer::Container::IntervalMap< I, T, Policy >::getOrElse(), Sawyer::Container::IntervalSetMap< I, S >::getUnion(), Sawyer::Container::IntervalMap< I, T, Policy >::insert(), and Sawyer::Container::IntervalMap< I, T, Policy >::operator[]().
value() [2/2]
template<class K , class T , class Cmp = std::less<K>, class Alloc = std::allocator<std::pair<const K, T> >> const Value & Sawyer::Container::Map< K, T, Cmp, Alloc >::Node::value () const inline
Value part of key/value node.
Returns a reference to the value part of a key/value node.
Definition at line 124 of file Sawyer/Map.h.
The documentation for this class was generated from the following file:
Sawyer/Map.h