ROSE: Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue Class Reference
Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue Class Reference
Description
Values in the NullSemantics domain.
Values are essentially void.
Definition at line 28 of file NullSemantics.h.
#include <Rose/BinaryAnalysis/InstructionSemantics/NullSemantics.h>
Public Types
using Super = BaseSemantics::SValue
Base type.
using Ptr = SValuePtr
Shared-ownership pointer.
Public Types inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue
using Ptr = SValuePtr
Shared-ownership pointer.
Public Member Functions
virtual BaseSemantics::SValuePtr bottom_ (size_t nBits) const override
Data-flow bottom value.
virtual BaseSemantics::SValuePtr undefined_ (size_t nBits) const override
Create a new undefined semantic value.
virtual BaseSemantics::SValuePtr unspecified_ (size_t nBits) const override
Create a new unspecified semantic value.
virtual BaseSemantics::SValuePtr number_ (size_t nBits, uint64_t number) const override
Create a new concrete semantic value.
virtual BaseSemantics::SValuePtr copy (size_t new_width=0) const override
Create a new value from an existing value, changing the width if new_width is non-zero.
virtual Sawyer::Optional< BaseSemantics::SValuePtr > createOptionalMerge (const BaseSemantics::SValuePtr &, const BaseSemantics::MergerPtr &, const SmtSolverPtr &) const override
Possibly create a new value by merging two existing values.
virtual bool isBottom () const override
Determines whether a value is a data-flow bottom.
virtual void print (std::ostream &stream, BaseSemantics::Formatter &) const override
Print a value to a stream using default format.
virtual void hash (Combinatorics::Hasher &hasher) const override
Hash this semantic value.
virtual bool is_number () const override
Virtual API.
virtual uint64_t get_number () const override
Virtual API.
virtual bool may_equal (const BaseSemantics::SValuePtr &, const SmtSolverPtr &=SmtSolverPtr()) const override
Virtual API.
virtual bool must_equal (const BaseSemantics::SValuePtr &other, const SmtSolverPtr &=SmtSolverPtr()) const override
Virtual API.
Public Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue
virtual SValuePtr boolean_ (bool value) const
Create a new, Boolean value.
SValuePtr createMerged (const SValuePtr &other, const MergerPtr &merger, const SmtSolverPtr &solver) const
Create a new value by merging two existing values.
size_t nBits () const
Property: value width.
bool isConcrete () const
Determines if the value is a concrete number.
Sawyer::Optional< uint64_t > toUnsigned () const
Converts a concrete value to a native unsigned integer.
Sawyer::Optional< int64_t > toSigned () const
Converts a concrete value to a native signed integer.
bool mustEqual (const SValuePtr &other, const SmtSolverPtr &solver=SmtSolverPtr()) const
Tests two values for equality.
bool mayEqual (const SValuePtr &other, const SmtSolverPtr &solver=SmtSolverPtr()) const
Tests two values for possible equality.
bool isTrue () const
Returns true if concrete non-zero.
bool isFalse () const
Returns true if concrete zero.
std::string toString () const
Render this symbolic expression as a string.
std::string comment () const
Property: Comment.
void comment (const std::string &) const
Property: Comment.
void print (std::ostream &) const
Print a value to a stream using default format.
WithFormatter with_format (Formatter &fmt)
Used for printing values with formatting.
WithFormatter operator+ (Formatter &fmt)
Used for printing values with formatting.
WithFormatter operator+ (const std::string &linePrefix)
Used for printing values with formatting.
virtual size_t get_width () const
Virtual API.
virtual void set_width (size_t nbits)
Virtual API.
virtual std::string get_comment () const
Some subclasses support the ability to add comments to values.
virtual void set_comment (const std::string &) const
Some subclasses support the ability to add comments to values.
Public Member Functions inherited from Sawyer::SharedObject
SharedObject ()
Default constructor.
SharedObject (const SharedObject &)
Copy constructor.
virtual ~SharedObject ()
Virtual destructor.
SharedObject & operator= (const SharedObject &)
Assignment.
Public Member Functions inherited from Sawyer::SharedFromThis< SValue >
SharedPointer< SValue > sharedFromThis ()
Create a shared pointer from this.
SharedPointer< const SValue > sharedFromThis () const
Create a shared pointer from this.
Static Public Member Functions
static SValuePtr instance ()
Instantiate a new prototypical values.
static SValuePtr instance (size_t nbits)
Instantiate a new undefined value.
static SValuePtr instance (size_t nbits, uint64_t)
Instantiate a new concrete value.
static SValuePtr instance (const SValuePtr &other)
Instantiate a new copy of an existing value.
static SValuePtr promote (const BaseSemantics::SValuePtr &v)
Promote a base value to a NullSemantics value.
Static Public Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue
static SValuePtr promote (const SValuePtr &x)
Static Public Member Functions inherited from Sawyer::SmallObject
static SynchronizedPoolAllocator & poolAllocator ()
Return the pool allocator for this class.
static void * operator new (size_t size)
static void operator delete (void *ptr, size_t size)
Protected Member Functions
SValue (size_t nbits)
Protected Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue
SValue (size_t nbits)
SValue (const SValue &other)
Additional Inherited Members
Protected Attributes inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue
size_t width
Member Typedef Documentation
Super
using Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::Super = BaseSemantics::SValue
Base type.
Definition at line 31 of file NullSemantics.h.
Ptr
using Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::Ptr = SValuePtr
Shared-ownership pointer.
Definition at line 34 of file NullSemantics.h.
Constructor & Destructor Documentation
SValue()
Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::SValue (size_t nbits) inline explicit protected
Definition at line 39 of file NullSemantics.h.
Member Function Documentation
instance() [1/4]
static SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::instance () inline static
Instantiate a new prototypical values.
Prototypical values are only used for their virtual constructors.
Definition at line 45 of file NullSemantics.h.
Referenced by bottom_(), number_(), undefined_(), and unspecified_().
instance() [2/4]
static SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::instance (size_t nbits) inline static
Instantiate a new undefined value.
Definition at line 50 of file NullSemantics.h.
instance() [3/4]
static SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::instance (size_t nbits, uint64_t) inline static
Instantiate a new concrete value.
Definition at line 55 of file NullSemantics.h.
instance() [4/4]
static SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::instance (const SValuePtr & other) inline static
Instantiate a new copy of an existing value.
Definition at line 60 of file NullSemantics.h.
bottom_()
virtual BaseSemantics::SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::bottom_ (size_t nBits) const inline override virtual
Data-flow bottom value.
Returns a new value that represents bottom in a data-flow analysis. If a semantic domain can represent a bottom value then the isBottom predicate is true when invoked on this method's return value. If a semantic domain cannot support a bottom value, then it may return some other value.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 67 of file NullSemantics.h.
References instance(), and Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue::nBits().
undefined_()
virtual BaseSemantics::SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::undefined_ (size_t nbits) const inline override virtual
Create a new undefined semantic value.
The new semantic value will have the same dynamic type as the value on which this virtual method is called. This is the most common way that a new value is created. The unspecified_ method is closely related.
See also
unspecified_
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 70 of file NullSemantics.h.
References instance(), and Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue::nBits().
unspecified_()
virtual BaseSemantics::SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::unspecified_ (size_t nbits) const inline override virtual
Create a new unspecified semantic value.
The new semantic value will have the same dynamic type as the value on which this virtual method is called. Undefined (undefined_) and unspecified are closely related. Unspecified values are the same as undefined values except they're instantiated as the result of some machine instruction where the ISA documentation indicates that the value is unspecified (e.g., status flags for x86 shift and rotate instructions).
Most semantic domains make no distinction between undefined and unspecified.
See also
undefined_
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 73 of file NullSemantics.h.
References instance(), and Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue::nBits().
number_()
virtual BaseSemantics::SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::number_ (size_t nbits, uint64_t number) const inline override virtual
Create a new concrete semantic value.
The new value will represent the specified concrete value and have the same dynamic type as the value on which this virtual method is called. This is the most common way that a new constant is created. The number is truncated to contain nbits bits (higher order bits are cleared).
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 76 of file NullSemantics.h.
References instance(), and Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue::nBits().
copy()
virtual BaseSemantics::SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::copy (size_t new_width = 0) const inline override virtual
Create a new value from an existing value, changing the width if new_width is non-zero.
Increasing the width logically adds zero bits to the most significant side of the value; decreasing the width logically removes bits from the most significant side of the value.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 79 of file NullSemantics.h.
createOptionalMerge()
virtual Sawyer::Optional< BaseSemantics::SValuePtr > Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::createOptionalMerge (const BaseSemantics::SValuePtr & other, const BaseSemantics::MergerPtr & merger, const SmtSolverPtr & solver) const inline override virtual
Possibly create a new value by merging two existing values.
This method optionally returns a new semantic value as the data-flow merge of this and other. If the two inputs are "equal" in some sense of the dataflow implementation then nothing is returned, otherwise a new value is returned. Typical usage is like this:
 if (SValuePtr merged = v1->createOptionalMerge(v2).orDefault()) {
     std::cout <<"v1 and v2 were merged to " <<*merged <<"\n";
 } else {
     std::cout <<"no merge is necessary\n";
 }
 or
@code
 SValuePtr merge;
 if (v1->createOptionalMerge(v2).assignTo(merged)) {
     std::cout <<"v1 and v2 were merged to " <<*merged <<"\n";
 } else {
     std::cout <<"v1 and v2 are equal in some sense (no merge necessary)\n";
 }
If you always want a copy regardless of whether the merge is necessary, then use the createMerged convenience function instead.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 86 of file NullSemantics.h.
promote()
static SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::promote (const BaseSemantics::SValuePtr & v) inline static
Promote a base value to a NullSemantics value.
The value v must have a NullSemantics::SValue dynamic type.
Definition at line 94 of file NullSemantics.h.
References Sawyer::SharedPointer< T >::dynamicCast().
isBottom()
virtual bool Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::isBottom () const inline override virtual
Determines whether a value is a data-flow bottom.
Returns true if this value represents a bottom value for data-flow analysis. Any RiscOperation performed on an operand whose isBottom predicate returns true will itself return a bottom value. This includes operations like "xor x x" which would normally return zero.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 103 of file NullSemantics.h.
print()
virtual void Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::print (std::ostream & , BaseSemantics::Formatter &) const inline override virtual
Print a value to a stream using default format.
The value will normally occupy a single line and not contain leading space or line termination. See also, with_format().
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 107 of file NullSemantics.h.
References Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue::nBits().
hash()
virtual void Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::hash (Combinatorics::Hasher &) const inline override virtual
Hash this semantic value.
Hashes the value by appending it to the specified hasher.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 111 of file NullSemantics.h.
References Rose::Combinatorics::Hasher::insert().
is_number()
virtual bool Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::is_number () const inline override virtual
Virtual API.
See isConcrete.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 121 of file NullSemantics.h.
get_number()
virtual uint64_t Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::get_number () const inline override virtual
Virtual API.
See toUnsigned and toSigned.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 126 of file NullSemantics.h.
may_equal()
virtual bool Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::may_equal (const BaseSemantics::SValuePtr & other, const SmtSolverPtr & solver = SmtSolverPtr()) const inline override virtual
Virtual API.
See mayEqual.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 133 of file NullSemantics.h.
must_equal()
virtual bool Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::SValue::must_equal (const BaseSemantics::SValuePtr & other, const SmtSolverPtr & solver = SmtSolverPtr()) const inline override virtual
Virtual API.
See mustEqual.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::SValue.
Definition at line 138 of file NullSemantics.h.
The documentation for this class was generated from the following file:
NullSemantics.h