ROSE: Sawyer::Container::NullBuffer< A, T > Class Template Reference
Sawyer::Container::NullBuffer< A, T > Class Template Reference
Description
template<class A, class T>
class Sawyer::Container::NullBuffer< A, T >
Buffer that has no data.
This can be useful to reserve areas of of a BufferMap address space without actually storing any data at them. All reads return default values and writes using such a buffer will fail (return zero).
Definition at line 22 of file NullBuffer.h.
#include <Sawyer/NullBuffer.h>
Public Types
typedef A Address
Type of addresses.
typedef T Value
Type of values.
typedef Buffer< A, T > Super
Type of base class.
Public Types inherited from Sawyer::Container::Buffer< A, T >
typedef SharedPointer< Buffer > Ptr
Reference counting smart pointer.
typedef A Address
Key type for addressing data.
typedef T Value
Type of values stored in the buffer.
Public Member Functions
Buffer< A, T >::Ptr copy () const
Create a new copy of buffer data.
Address available (Address start) const
Distance to end of buffer.
void resize (Address newSize)
Change the size of the buffer.
Address read (Value *buf, Address address, Address n) const
Reads data from a buffer.
Address write (const Value *, Address, Address)
Writes data to a buffer.
const Value * data () const
Data for the buffer.
Public Member Functions inherited from Sawyer::Container::Buffer< A, T >
virtual Address size () const
Size of buffer.
virtual void sync ()
Synchronize buffer with persistent storage.
const std::string & name () const
Property: Name.
void name (const std::string &s)
Property: Name.
bool copyOnWrite () const
Property: Copy on write.
void copyOnWrite (bool b)
Property: Copy on write.
Public Member Functions inherited from Sawyer::SharedObject
SharedObject ()
Default constructor.
SharedObject (const SharedObject &)
Copy constructor.
virtual ~SharedObject ()
Virtual destructor.
SharedObject & operator= (const SharedObject &)
Assignment.
Static Public Member Functions
static Buffer< A, T >::Ptr instance (Address size)
Construct a new buffer.
Protected Member Functions
NullBuffer (Address size)
Protected Member Functions inherited from Sawyer::Container::Buffer< A, T >
Buffer (const std::string &name="")
Member Typedef Documentation
Address
template<class A , class T > typedef A Sawyer::Container::NullBuffer< A, T >::Address
Type of addresses.
Definition at line 24 of file NullBuffer.h.
Value
template<class A , class T > typedef T Sawyer::Container::NullBuffer< A, T >::Value
Type of values.
Definition at line 25 of file NullBuffer.h.
Super
template<class A , class T > typedef Buffer<A, T> Sawyer::Container::NullBuffer< A, T >::Super
Type of base class.
Definition at line 26 of file NullBuffer.h.
Constructor & Destructor Documentation
NullBuffer() [1/2]
template<class A , class T > Sawyer::Container::NullBuffer< A, T >::NullBuffer () inline protected
Definition at line 62 of file NullBuffer.h.
NullBuffer() [2/2]
template<class A , class T > Sawyer::Container::NullBuffer< A, T >::NullBuffer (Address size) inline explicit protected
Definition at line 63 of file NullBuffer.h.
Member Function Documentation
instance()
template<class A , class T > static Buffer< A, T >::Ptr Sawyer::Container::NullBuffer< A, T >::instance (Address size) inline static
Construct a new buffer.
The new buffer will act as if it contains size values, although no values will actually be stored.
Definition at line 69 of file NullBuffer.h.
References Sawyer::Container::Buffer< A, T >::size().
Referenced by Sawyer::Container::NullBuffer< A, T >::copy().
copy()
template<class A , class T > Buffer< A, T >::Ptr Sawyer::Container::NullBuffer< A, T >::copy () const inline virtual
Create a new copy of buffer data.
Returns a new buffer containing the same data as the old buffer. Some buffer types cannot make an exact copy, in which case they should return an AllocatingBuffer that holds a snapshot of the source buffer's data as it existed at the time of this operation.
Implements Sawyer::Container::Buffer< A, T >.
Definition at line 73 of file NullBuffer.h.
References Sawyer::Container::NullBuffer< A, T >::instance().
available()
template<class A , class T > Address Sawyer::Container::NullBuffer< A, T >::available (Address address) const inline virtual
Distance to end of buffer.
The distance in units of the Value type from the specified address (inclusive) to the last element of the buffer (inclusive). If the address is beyond the end of the buffer then a distance of zero is returned rather than a negative distance. Note that the return value will overflow to zero if the buffer spans the entire address space.
Implements Sawyer::Container::Buffer< A, T >.
Definition at line 77 of file NullBuffer.h.
Referenced by Sawyer::Container::NullBuffer< A, T >::read().
resize()
template<class A , class T > void Sawyer::Container::NullBuffer< A, T >::resize (Address n) inline virtual
Change the size of the buffer.
Truncates the buffer to a smaller size, or extends the buffer as necessary to make its size n values.
Implements Sawyer::Container::Buffer< A, T >.
Definition at line 81 of file NullBuffer.h.
read()
template<class A , class T > Address Sawyer::Container::NullBuffer< A, T >::read (Value * buf, Address address, Address n) const inline virtual
Reads data from a buffer.
Reads up to n values from this buffer beginning at the specified address and copies them to the caller-supplied argument. Returns the number of values actually copied, which may be smaller than the number requested. The output buffer is not zero-padded for short reads. Also note that the return value may overflow to zero if the entire address space is read.
As a special case, if buf is a null pointer, then no data is copied and the return value indicates the number of values that would have been copied had buf been non-null.
Implements Sawyer::Container::Buffer< A, T >.
Definition at line 85 of file NullBuffer.h.
References Sawyer::Container::NullBuffer< A, T >::available().
write()
template<class A , class T > Address Sawyer::Container::NullBuffer< A, T >::write (const Value * buf, Address address, Address n) inline virtual
Writes data to a buffer.
Writes up to n values from buf into this buffer starting at the specified address. Returns the number of values actually written, which might be smaller than n. The return value will be less than n if an error occurs, but note that the return value may overflow to zero if the entire address space is written.
Implements Sawyer::Container::Buffer< A, T >.
Definition at line 94 of file NullBuffer.h.
data()
template<class A , class T > const Value * Sawyer::Container::NullBuffer< A, T >::data () const inline virtual
Data for the buffer.
Returns a pointer for the buffer data. Those subclasses that don't support this method will return the null pointer.
Implements Sawyer::Container::Buffer< A, T >.
Definition at line 98 of file NullBuffer.h.
The documentation for this class was generated from the following file:
NullBuffer.h