ROSE: SgClassDeclaration Class Reference
SgClassDeclaration Class Reference
Description
This class represents the concept of a class declaration statement. It includes the concept of an instantiated class template as well.
Declaration statements are where variables and types are defined and become available for use within a program. Declarations are strored in symbols (SgSymbol) and used to associate the symbol with a location within a scope within the application source code. There are many different types of declarations, within Sage III the SgDeclaration forms a base class for numerous IR nodes such as: class declarations (including structs and unions), enum declarations, function declarations, namespace declarations, pragma declarations, template declarations, typedef declarations, using declarations, using directives, variable declarations, etc.
An important concept for a few types fo declarations is that of defining vs. non-defining. Defining declarations are associated with definitions, for example a class definition or function definition. A class declaration where a class is defined (instead of a forward declaration) is a defining declaration. A forward declaration is a non-defining declaration. Some declarations are not explicitly forward declarations, they are non-defining declarations. Only declarations where there is a definition are defining declarations. Because definitions can at most appear once within a translation unit (a source file and it included header files), there is at most one defining declaration. The defining declaration is never shared, however the non-defining declaration can be shared and is required to be shared if there is more than one location in the AST where a non-defining declaration is required. There is at most one defining and one non-defining declaration (at some point they will also share their name, but this is not implemented yet). If a variable is defined to be extern or only defined through a refererence or pointer, then there would be no defining declaration (only a non-defining declaration).
The following code contains no defining declaration for the type "foobar":
typedef struct foobar *((FunctionPointer)(void);
foobar* foobar_pointer = NULL;
and yet is vailid code (even though there is no explicit forward declaration of "foobar" as a class (or struct). In this case foobar is represented using a non-defining declaration internally and that declaration is reference multiple types (once within each statement). Note that the code abouve is valid C++, and not valid C code (to make it valid C code we would have to add "struct" the pointer declaration, for example:
struct foobar* foobar_pointer = NULL;
So C++ is not always a super set of C :-).
Different types of declarations explained: C and C++ declarations can come in several forms, for example:
typedef struct { int A; } A; // unnamed class declaration (which gets a name from the typedef)
struct A { int i; };         // autonomous declaration
struct B { int i; } b;       // non autonomous declaration
In these cases "struct" and "class" can be used interchangablily. Internally "struct" and "class" are he same (but with a different enum to classify them, see SgNameType and SgClassType). Clearly most C++ code uses autonomous declarations.
There are no uses of this IR node anywhere. All statements are derived from this SgClassDeclaration class.
This is a base class for all statements.
See also
Example of using a SgClassDeclaration object
Definition at line 300246 of file Cxx_Grammar.h.
Public Types
enum class_types {
e_class ,
e_struct ,
e_union ,
e_template_parameter ,
e_fortran_module ,
e_java_interface ,
e_java_enum ,
e_java_parameter ,
e_jovial_block ,
e_jovial_table
}
enum { static_variant = V_SgClassDeclaration }
static variant value
typedef SgDeclarationStatement base_node_type
Public Types inherited from SgDeclarationStatement
enum template_specialization_enum {
e_unknown = 0 ,
e_no_specialization = 1 ,
e_partial_specialization = 2 ,
e_specialization = 3 ,
e_template_specialization_last = 4
}
Template Specialization Support.
enum gnu_extension_visability_attribute_enum {
e_gnu_attribute_visability_unknown = 0 ,
e_gnu_attribute_visability_unspecified = 1 ,
e_gnu_attribute_visability_hidden = 2 ,
e_gnu_attribute_visability_protected = 3 ,
e_gnu_attribute_visability_internal = 4 ,
e_last_gnu_visability_attribute
}
GNU extension for visibility modifier (only one value can be specified)
enum { static_variant = V_SgDeclarationStatement }
static variant value
typedef SgStatement base_node_type
Public Types inherited from SgStatement
enum { static_variant = V_SgStatement }
static variant value
typedef SgLocatedNode base_node_type
Public Types inherited from SgLocatedNode
enum { static_variant = V_SgLocatedNode }
static variant value
typedef SgNode base_node_type
Public Types inherited from SgNode
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
virtual SgNode * copy (SgCopyHelp &help) const override
virtual SgName get_qualified_name () const
virtual SgName get_mangled_name (void) const override
SgName get_mangled_qualified_name (int &cnt)
virtual bool hasExplicitScope () const override
Support for where the scope is explicitly required.
virtual unsigned int cfgIndexForEnd () const override
Determine the CFG index for the end of this construct.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index) override
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index) override
Find the in edges of a CFG node – internal version.
virtual SgSymbol * get_symbol_from_symbol_table () const override
FOR INTERNAL USE Get the associated symbol from the symbol table in the stored scope. Users should use the SgDeclarationStatement::search_for_symbol_from_symbol_table() instead.
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const override
int get_name_qualification_length () const
void set_name_qualification_length (int name_qualification_length)
bool get_type_elaboration_required () const
void set_type_elaboration_required (bool type_elaboration_required)
bool get_global_qualification_required () const
void set_global_qualification_required (bool global_qualification_required)
bool isSpecialization () const
bool isPartialSpecialization () const
virtual std::string class_name () const override
returns a string representing the class name
virtual VariantT variantT () const override
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer () override
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer () override
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors () override
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx) override
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child) override
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI () override
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const override
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor) override
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const override
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const override
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgClassDeclaration (const SgClassDeclarationStorageClass &source)
IR node constructor to support AST File I/O.
SgClassDeclaration * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
SgName get_name () const
void set_name (SgName name)
SgClassDeclaration::class_types get_class_type () const
void set_class_type (SgClassDeclaration::class_types class_type)
SgClassType * get_type () const
void set_type (SgClassType *type)
SgClassDefinition * get_definition () const
void set_definition (SgClassDefinition *definition)
SgScopeStatement * get_scope () const override
Returns scope of current statement.
void set_scope (SgScopeStatement *scope) override
Support for setting scopes (only meaningful on IR statements that store the scope explicitly).
SgDeclarationStatement::template_specialization_enum get_specialization () const
void set_specialization (SgDeclarationStatement::template_specialization_enum specialization)
bool get_from_template () const
void set_from_template (bool from_template)
bool get_fixupScope () const
void set_fixupScope (bool fixupScope)
bool get_isUnNamed () const
void set_isUnNamed (bool isUnNamed)
bool get_explicit_annotation_interface () const
void set_explicit_annotation_interface (bool explicit_annotation_interface)
bool get_explicit_interface () const
void set_explicit_interface (bool explicit_interface)
bool get_explicit_enum () const
void set_explicit_enum (bool explicit_enum)
bool get_explicit_anonymous () const
void set_explicit_anonymous (bool explicit_anonymous)
SgExprListExp * get_decoratorList () const
void set_decoratorList (SgExprListExp *decoratorList)
bool get_isAutonomousDeclaration () const
void set_isAutonomousDeclaration (bool isAutonomousDeclaration)
bool get_isRepresentingTemplateParameterInTemplateDeclaration () const
void set_isRepresentingTemplateParameterInTemplateDeclaration (bool isRepresentingTemplateParameterInTemplateDeclaration)
SgBaseClass * get_adaParentType () const
void set_adaParentType (SgBaseClass *adaParentType)
virtual ~SgClassDeclaration ()
This is the destructor.
SgClassDeclaration (Sg_File_Info *startOfConstruct, SgName name="", SgClassDeclaration::class_types class_type=SgClassDeclaration::e_class, SgClassType *type=NULL, SgClassDefinition *definition=NULL)
SgClassDeclaration (SgName name, SgClassDeclaration::class_types class_type, SgClassType *type, SgClassDefinition *definition)
Public Member Functions inherited from SgDeclarationStatement
bool isForward () const
Returns boolean value indicating if this is a forward declaration.
void setForward ()
Marks a declaration as a forward declaration.
void unsetForward ()
Marks a forward declaration as a non-forward declaration.
bool isNameOnly () const
void setNameOnly ()
void unsetNameOnly ()
bool isExternBrace () const
void setExternBrace ()
void unsetExternBrace ()
bool skipElaborateType () const
void setSkipElaborateType ()
void unsetSkipElaborateType ()
SgQualifiedNamePtrList & get_qualifiedNameList ()
const SgQualifiedNamePtrList & get_qualifiedNameList () const
void set_qualifiedNameList (const SgQualifiedNamePtrList &x)
SgDeclarationStatement * get_declaration_associated_with_symbol () const
SgSymbol * search_for_symbol_from_symbol_table () const
User interface for retrieving the associated symbol from the declaration.
bool hasAssociatedSymbol () const
Returns boolean value true of this type of declaration has an associated sysmbol.
SgName get_qualified_name_prefix () const
This function generates the qualified name prefix to be used with the named declaration (only applied to restricted set of declarations where name qualification can be used).
SgName get_template_name () const
This function returns the template name (taken from the template declaration for the class, function, member function, or variable template declaration).
SgDeclarationStatement * get_definingDeclaration () const
This is an access function for the SgDeclarationStatement::p_definingDeclaration data member (see that variable's documentation for details).
void set_definingDeclaration (SgDeclarationStatement *definingDeclaration)
This is an access function for the SgDeclarationStatement::p_definingDeclaration data member (see that variable's documentation for details).
SgDeclarationStatement * get_firstNondefiningDeclaration () const
This is an access function for the SgDeclarationStatement::p_firstNondefiningDeclaration data member (see that variable's documentation for details).
void set_firstNondefiningDeclaration (SgDeclarationStatement *firstNondefiningDeclaration)
This is an access function for the SgDeclarationStatement::p_firstNondefiningDeclaration data member (see that variable's documentation for details).
SgType * get_type () const
std::string unparseNameToString ()
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgDeclarationStatement (const SgDeclarationStatementStorageClass &source)
IR node constructor to support AST File I/O.
SgDeclarationStatement * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
unsigned int get_decl_attributes () const
void set_decl_attributes (unsigned int decl_attributes)
std::string get_linkage () const
void set_linkage (std::string linkage)
const SgDeclarationModifier & get_declarationModifier () const
SgDeclarationModifier & get_declarationModifier ()
Returns SgDeclarationModifier object by reference (so that it can be set).
bool get_nameOnly () const
void set_nameOnly (bool nameOnly)
bool get_forward () const
void set_forward (bool forward)
bool get_externBrace () const
void set_externBrace (bool externBrace)
bool get_skipElaborateType () const
void set_skipElaborateType (bool skipElaborateType)
std::string get_binding_label () const
void set_binding_label (std::string binding_label)
SgDeclarationScope * get_declarationScope () const
void set_declarationScope (SgDeclarationScope *declarationScope)
bool get_unparse_template_ast () const
void set_unparse_template_ast (bool unparse_template_ast)
SgExprListExp * get_adaAspects () const
void set_adaAspects (SgExprListExp *adaAspects)
virtual ~SgDeclarationStatement ()
This is the destructor.
SgDeclarationStatement (Sg_File_Info *startOfConstruct)
This is the constructor.
Public Member Functions inherited from SgStatement
virtual void setExtern ()
This function sets "extern" status for the current statement.
virtual void setStatic ()
This function sets "static" status for the current statement.
void insert_statement (SgStatement *target, SgStatement *newstmt, bool inFront=true)
This function inserts a single statement at the position indicated by target.
void insert_statement (SgStatement *target, const SgStatementPtrList &newstmtList, bool inFront=true)
This function inserts a list of statements at the position indicated by target.
void replace_statement (SgStatement *target, SgStatement *newstmt)
This function replaces the target statement with a single statement.
void replace_statement (SgStatement *target, const SgStatementPtrList &newstmtList)
This function replaces the target statement with a list of statements.
void remove_statement (SgStatement *)
This function removes the target statement from the AST.
void insert_statement_from_basicBlock (SgStatement *target, SgStatement *newstmt, bool inFront=true)
This function inserts a statement at the position indicated by target. If newstmt is a basicBlock, statements inside newstmt are extracted and then inserted.
void replace_statement_from_basicBlock (SgStatement *target, SgStatement *newstmt)
This function replaces the target statement with a new statement. If newstmt is a basicBlock, statements inside newstmt are extracted and then inserted.
virtual int replace_expression (SgExpression *original_expression, SgExpression *new_expression)
support general replace functions, used in statements that directly contain SgExpression IR nodes.
virtual bool cfgIsIndexInteresting (unsigned int index) const override
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n) override
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n) override
Find the index just after n in this node's CFG children.
virtual bool isChildUsedAsLValue (const SgExpression *child) const
Virtual function to determine if the provided expression is used as an l-value within the cotext of this statement.
virtual void set_end_numeric_label (SgLabelRefExp *end_numeric_label)
virtual bool has_end_numeric_label () const
bool hasExplicitType ()
Some statement store internal SgType pointers explicitly. This function is true if it has a data member that is a type (only applies to SgTypedefDeclaration).
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgStatement (const SgStatementStorageClass &source)
IR node constructor to support AST File I/O.
SgStatement * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
SgLabelRefExp * get_numeric_label () const
void set_numeric_label (SgLabelRefExp *numeric_label)
int get_source_sequence_value () const
void set_source_sequence_value (int source_sequence_value)
virtual ~SgStatement ()
This is the destructor.
SgStatement (Sg_File_Info *startOfConstruct)
This is the constructor.
Public Member Functions inherited from SgLocatedNode
const std::string & getFilenameString () const
void addToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo::RelativePositionType locationInList=PreprocessingInfo::after)
This function adds comment or CPP directives to the current IR node.
void insertToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo *anchorInfoPtr, bool insertAfter=true)
Insert prepInfo After (or before if last parameter is false) an anchor info ptr in the list of preprocessing info attached to the current node. This is useful to insert things in the middle.
virtual Sg_File_Info * get_file_info () const override
Interface function to implement original SAGE interface to SgFile_Info objects.
virtual void set_file_info (Sg_File_Info *X)
Access function calls set_startingConstruct(Sg_File_Info*) member function.
void setCompilerGenerated ()
Allow IR nodes (mostly SgLocatedNode) to be marked as compiler generated.
void unsetCompilerGenerated ()
bool isCompilerGenerated () const
Simple test for if this is a compiler generated node.
void setTransformation ()
Allow IR nodes (mostly SgLocatedNode) to be marked as a transformation.
void unsetTransformation ()
bool isTransformation () const
Simple test for if this is a part of a transformation.
void setFrontendSpecific ()
Allow IR nodes (mostly SgLocatedNode) to be marked as front-end specific (generated by the front-end to support a specific backend compiler; e.g. GNU gcc and g++).
void unsetFrontendSpecific ()
bool isFrontendSpecific () const
Simple test for if this is a frontend specific IR node.
void setShared ()
Allow IR nodes (mostly SgLocatedNode) to be marked as shared.
void unsetShared ()
bool isShared () const
Simple test for if this is a shared IR node.
void setSourcePositionUnavailableInFrontend ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetSourcePositionUnavailableInFrontend ()
void setOutputInCodeGeneration ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetOutputInCodeGeneration ()
bool isOutputInCodeGeneration () const
int get_physical_file_id ()
Allow IR nodes (mostly SgLocatedNode) to be queried for there physical file ID.
AttachedPreprocessingInfoType *& getAttachedPreprocessingInfo (void)
Computes the number of nodes in the defined subtree of the AST.
Sg_File_Info * generateMatchingFileInfo ()
virtual void addNewAttribute (std::string s, AstAttribute *a) override
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const override
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a) override
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a) override
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s) override
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const override
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const override
Returns the number of attributes on this IR node.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgLocatedNode (const SgLocatedNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgLocatedNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
Sg_File_Info * get_startOfConstruct () const override
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
void set_startOfConstruct (Sg_File_Info *startOfConstruct)
This function sets the current source location position of the start of the current construct.
Sg_File_Info * get_endOfConstruct () const override
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
void set_endOfConstruct (Sg_File_Info *endOfConstruct)
This function sets the current source location position of the end of the current construct.
AttachedPreprocessingInfoType * get_attachedPreprocessingInfoPtr () const
void set_attachedPreprocessingInfoPtr (AttachedPreprocessingInfoType *attachedPreprocessingInfoPtr)
AstAttributeMechanism * get_attributeMechanism () const override
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
void set_attributeMechanism (AstAttributeMechanism *attributeMechanism) override
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
bool get_containsTransformationToSurroundingWhitespace () const
void set_containsTransformationToSurroundingWhitespace (bool containsTransformationToSurroundingWhitespace)
virtual ~SgLocatedNode ()
This is the destructor.
SgLocatedNode (Sg_File_Info *startOfConstruct=NULL)
This is the constructor.
Public Member Functions inherited from SgNode
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
Static Public Member Functions
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgClassDeclaration * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgClassDeclaration *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgClassDeclaration *sgnode)
Static Public Member Functions inherited from SgDeclarationStatement
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgDeclarationStatement * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgDeclarationStatement *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgDeclarationStatement *sgnode)
Static Public Member Functions inherited from SgStatement
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgStatement * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgStatement *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgStatement *sgnode)
Static Public Member Functions inherited from SgLocatedNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgLocatedNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgLocatedNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgLocatedNode *sgnode)
Static Public Member Functions inherited from SgNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Protected Member Functions
virtual bool replace_child (SgStatement *, SgStatement *, bool extractListFromBasicBlock=false) override
Private supporting function for low level SageIII rewrite interface.
SgClassDefinition * compute_classDefinition () const
Protected Member Functions inherited from SgDeclarationStatement
void resetTemplateNameSupport (bool &nameResetFromMangledForm, SgName &name)
void testForBadGenerateTemplateName (const std::string &name)
bool skipEmptyTemplateArgumentListTest (SgFunctionDeclaration *functionDeclaration)
SgName fixupTemplateNameForMangledNameSupport (const SgName &s) const
SgName generate_alternative_name_for_unnamed_declaration (SgNode *parent) const
SgName generate_alternative_name_for_unnamed_declaration_in_scope (SgScopeStatement *scope) const
Protected Member Functions inherited from SgStatement
virtual bool insert_child (SgStatement *, SgStatement *, bool inFront=true, bool extractListFromBasicBlock=false)
Private supporting function for low level SageIII rewrite interface.
Protected Member Functions inherited from SgNode
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Protected Attributes
SgName p_name
This is the name of the class or instantiated class template.
SgClassDeclaration::class_types p_class_type
Enum value classifying this as a class,struct,or union.
SgClassType * p_type
This is the type used in the declaration (SgClassType).
SgClassDefinition * p_definition
This is the class definition (alway a valid pointer, except for explicitly marked forward declarations).
SgScopeStatement * p_scope
SgDeclarationStatement::template_specialization_enum p_specialization
bool p_from_template
This records if the class declaration is associated with a template.
bool p_fixupScope
bool p_isUnNamed
bool p_explicit_annotation_interface
bool p_explicit_interface
bool p_explicit_enum
bool p_explicit_anonymous
SgExprListExp * p_decoratorList
int p_name_qualification_length
bool p_type_elaboration_required
bool p_global_qualification_required
bool p_isAutonomousDeclaration
bool p_isRepresentingTemplateParameterInTemplateDeclaration
SgBaseClass * p_adaParentType
Protected Attributes inherited from SgDeclarationStatement
unsigned int p_decl_attributes
This is old and used to be used to hold modifiers.
std::string p_linkage
This string stores the value "C", "C++", or "fortran" to define the external linkage for generating linkable names.
SgDeclarationModifier p_declarationModifier
This is the mechanism to handle declaration modifiers.
bool p_nameOnly
I think this is somewhat redundant with the purpose of specifying a forward declaration. Either that or it is information used by the unparser (Oh, I hope not!).
bool p_forward
This marks a declaration as being an explicit forward declaration.
bool p_externBrace
This marks that the declaration appeared with "extern".
bool p_skipElaborateType
This marks "type elaboration" which is the use of the keyword "class" before variables of type class.
SgDeclarationStatement * p_definingDeclaration
This pointer is valid only if a defining declaration exists, and stores the defining declaration where the declaration was defined.
SgDeclarationStatement * p_firstNondefiningDeclaration
This pointer is valid if there is a non-defining declaration, and stores the first non-defining declaration where a declaration was made explicitly (as in forward declaration) or implicitly as in the case of a few IR nodes (e.g. SgClassDeclaration). See description of SgDeclarationStatement.
SgQualifiedNamePtrList p_qualifiedNameList
std::string p_binding_label
SgDeclarationScope * p_declarationScope
bool p_unparse_template_ast
SgExprListExp * p_adaAspects
Protected Attributes inherited from SgStatement
SgLabelRefExp * p_numeric_label
int p_source_sequence_value
Protected Attributes inherited from SgLocatedNode
Sg_File_Info * p_startOfConstruct
This pointer is always valid and stores the source position of the start of the current construct.
Sg_File_Info * p_endOfConstruct
This pointer is always valid and stores the source position of the end of the current construct.
AttachedPreprocessingInfoType * p_attachedPreprocessingInfoPtr
Holds comments and/or preprocessor directives located before or after the current statement of expression.
AstAttributeMechanism * p_attributeMechanism
bool p_containsTransformationToSurroundingWhitespace
Protected Attributes inherited from SgNode
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Additional Inherited Members
Static Protected Attributes inherited from SgNode
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Member Typedef Documentation
base_node_type
typedef SgDeclarationStatement SgClassDeclaration::base_node_type
Definition at line 300740 of file Cxx_Grammar.h.
Member Enumeration Documentation
class_types
enum SgClassDeclaration::class_types
A declaration can be of either class, struct, union, or ...
Enumerator
e_class
class declaration (default)
e_struct
struct declaration
e_union
union declaration
e_template_parameter
type parameter in a template declaration
e_fortran_module
A Fortran module declaration
e_java_interface
A Java interface type declaration
e_java_enum
A Java enum type declaration
e_java_parameter
A Java parameter type declaration
e_jovial_block
A Jovial block type declaration
e_jovial_table
A Jovial table type declaration
Definition at line 300259 of file Cxx_Grammar.h.
anonymous enum
anonymous enum
static variant value
Definition at line 300361 of file Cxx_Grammar.h.
Constructor & Destructor Documentation
~SgClassDeclaration()
SgClassDeclaration::~SgClassDeclaration () virtual
This is the destructor.
There are a lot of things to delete, but nothing is deleted in this destructor.
Member Function Documentation
copy()
virtual SgNode * SgClassDeclaration::copy (SgCopyHelp & help) const override virtual
Reimplemented from SgDeclarationStatement.
get_mangled_name()
virtual SgName SgClassDeclaration::get_mangled_name (void) const override virtual
Reimplemented from SgDeclarationStatement.
get_mangled_qualified_name()
SgName SgClassDeclaration::get_mangled_qualified_name (int & cnt)
replace_child()
virtual bool SgClassDeclaration::replace_child (SgStatement * target, SgStatement * newStmt, bool extractListFromBasicBlock = false) override protected virtual
Private supporting function for low level SageIII rewrite interface.
This function implements special semantics for the insertion of a collection of statements in a block. If extractListFromBasicBlock is true then the statements in the block are extracts and placed into the same scope as the target position.
Returns
Returns bool.
Reimplemented from SgStatement.
hasExplicitScope()
virtual bool SgClassDeclaration::hasExplicitScope () const override virtual
Support for where the scope is explicitly required.
Reimplemented from SgStatement.
cfgIndexForEnd()
virtual unsigned int SgClassDeclaration::cfgIndexForEnd () const override virtual
Determine the CFG index for the end of this construct.
Reimplemented from SgStatement.
Reimplemented in SgModuleStatement.
cfgOutEdges()
virtual std::vector< VirtualCFG::CFGEdge > SgClassDeclaration::cfgOutEdges (unsigned int index) override virtual
Find the out edges of a CFG node – internal version.
Reimplemented from SgStatement.
Reimplemented in SgModuleStatement.
cfgInEdges()
virtual std::vector< VirtualCFG::CFGEdge > SgClassDeclaration::cfgInEdges (unsigned int index) override virtual
Find the in edges of a CFG node – internal version.
Reimplemented from SgStatement.
Reimplemented in SgModuleStatement.
get_symbol_from_symbol_table()
virtual SgSymbol * SgClassDeclaration::get_symbol_from_symbol_table () const override virtual
FOR INTERNAL USE Get the associated symbol from the symbol table in the stored scope. Users should use the SgDeclarationStatement::search_for_symbol_from_symbol_table() instead.
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateInstantiationDecl.
Referenced by SageBuilder::buildClassDeclaration_nfi(), SageBuilder::buildNondefiningClassDeclaration_nfi(), SageBuilder::buildNondefiningTemplateClassDeclaration_nfi(), SageBuilder::buildTemplateClassDeclaration_nfi(), SageInterface::deleteAST(), SageInterface::fixStructDeclaration(), and CollectDependentDeclarationsTraversal::visit().
fixupCopy_scopes()
virtual void SgClassDeclaration::fixupCopy_scopes (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgDeclarationStatement.
fixupCopy_symbols()
virtual void SgClassDeclaration::fixupCopy_symbols (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgDeclarationStatement.
fixupCopy_references()
virtual void SgClassDeclaration::fixupCopy_references (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgDeclarationStatement.
class_name()
virtual std::string SgClassDeclaration::class_name () const override virtual
returns a string representing the class name
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
Referenced by SageInterface::appendStatement(), SageBuilder::buildClassDeclaration_nfi(), SageBuilder::buildNondefiningClassDeclaration(), SageBuilder::buildNondefiningClassDeclaration_nfi(), SageInterface::getClassTypeChainForMemberReference(), SageInterface::getEnclosingFileNode(), and SageInterface::rebuildSymbolTable().
variantT()
virtual VariantT SgClassDeclaration::variantT () const override virtual
returns new style SageIII enum values
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
Referenced by SageBuilder::buildNondefiningClassDeclaration_nfi().
operator delete()
void SgClassDeclaration::operator delete (void * pointer) inline
Definition at line 300416 of file Cxx_Grammar.h.
get_traversalSuccessorContainer()
virtual std::vector< SgNode * > SgClassDeclaration::get_traversalSuccessorContainer () override virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
get_traversalSuccessorNamesContainer()
virtual std::vector< std::string > SgClassDeclaration::get_traversalSuccessorNamesContainer () override virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
get_numberOfTraversalSuccessors()
virtual size_t SgClassDeclaration::get_numberOfTraversalSuccessors () override virtual
return number of children in the traversal successor list
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
get_traversalSuccessorByIndex()
virtual SgNode * SgClassDeclaration::get_traversalSuccessorByIndex (size_t idx) override virtual
index-based access to traversal successors by index number
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
get_childIndex()
virtual size_t SgClassDeclaration::get_childIndex (SgNode * child) override virtual
index-based access to traversal successors by child node
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
roseRTI()
virtual RTIReturnType SgClassDeclaration::roseRTI () override virtual
return C++ Runtime-Time-Information
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
sage_class_name()
virtual const char * SgClassDeclaration::sage_class_name () const override virtual
returns a C style string (char*) representing the class name
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
accept()
virtual void SgClassDeclaration::accept (ROSE_VisitorPattern & visitor) override virtual
support for the classic visitor pattern done in GoF
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
isInMemoryPool()
virtual bool SgClassDeclaration::isInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
checkDataMemberPointersIfInMemoryPool()
virtual void SgClassDeclaration::checkDataMemberPointersIfInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
returnDataMemberPointers()
virtual std::vector< std::pair< SgNode *, std::string > > SgClassDeclaration::returnDataMemberPointers () const override virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
processDataMemberReferenceToPointers()
virtual void SgClassDeclaration::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
getChildIndex()
virtual long SgClassDeclaration::getChildIndex (SgNode * childNode) const override virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented from SgDeclarationStatement.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
addRegExpAttribute()
SgClassDeclaration * SgClassDeclaration::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
post_construction_initialization()
void SgClassDeclaration::post_construction_initialization () override virtual
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
Reimplemented from SgNode.
Reimplemented in SgTemplateClassDeclaration, SgTemplateInstantiationDecl, SgDerivedTypeStatement, SgModuleStatement, SgJavaPackageDeclaration, and SgJovialTableStatement.
get_scope()
SgScopeStatement * SgClassDeclaration::get_scope (void) const override virtual
Returns scope of current statement.
This functions returns a pointer to the inner most SgScopeStatement where the current statement is located. This is a function called after the parents have been set. It is not called by the EDG/SAGE interface and is only called after the SAGE AST has been built and the parent pointers set within a separate phase. Improtant exception: The SgFunctionParameterList should have as it's scope the SgFunctionDefinition, but it is a sibling of the SgFunctionDefinition (both the SgFunctionParameterList and the SgFunctionDefinition have the SgFunctionDeclaration as a parent. Thus the scope of the SgFunctionParameterList is computed to be the SgGlobal (global scope) most often; which is an error). So we handle this case explicitly.
Returns
Returns valid pointer to SgScopeStatement.
Reimplemented from SgStatement.
Referenced by SageBuilder::buildClassDeclaration_nfi(), SageBuilder::buildDefiningClassDeclaration(), SageBuilder::buildNondefiningClassDeclaration(), SageBuilder::buildNondefiningClassDeclaration_nfi(), SageBuilder::buildNondefiningTemplateClassDeclaration_nfi(), SageBuilder::buildTemplateClassDeclaration_nfi(), SageInterface::deleteAST(), SageInterface::fixStructDeclaration(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::generateUniqueNameForUseAsIdentifier_support(), and SageInterface::rebuildSymbolTable().
set_scope()
void SgClassDeclaration::set_scope (SgScopeStatement * newScope) override virtual
Support for setting scopes (only meaningful on IR statements that store the scope explicitly).
Reimplemented from SgStatement.
Referenced by SageBuilder::buildDefiningClassDeclaration(), SageBuilder::buildNondefiningClassDeclaration(), SageBuilder::buildNondefiningClassDeclaration_nfi(), SageBuilder::buildNondefiningTemplateClassDeclaration_nfi(), SageBuilder::buildTemplateClassDeclaration_nfi(), SageInterface::fixStructDeclaration(), and SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst().
Member Data Documentation
p_name
SgClassDeclaration::p_name protected
This is the name of the class or instantiated class template.
Definition at line 300834 of file Cxx_Grammar.h.
p_class_type
SgClassDeclaration::p_class_type protected
Enum value classifying this as a class,struct,or union.
Definition at line 300838 of file Cxx_Grammar.h.
p_type
SgClassDeclaration::p_type protected
This is the type used in the declaration (SgClassType).
Definition at line 300842 of file Cxx_Grammar.h.
p_definition
SgClassDeclaration::p_definition protected
This is the class definition (alway a valid pointer, except for explicitly marked forward declarations).
When this is a defining or nondefining declartion the p_definition pointer is always valid. However, as a separate rule, all forward declarations are both makred explicit as forward declarations AND have a NULL value for their p_definition pointer.
Definition at line 300846 of file Cxx_Grammar.h.
p_scope
SgScopeStatement* SgClassDeclaration::p_scope protected
Definition at line 300850 of file Cxx_Grammar.h.
p_specialization
SgDeclarationStatement::template_specialization_enum SgClassDeclaration::p_specialization protected
Definition at line 300854 of file Cxx_Grammar.h.
p_from_template
SgClassDeclaration::p_from_template protected
This records if the class declaration is associated with a template.
This boolean value is set to true if this is a non-template class nested in a templated class. We have an explicit IR node for template classes, but this is only flag to indicate that several template specific rules apply to the declaration of this class if the value is true. For example, the class will not be output unless it is transformed, then the required specialization is required for the parent templated class.
Definition at line 300858 of file Cxx_Grammar.h.
p_fixupScope
bool SgClassDeclaration::p_fixupScope protected
Definition at line 300862 of file Cxx_Grammar.h.
p_isUnNamed
bool SgClassDeclaration::p_isUnNamed protected
Definition at line 300866 of file Cxx_Grammar.h.
p_explicit_annotation_interface
bool SgClassDeclaration::p_explicit_annotation_interface protected
Definition at line 300870 of file Cxx_Grammar.h.
p_explicit_interface
bool SgClassDeclaration::p_explicit_interface protected
Definition at line 300874 of file Cxx_Grammar.h.
p_explicit_enum
bool SgClassDeclaration::p_explicit_enum protected
Definition at line 300878 of file Cxx_Grammar.h.
p_explicit_anonymous
bool SgClassDeclaration::p_explicit_anonymous protected
Definition at line 300882 of file Cxx_Grammar.h.
p_decoratorList
SgExprListExp* SgClassDeclaration::p_decoratorList protected
Definition at line 300886 of file Cxx_Grammar.h.
p_name_qualification_length
int SgClassDeclaration::p_name_qualification_length protected
Definition at line 300890 of file Cxx_Grammar.h.
p_type_elaboration_required
bool SgClassDeclaration::p_type_elaboration_required protected
Definition at line 300894 of file Cxx_Grammar.h.
p_global_qualification_required
bool SgClassDeclaration::p_global_qualification_required protected
Definition at line 300898 of file Cxx_Grammar.h.
p_isAutonomousDeclaration
bool SgClassDeclaration::p_isAutonomousDeclaration protected
Definition at line 300902 of file Cxx_Grammar.h.
p_isRepresentingTemplateParameterInTemplateDeclaration
bool SgClassDeclaration::p_isRepresentingTemplateParameterInTemplateDeclaration protected
Definition at line 300906 of file Cxx_Grammar.h.
p_adaParentType
SgBaseClass* SgClassDeclaration::p_adaParentType protected
Definition at line 300910 of file Cxx_Grammar.h.
The documentation for this class was generated from the following files:
Cxx_Grammar.h
SgClassDeclaration.docs