ROSE: SgTemplateArgument Class Reference
SgTemplateArgument Class Reference
Description
This class represents template argument within the use of a template to build an instantiation.
The template argument is used for the instatiation of templates. They can also have default values and not be specified explicitly.
Definition at line 51254 of file Cxx_Grammar.h.
Public Types
enum template_argument_enum {
argument_undefined = 0 ,
type_argument = 1 ,
nontype_argument = 2 ,
template_template_argument = 3 ,
start_of_pack_expansion_argument = 4
}
enum { static_variant = V_SgTemplateArgument }
static variant value
typedef SgSupport base_node_type
Public Types inherited from SgSupport
enum { static_variant = V_SgSupport }
static variant value
typedef SgNode base_node_type
Public Types inherited from SgNode
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
virtual SgNode * copy (SgCopyHelp &help) const override
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
SgTemplateArgument (SgType *parameter, bool explicitlySpecified)
Constructor used with types.
SgTemplateArgument (SgExpression *parameter, bool explicitlySpecified)
Constructor used with expressions.
SgTemplateArgument (SgTemplateDeclaration *parameter, bool explicitlySpecified)
SgTemplateArgument (bool explicitlySpecified)
SgName get_mangled_name (void) const
Returns the template argument in mangled form.
SgScopeStatement * get_scope () const
Some template arguments have an associated scope (e.g. named types, and template template arguments)
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const override
SgName get_qualified_name_prefix () const
This function generates the qualified name prefix to be used with the template argument type.
SgName get_qualified_name_prefix_for_type () const
This function generates the qualified name prefix to be used with the named declaration (only applied to restricted set of declarations where name qualification can be used).
int get_name_qualification_length () const
void set_name_qualification_length (int name_qualification_length)
bool get_type_elaboration_required () const
void set_type_elaboration_required (bool type_elaboration_required)
bool get_global_qualification_required () const
void set_global_qualification_required (bool global_qualification_required)
bool get_requiresGlobalNameQualificationOnType () const
void set_requiresGlobalNameQualificationOnType (bool requiresGlobalNameQualificationOnType)
int get_name_qualification_length_for_type () const
void set_name_qualification_length_for_type (int name_qualification_length_for_type)
bool get_type_elaboration_required_for_type () const
void set_type_elaboration_required_for_type (bool type_elaboration_required_for_type)
bool get_global_qualification_required_for_type () const
void set_global_qualification_required_for_type (bool global_qualification_required_for_type)
void display (const std::string &label) const
std::string unparseToStringSupport ()
std::string template_argument_kind () const
bool isTemplateArgumentFromAnonymousClass () const
void outputTemplateArgument (bool &skip_unparsing, bool &stop_unparsing)
virtual std::string class_name () const override
returns a string representing the class name
virtual VariantT variantT () const override
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer () override
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer () override
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors () override
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx) override
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child) override
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI () override
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const override
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor) override
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const override
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const override
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgTemplateArgument (const SgTemplateArgumentStorageClass &source)
IR node constructor to support AST File I/O.
SgTemplateArgument * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
SgTemplateArgument::template_argument_enum get_argumentType () const
This function returns argumentType.
void set_argumentType (SgTemplateArgument::template_argument_enum argumentType)
This function sets argumentType.
bool get_isArrayBoundUnknownType () const
This function returns isArrayBoundUnknownType.
void set_isArrayBoundUnknownType (bool isArrayBoundUnknownType)
This function sets isArrayBoundUnknownType.
SgType * get_type () const
This function returns argumentType.
void set_type (SgType *type)
SgType * get_unparsable_type_alias () const
void set_unparsable_type_alias (SgType *unparsable_type_alias)
SgExpression * get_expression () const
This function returns argumentExpression.
void set_expression (SgExpression *expression)
SgDeclarationStatement * get_templateDeclaration () const
void set_templateDeclaration (SgDeclarationStatement *templateDeclaration)
SgInitializedName * get_initializedName () const
void set_initializedName (SgInitializedName *initializedName)
bool get_explicitlySpecified () const
This function returns explicitlySpecified.
void set_explicitlySpecified (bool explicitlySpecified)
This function sets explicitlySpecified.
SgTemplateArgument * get_previous_instance () const
void set_previous_instance (SgTemplateArgument *previous_instance)
SgTemplateArgument * get_next_instance () const
void set_next_instance (SgTemplateArgument *next_instance)
bool get_is_pack_element () const
void set_is_pack_element (bool is_pack_element)
virtual ~SgTemplateArgument ()
This is the destructor.
SgTemplateArgument (SgTemplateArgument::template_argument_enum argumentType=argument_undefined, bool isArrayBoundUnknownType=false, SgType *type=nullptr, SgExpression *expression=nullptr, SgDeclarationStatement *templateDeclaration=nullptr, bool explicitlySpecified=true)
Public Member Functions inherited from SgSupport
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgSupport (const SgSupportStorageClass &source)
IR node constructor to support AST File I/O.
SgSupport * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
virtual ~SgSupport ()
This is the destructor.
SgSupport ()
This is the constructor.
Public Member Functions inherited from SgNode
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
virtual void addNewAttribute (std::string s, AstAttribute *a)
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a)
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a)
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s)
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const
Returns the number of attributes on this IR node.
virtual AstAttributeMechanism * get_attributeMechanism () const
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
virtual void set_attributeMechanism (AstAttributeMechanism *a)
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
virtual Sg_File_Info * get_file_info (void) const
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
virtual Sg_File_Info * get_startOfConstruct (void) const
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
virtual Sg_File_Info * get_endOfConstruct (void) const
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
virtual unsigned int cfgIndexForEnd () const
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n)
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n)
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index=false)
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index=false)
Find the in edges of a CFG node – internal version.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
virtual void addNewAttribute (std::string s, AstAttribute *a)
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a)
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a)
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s)
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const
Returns the number of attributes on this IR node.
virtual AstAttributeMechanism * get_attributeMechanism () const
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
virtual void set_attributeMechanism (AstAttributeMechanism *a)
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
virtual Sg_File_Info * get_file_info (void) const
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
virtual Sg_File_Info * get_startOfConstruct (void) const
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
virtual Sg_File_Info * get_endOfConstruct (void) const
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
virtual unsigned int cfgIndexForEnd () const
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n)
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n)
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index=false)
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index=false)
Find the in edges of a CFG node – internal version.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
Static Public Member Functions
static bool is_matching_type (const SgTemplateArgument &X, const SgTemplateArgument &Y)
static bool is_matching_nontype (const SgTemplateArgument &X, const SgTemplateArgument &Y)
static bool is_matching_template (const SgTemplateArgument &X, const SgTemplateArgument &Y)
static bool is_matching_template_pack_expansion (const SgTemplateArgument &X, const SgTemplateArgument &Y)
static bool is_matching_kind (const SgTemplateArgument &X, const SgTemplateArgument &Y)
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgTemplateArgument * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgTemplateArgument *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgTemplateArgument *sgnode)
Static Public Member Functions inherited from SgSupport
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgSupport * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgSupport *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgSupport *sgnode)
Static Public Member Functions inherited from SgNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Protected Attributes
SgTemplateArgument::template_argument_enum p_argumentType
bool p_isArrayBoundUnknownType
Template arguments can be used as array bounds, if so this this marks the arguments use as such.
SgType * p_type
This is the template argument's reference to a type (if it is a type).
SgType * p_unparsable_type_alias
SgExpression * p_expression
This is the template argument's reference to an expression (if it is an expression).
SgDeclarationStatement * p_templateDeclaration
SgInitializedName * p_initializedName
bool p_explicitlySpecified
This true only if for a function template the argument is explicit in the source code (it need not always be.)
int p_name_qualification_length
bool p_type_elaboration_required
bool p_global_qualification_required
bool p_requiresGlobalNameQualificationOnType
int p_name_qualification_length_for_type
bool p_type_elaboration_required_for_type
bool p_global_qualification_required_for_type
SgTemplateArgument * p_previous_instance
SgTemplateArgument * p_next_instance
bool p_is_pack_element
Protected Attributes inherited from SgNode
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Additional Inherited Members
Protected Member Functions inherited from SgNode
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Static Protected Attributes inherited from SgNode
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Member Typedef Documentation
base_node_type
typedef SgSupport SgTemplateArgument::base_node_type
Definition at line 51771 of file Cxx_Grammar.h.
Member Enumeration Documentation
template_argument_enum
enum SgTemplateArgument::template_argument_enum
Different uses of a template argument
Enumerator
argument_undefined
undefined (error)
type_argument
type parameter
nontype_argument
nontype parameter
template_template_argument
template template parameter
start_of_pack_expansion_argument
start of pack expansion parameter
Definition at line 51268 of file Cxx_Grammar.h.
anonymous enum
anonymous enum
static variant value
Definition at line 51392 of file Cxx_Grammar.h.
Constructor & Destructor Documentation
~SgTemplateArgument()
SgTemplateArgument::~SgTemplateArgument () virtual
This is the destructor.
There is nothing to delete in this object.
Member Function Documentation
copy()
virtual SgNode * SgTemplateArgument::copy (SgCopyHelp & help) const override virtual
Reimplemented from SgSupport.
post_construction_initialization()
void SgTemplateArgument::post_construction_initialization () override virtual
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
Reimplemented from SgNode.
fixupCopy_scopes()
virtual void SgTemplateArgument::fixupCopy_scopes (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgNode.
fixupCopy_symbols()
virtual void SgTemplateArgument::fixupCopy_symbols (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgNode.
fixupCopy_references()
virtual void SgTemplateArgument::fixupCopy_references (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgNode.
class_name()
virtual std::string SgTemplateArgument::class_name () const override virtual
returns a string representing the class name
Reimplemented from SgSupport.
variantT()
virtual VariantT SgTemplateArgument::variantT () const override virtual
returns new style SageIII enum values
Reimplemented from SgSupport.
operator delete()
void SgTemplateArgument::operator delete (void * pointer) inline
Definition at line 51447 of file Cxx_Grammar.h.
get_traversalSuccessorContainer()
virtual std::vector< SgNode * > SgTemplateArgument::get_traversalSuccessorContainer () override virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
Reimplemented from SgSupport.
get_traversalSuccessorNamesContainer()
virtual std::vector< std::string > SgTemplateArgument::get_traversalSuccessorNamesContainer () override virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
Reimplemented from SgSupport.
get_numberOfTraversalSuccessors()
virtual size_t SgTemplateArgument::get_numberOfTraversalSuccessors () override virtual
return number of children in the traversal successor list
Reimplemented from SgSupport.
get_traversalSuccessorByIndex()
virtual SgNode * SgTemplateArgument::get_traversalSuccessorByIndex (size_t idx) override virtual
index-based access to traversal successors by index number
Reimplemented from SgSupport.
get_childIndex()
virtual size_t SgTemplateArgument::get_childIndex (SgNode * child) override virtual
index-based access to traversal successors by child node
Reimplemented from SgSupport.
roseRTI()
virtual RTIReturnType SgTemplateArgument::roseRTI () override virtual
return C++ Runtime-Time-Information
Reimplemented from SgSupport.
sage_class_name()
virtual const char * SgTemplateArgument::sage_class_name () const override virtual
returns a C style string (char*) representing the class name
Reimplemented from SgSupport.
accept()
virtual void SgTemplateArgument::accept (ROSE_VisitorPattern & visitor) override virtual
support for the classic visitor pattern done in GoF
Reimplemented from SgSupport.
isInMemoryPool()
virtual bool SgTemplateArgument::isInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgSupport.
checkDataMemberPointersIfInMemoryPool()
virtual void SgTemplateArgument::checkDataMemberPointersIfInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgSupport.
returnDataMemberPointers()
virtual std::vector< std::pair< SgNode *, std::string > > SgTemplateArgument::returnDataMemberPointers () const override virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented from SgSupport.
processDataMemberReferenceToPointers()
virtual void SgTemplateArgument::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented from SgSupport.
getChildIndex()
virtual long SgTemplateArgument::getChildIndex (SgNode * childNode) const override virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented from SgSupport.
addRegExpAttribute()
SgTemplateArgument * SgTemplateArgument::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
get_argumentType()
SgTemplateArgument::template_argument_enum SgTemplateArgument::get_argumentType () const
This function returns argumentType.
Returns
Returns SgTemplateArgument::template_argument_enum.
Referenced by SageBuilder::appendTemplateArgumentsToName(), SageInterface::get_name(), and SageInterface::templateArgumentEquivalence().
set_argumentType()
SgTemplateArgument::set_argumentType (SgTemplateArgument::template_argument_enum argumentType)
This function sets argumentType.
Returns
Returns void.
get_isArrayBoundUnknownType()
bool SgTemplateArgument::get_isArrayBoundUnknownType () const
This function returns isArrayBoundUnknownType.
Returns
Returns bool.
set_isArrayBoundUnknownType()
SgTemplateArgument::set_isArrayBoundUnknownType (bool isArrayBoundUnknownType)
This function sets isArrayBoundUnknownType.
Returns
Returns void.
get_type()
SgType * SgTemplateArgument::get_type () const
This function returns argumentType.
Returns
Returns SgType pointer.
Referenced by SageBuilder::appendTemplateArgumentsToName(), SageInterface::get_name(), and SageInterface::templateArgumentEquivalence().
get_expression()
SgExpression * SgTemplateArgument::get_expression () const
This function returns argumentExpression.
Returns
Returns SgExpression pointer.
Referenced by SageBuilder::appendTemplateArgumentsToName(), SageInterface::get_name(), and SageInterface::templateArgumentEquivalence().
get_explicitlySpecified()
bool SgTemplateArgument::get_explicitlySpecified () const
This function returns explicitlySpecified.
Returns
Returns bool.
set_explicitlySpecified()
SgTemplateArgument::set_explicitlySpecified (bool explicitlySpecified)
This function sets explicitlySpecified.
Returns
Returns void.
Member Data Documentation
p_argumentType
SgTemplateArgument::template_argument_enum SgTemplateArgument::p_argumentType protected
Definition at line 51837 of file Cxx_Grammar.h.
p_isArrayBoundUnknownType
SgTemplateArgument::p_isArrayBoundUnknownType protected
Template arguments can be used as array bounds, if so this this marks the arguments use as such.
Definition at line 51841 of file Cxx_Grammar.h.
p_type
SgTemplateArgument::p_type protected
This is the template argument's reference to a type (if it is a type).
This pointer is valid if the argumentType is "type_argument".
Definition at line 51845 of file Cxx_Grammar.h.
p_unparsable_type_alias
SgType* SgTemplateArgument::p_unparsable_type_alias protected
Definition at line 51849 of file Cxx_Grammar.h.
p_expression
SgTemplateArgument::p_expression protected
This is the template argument's reference to an expression (if it is an expression).
This pointer is valid if the argumentType is "nontype_argument".
Definition at line 51853 of file Cxx_Grammar.h.
p_templateDeclaration
SgDeclarationStatement* SgTemplateArgument::p_templateDeclaration protected
Definition at line 51857 of file Cxx_Grammar.h.
p_initializedName
SgInitializedName* SgTemplateArgument::p_initializedName protected
Definition at line 51861 of file Cxx_Grammar.h.
p_explicitlySpecified
SgTemplateArgument::p_explicitlySpecified protected
This true only if for a function template the argument is explicit in the source code (it need not always be.)
For template<typename T> void foo(T t); we could specify:
foo(1.0); or:
foo<float>(1.0); only in the second case is the template argument explicit. For all instantiated member function templates the value is false.
Definition at line 51865 of file Cxx_Grammar.h.
p_name_qualification_length
int SgTemplateArgument::p_name_qualification_length protected
Definition at line 51869 of file Cxx_Grammar.h.
p_type_elaboration_required
bool SgTemplateArgument::p_type_elaboration_required protected
Definition at line 51873 of file Cxx_Grammar.h.
p_global_qualification_required
bool SgTemplateArgument::p_global_qualification_required protected
Definition at line 51877 of file Cxx_Grammar.h.
p_requiresGlobalNameQualificationOnType
bool SgTemplateArgument::p_requiresGlobalNameQualificationOnType protected
Definition at line 51881 of file Cxx_Grammar.h.
p_name_qualification_length_for_type
int SgTemplateArgument::p_name_qualification_length_for_type protected
Definition at line 51885 of file Cxx_Grammar.h.
p_type_elaboration_required_for_type
bool SgTemplateArgument::p_type_elaboration_required_for_type protected
Definition at line 51889 of file Cxx_Grammar.h.
p_global_qualification_required_for_type
bool SgTemplateArgument::p_global_qualification_required_for_type protected
Definition at line 51893 of file Cxx_Grammar.h.
p_previous_instance
SgTemplateArgument* SgTemplateArgument::p_previous_instance protected
Definition at line 51897 of file Cxx_Grammar.h.
p_next_instance
SgTemplateArgument* SgTemplateArgument::p_next_instance protected
Definition at line 51901 of file Cxx_Grammar.h.
p_is_pack_element
bool SgTemplateArgument::p_is_pack_element protected
Definition at line 51905 of file Cxx_Grammar.h.
The documentation for this class was generated from the following files:
Cxx_Grammar.h
SgTemplateArgument.docs