ROSE: Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState Class Reference
Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState Class Reference
Description
Null register state.
This register state does not store any values. Read operations always return (new) undefined values.
Definition at line 155 of file NullSemantics.h.
#include <Rose/BinaryAnalysis/InstructionSemantics/NullSemantics.h>
Public Types
using Super = BaseSemantics::RegisterState
Base type.
using Ptr = RegisterStatePtr
Shared-ownership pointer.
Public Types inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState
using Ptr = RegisterStatePtr
Shared-ownership pointer.
Public Member Functions
virtual BaseSemantics::RegisterStatePtr create (const BaseSemantics::SValuePtr &protoval, const RegisterDictionaryPtr &regdict) const override
Virtual constructor.
virtual BaseSemantics::RegisterStatePtr clone () const override
Make a copy of this register state.
virtual bool merge (const BaseSemantics::RegisterStatePtr &, BaseSemantics::RiscOperators *) override
Merge register states for data flow analysis.
virtual void clear () override
Removes stored values from the register state.
virtual void zero () override
Set all registers to the zero.
virtual BaseSemantics::SValuePtr readRegister (RegisterDescriptor reg, const BaseSemantics::SValuePtr &, BaseSemantics::RiscOperators *) override
Read a value from a register.
virtual BaseSemantics::SValuePtr peekRegister (RegisterDescriptor reg, const BaseSemantics::SValuePtr &, BaseSemantics::RiscOperators *) override
Read a register without side effects.
virtual void writeRegister (RegisterDescriptor, const BaseSemantics::SValuePtr &, BaseSemantics::RiscOperators *) override
Write a value to a register.
virtual void updateReadProperties (RegisterDescriptor) override
Update register properties after reading a register.
virtual void updateWriteProperties (RegisterDescriptor, BaseSemantics::InputOutputProperty) override
Update register properties after writing to a register.
virtual void hash (Combinatorics::Hasher &, BaseSemantics::RiscOperators *) const override
Hash the register state.
virtual void print (std::ostream &, BaseSemantics::Formatter &) const override
Print the register contents.
Public Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState
SValuePtr protoval () const
Return the protoval.
MergerPtr merger () const
Property: Merger.
void merger (const MergerPtr &m)
Property: Merger.
RegisterDictionaryPtr registerDictionary () const
Property: Register dictionary.
void registerDictionary (const RegisterDictionaryPtr &)
Property: Register dictionary.
void print (std::ostream &stream, const std::string prefix="") const
Print the register contents.
WithFormatter with_format (Formatter &fmt)
Used for printing register states with formatting.
WithFormatter operator+ (Formatter &fmt)
Used for printing register states with formatting.
WithFormatter operator+ (const std::string &linePrefix)
Used for printing register states with formatting.
Static Public Member Functions
static RegisterStatePtr instance (const BaseSemantics::SValuePtr &protoval, const RegisterDictionaryPtr &regdict)
static RegisterStatePtr promote (const BaseSemantics::RegisterStatePtr &from)
Static Public Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState
static RegisterStatePtr promote (const RegisterStatePtr &)
Protected Member Functions
RegisterState (const RegisterState &other)
RegisterState (const BaseSemantics::SValuePtr &protoval, const RegisterDictionaryPtr &regdict)
Protected Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState
RegisterState (const SValuePtr &protoval, const RegisterDictionaryPtr &regdict)
Additional Inherited Members
Protected Attributes inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState
RegisterDictionaryPtr regdict
Registers that are able to be stored by this state.
Member Typedef Documentation
Super
using Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::Super = BaseSemantics::RegisterState
Base type.
Definition at line 158 of file NullSemantics.h.
Ptr
using Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::Ptr = RegisterStatePtr
Shared-ownership pointer.
Definition at line 161 of file NullSemantics.h.
Constructor & Destructor Documentation
RegisterState() [1/2]
Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::RegisterState (const RegisterState & other) inline protected
Definition at line 164 of file NullSemantics.h.
RegisterState() [2/2]
Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::RegisterState (const BaseSemantics::SValuePtr & protoval, const RegisterDictionaryPtr & regdict) inline protected
Definition at line 167 of file NullSemantics.h.
Member Function Documentation
instance()
static RegisterStatePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::instance (const BaseSemantics::SValuePtr & protoval, const RegisterDictionaryPtr & regdict) inline static
Definition at line 171 of file NullSemantics.h.
create()
virtual BaseSemantics::RegisterStatePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::create (const BaseSemantics::SValuePtr & protoval, const RegisterDictionaryPtr & regdict) const inline override virtual
Virtual constructor.
The protoval argument must be a non-null pointer to a semantic value which will be used only to create additional instances of the value via its virtual constructors. The prototypical value is normally of the same type for all parts of a semantic analysis. The register state must be compatible with the rest of the binary analysis objects in use.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 175 of file NullSemantics.h.
References Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState::protoval(), and Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState::regdict.
clone()
virtual BaseSemantics::RegisterStatePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::clone () const inline override virtual
Make a copy of this register state.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 180 of file NullSemantics.h.
promote()
static RegisterStatePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::promote (const BaseSemantics::RegisterStatePtr & from) inline static
Definition at line 184 of file NullSemantics.h.
merge()
virtual bool Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::merge (const BaseSemantics::RegisterStatePtr & other, BaseSemantics::RiscOperators * ops) inline override virtual
Merge register states for data flow analysis.
Merges the other state into this state, returning true if this state changed.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 190 of file NullSemantics.h.
clear()
virtual void Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::clear () inline override virtual
Removes stored values from the register state.
Depending on the register state implementation, this could either store new, distinct undefined values in each register, or it could simply erase all information about stored values leaving the register state truly empty. For instance RegisterStateGeneric, which uses variable length arrays to store information about a dynamically changing set of registers, clears its arrays to zero length.
Register states can also be initialized by clearing them or by explicitly writing new values into each desired register (or both). See BaseSemantics::RegisterStateGeneric::initialize_nonoverlapping for one way to initialize that register state.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 194 of file NullSemantics.h.
zero()
virtual void Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::zero () inline override virtual
Set all registers to the zero.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 195 of file NullSemantics.h.
readRegister()
virtual BaseSemantics::SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::readRegister (RegisterDescriptor reg, const BaseSemantics::SValuePtr & dflt, BaseSemantics::RiscOperators * ops) inline override virtual
Read a value from a register.
The register descriptor, reg, not only describes which register, but also which bits of that register (e.g., "al", "ah", "ax", "eax", and "rax" are all the same hardware register on an amd64, but refer to different parts of that register). The RISC operations are provided so that they can be used to extract the correct bits from a wider hardware register if necessary.
The dflt value is written into the register state if the register was not defined in the state. By doing this, a subsequent read of the same register will return the same value. Some register states cannot distinguish between a register that was never accessed and a register that was only read, in which case dflt is not used since all registers are already initialized.
See BaseSemantics::RiscOperators::readRegister for more details.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 198 of file NullSemantics.h.
References Rose::BinaryAnalysis::RegisterDescriptor::nBits(), and Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState::protoval().
peekRegister()
virtual BaseSemantics::SValuePtr Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::peekRegister (RegisterDescriptor reg, const BaseSemantics::SValuePtr & dflt, BaseSemantics::RiscOperators * ops) inline override virtual
Read a register without side effects.
This is similar to readRegister except it doesn't modify the register state in any way.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 203 of file NullSemantics.h.
References Rose::BinaryAnalysis::RegisterDescriptor::nBits(), and Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState::protoval().
writeRegister()
virtual void Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::writeRegister (RegisterDescriptor reg, const BaseSemantics::SValuePtr & value, BaseSemantics::RiscOperators * ops) inline override virtual
Write a value to a register.
The register descriptor, reg, not only describes which register, but also which bits of that register (e.g., "al", "ah", "ax", "eax", and "rax" are all the same hardware register on an amd64, but refer to different parts of that register). The RISC operations are provided so that they can be used to insert the value bits into a wider the hardware register if necessary. See BaseSemantics::RiscOperators::readRegister for more details.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 207 of file NullSemantics.h.
updateReadProperties()
virtual void Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::updateReadProperties (RegisterDescriptor) inline override virtual
Update register properties after reading a register.
This should be called by all implementations of BaseSemantics::RiscOperators::readRegister. Depending on the semantic domain, it usually adds the READ property to all bits of the register, and conditionally adds READ_BEFORE_WRITE and/or READ_UNINITIALIZED properties to parts of the register.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 209 of file NullSemantics.h.
updateWriteProperties()
virtual void Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::updateWriteProperties (RegisterDescriptor , BaseSemantics::InputOutputProperty) inline override virtual
Update register properties after writing to a register.
This should be called by all implementations of BaseSemantics::RiscOperators::writeRegister. Depending on the domain, it usually adds the WRITE or INIT property to the bits of the rgister.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 210 of file NullSemantics.h.
hash()
virtual void Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::hash (Combinatorics::Hasher & , BaseSemantics::RiscOperators *) const inline override virtual
Hash the register state.
Hashes the register state by appending its data to the specified hasher.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 212 of file NullSemantics.h.
print()
virtual void Rose::BinaryAnalysis::InstructionSemantics::NullSemantics::RegisterState::print (std::ostream & , BaseSemantics::Formatter &) const inline override virtual
Print the register contents.
This emits one line per register and contains the register name and its value.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RegisterState.
Definition at line 214 of file NullSemantics.h.
The documentation for this class was generated from the following file:
NullSemantics.h