ROSE: Sawyer::CommandLine::NonNegativeIntegerParser< T > Class Template Reference
Sawyer::CommandLine::NonNegativeIntegerParser< T > Class Template Reference
Description
template<typename T>
class Sawyer::CommandLine::NonNegativeIntegerParser< T >
Parses a non-negative integer and converts it to numeric type T.
Matches a non-negative integer in the mathematical sense in C++ decimal, octal, or hexadecimal format, and attempts to convert it to the type T. If the integer cannot be converted to type T then an std::range_error is thrown, which is most likely caught by higher layers of the library and converted to an std::runtime_error with additional information about the failure. The syntax is that which is recognized by the strtoull function except that a leading minus sign is not allowed (yes, strtoull parses negative numbers and returns them as unsigned), plus trailing white space.
See also
nonNegativeIntegerParser factory, and Command line parser factories.
Definition at line 1031 of file Sawyer/CommandLine.h.
#include <Sawyer/CommandLine.h>
Public Types
typedef SharedPointer< NonNegativeIntegerParser > Ptr
Reference counting pointer for this class.
Public Types inherited from Sawyer::CommandLine::ValueParser
typedef SharedPointer< ValueParser > Ptr
Reference counting pointer for this class.
Static Public Member Functions
static Ptr instance ()
Allocating constructor.
static Ptr instance (const ValueSaver::Ptr &valueSaver)
Allocating constructor.
Protected Member Functions
NonNegativeIntegerParser ()
Constructor for derived classes.
NonNegativeIntegerParser (const ValueSaver::Ptr &valueSaver)
Constructor for derived classes.
Protected Member Functions inherited from Sawyer::CommandLine::ValueParser
ValueParser ()
Constructor for derived classes.
ValueParser (const ValueSaver::Ptr &valueSaver)
Constructor for derived classes.
Additional Inherited Members
Public Member Functions inherited from Sawyer::CommandLine::ValueParser
ParsedValue matchString (const std::string &)
Parse the entire string and return a value.
ParsedValue match (Cursor &)
Parse a value from the beginning of the specified string.
Ptr valueSaver (const ValueSaver::Ptr &f)
Property: functor responsible for saving a parsed value in user storage.
const ValueSaver::Ptr valueSaver () const
Property: functor responsible for saving a parsed value in user storage.
Public Member Functions inherited from Sawyer::SharedObject
SharedObject ()
Default constructor.
SharedObject (const SharedObject &)
Copy constructor.
virtual ~SharedObject ()
Virtual destructor.
SharedObject & operator= (const SharedObject &)
Assignment.
Public Member Functions inherited from Sawyer::SharedFromThis< ValueParser >
SharedPointer< ValueParser > sharedFromThis ()
Create a shared pointer from this.
SharedPointer< const ValueParser > sharedFromThis () const
Create a shared pointer from this.
Member Typedef Documentation
Ptr
template<typename T > typedef SharedPointer<NonNegativeIntegerParser> Sawyer::CommandLine::NonNegativeIntegerParser< T >::Ptr
Reference counting pointer for this class.
Definition at line 1040 of file Sawyer/CommandLine.h.
Constructor & Destructor Documentation
NonNegativeIntegerParser() [1/2]
template<typename T > Sawyer::CommandLine::NonNegativeIntegerParser< T >::NonNegativeIntegerParser () inline protected
Constructor for derived classes.
Non-subclass users should use instance instead.
Definition at line 1034 of file Sawyer/CommandLine.h.
Referenced by Sawyer::CommandLine::NonNegativeIntegerParser< T >::instance().
NonNegativeIntegerParser() [2/2]
template<typename T > Sawyer::CommandLine::NonNegativeIntegerParser< T >::NonNegativeIntegerParser (const ValueSaver::Ptr & valueSaver) inline protected
Constructor for derived classes.
Non-subclass users should use instance instead.
Definition at line 1037 of file Sawyer/CommandLine.h.
Member Function Documentation
instance() [1/2]
template<typename T > static Ptr Sawyer::CommandLine::NonNegativeIntegerParser< T >::instance () inline static
Allocating constructor.
Returns a pointer to a new NonNegativeIntegerParser object. Uses will most likely want to use the nonNegativeIntegerParser factory instead, which requires less typing.
See also
Command line parser factories
Definition at line 1045 of file Sawyer/CommandLine.h.
Referenced by Sawyer::CommandLine::nonNegativeIntegerParser(), and Sawyer::CommandLine::nonNegativeIntegerParser().
instance() [2/2]
template<typename T > static Ptr Sawyer::CommandLine::NonNegativeIntegerParser< T >::instance (const ValueSaver::Ptr & valueSaver) inline static
Allocating constructor.
Returns a pointer to a new NonNegativeIntegerParser object. Uses will most likely want to use the nonNegativeIntegerParser factory instead, which takes the same arguments, but requires less typing.
See also
Command line parser factories
Definition at line 1050 of file Sawyer/CommandLine.h.
References Sawyer::CommandLine::NonNegativeIntegerParser< T >::NonNegativeIntegerParser(), and Sawyer::CommandLine::ValueParser::valueSaver().
The documentation for this class was generated from the following file:
Sawyer/CommandLine.h