ROSE: SgType Class Reference
SgType Class Reference
Description
This class represents the base class for all types.
There are no uses of this IR node anywhere. All SgType based IR nodes are derived from this SgType class.
Discussion of get_base_type() and findBaseType():
fileBaseType() will recursively strip away all typedefs, reference, pointers, arrays, and modifiers
get_base_type() is a member function on some IR nodes derived from SgType and returns the non-recursively striped (immediate) type under the typedefs, reference, pointers, arrays, modifiers, etc.
Note that the typedefs for which the current SgType is the base type are stored in a list. There is a special IR node (SgTypedefSeq) to maintain this list (which is internally an STL list). We could also store pointers to other SgType IR nodes where pointers and references have been taken to the current IR node, but currently only typedefs are stored explicitly. As a result of storing the typedefs, the builtin types store the list for most SgType IR nodes (since ther is only a single SgType IR node for most SgType derived classes). We could imagine storing the SgTypedefSeq as static data members of the derived SgType classes, but this would not work since then all SgNamedType IR nodes would share the same list of typedefs. So this is the correct location for this list.
Definition at line 85326 of file Cxx_Grammar.h.
Public Types
enum fortran_attribute_specifiers_enum {
e_unknown_attribute_specifier = 0 ,
e_public_access ,
e_private_access ,
e_allocatable ,
e_asynchronous ,
e_bind ,
e_data ,
e_dimension ,
e_intent ,
e_optional ,
e_parameter ,
e_pointer ,
e_protected ,
e_save ,
e_target ,
e_value ,
e_volatile ,
e_last_attribute_specifier
}
enum { static_variant = V_SgType }
static variant value
typedef SgNode base_node_type
Public Types inherited from SgNode
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
virtual SgNode * copy (SgCopyHelp &help) const override
SgType ()
This is the constructor.
SgType (const SgType &X)
copy constructor
virtual SgName get_mangled (void) const
virtual SgExpression * get_type_kind () const
virtual void set_type_kind (SgExpression *type_kind)
bool isUnsignedType () const
Compute numerical properties of type.
bool isIntegerType () const
There are many sorts of integer types (this queries an arbitrary type).
bool isFloatType () const
There are several sorts of float types (this queries an arbitrary type).
bool isPrimativeType () const
There are many sorts of primative types (this queries an arbitrary type).
bool hasExplicitType ()
Some types store internal SgType pointers explicitly while others compute them from other data. This function is true if it has a data member that is a type (pointer, array, etc.).
bool containsInternalTypes ()
Some types can hide other type IR nodes internally. This function is true if it can hide another type (pointer, array, etc.).
std::vector< SgType * > getInternalTypes () const
Generate a container of types hidden in the input type.
void reset_base_type (SgType *baseType)
Reset the base type. This function resets the base type. It is an error to call it for types where containsInternalTypes() == false.
SgType * findBaseType () const
Return the base type of the associated type. The base type is important when dealing with pointers, arrays, etc.
SgType * dereference ()
Returns type hidden behind pointer of reference.
const SgType * dereference () const
Returns type hidden behind pointer of reference.
SgType * stripType (unsigned char bit_array=STRIP_MODIFIER_TYPE|STRIP_REFERENCE_TYPE|STRIP_RVALUE_REFERENCE_TYPE|STRIP_POINTER_TYPE|STRIP_ARRAY_TYPE|STRIP_TYPEDEF_TYPE|STRIP_POINTER_MEMBER_TYPE) const
Returns hidden type beneath layers of typedefs, pointers, references, modifiers, array representation, etc.
SgType * stripTypedefsAndModifiers () const
This only strips away typedefs and modifiers (specialized usage).
SgDeclarationStatement * getAssociatedDeclaration () const
bool isEquivalentType (const SgType *other_type) const
Type equivalence is the concept of equality between types independent of access permissions (e.g. private or protected types in a class).
virtual void addNewAttribute (std::string s, AstAttribute *a) override
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const override
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a) override
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a) override
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s) override
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const override
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const override
Returns the number of attributes on this IR node.
virtual std::string class_name () const override
returns a string representing the class name
virtual VariantT variantT () const override
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer () override
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer () override
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors () override
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx) override
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child) override
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI () override
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const override
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor) override
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const override
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const override
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgType (const SgTypeStorageClass &source)
IR node constructor to support AST File I/O.
SgType * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
bool get_isCoArray () const
void set_isCoArray (bool isCoArray)
int get_substitutedForTemplateParam () const
void set_substitutedForTemplateParam (int substitutedForTemplateParam)
SgReferenceType * get_ref_to () const
void set_ref_to (SgReferenceType *ref_to)
SgPointerType * get_ptr_to () const
void set_ptr_to (SgPointerType *ptr_to)
SgModifierNodes * get_modifiers () const
void set_modifiers (SgModifierNodes *modifiers)
SgTypedefSeq * get_typedefs () const
void set_typedefs (SgTypedefSeq *typedefs)
SgRvalueReferenceType * get_rvalue_ref_to () const
void set_rvalue_ref_to (SgRvalueReferenceType *rvalue_ref_to)
SgDeclType * get_decltype_ref_to () const
void set_decltype_ref_to (SgDeclType *decltype_ref_to)
SgTypeOfType * get_typeof_ref_to () const
void set_typeof_ref_to (SgTypeOfType *typeof_ref_to)
bool get_hasTypeKindStar () const
void set_hasTypeKindStar (bool hasTypeKindStar)
AstAttributeMechanism * get_attributeMechanism () const override
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
void set_attributeMechanism (AstAttributeMechanism *attributeMechanism) override
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
virtual ~SgType ()
This is the destructor.
Public Member Functions inherited from SgNode
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const
virtual Sg_File_Info * get_file_info (void) const
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
virtual Sg_File_Info * get_startOfConstruct (void) const
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
virtual Sg_File_Info * get_endOfConstruct (void) const
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
virtual unsigned int cfgIndexForEnd () const
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n)
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n)
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index=false)
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index=false)
Find the in edges of a CFG node – internal version.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const
virtual Sg_File_Info * get_file_info (void) const
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
virtual Sg_File_Info * get_startOfConstruct (void) const
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
virtual Sg_File_Info * get_endOfConstruct (void) const
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
virtual unsigned int cfgIndexForEnd () const
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n)
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n)
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index=false)
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index=false)
Find the in edges of a CFG node – internal version.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
Static Public Member Functions
static SgType * arithmetic_conversions (SgType *, SgType *)
performs simple conversions
static SgType * integer_promotion (SgType *, SgType *)
handles promotion to integer
static SgType * float_promotion (SgType *, SgType *)
handles promotion to float
static bool handledUsingLocalTable (SgType *t)
static SgScopeStatement * getCurrentScope ()
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgType * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgType *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgType *sgnode)
Static Public Member Functions inherited from SgNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Static Public Attributes
static const unsigned char STRIP_MODIFIER_TYPE = ((unsigned char) 1 << 0)
static const unsigned char STRIP_REFERENCE_TYPE = ((unsigned char) 1 << 1)
static const unsigned char STRIP_RVALUE_REFERENCE_TYPE = ((unsigned char) 1 << 2)
static const unsigned char STRIP_POINTER_TYPE = ((unsigned char) 1 << 3)
static const unsigned char STRIP_ARRAY_TYPE = ((unsigned char) 1 << 4)
static const unsigned char STRIP_TYPEDEF_TYPE = ((unsigned char) 1 << 5)
static const unsigned char STRIP_POINTER_MEMBER_TYPE = ((unsigned char) 1 << 6)
Protected Member Functions
SgName mangledNameSupport (SgName &fname, SgUnparse_Info &info)
Protected Member Functions inherited from SgNode
virtual void post_construction_initialization ()
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void post_construction_initialization ()
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Protected Attributes
bool p_isCoArray
int p_substitutedForTemplateParam
This boolean variable marks if the current type was originally a template parameter.
SgReferenceType * p_ref_to
This holds the pointer to a SgReferenceType if this type is a reference to another type.
SgPointerType * p_ptr_to
This holds the pointer to a SgPointerType if this type is a pointer to another type.
SgModifierNodes * p_modifiers
This points to any SgModifierNodes if this type contains type modifiers.
SgTypedefSeq * p_typedefs
This points to IR node which holds a list of typedefs where the base_type if this SgType.
SgRvalueReferenceType * p_rvalue_ref_to
SgDeclType * p_decltype_ref_to
SgTypeOfType * p_typeof_ref_to
SgExpression * p_type_kind
bool p_hasTypeKindStar
AstAttributeMechanism * p_attributeMechanism
Protected Attributes inherited from SgNode
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Additional Inherited Members
Static Protected Attributes inherited from SgNode
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Member Typedef Documentation
base_node_type
typedef SgNode SgType::base_node_type
Definition at line 85997 of file Cxx_Grammar.h.
Member Enumeration Documentation
fortran_attribute_specifiers_enum
enum SgType::fortran_attribute_specifiers_enum
Definition at line 85467 of file Cxx_Grammar.h.
anonymous enum
anonymous enum
static variant value
Definition at line 85618 of file Cxx_Grammar.h.
Constructor & Destructor Documentation
SgType() [1/2]
SgType::SgType ()
This is the constructor.
This constructor builds the SgType base class.
See also
Example:create an SgType object
SgType() [2/2]
SgType::SgType (const SgType & X)
copy constructor
The Copy constructor is provide to support the AST copy mechanism, where types are copied to support copying of named types.
~SgType()
SgType::~SgType () virtual
This is the destructor.
There is nothing to delete in this object.
Member Function Documentation
copy()
virtual SgNode * SgType::copy (SgCopyHelp & help) const override virtual
Reimplemented from SgNode.
get_mangled()
virtual SgName SgType::get_mangled (void) const virtual
Returns a mangled string representation of this type. Equivalent types have the same mangled string.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
isUnsignedType()
bool SgType::isUnsignedType () const
Compute numerical properties of type.
name Numerical Modifiers
These define numeric properties of the type (e.g. int, float, etc.) There are many sorts of unsigned types (this queries an arbitrary type).
hasExplicitType()
bool SgType::hasExplicitType ()
Some types store internal SgType pointers explicitly while others compute them from other data. This function is true if it has a data member that is a type (pointer, array, etc.).
Result is true if it stores a type explicitly as a data member, else false.
containsInternalTypes()
bool SgType::containsInternalTypes ()
Some types can hide other type IR nodes internally. This function is true if it can hide another type (pointer, array, etc.).
Result is true if it can hide a one or more types, else false.
getInternalTypes()
std::vector< SgType * > SgType::getInternalTypes () const
Generate a container of types hidden in the input type.
Returns a vector of types hidden in the input type (pointer, array, etc.).
Referenced by SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageBuilder::getTargetFileType(), and SageInterface::isEquivalentType().
mangledNameSupport()
SgName SgType::mangledNameSupport (SgName & fname, SgUnparse_Info & info) protected
addNewAttribute()
virtual void SgType::addNewAttribute (std::string s, AstAttribute * a) override virtual
Add a new attribute represented by the named string.
Reimplemented from SgNode.
getAttribute()
virtual AstAttribute * SgType::getAttribute (std::string s) const override virtual
Returns attribute of name 's'.
Reimplemented from SgNode.
updateAttribute()
virtual void SgType::updateAttribute (std::string s, AstAttribute * a) override virtual
Replace existing attribute of name 's' with new AstAttribute.
Reimplemented from SgNode.
setAttribute()
virtual void SgType::setAttribute (std::string s, AstAttribute * a) override virtual
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
Reimplemented from SgNode.
removeAttribute()
virtual void SgType::removeAttribute (std::string s) override virtual
Remove attribute of name 's' if present.
Reimplemented from SgNode.
attributeExists()
virtual bool SgType::attributeExists (std::string s) const override virtual
Tests if attribute of name 's' is present.
Reimplemented from SgNode.
numberOfAttributes()
virtual int SgType::numberOfAttributes () const override virtual
Returns the number of attributes on this IR node.
Reimplemented from SgNode.
class_name()
virtual std::string SgType::class_name () const override virtual
returns a string representing the class name
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
Referenced by SageBuilder::appendTemplateArgumentsToName(), SageBuilder::buildConstVolatileType(), SageBuilder::buildFortranKindType(), SageBuilder::buildRestrictType(), SageBuilder::buildTemplateInstantiationTypedefDeclaration_nfi(), SageBuilder::buildTypeOfType(), SageBuilder::buildUpcBlockIndefiniteType(), SageBuilder::buildUpcBlockNumberType(), SageBuilder::buildUpcBlockStarType(), SageBuilder::buildUpcRelaxedType(), SageBuilder::buildUpcSharedType(), SageBuilder::buildUpcStrictType(), SageBuilder::buildVolatileType(), SageInterface::detectCycleInType(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::get_name(), SageInterface::getClassTypeChainForMemberReference(), SageBuilder::getTargetFileType(), SageBuilder::getTargetFileTypeSupport(), SageInterface::isEquivalentType(), SageInterface::templateArgumentEquivalence(), and CollectDependentDeclarationsTraversal::visit().
variantT()
virtual VariantT SgType::variantT () const override virtual
returns new style SageIII enum values
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
Referenced by SageInterface::get_name(), and SageInterface::isEquivalentType().
operator delete()
void SgType::operator delete (void * pointer) inline
Definition at line 85673 of file Cxx_Grammar.h.
get_traversalSuccessorContainer()
virtual std::vector< SgNode * > SgType::get_traversalSuccessorContainer () override virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
get_traversalSuccessorNamesContainer()
virtual std::vector< std::string > SgType::get_traversalSuccessorNamesContainer () override virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
get_numberOfTraversalSuccessors()
virtual size_t SgType::get_numberOfTraversalSuccessors () override virtual
return number of children in the traversal successor list
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
get_traversalSuccessorByIndex()
virtual SgNode * SgType::get_traversalSuccessorByIndex (size_t idx) override virtual
index-based access to traversal successors by index number
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
get_childIndex()
virtual size_t SgType::get_childIndex (SgNode * child) override virtual
index-based access to traversal successors by child node
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
roseRTI()
virtual RTIReturnType SgType::roseRTI () override virtual
return C++ Runtime-Time-Information
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
sage_class_name()
virtual const char * SgType::sage_class_name () const override virtual
returns a C style string (char*) representing the class name
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
accept()
virtual void SgType::accept (ROSE_VisitorPattern & visitor) override virtual
support for the classic visitor pattern done in GoF
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
isInMemoryPool()
virtual bool SgType::isInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
checkDataMemberPointersIfInMemoryPool()
virtual void SgType::checkDataMemberPointersIfInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
returnDataMemberPointers()
virtual std::vector< std::pair< SgNode *, std::string > > SgType::returnDataMemberPointers () const override virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
processDataMemberReferenceToPointers()
virtual void SgType::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
getChildIndex()
virtual long SgType::getChildIndex (SgNode * childNode) const override virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented from SgNode.
Reimplemented in SgTypeUnknown, SgTypeChar, SgTypeSignedChar, SgTypeUnsignedChar, SgTypeShort, SgTypeSignedShort, SgTypeUnsignedShort, SgTypeInt, SgTypeSignedInt, SgTypeUnsignedInt, SgTypeLong, SgTypeSignedLong, SgTypeUnsignedLong, SgTypeVoid, SgTypeGlobalVoid, SgTypeWchar, SgTypeFloat, SgTypeDouble, SgTypeLongLong, SgTypeSignedLongLong, SgTypeUnsignedLongLong, SgTypeSigned128bitInteger, SgTypeUnsigned128bitInteger, SgTypeFloat80, SgTypeLongDouble, SgTypeString, SgTypeBool, SgPointerType, SgPointerMemberType, SgReferenceType, SgNamedType, SgClassType, SgJavaParameterType, SgJovialTableType, SgEnumType, SgTypedefType, SgNonrealType, SgJavaParameterizedType, SgJavaQualifiedType, SgJavaWildcardType, SgAdaTaskType, SgAdaProtectedType, SgAdaFormalType, SgAdaDiscriminatedType, SgModifierType, SgFunctionType, SgMemberFunctionType, SgPartialFunctionType, SgPartialFunctionModifierType, SgArrayType, SgTypeEllipse, SgTemplateType, SgQualifiedNameType, SgTypeComplex, SgTypeImaginary, SgTypeDefault, SgTypeCAFTeam, SgTypeCrayPointer, SgTypeLabel, SgJavaUnionType, SgRvalueReferenceType, SgTypeNullptr, SgDeclType, SgTypeOfType, SgTypeMatrix, SgTypeTuple, SgTypeChar16, SgTypeChar32, SgTypeFloat128, SgTypeFixed, SgAutoType, SgAdaAccessType, SgAdaSubtype, SgAdaDiscreteType, SgAdaModularType, SgAdaDerivedType, SgAdaSubroutineType, SgJovialBitType, and SgRangeType.
addRegExpAttribute()
SgType * SgType::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
get_attributeMechanism()
AstAttributeMechanism * SgType::get_attributeMechanism () const override virtual
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
This is an access function used for getting the interally held pointer to a valid AstAttributeMechanism. It provides access to lower level functionality of the AstAttributeMechanism, put is mostly of use to internal tools.
Reimplemented from SgNode.
set_attributeMechanism()
void SgType::set_attributeMechanism (AstAttributeMechanism * a) override virtual
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
This is an access function used for setting the interally held pointer to a valid AstAttributeMechanism.
Reimplemented from SgNode.
Member Data Documentation
STRIP_MODIFIER_TYPE
const unsigned char SgType::STRIP_MODIFIER_TYPE = ((unsigned char) 1 << 0) static
Definition at line 85404 of file Cxx_Grammar.h.
STRIP_REFERENCE_TYPE
const unsigned char SgType::STRIP_REFERENCE_TYPE = ((unsigned char) 1 << 1) static
Definition at line 85405 of file Cxx_Grammar.h.
STRIP_RVALUE_REFERENCE_TYPE
const unsigned char SgType::STRIP_RVALUE_REFERENCE_TYPE = ((unsigned char) 1 << 2) static
Definition at line 85406 of file Cxx_Grammar.h.
STRIP_POINTER_TYPE
const unsigned char SgType::STRIP_POINTER_TYPE = ((unsigned char) 1 << 3) static
Definition at line 85407 of file Cxx_Grammar.h.
STRIP_ARRAY_TYPE
const unsigned char SgType::STRIP_ARRAY_TYPE = ((unsigned char) 1 << 4) static
Definition at line 85408 of file Cxx_Grammar.h.
STRIP_TYPEDEF_TYPE
const unsigned char SgType::STRIP_TYPEDEF_TYPE = ((unsigned char) 1 << 5) static
Definition at line 85409 of file Cxx_Grammar.h.
STRIP_POINTER_MEMBER_TYPE
const unsigned char SgType::STRIP_POINTER_MEMBER_TYPE = ((unsigned char) 1 << 6) static
Definition at line 85415 of file Cxx_Grammar.h.
p_isCoArray
bool SgType::p_isCoArray protected
Definition at line 86053 of file Cxx_Grammar.h.
p_substitutedForTemplateParam
int SgType::p_substitutedForTemplateParam protected
This boolean variable marks if the current type was originally a template parameter.
Definition at line 86057 of file Cxx_Grammar.h.
p_ref_to
SgReferenceType SgType::p_ref_to protected
This holds the pointer to a SgReferenceType if this type is a reference to another type.
Definition at line 86061 of file Cxx_Grammar.h.
p_ptr_to
SgPointerType SgType::p_ptr_to protected
This holds the pointer to a SgPointerType if this type is a pointer to another type.
Definition at line 86065 of file Cxx_Grammar.h.
p_modifiers
SgReferenceType SgType::p_modifiers protected
This points to any SgModifierNodes if this type contains type modifiers.
Definition at line 86069 of file Cxx_Grammar.h.
p_typedefs
SgTypedefSeq SgType::p_typedefs protected
This points to IR node which holds a list of typedefs where the base_type if this SgType.
See also
SgTypedefSeq
Definition at line 86073 of file Cxx_Grammar.h.
p_rvalue_ref_to
SgRvalueReferenceType* SgType::p_rvalue_ref_to protected
Definition at line 86077 of file Cxx_Grammar.h.
p_decltype_ref_to
SgDeclType* SgType::p_decltype_ref_to protected
Definition at line 86081 of file Cxx_Grammar.h.
p_typeof_ref_to
SgTypeOfType* SgType::p_typeof_ref_to protected
Definition at line 86085 of file Cxx_Grammar.h.
p_type_kind
SgExpression* SgType::p_type_kind protected
Definition at line 86089 of file Cxx_Grammar.h.
p_hasTypeKindStar
bool SgType::p_hasTypeKindStar protected
Definition at line 86093 of file Cxx_Grammar.h.
p_attributeMechanism
AstAttributeMechanism* SgType::p_attributeMechanism protected
Definition at line 86097 of file Cxx_Grammar.h.
The documentation for this class was generated from the following files:
Cxx_Grammar.h
SgType.docs