ROSE: SgAsmBlock Class Reference
SgAsmBlock Class Reference
Description
Instruction basic block.
A SgAsmBlock usually represents a sequence of instructions. It's also used for grouping other things such as functions. A SgAsmBlock represents a basic block if and only if it has at least one descendant of type SgAsmInstruction and it has no descendants of type SgAsmBlock.
In the absence of interrupt handling, the instructions of a basic block are executed entirely. In the absense of multi-threading, no other instructions intervene.
The instructions of a basic block need not be contiguous in virtual memory. They also do not need to be at increasing virtual addresses.
If the basic block has a parent pointer, then the closest SgAsmFunction ancestor is the one to which this basic block belongs. In the Partitioner API, a basic block can be owned by more than one function.
An AST may have multiple SgAsmBlock objects that represent the same basic block. This happens when a single block belongs to more than one function.
See also, Rose::BinaryAnalysis::Partitioner2::BasicBlock, which represents a basic block outside the AST.
Definition at line 40507 of file binaryInstruction.C.
Public Types
enum Reason {
BLK_NONE = 0x00000000 ,
BLK_ENTRY_POINT = 0x00010000 ,
BLK_PADDING = 0x00020000 ,
BLK_FRAGMENT = 0x00080000 ,
BLK_CFGHEAD = 0x00100000 ,
BLK_USERDEF = 0x00200000 ,
BLK_LEFTOVERS = 0x00400000 ,
BLK_JUMPTABLE = 0x00800000 ,
BLK_GRAPH1 = 0x01000000 ,
BLK_GRAPH2 = 0x02000000 ,
BLK_GRAPH3 = 0x04000000 ,
BLK_DEFAULT = BLK_NONE ,
BLK_MISCMASK = 0x000000ff ,
BLK_FINDDATA = 0x00000001 ,
BLK_POSTFUNC = 0x00000002
}
Reasons why a basic block might have been assigned to a function.
Public Types inherited from SgNode
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
void appendStatement (SgAsmStatement *)
Add the specified statement to the end of the statement list.
void removeStatement (SgAsmStatement *)
Erase the specified statement.
void removeChildren ()
Removes all statements from the block.
rose_addr_t get_fallthroughVa ()
Fall-through virtual address.
SgAsmFunction * get_enclosingFunction () const
Returns the function that owns this block.
bool hasInstructions () const
Determins if a block contains instructions.
bool isBasicBlock () const
Determine if a block contains instructions.
bool isFunctionCall (rose_addr_t &target_va, rose_addr_t &return_va)
Returns true if basic block appears to be a function call.
std::string reasonString (bool pad) const
Returns reason string for this block.
bool get_successors_complete () const
void set_successors_complete (bool)
SgAsmBlock * get_immediate_dominator () const
void set_immediate_dominator (SgAsmBlock *)
size_t get_cached_vertex () const
void set_cached_vertex (size_t)
double get_code_likelihood () const
void set_code_likelihood (double)
void append_statement (SgAsmStatement *)
void remove_statement (SgAsmStatement *)
void remove_children ()
rose_addr_t get_fallthrough_va ()
SgAsmFunction * get_enclosing_function () const
bool has_instructions () const
bool is_basic_block () const
bool is_function_call (rose_addr_t &, rose_addr_t &)
std::string reason_str (bool) const
virtual ~SgAsmBlock ()
Destructor.
SgAsmBlock ()
Default constructor.
SgAsmBlock (rose_addr_t const &address)
Constructor.
rose_addr_t const & get_id () const
Property: Identification.
void set_id (rose_addr_t const &)
Property: Identification.
unsigned const & get_reason () const
Property: Reasons this block was created.
void set_reason (unsigned const &)
Property: Reasons this block was created.
SgAsmStatementPtrList const & get_statementList () const
Property: Statements of which this block is composed.
SgAsmStatementPtrList & get_statementList ()
Property: Statements of which this block is composed.
void set_statementList (SgAsmStatementPtrList const &)
Property: Statements of which this block is composed.
SgAsmIntegerValuePtrList const & get_successors () const
Property: Control flow successors.
SgAsmIntegerValuePtrList & get_successors ()
Property: Control flow successors.
void set_successors (SgAsmIntegerValuePtrList const &)
Property: Control flow successors.
bool const & get_successorsComplete () const
Property: Whether the successors list is complete.
void set_successorsComplete (bool const &)
Property: Whether the successors list is complete.
SgAsmBlock *const & get_immediateDominator () const
Property: Holds the immediate dominator block in the control flow graph.
void set_immediateDominator (SgAsmBlock *const &)
Property: Holds the immediate dominator block in the control flow graph.
size_t const & get_cachedVertex () const
Property: Cached vertex for control flow graphs.
void set_cachedVertex (size_t const &)
Property: Cached vertex for control flow graphs.
double const & get_codeLikelihood () const
Property: Likelihood that this block represents real instructions.
void set_codeLikelihood (double const &)
Property: Likelihood that this block represents real instructions.
int64_t const & get_stackDeltaOut () const
Property: Stack pointer at block exit w.r.t.
void set_stackDeltaOut (int64_t const &)
Property: Stack pointer at block exit w.r.t.
Public Member Functions inherited from SgAsmStatement
virtual ~SgAsmStatement ()
Destructor.
rose_addr_t const & get_address () const
Property: Starting virtual address.
void set_address (rose_addr_t const &)
Property: Starting virtual address.
std::string const & get_comment () const
Property: Commentary.
void set_comment (std::string const &)
Property: Commentary.
Public Member Functions inherited from SgAsmNode
virtual ~SgAsmNode ()
Destructor.
Sawyer::Attribute::Storage const & attributes () const
Attribute storage.
Sawyer::Attribute::Storage & attributes ()
Attribute storage.
Public Member Functions inherited from SgNode
virtual SgNode * copy (SgCopyHelp &help) const
virtual std::string class_name () const
returns a string representing the class name
virtual VariantT variantT () const
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual size_t get_numberOfTraversalSuccessors ()
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx)
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child)
index-based access to traversal successors by child node
virtual const char * sage_class_name () const
generates string representing the class name: (e.g. for SgNode returns "SgNode").
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor)
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool ()
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool ()
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *)
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
virtual void addNewAttribute (std::string s, AstAttribute *a)
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a)
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a)
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s)
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const
Returns the number of attributes on this IR node.
virtual AstAttributeMechanism * get_attributeMechanism () const
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
virtual void set_attributeMechanism (AstAttributeMechanism *a)
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const
virtual Sg_File_Info * get_file_info (void) const
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
virtual Sg_File_Info * get_startOfConstruct (void) const
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
virtual Sg_File_Info * get_endOfConstruct (void) const
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
virtual unsigned int cfgIndexForEnd () const
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n)
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n)
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index=false)
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index=false)
Find the in edges of a CFG node – internal version.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
virtual SgNode * copy (SgCopyHelp &help) const
virtual std::string class_name () const
returns a string representing the class name
virtual VariantT variantT () const
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer ()
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer ()
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors ()
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx)
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child)
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI ()
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor)
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool ()
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool ()
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *)
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
virtual void addNewAttribute (std::string s, AstAttribute *a)
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a)
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a)
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s)
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const
Returns the number of attributes on this IR node.
virtual AstAttributeMechanism * get_attributeMechanism () const
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
virtual void set_attributeMechanism (AstAttributeMechanism *a)
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const
virtual Sg_File_Info * get_file_info (void) const
File information containing filename, line number, column number, and if the SgNode is a part of a new transformation, etc.
virtual Sg_File_Info * get_startOfConstruct (void) const
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
virtual Sg_File_Info * get_endOfConstruct (void) const
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
virtual unsigned int cfgIndexForEnd () const
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n)
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n)
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index=false)
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index=false)
Find the in edges of a CFG node – internal version.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer ()
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer ()
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual RTIReturnType roseRTI ()
return C++ Runtime-Time-Information
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
Static Public Member Functions
static std::string reasonKey (const std::string &prefix="")
Multi-line string describing the letters used for basic block reasons.
static std::string reasonString (bool pad, unsigned reason)
Converts a reason bit vector to a human-friendly string.
static std::string reason_key (const std::string &="")
static std::string reason_str (bool, unsigned)
Static Public Member Functions inherited from SgNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Protected Member Functions
void initializeProperties ()
Initialize all properties that have explicit initial values.
Protected Member Functions inherited from SgAsmStatement
SgAsmStatement ()
Default constructor.
SgAsmStatement (rose_addr_t const &address)
Constructor.
void initializeProperties ()
Initialize all properties that have explicit initial values.
Protected Member Functions inherited from SgAsmNode
SgAsmNode ()
Default constructor.
void initializeProperties ()
Initialize all properties that have explicit initial values.
Protected Member Functions inherited from SgNode
virtual void post_construction_initialization ()
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void post_construction_initialization ()
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Additional Inherited Members
Protected Attributes inherited from SgNode
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Static Protected Attributes inherited from SgNode
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Member Enumeration Documentation
Reason
enum SgAsmBlock::Reason
Reasons why a basic block might have been assigned to a function.
Enumerator
BLK_NONE
No particular reason.
Mostly just for initialization.
BLK_ENTRY_POINT
Block is an entry point for the function.
BLK_PADDING
Block is used for padding.
BLK_FRAGMENT
This block created because it seems to belong to the function although CFG traversal did not find it.
BLK_CFGHEAD
Block serves as an explicit starting point for CFG analysis.
BLK_USERDEF
User says block belongs to the function.
BLK_LEFTOVERS
Block is being assigned to a FUNC_LEFTOVERS function because it could not be assigned to any other function.
BLK_JUMPTABLE
Table of code addresses used by indirect branches.
BLK_GRAPH1
Block was added by the main CFG analysis.
BLK_GRAPH2
Block was added by a second pass of CFG analysis.
BLK_GRAPH3
Block was added by a third pass of CFG analysis.
BLK_MISCMASK
Miscellaneous reasons go here.
We can store only one such reason at a time.
BLK_FINDDATA
Added by Partitioner::FindData, which attaches unassigned parts of the disassembly address space to the preceding function.
BLK_POSTFUNC
Added by Partitioner::FindPostFunctionInsns, which adds unassigned instructions to the immediately preceding function.
Definition at line 40592 of file binaryInstruction.C.
Member Function Documentation
get_id()
rose_addr_t const & SgAsmBlock::get_id () const
Property: Identification.
Block unique identification number. Not used by ROSE.
set_id()
void SgAsmBlock::set_id (rose_addr_t const &)
Property: Identification.
Block unique identification number. Not used by ROSE.
get_reason()
unsigned const & SgAsmBlock::get_reason () const
Property: Reasons this block was created.
This property holds a bit mask of SgAsmBlock::Reason bits that indicate why this block was created.
set_reason()
void SgAsmBlock::set_reason (unsigned const &)
Property: Reasons this block was created.
This property holds a bit mask of SgAsmBlock::Reason bits that indicate why this block was created.
get_statementList() [1/2]
SgAsmStatementPtrList const & SgAsmBlock::get_statementList () const
Property: Statements of which this block is composed.
This is the list of "statements" that belong to this block. Statements are usually instructions, but historical code may have used basic blocks with other children.
Referenced by Rose::BinaryAnalysis::ControlFlow::explode_blocks().
get_statementList() [2/2]
SgAsmStatementPtrList & SgAsmBlock::get_statementList ()
Property: Statements of which this block is composed.
This is the list of "statements" that belong to this block. Statements are usually instructions, but historical code may have used basic blocks with other children.
set_statementList()
void SgAsmBlock::set_statementList (SgAsmStatementPtrList const &)
Property: Statements of which this block is composed.
This is the list of "statements" that belong to this block. Statements are usually instructions, but historical code may have used basic blocks with other children.
get_successors() [1/2]
SgAsmIntegerValuePtrList const & SgAsmBlock::get_successors () const
Property: Control flow successors.
This property holds the list of addresses which are control flow successors of this block. The Partitioner2 name space has a more useful definition of control flow graph that can reference indeterminate addresses and store data in the edges, and which is copiable.
Referenced by Rose::BinaryAnalysis::ControlFlow::apply_to_ast(), Rose::BinaryAnalysis::ControlFlow::build_block_cfg_from_ast(), and Rose::BinaryAnalysis::FunctionCall::build_cg_from_ast().
get_successors() [2/2]
SgAsmIntegerValuePtrList & SgAsmBlock::get_successors ()
Property: Control flow successors.
This property holds the list of addresses which are control flow successors of this block. The Partitioner2 name space has a more useful definition of control flow graph that can reference indeterminate addresses and store data in the edges, and which is copiable.
set_successors()
void SgAsmBlock::set_successors (SgAsmIntegerValuePtrList const &)
Property: Control flow successors.
This property holds the list of addresses which are control flow successors of this block. The Partitioner2 name space has a more useful definition of control flow graph that can reference indeterminate addresses and store data in the edges, and which is copiable.
get_successorsComplete()
bool const & SgAsmBlock::get_successorsComplete () const
Property: Whether the successors list is complete.
This property is true if the "successors" property holds an incomplete list of successors. Since this representation of a control flow graph is unable to represent edges that point to indeterminate addresses (e.g., computed branches), the "successors_complete" property can be used.
The Partitioner2 name space has a more useful definition of control flow graph that can reference indeterminate addresses and store data in the edges, and which is copiable.
set_successorsComplete()
void SgAsmBlock::set_successorsComplete (bool const &)
Property: Whether the successors list is complete.
This property is true if the "successors" property holds an incomplete list of successors. Since this representation of a control flow graph is unable to represent edges that point to indeterminate addresses (e.g., computed branches), the "successors_complete" property can be used.
The Partitioner2 name space has a more useful definition of control flow graph that can reference indeterminate addresses and store data in the edges, and which is copiable.
Referenced by Rose::BinaryAnalysis::ControlFlow::apply_to_ast().
get_immediateDominator()
SgAsmBlock *const & SgAsmBlock::get_immediateDominator () const
Property: Holds the immediate dominator block in the control flow graph.
The immediate dominator is the closest block to this one (by following reverse control flow edges) through which all control paths pass in order to get from the function entry block to this block.
The Partitioner2 name space has a more useful definition of control flow graph that can reference indeterminate addresses and store data in the edges, and which is copiable.
set_immediateDominator()
void SgAsmBlock::set_immediateDominator (SgAsmBlock *const &)
Property: Holds the immediate dominator block in the control flow graph.
The immediate dominator is the closest block to this one (by following reverse control flow edges) through which all control paths pass in order to get from the function entry block to this block.
The Partitioner2 name space has a more useful definition of control flow graph that can reference indeterminate addresses and store data in the edges, and which is copiable.
get_cachedVertex()
size_t const & SgAsmBlock::get_cachedVertex () const
Property: Cached vertex for control flow graphs.
This property is used by the virtual control flow graph mechanism.
The Partitioner2 name space has a more useful definition of control flow graph that can reference indeterminate addresses and store data in the edges, and which is copiable.
set_cachedVertex()
void SgAsmBlock::set_cachedVertex (size_t const &)
Property: Cached vertex for control flow graphs.
This property is used by the virtual control flow graph mechanism.
The Partitioner2 name space has a more useful definition of control flow graph that can reference indeterminate addresses and store data in the edges, and which is copiable.
Referenced by Rose::BinaryAnalysis::ControlFlow::cache_vertex_descriptors().
get_codeLikelihood()
double const & SgAsmBlock::get_codeLikelihood () const
Property: Likelihood that this block represents real instructions.
This property holds the results of an analysis that determines how likely it is that the memory from which this basic block was disassembled represents actual instructions that would be executed when the specimen runs.
set_codeLikelihood()
void SgAsmBlock::set_codeLikelihood (double const &)
Property: Likelihood that this block represents real instructions.
This property holds the results of an analysis that determines how likely it is that the memory from which this basic block was disassembled represents actual instructions that would be executed when the specimen runs.
get_stackDeltaOut()
int64_t const & SgAsmBlock::get_stackDeltaOut () const
Property: Stack pointer at block exit w.r.t.
stack pointer at function entry.
This is the difference between the stack pointer after the last instruction of this block executes and the stack pointer when this block's function was entered. It stores the result of a stack delta analysis. If stack delta analysis hasn't run, or was unable to determine a constant delta, then the special value SgAsmInstruction::INVALID_STACK_DELTA is stored.
set_stackDeltaOut()
void SgAsmBlock::set_stackDeltaOut (int64_t const &)
Property: Stack pointer at block exit w.r.t.
stack pointer at function entry.
This is the difference between the stack pointer after the last instruction of this block executes and the stack pointer when this block's function was entered. It stores the result of a stack delta analysis. If stack delta analysis hasn't run, or was unable to determine a constant delta, then the special value SgAsmInstruction::INVALID_STACK_DELTA is stored.
appendStatement()
void SgAsmBlock::appendStatement (SgAsmStatement *)
Add the specified statement to the end of the statement list.
This is is usually used to add the next instruction to the end of a basic block.
removeStatement()
void SgAsmBlock::removeStatement (SgAsmStatement *)
Erase the specified statement.
If the specified statement exists in the "statementList" property then it is erased but not deleted.
removeChildren()
void SgAsmBlock::removeChildren ()
Removes all statements from the block.
This makes the block empty, and not having a unique starting virtual address. It does not erase all children, just the statement children. None of the statements that are erased are deleted.
get_fallthroughVa()
rose_addr_t SgAsmBlock::get_fallthroughVa ()
Fall-through virtual address.
A block's fall-through address is the virtual address that follows the last byte of the block's last instruction. The block must have instructions (e.g., it cannot be a strict data block).
get_enclosingFunction()
SgAsmFunction * SgAsmBlock::get_enclosingFunction () const
Returns the function that owns this block.
This is just a convenience wrapper around SageInterface::getEnclosingNode.
Referenced by Rose::BinaryAnalysis::FunctionCall::build_cg_from_ast(), and Rose::BinaryAnalysis::FunctionCall::build_cg_from_cfg().
hasInstructions()
bool SgAsmBlock::hasInstructions () const
Determins if a block contains instructions.
Returns true if the block has instructions, false otherwise. We look only at the immediate descendants of this block. See also, SageInterface::querySubTree in order to get the list of all instructions or to consider all descendants.
isBasicBlock()
bool SgAsmBlock::isBasicBlock () const
Determine if a block contains instructions.
Returns true if the block has instructions, false otherwise. We look only at the immediate descendants of this block. See also, SageInterface::querySubTree in order to get the list of all instructions or to consider all descendants.
isFunctionCall()
bool SgAsmBlock::isFunctionCall (rose_addr_t & target_va, rose_addr_t & return_va)
Returns true if basic block appears to be a function call.
If the target address is known and is a single value then it is stored in the target_va argument, otherwise we store the maximum 64-bit address. If the return address for the function call is known then it is stored in the return_va argument, otherwise return_va will contain the maximum 64-bit address. The return address is usually the fall-through address of the basic block.
Note: Use this function in preference to SgAsmInstruction::isFunctionCallSlow() because the latter is intended to be used by the Partitioner before an AST is created and might not be as accurate.
Referenced by Rose::BinaryAnalysis::ControlFlow::fixup_fcall_fret().
reasonKey()
static std::string SgAsmBlock::reasonKey (const std::string & prefix = "") static
Multi-line string describing the letters used for basic block reasons.
The letters are returned by the padding version of reasonString and appear in unparser output.
reasonString() [1/2]
std::string SgAsmBlock::reasonString (bool pad) const
Returns reason string for this block.
The reason string is a very short string describing the reason that the block was created.
reasonString() [2/2]
static std::string SgAsmBlock::reasonString (bool pad, unsigned reason) static
Converts a reason bit vector to a human-friendly string.
The second argument is the bit vector of SgAsmBlock::Reason bits. Some of the positions in the padded return value are used for more than one bit. For instance, the first character can be "L" for leftovers, "N" for padding, "E" for entry point, or "-" for none of the above.
initializeProperties()
void SgAsmBlock::initializeProperties () protected
Initialize all properties that have explicit initial values.
This function is mostly for use in user-defined constructors where the user desires to initialize all the properties but does not know the names of the data members that store the property values. This function initializes the properties that have explicit initializations within this class, but does not recursively initialize base classes.
The documentation for this class was generated from the following file:
binaryInstruction.C