ROSE: Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList Class Reference
Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList Class Reference
Description
Simple list-based memory state.
MemoryCellList uses a list of MemoryCell objects to represent the memory state. Each memory cell contains at least an address and a value, both of which have a run-time width. The default MemoryCellList configuration restricts memory cell values to be one byte wide and requires the caller to perform any necessary byte extraction or concatenation when higher software layers are reading/writing multi-byte values. Using one-byte values simplifies the aliasing calculations. The super class defines a byteRestricted property that can be set to false to allow the memory to store variable-width cell values.
MemoryCellList also provides a scan() method that returns a list of memory cells that alias a specified address. This method can be used by a higher-level readMemory() operation in preference to the usual MemoryState::readMemory().
There is no requirement that a State use a MemoryCellList as its memory state; it can use any subclass of MemoryState. Since MemoryCellList is derived from MemoryState it must provide virtual allocating constructors, which makes it possible for users to define their own subclasses and use them in the semantic framework.
This implementation stores memory cells in reverse chronological order: the most recently created cells appear at the beginning of the list. Subclasses, of course, are free to reorder the list however they want.
Definition at line 39 of file MemoryCellList.h.
#include <Rose/BinaryAnalysis/InstructionSemantics/BaseSemantics/MemoryCellList.h>
Public Types
using Super = MemoryCellState
Base type.
using Ptr = MemoryCellListPtr
Shared-ownership pointer.
Public Types inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState
using Super = MemoryState
Base type.
using Ptr = MemoryCellStatePtr
Shared-ownership pointer.
Public Types inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState
typedef MemoryStatePtr Ptr
Shared-ownership pointer.
Public Member Functions
virtual MemoryStatePtr create (const SValuePtr &addrProtoval, const SValuePtr &valProtoval) const override
Virtual allocating constructor.
virtual MemoryStatePtr create (const MemoryCellPtr &protocell) const
Virtual allocating constructor.
virtual MemoryStatePtr clone () const override
Virtual allocating copy constructor.
virtual void clear () override
Clear memory.
virtual bool merge (const MemoryStatePtr &other, RiscOperators *addrOps, RiscOperators *valOps) override
Merge memory states for data flow analysis.
virtual std::vector< MemoryCellPtr > matchingCells (MemoryCell::Predicate &) const override
Find all matching cells.
virtual std::vector< MemoryCellPtr > leadingCells (MemoryCell::Predicate &) const override
Find leading matching cells.
virtual void eraseMatchingCells (MemoryCell::Predicate &) override
Remove all matching cells.
virtual void eraseLeadingCells (MemoryCell::Predicate &) override
Remove leading matching cells.
virtual void traverse (MemoryCell::Visitor &) override
Traverse and modify cells.
virtual void hash (Combinatorics::Hasher &, RiscOperators *addrOps, RiscOperators *valOps) const override
Calculate a hash for this memory state.
virtual SValuePtr readMemory (const SValuePtr &address, const SValuePtr &dflt, RiscOperators *addrOps, RiscOperators *valOps) override
Read a value from memory.
virtual SValuePtr peekMemory (const SValuePtr &address, const SValuePtr &dflt, RiscOperators *addrOps, RiscOperators *valOps) override
Read a value from memory without side effects.
virtual void writeMemory (const SValuePtr &addr, const SValuePtr &value, RiscOperators *addrOps, RiscOperators *valOps) override
Write a value to memory.
virtual void print (std::ostream &, Formatter &) const override
Print a memory state to more than one line of output.
bool mergeNoAliasing (const MemoryStatePtr &other, RiscOperators *addrOps, RiscOperators *valOps)
Merge two states without aliasing.
bool mergeWithAliasing (const MemoryStatePtr &other, RiscOperators *addrOps, RiscOperators *valOps)
Merge two states with aliasing.
virtual bool isAllPresent (const SValuePtr &address, size_t nBytes, RiscOperators *addrOps, RiscOperators *valOps) const
Predicate to determine whether all bytes are present.
template<class Iterator >
CellList scan (Iterator &cursor, const SValuePtr &addr, size_t nBits, RiscOperators *addrOps, RiscOperators *valOps) const
Scan cell list to find matching cells.
virtual AddressSet getWritersUnion (const SValuePtr &addr, size_t nBits, RiscOperators *addrOps, RiscOperators *valOps) override
Writers for an address.
virtual AddressSet getWritersIntersection (const SValuePtr &addr, size_t nBits, RiscOperators *addrOps, RiscOperators *valOps) override
Writers for an address.
bool occlusionsErased () const
Property: erase occluded cells.
void occlusionsErased (bool b)
Property: erase occluded cells.
virtual const CellList & get_cells () const
Returns the list of all memory cells.
virtual CellList & get_cells ()
Returns the list of all memory cells.
Public Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState
virtual void updateReadProperties (const CellList &)
Adjust I/O properties after reading memory.
virtual void updateWriteProperties (const CellList &, InputOutputPropertySet)
Adjust I/O properties after writing memory.
void eraseNonWritten ()
Erase cells that have no writers.
std::vector< MemoryCellPtr > allCells () const
All cells.
virtual MemoryCellPtr latestWrittenCell () const
Property: Cell most recently written.
virtual void latestWrittenCell (const MemoryCellPtr &cell)
Property: Cell most recently written.
Public Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState
SValuePtr get_addr_protoval () const
Return the address protoval.
SValuePtr get_val_protoval () const
Return the value protoval.
MergerPtr merger () const
Property: Merger.
void merger (const MergerPtr &)
Property: Merger.
bool byteRestricted () const
Indicates whether memory cell values are required to be eight bits wide.
void byteRestricted (bool)
Indicates whether memory cell values are required to be eight bits wide.
ByteOrder::Endianness get_byteOrder () const
Memory byte order.
void set_byteOrder (ByteOrder::Endianness)
Memory byte order.
void print (std::ostream &, const std::string prefix="") const
Print a memory state to more than one line of output.
WithFormatter with_format (Formatter &)
Used for printing memory states with formatting.
WithFormatter operator+ (Formatter &)
Used for printing memory states with formatting.
WithFormatter operator+ (const std::string &linePrefix)
Used for printing memory states with formatting.
Static Public Member Functions
static MemoryCellListPtr instance (const SValuePtr &addrProtoval, const SValuePtr &valProtoval)
Instantiate a new prototypical memory state.
static MemoryCellListPtr instance (const MemoryCellPtr &protocell)
Instantiate a new memory state with prototypical memory cell.
static MemoryCellListPtr instance (const MemoryCellListPtr &other)
Instantiate a new copy of an existing memory state.
static MemoryCellListPtr promote (const BaseSemantics::MemoryStatePtr &m)
Promote a base memory state pointer to a BaseSemantics::MemoryCellList pointer.
Static Public Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState
static MemoryCellStatePtr promote (const BaseSemantics::MemoryStatePtr &m)
Promote a base memory state pointer to a BaseSemantics::MemoryCellState pointer.
Static Public Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState
static MemoryStatePtr promote (const MemoryStatePtr &)
Protected Member Functions
MemoryCellList (const MemoryCellPtr &protocell)
MemoryCellList (const SValuePtr &addrProtoval, const SValuePtr &valProtoval)
MemoryCellList (const MemoryCellList &other)
virtual SValuePtr mergeCellValues (const CellList &cells, const SValuePtr &dflt, RiscOperators *addrOps, RiscOperators *valOps)
virtual AddressSet mergeCellWriters (const CellList &cells)
virtual InputOutputPropertySet mergeCellProperties (const CellList &cells)
virtual MemoryCellPtr insertReadCell (const SValuePtr &addr, const SValuePtr &value)
virtual MemoryCellPtr insertReadCell (const SValuePtr &addr, const SValuePtr &value, const AddressSet &writers, const InputOutputPropertySet &props)
Protected Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState
MemoryCellState (const MemoryCellPtr &protocell)
MemoryCellState (const SValuePtr &addrProtoval, const SValuePtr &valProtoval)
MemoryCellState (const MemoryCellState &other)
Protected Member Functions inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState
MemoryState (const SValuePtr &addrProtoval, const SValuePtr &valProtoval)
MemoryState (const MemoryStatePtr &other)
Protected Attributes
CellList cells
bool occlusionsErased_
Protected Attributes inherited from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState
MemoryCellPtr protocell
MemoryCellPtr latestWrittenCell_
Member Typedef Documentation
Super
using Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::Super = MemoryCellState
Base type.
Definition at line 42 of file MemoryCellList.h.
Ptr
using Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::Ptr = MemoryCellListPtr
Shared-ownership pointer.
Definition at line 45 of file MemoryCellList.h.
Constructor & Destructor Documentation
MemoryCellList() [1/4]
Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::MemoryCellList () inline protected
Definition at line 68 of file MemoryCellList.h.
MemoryCellList() [2/4]
Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::MemoryCellList (const MemoryCellPtr & protocell) inline explicit protected
Definition at line 71 of file MemoryCellList.h.
MemoryCellList() [3/4]
Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::MemoryCellList (const SValuePtr & addrProtoval, const SValuePtr & valProtoval) inline protected
Definition at line 74 of file MemoryCellList.h.
MemoryCellList() [4/4]
Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::MemoryCellList (const MemoryCellList & other) inline protected
Definition at line 78 of file MemoryCellList.h.
Member Function Documentation
instance() [1/3]
static MemoryCellListPtr Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::instance (const SValuePtr & addrProtoval, const SValuePtr & valProtoval) inline static
Instantiate a new prototypical memory state.
This constructor uses the default type for the cell type (based on the semantic domain). The prototypical values are usually the same (addresses and stored values are normally the same type).
Definition at line 90 of file MemoryCellList.h.
Referenced by create(), and create().
instance() [2/3]
static MemoryCellListPtr Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::instance (const MemoryCellPtr & protocell) inline static
Instantiate a new memory state with prototypical memory cell.
Definition at line 95 of file MemoryCellList.h.
instance() [3/3]
static MemoryCellListPtr Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::instance (const MemoryCellListPtr & other) inline static
Instantiate a new copy of an existing memory state.
Definition at line 100 of file MemoryCellList.h.
create() [1/2]
virtual MemoryStatePtr Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::create (const SValuePtr & addrProtoval, const SValuePtr & valProtoval) const inline override virtual
Virtual allocating constructor.
Allocates and constructs a new MemoryState object having the same dynamic type as this object. A prototypical SValue must be supplied and will be used to construct any additional SValue objects needed during the operation of a MemoryState. Two prototypical values are supplied, one for addresses and another for values stored at those addresses, although they will almost always be the same.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState.
Reimplemented in Rose::BinaryAnalysis::InstructionSemantics::IntervalSemantics::MemoryState, Rose::BinaryAnalysis::InstructionSemantics::SymbolicSemantics::MemoryListState, and Rose::BinaryAnalysis::Partitioner2::Semantics::MemoryState< Super >.
Definition at line 108 of file MemoryCellList.h.
References instance().
create() [2/2]
virtual MemoryStatePtr Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::create (const MemoryCellPtr & protocell) const inline virtual
Virtual allocating constructor.
Reimplemented in Rose::BinaryAnalysis::InstructionSemantics::IntervalSemantics::MemoryState, Rose::BinaryAnalysis::InstructionSemantics::SymbolicSemantics::MemoryListState, and Rose::BinaryAnalysis::Partitioner2::Semantics::MemoryState< Super >.
Definition at line 113 of file MemoryCellList.h.
References instance().
clone()
virtual MemoryStatePtr Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::clone () const inline override virtual
Virtual allocating copy constructor.
Creates a new MemoryState object which is a copy of this object.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState.
Reimplemented in Rose::BinaryAnalysis::InstructionSemantics::IntervalSemantics::MemoryState, Rose::BinaryAnalysis::InstructionSemantics::SymbolicSemantics::MemoryListState, and Rose::BinaryAnalysis::Partitioner2::Semantics::MemoryState< Super >.
Definition at line 117 of file MemoryCellList.h.
promote()
static MemoryCellListPtr Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::promote (const BaseSemantics::MemoryStatePtr & m) inline static
Promote a base memory state pointer to a BaseSemantics::MemoryCellList pointer.
The memory state m must have a BaseSemantics::MemoryCellList dynamic type.
Definition at line 126 of file MemoryCellList.h.
clear()
virtual void Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::clear () override virtual
Clear memory.
Removes all memory cells from this memory state.
Reimplemented from Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState.
merge()
virtual bool Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::merge (const MemoryStatePtr & other, RiscOperators * addrOps, RiscOperators * valOps) override virtual
Merge memory states for data flow analysis.
Merges the other state into this state, returning true if this state changed.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState.
matchingCells()
virtual std::vector< MemoryCellPtr > Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::matchingCells (MemoryCell::Predicate &) const override virtual
Find all matching cells.
Returns a vector of cells for which the predicate returns true.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState.
leadingCells()
virtual std::vector< MemoryCellPtr > Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::leadingCells (MemoryCell::Predicate &) const override virtual
Find leading matching cells.
Returns the vector of cells obtained by invoking the predicate on each cell and returning those leading cells for which the predicate is true. The first cell for which the predicate is false terminates the traversal and does not appear in the return value.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState.
eraseMatchingCells()
virtual void Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::eraseMatchingCells (MemoryCell::Predicate &) override virtual
Remove all matching cells.
Traverses the memory cells and removes those for which the predicate returns true.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState.
eraseLeadingCells()
virtual void Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::eraseLeadingCells (MemoryCell::Predicate &) override virtual
Remove leading matching cells.
Traverses the memory cells and removes those for which the predicate returns true. The traversal is terminated the first time the predicate returns false.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState.
traverse()
virtual void Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::traverse (MemoryCell::Visitor &) override virtual
Traverse and modify cells.
Traverse cells and optionally modify them.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState.
hash()
virtual void Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::hash (Combinatorics::Hasher & , RiscOperators * addrOps, RiscOperators * valOps) const override virtual
Calculate a hash for this memory state.
This hashes the addresses and values stored in memory. The goal is to be able to identify when two memory states are the "same". An analysis might be able to take shortcuts if it encounters a state that it has seen before.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState.
readMemory()
virtual SValuePtr Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::readMemory (const SValuePtr & address, const SValuePtr & dflt, RiscOperators * addrOps, RiscOperators * valOps) override virtual
Read a value from memory.
See BaseSemantics::MemoryState() for requirements. This implementation scans the reverse chronological cell list until it finds a cell that must alias the specified addresses and value size. Along the way, it accumulates a list of cells that may alias the specified address. If the accumulated list does not contain exactly one cell, or the scan fell off the end of the list, then dflt becomes the return value, otherwise the return value is the single value on the accumulated list. If the dflt value is returned, then it is also pushed onto the front of the cell list.
The width of the dflt value determines how much data is read. The base implementation assumes that all cells contain 8-bit values.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState.
Reimplemented in Rose::BinaryAnalysis::InstructionSemantics::IntervalSemantics::MemoryState, Rose::BinaryAnalysis::InstructionSemantics::SymbolicSemantics::MemoryListState, and Rose::BinaryAnalysis::Partitioner2::Semantics::MemoryState< Super >.
peekMemory()
virtual SValuePtr Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::peekMemory (const SValuePtr & address, const SValuePtr & dflt, RiscOperators * addrOps, RiscOperators * valOps) override virtual
Read a value from memory without side effects.
This is similar to readMemory except there are no side effects. The memory state is not modified by this function.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState.
Reimplemented in Rose::BinaryAnalysis::InstructionSemantics::IntervalSemantics::MemoryState, Rose::BinaryAnalysis::InstructionSemantics::SymbolicSemantics::MemoryListState, and Rose::BinaryAnalysis::Partitioner2::Semantics::MemoryState< Super >.
writeMemory()
virtual void Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::writeMemory (const SValuePtr & addr, const SValuePtr & value, RiscOperators * addrOps, RiscOperators * valOps) override virtual
Write a value to memory.
See BaseSemantics::MemoryState() for requirements. This implementation creates a new memory cell and pushes it onto the front of the cell list.
The base implementation assumes that all cells contain 8-bit values.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState.
Reimplemented in Rose::BinaryAnalysis::InstructionSemantics::IntervalSemantics::MemoryState, Rose::BinaryAnalysis::InstructionSemantics::SymbolicSemantics::MemoryListState, and Rose::BinaryAnalysis::Partitioner2::Semantics::MemoryState< Super >.
print()
virtual void Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::print (std::ostream & , Formatter &) const override virtual
Print a memory state to more than one line of output.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryState.
Reimplemented in Rose::BinaryAnalysis::Partitioner2::Semantics::MemoryState< Super >.
mergeNoAliasing()
bool Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::mergeNoAliasing (const MemoryStatePtr & other, RiscOperators * addrOps, RiscOperators * valOps)
Merge two states without aliasing.
The other state is merged into this state without considering any aliasing. Returns true if this state changed, false otherwise.
mergeWithAliasing()
bool Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::mergeWithAliasing (const MemoryStatePtr & other, RiscOperators * addrOps, RiscOperators * valOps)
Merge two states with aliasing.
The other state is merged into this state while considering any aliasing. Returns true if this state changed, false otherwise.
isAllPresent()
virtual bool Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::isAllPresent (const SValuePtr & address, size_t nBytes, RiscOperators * addrOps, RiscOperators * valOps) const virtual
Predicate to determine whether all bytes are present.
Returns true if bytes at the specified address and the following consecutive addresses are all present in this memory state.
occlusionsErased() [1/2]
bool Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::occlusionsErased () const inline
Property: erase occluded cells.
If this property is true, then writing a new cell to memory will also erase all older cells that must alias the new cell. Erasing occlusions can adversely affect performance for some semantic domains.
Definition at line 198 of file MemoryCellList.h.
occlusionsErased() [2/2]
void Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::occlusionsErased (bool b) inline
Property: erase occluded cells.
If this property is true, then writing a new cell to memory will also erase all older cells that must alias the new cell. Erasing occlusions can adversely affect performance for some semantic domains.
Definition at line 199 of file MemoryCellList.h.
scan()
template<class Iterator > CellList Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::scan (Iterator & cursor, const SValuePtr & addr, size_t nBits, RiscOperators * addrOps, RiscOperators * valOps) const inline
Scan cell list to find matching cells.
Scans the cell list from front to back (reverse chronological order) and build a list of cells that may alias the given address and size. The returned list is also in reverse chronological order. The scanning begins at the specified cursor and ends either when an exact alias is found or the end of the list is reached. In either case, the cell that caused the scan to terminate is returned–either the exact alias or the end iterator.
Typical usage is like this:
MemoryCellList::CellList::iterator cursor = memory->get_cells().begin();
MemoryCellList::CellList cells = memory->scan(cursor, address, 8, addrOps, valOps);
if (cursor != memory->get_cells().end())
    std::cerr <<"found exact alias: " <<*cursor <<"\n";
Definition at line 218 of file MemoryCellList.h.
References Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::RiscOperators::undefined_().
get_cells() [1/2]
virtual const CellList & Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::get_cells () const inline virtual
Returns the list of all memory cells.
Definition at line 235 of file MemoryCellList.h.
get_cells() [2/2]
virtual CellList & Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::get_cells () inline virtual
Returns the list of all memory cells.
Definition at line 236 of file MemoryCellList.h.
getWritersUnion()
virtual AddressSet Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::getWritersUnion (const SValuePtr & addr, size_t nBits, RiscOperators * addrOps, RiscOperators * valOps) override virtual
Writers for an address.
Returns the set of all writers that wrote to the specified address or any address that might alias the specified address. Memory states that don't normally compute aliases (e.g., MemoryCellMap) return only the writers for the specified address, not any aliases, and in this case getWritersUnion and getWritersIntersection return the same set.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState.
getWritersIntersection()
virtual AddressSet Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::getWritersIntersection (const SValuePtr & addr, size_t nBits, RiscOperators * addrOps, RiscOperators * valOps) override virtual
Writers for an address.
Returns the set of all writers that wrote to the specified address and any address that might alias the specified address. Memory states that don't normally compute aliases (e.g., MemoryCellMap) return only the writers for the specified address, not any aliases, and in this case getWritersUnion and getWritersIntersection return the same set.
Implements Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellState.
Member Data Documentation
cells
CellList Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::cells protected
Definition at line 48 of file MemoryCellList.h.
occlusionsErased_
bool Rose::BinaryAnalysis::InstructionSemantics::BaseSemantics::MemoryCellList::occlusionsErased_ protected
Definition at line 49 of file MemoryCellList.h.
The documentation for this class was generated from the following file:
MemoryCellList.h