ROSE: SgExpression Class Reference
SgExpression Class Reference
Description
This class represents the notion of an expression. Expressions are derived from SgLocatedNodes, since similar to statement, expressions have a concrete location within the user's source code.
There are no direct uses of this IR node anywhere. All expressions are derived from this IR node to build derived classes such as unary and binary operators, conditional expressions, delete expression, variable reference expressions, etc.
Note
The SgExpression class has a virtual get_type() member function which returns the type associated with any expression. The get_type() support has the following properties:
The type is not explicitly stored in the IR, except for:
SgCastExp
SgNewExp
SgAssignInitializer
SgAggregateInitializer
SgConstructorInitializer
SgVarArgOp
SgVarArgStartOp
SgVarArgEndOp
SgVarArgCopyOp
SgVarArgStartOneOperandOp
Binary operators return the type associated with the lhs operand, except for (which return the type associated with the rhs operand):
SgDotExp
SgArrowExp
SgDotStarOp
SgArrowStarOp
Unary operators return the type of their operand
Value expressions return predefined types (that or their value)
Other special cases include:
SgPntrArrRefExp, returns the element type of the array being referenced by the lhs (non-trivial implementation), must handle cases of:
SgArrayType
SgPointerType
SgTypedefType
SgPointerDerefExp, returns the type of the dereferenced pointer (non-trivial implementation), must handle cases of:
SgArrayType
SgPointerType
SgTypedefType
SgReferenceType
SgFunctionType
SgMemberFunctionType
SgAddressOfOp, creates a pointer to the base type which is stored internally.
SgFunctionCallExp, returns the return type of the function being called (except in special cases, this might require more work later). Migration to the correct implementation is more complex due to requirements of backward compatability with older design.
SgSizeOfOp, returns SgTypeUnsignedInt
SgTypeIdOp, returns type of stored operand (not clear if this is correct)
SgConditionalExp, tests for matching of types from true and false branches, but returns type associated with true branch. The types from each branch frequently don't match in application codes.
SgDeleteExp, returns SgTypeVoid (used to return SgDefaultType)
SgExprListExp, returns SgDefaultType, but should return type of last expression.
SgVarRefExp, returns the type associated with the SgSymbol stored internally.
SgFunctionRefExp, returns the type associated with the SgSymbol stored internally.
SgMemberFunctionRefExp, returns the type associated with the SgSymbol stored internally.
SgThisExp, returns a SgPointerType constructed from the type of the class symbol (stored inteernally).
SgEnumVal, returns a SgTypeInt
SgLongLongIntVal, returns SgTypeLong (should return SgTypeLongLong)
SgNewExp, returns a pointer to p_specified_type (explicitly stored there)
Logical operators return SgTypeInt, these include:
SgAndOp
SgOrOp
SgNotOp
All others operate as a SgBinaryOp (type of lhs operand) or SgUnaryOp (type of operand). not clear if this is the correct behavior.
The following expressions return a SgTypeDefault:
SgThrowOp
SgNullExpression
SgVariantExpression
get_type() vs. get_expression_type(). Note that there is of some IR nodes a get_expression_type() which is always a data access function to a stored type. The get_expression_type() function is for internal use only. Where used, this function can return NULL if the explicitly stored p_expression_type variable is not needed (this is to support it later being removed). Although the type should be computed most of the time, there are some IR nodes where it must be stored explicitly (detailed above; for example where the SgTypeDefault is used and for SgCastExp, etc.). The function get_expression_type() is not a part of the user interface and users should call get_type() instead.
Definition at line 474495 of file Cxx_Grammar.h.
Public Types
enum { static_variant = V_SgExpression }
static variant value
typedef SgLocatedNode base_node_type
Public Types inherited from SgLocatedNode
enum { static_variant = V_SgLocatedNode }
static variant value
typedef SgNode base_node_type
Public Types inherited from SgNode
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
virtual SgNode * copy (SgCopyHelp &help) const override
virtual int replace_expression (SgExpression *oldChild, SgExpression *newChild)
This class represents the base class of all the expressions within this grammar.
virtual SgType * get_type () const
unparsing support for pragmas
virtual int precedence () const
return precedence (scale of 0-10, as I recall)
virtual unsigned int cfgIndexForEnd () const override
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const override
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n) override
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n) override
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index) override
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index) override
Find the in edges of a CFG node – internal version.
virtual bool isDefinable () const
For Fortran. When called from a node of any other language, behavior is undefined (see SageInterface::is_Fortran_language). Returns a bool value which is true if the current expression is "almost definable". "Almost definable" here means as defined by the Fortran standard (2.5.5), with the caveat that allocatable variables are always called an lvalue. The Fortran standard dictates that an allocatable variable which has not been allocated is not definable. In the general case, it cannot be statically determined whether an allocatable variable has been allocated or not. Note: constants in Fortran are not lvalues, while in C and C++ lvalues may be const.
virtual bool isUsedAsDefinable () const
For Fortran. When called from a node of any other language, behavior is undefined (see SageInterface::is_Fortran_language).
virtual bool isLValue () const
For C and C++. When called from a node of any other language, behavior is undefined (see SageInterface::is_C*_language). Returns a bool value which is true if the current expression is an lvalue, as defined by the C++ standard.
virtual bool isUsedAsLValue () const
For C and C++. When called from a node of any other language, behavior is undefined (see SageInterface::is_C*_language).
virtual bool isChildUsedAsLValue (const SgExpression *child) const
For C and C++. When called from a node of any other language, behavior is undefined (see SageInterface::is_C*_language).
virtual Sg_File_Info * get_file_info (void) const override
Interface function to implement original SAGE interface to SgFile_Info objects.
virtual void set_file_info (Sg_File_Info *X) override
Access function calls set_startingConstruct(Sg_File_Info*) member function.
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const override
SgName get_qualified_name_prefix () const
This function generates the qualified name prefix to be used with the type referenced by this expression.
SgName get_qualified_name_prefix_for_referenced_type () const
This function generates the qualified name prefix to be used with the type referenced by this expression.
virtual int get_name_qualification_length () const
virtual void set_name_qualification_length (int name_qualification_length)
virtual bool get_type_elaboration_required () const
virtual void set_type_elaboration_required (bool type_elaboration_required)
virtual bool get_global_qualification_required () const
virtual void set_global_qualification_required (bool global_qualification_required)
virtual int get_name_qualification_for_pointer_to_member_class_length () const
virtual void set_name_qualification_for_pointer_to_member_class_length (int name_qualification_length)
virtual bool get_type_elaboration_for_pointer_to_member_class_required () const
virtual void set_type_elaboration_for_pointer_to_member_class_required (bool type_elaboration_required)
virtual bool get_global_qualification_for_pointer_to_member_class_required () const
virtual void set_global_qualification_for_pointer_to_member_class_required (bool global_qualification_required)
virtual SgExpression * get_originalExpressionTree () const
virtual void set_originalExpressionTree (SgExpression *X)
bool hasExplicitType ()
Some expressions store internal SgType pointers explicitly while others compute them from other expressions. This function is true if it has a data member that is a type (pointer, array, etc.).
void set_explicitly_stored_type (SgType *type)
Some expressions store internal SgType pointers explicitly, this allows these IR nodes to be reset with new types (used in the snippet support).
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
virtual std::string class_name () const override
returns a string representing the class name
virtual VariantT variantT () const override
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer () override
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer () override
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors () override
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx) override
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child) override
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI () override
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const override
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor) override
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const override
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const override
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgExpression (const SgExpressionStorageClass &source)
IR node constructor to support AST File I/O.
SgExpression * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
bool get_need_paren () const
returns bool value if front-end considers parenthesis to be required.
void set_need_paren (bool need_paren)
This function allows the p_need_paren flag to be set (used internally).
bool get_lvalue () const
Returns a bool value if the current expression is assigned to.
void set_lvalue (bool lvalue)
This function allows the p_lvalue flag to be set (used internally).
bool get_global_qualified_name () const
void set_global_qualified_name (bool global_qualified_name)
Sg_File_Info * get_operatorPosition () const
void set_operatorPosition (Sg_File_Info *operatorPosition)
virtual ~SgExpression ()
This is the destructor.
SgExpression (Sg_File_Info *startOfConstruct)
This is the constructor.
Public Member Functions inherited from SgLocatedNode
const std::string & getFilenameString () const
void addToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo::RelativePositionType locationInList=PreprocessingInfo::after)
This function adds comment or CPP directives to the current IR node.
void insertToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo *anchorInfoPtr, bool insertAfter=true)
Insert prepInfo After (or before if last parameter is false) an anchor info ptr in the list of preprocessing info attached to the current node. This is useful to insert things in the middle.
void setCompilerGenerated ()
Allow IR nodes (mostly SgLocatedNode) to be marked as compiler generated.
void unsetCompilerGenerated ()
bool isCompilerGenerated () const
Simple test for if this is a compiler generated node.
void setTransformation ()
Allow IR nodes (mostly SgLocatedNode) to be marked as a transformation.
void unsetTransformation ()
bool isTransformation () const
Simple test for if this is a part of a transformation.
void setFrontendSpecific ()
Allow IR nodes (mostly SgLocatedNode) to be marked as front-end specific (generated by the front-end to support a specific backend compiler; e.g. GNU gcc and g++).
void unsetFrontendSpecific ()
bool isFrontendSpecific () const
Simple test for if this is a frontend specific IR node.
void setShared ()
Allow IR nodes (mostly SgLocatedNode) to be marked as shared.
void unsetShared ()
bool isShared () const
Simple test for if this is a shared IR node.
void setSourcePositionUnavailableInFrontend ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetSourcePositionUnavailableInFrontend ()
void setOutputInCodeGeneration ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetOutputInCodeGeneration ()
bool isOutputInCodeGeneration () const
int get_physical_file_id ()
Allow IR nodes (mostly SgLocatedNode) to be queried for there physical file ID.
AttachedPreprocessingInfoType *& getAttachedPreprocessingInfo (void)
Computes the number of nodes in the defined subtree of the AST.
Sg_File_Info * generateMatchingFileInfo ()
virtual void addNewAttribute (std::string s, AstAttribute *a) override
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const override
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a) override
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a) override
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s) override
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const override
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const override
Returns the number of attributes on this IR node.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgLocatedNode (const SgLocatedNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgLocatedNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
Sg_File_Info * get_startOfConstruct () const override
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
void set_startOfConstruct (Sg_File_Info *startOfConstruct)
This function sets the current source location position of the start of the current construct.
Sg_File_Info * get_endOfConstruct () const override
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
void set_endOfConstruct (Sg_File_Info *endOfConstruct)
This function sets the current source location position of the end of the current construct.
AttachedPreprocessingInfoType * get_attachedPreprocessingInfoPtr () const
void set_attachedPreprocessingInfoPtr (AttachedPreprocessingInfoType *attachedPreprocessingInfoPtr)
AstAttributeMechanism * get_attributeMechanism () const override
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
void set_attributeMechanism (AstAttributeMechanism *attributeMechanism) override
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
bool get_containsTransformationToSurroundingWhitespace () const
void set_containsTransformationToSurroundingWhitespace (bool containsTransformationToSurroundingWhitespace)
virtual ~SgLocatedNode ()
This is the destructor.
SgLocatedNode (Sg_File_Info *startOfConstruct=NULL)
This is the constructor.
Public Member Functions inherited from SgNode
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
Static Public Member Functions
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgExpression * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgExpression *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgExpression *sgnode)
Static Public Member Functions inherited from SgLocatedNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgLocatedNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgLocatedNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgLocatedNode *sgnode)
Static Public Member Functions inherited from SgNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Protected Attributes
bool p_need_paren
This boolean value marks the current expression as requiring parenthises.
bool p_lvalue
This boolean variable marks the current expression as a left hand side value (lvalue).
bool p_global_qualified_name
Sg_File_Info * p_operatorPosition
Protected Attributes inherited from SgLocatedNode
Sg_File_Info * p_startOfConstruct
This pointer is always valid and stores the source position of the start of the current construct.
Sg_File_Info * p_endOfConstruct
This pointer is always valid and stores the source position of the end of the current construct.
AttachedPreprocessingInfoType * p_attachedPreprocessingInfoPtr
Holds comments and/or preprocessor directives located before or after the current statement of expression.
AstAttributeMechanism * p_attributeMechanism
bool p_containsTransformationToSurroundingWhitespace
Protected Attributes inherited from SgNode
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Additional Inherited Members
Protected Member Functions inherited from SgLocatedNode
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
Protected Member Functions inherited from SgNode
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Static Protected Attributes inherited from SgNode
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Member Typedef Documentation
base_node_type
typedef SgLocatedNode SgExpression::base_node_type
Definition at line 475026 of file Cxx_Grammar.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
static variant value
Definition at line 474647 of file Cxx_Grammar.h.
Constructor & Destructor Documentation
~SgExpression()
SgExpression::~SgExpression () virtual
This is the destructor.
Only the Sg_File_Info object can be deleted in this object.
SgExpression()
SgExpression::SgExpression (Sg_File_Info * startOfConstruct = NULL)
This is the constructor.
This constructor builds the SgExpression base class.
Parameters
startOfConstruct represents the position in the source code
See also
Example:create an SgExpression object
Member Function Documentation
copy()
virtual SgNode * SgExpression::copy (SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
replace_expression()
virtual int SgExpression::replace_expression (SgExpression * oldChild, SgExpression * newChild) virtual
This class represents the base class of all the expressions within this grammar.
It contains all the base functionality for the construction, manipulation, and unparsing support. Function to get user defined attributes (as I recall) Replace an expression child of this node with another one.
Reimplemented in SgUnaryOp, SgBinaryOp, SgCallExpression, SgSizeOfOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgOp, SgVarArgEndOp, SgNaryOp, SgAlignOfOp, SgExprListExp, and SgJovialPresetPositionExp.
Referenced by SageInterface::replaceExpression().
get_type()
SgExpression::get_type () const virtual
unparsing support for pragmas
Get the type associated with this expression.
get the type associated with this expression
This function is the correct user function to call to get the type (note that get_expression_type() is for internal use only).
Returns
Returns pointer to SgType (base class for all possible types)
Reimplemented in SgUnaryOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgCastExp, SgThrowOp, SgUserDefinedUnaryOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAndOp, SgOrOp, SgCommaOpExp, SgPntrArrRefExp, SgUserDefinedBinaryOp, SgMembershipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
Referenced by SageBuilder::buildComplexVal(), SageBuilder::buildComplexVal_nfi(), SageBuilder::buildCudaKernelCallExp_nfi(), SageBuilder::buildFunctionCallExp(), SageBuilder::buildFunctionCallExp_nfi(), SageBuilder::buildImaginaryVal(), SageBuilder::buildImaginaryVal_nfi(), SageBuilder::buildThrowOp(), SageInterface::createTempVariableAndReferenceForExpression(), SageInterface::createTempVariableForExpression(), SageBuilder::errorCheckingTargetAST(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::getClassTypeChainForMemberReference(), SageInterface::insertAfterUsingCommaOp(), SageInterface::replaceExpressionWithStatement(), and SageInterface::splitExpression().
precedence()
virtual int SgExpression::precedence () const virtual
return precedence (scale of 0-10, as I recall)
Reimplemented in SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgNaryBooleanOp, and SgNaryComparisonOp.
cfgIndexForEnd()
virtual unsigned int SgExpression::cfgIndexForEnd () const override virtual
Determine the CFG index for the end of this construct.
Reimplemented from SgNode.
Reimplemented in SgUnaryOp, SgThrowOp, SgBinaryOp, SgExprListExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgFunctionCallExp, SgSizeOfOp, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgInitializer, SgConstructorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgNullExpression, SgSubscriptExpression, SgAsteriskShapeExp, SgImpliedDo, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgPseudoDestructorRefExp, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgNoexceptOp, and SgNonrealRefExp.
cfgIsIndexInteresting()
virtual bool SgExpression::cfgIsIndexInteresting (unsigned int index) const override virtual
Determine whether a particular CFG node index is "interesting" for this kind of node.
Reimplemented from SgNode.
Reimplemented in SgAndOp, SgOrOp, and SgConditionalExp.
cfgFindChildIndex()
virtual unsigned int SgExpression::cfgFindChildIndex (SgNode * n) override virtual
Find the index of n in this node's CFG children.
Reimplemented from SgNode.
Reimplemented in SgCastExp, SgConditionalExp, SgNewExp, and SgDesignatedInitializer.
cfgFindNextChildIndex()
virtual unsigned int SgExpression::cfgFindNextChildIndex (SgNode * n) override virtual
Find the index just after n in this node's CFG children.
Reimplemented from SgNode.
cfgOutEdges()
virtual std::vector< VirtualCFG::CFGEdge > SgExpression::cfgOutEdges (unsigned int index) override virtual
Find the out edges of a CFG node – internal version.
Reimplemented from SgNode.
Reimplemented in SgUnaryOp, SgThrowOp, SgBinaryOp, SgAndOp, SgOrOp, SgExprListExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgFunctionCallExp, SgSizeOfOp, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgNullExpression, SgSubscriptExpression, SgAsteriskShapeExp, SgImpliedDo, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgPseudoDestructorRefExp, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgNoexceptOp, SgNonrealRefExp, and SgAdaAttributeExp.
cfgInEdges()
virtual std::vector< VirtualCFG::CFGEdge > SgExpression::cfgInEdges (unsigned int index) override virtual
Find the in edges of a CFG node – internal version.
Reimplemented from SgNode.
Reimplemented in SgUnaryOp, SgThrowOp, SgBinaryOp, SgAndOp, SgOrOp, SgExprListExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgFunctionCallExp, SgSizeOfOp, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgNullExpression, SgSubscriptExpression, SgAsteriskShapeExp, SgImpliedDo, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgPseudoDestructorRefExp, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgNoexceptOp, SgNonrealRefExp, and SgAdaAttributeExp.
isDefinable()
SgExpression::isDefinable (void) const virtual
For Fortran. When called from a node of any other language, behavior is undefined (see SageInterface::is_Fortran_language). Returns a bool value which is true if the current expression is "almost definable". "Almost definable" here means as defined by the Fortran standard (2.5.5), with the caveat that allocatable variables are always called an lvalue. The Fortran standard dictates that an allocatable variable which has not been allocated is not definable. In the general case, it cannot be statically determined whether an allocatable variable has been allocated or not. Note: constants in Fortran are not lvalues, while in C and C++ lvalues may be const.
Returns
Returns true if the current expression is almost definable.
Reimplemented in SgPointerAssignOp, SgVarRefExp, and SgCompoundLiteralExp.
isUsedAsDefinable()
SgExpression::isUsedAsDefinable (void) const virtual
For Fortran. When called from a node of any other language, behavior is undefined (see SageInterface::is_Fortran_language).
Returns a bool value which is true if the current expression is used as a definable value. That is, it is definable (assigned to).
Returns
Returns true if the current expression is used as a definable value.
isLValue()
SgExpression::isLValue (void) const virtual
For C and C++. When called from a node of any other language, behavior is undefined (see SageInterface::is_C*_language). Returns a bool value which is true if the current expression is an lvalue, as defined by the C++ standard.
Returns
Returns true if the current expression is an lvalue.
Reimplemented in SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgCastExp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgCommaOpExp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgCompoundAssignOp, SgVarRefExp, SgMemberFunctionRefExp, SgStringVal, SgFunctionCallExp, SgTypeIdOp, SgConditionalExp, SgAssignInitializer, SgAdaAncestorInitializer, SgCompoundLiteralExp, and SgAdaAttributeExp.
isUsedAsLValue()
SgExpression::isUsedAsLValue (void) const virtual
For C and C++. When called from a node of any other language, behavior is undefined (see SageInterface::is_C*_language).
Returns a bool value which is true if the current expression is used as an lvalue. That is, it is an lvalue and does not get converted to an rvalue by its parent expression.
Returns
Returns true if the current expression is used as an lvalue.
isChildUsedAsLValue()
SgExpression::isChildUsedAsLValue (const SgExpression * child) const virtual
For C and C++. When called from a node of any other language, behavior is undefined (see SageInterface::is_C*_language).
Returns a bool value which is true if the specified expression is used as an lvalue. That is, it is an lvalue and does not get converted to an rvalue by its parent expression.
Reimplemented in SgAdaAncestorInitializer, SgAdaAttributeExp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgCastExp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgCommaOpExp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgCompoundAssignOp, SgExprListExp, SgVarRefExp, SgMemberFunctionRefExp, SgStringVal, SgFunctionCallExp, SgTypeIdOp, SgConditionalExp, SgAssignInitializer, and SgCompoundLiteralExp.
get_file_info()
virtual Sg_File_Info * SgExpression::get_file_info (void) const override virtual
Interface function to implement original SAGE interface to SgFile_Info objects.
This function is added explicitly to provide the older interface to the file_info pointer which has been removed and replaced with two Sg_File_Info pointers to mark the start and end of the located node object (previously we only stored the starting location). This function still returns the starting location of the construct.
Reimplemented from SgLocatedNode.
Referenced by SageInterface::findFirstSgCastExpMarkedAsTransformation(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::functionCallExpressionPreceedsDeclarationWhichAssociatesScope(), and SageInterface::normalizeArrowExpWithAddressOfLeftOperand().
set_file_info()
virtual void SgExpression::set_file_info (Sg_File_Info * X) override virtual
Access function calls set_startingConstruct(Sg_File_Info*) member function.
Reimplemented from SgLocatedNode.
fixupCopy_scopes()
virtual void SgExpression::fixupCopy_scopes (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
fixupCopy_symbols()
virtual void SgExpression::fixupCopy_symbols (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
fixupCopy_references()
virtual void SgExpression::fixupCopy_references (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
hasExplicitType()
bool SgExpression::hasExplicitType ()
Some expressions store internal SgType pointers explicitly while others compute them from other expressions. This function is true if it has a data member that is a type (pointer, array, etc.).
Result is true if it stores a type explicitly as a data member, else false.
Referenced by SageBuilder::errorCheckingTargetAST(), and SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst().
post_construction_initialization()
void SgExpression::post_construction_initialization () override virtual
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
Reimplemented from SgNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgMinusMinusOp, SgPlusPlusOp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgSubtractOp, SgMultiplyOp, SgIntegerDivideOp, SgModOp, SgOrOp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgJavaUnsignedRshiftOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgPlusAssignOp, SgMinusAssignOp, SgIorAssignOp, SgMultAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgStringVal, SgShortVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgLongDoubleVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgFloat80Val, SgFloat128Val, SgVoidVal, SgFunctionCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgNewExp, SgThisExp, SgRefExp, SgInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgLabelRefExp, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgLambdaRefExp, SgKeyDatumPair, SgListComprehension, SgSetComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgFoldExpression, SgJovialTablePresetExp, and SgJovialPresetPositionExp.
class_name()
virtual std::string SgExpression::class_name () const override virtual
returns a string representing the class name
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
Referenced by SageInterface::annotateExpressionsWithUniqueNames(), SageBuilder::appendTemplateArgumentsToName(), SageBuilder::buildTypeOfType(), SageInterface::checkForInitializers(), SageBuilder::fixupCopyOfNodeFromSeparateFileInNewTargetAst(), SageInterface::functionCallExpressionPreceedsDeclarationWhichAssociatesScope(), SageInterface::get_name(), SageInterface::getClassTypeChainForMemberReference(), SageInterface::getDeclarationOfNamedFunction(), SageInterface::isPrefixOperator(), and SageInterface::templateArgumentEquivalence().
variantT()
virtual VariantT SgExpression::variantT () const override virtual
returns new style SageIII enum values
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
Referenced by SageInterface::functionCallExpressionPreceedsDeclarationWhichAssociatesScope(), SageInterface::get_name(), SageInterface::getForLoopInformations(), SageInterface::isAssignmentStatement(), SageInterface::isCanonicalDoLoop(), SageInterface::isCanonicalForLoop(), SageInterface::isConstantFalse(), SageInterface::isConstantTrue(), SageInterface::normalizeForLoopIncrement(), SageInterface::normalizeForLoopTest(), SageInterface::replaceWithPattern(), and SageInterface::templateArgumentEquivalence().
operator delete()
void SgExpression::operator delete (void * pointer) inline
Definition at line 474702 of file Cxx_Grammar.h.
get_traversalSuccessorContainer()
virtual std::vector< SgNode * > SgExpression::get_traversalSuccessorContainer () override virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
get_traversalSuccessorNamesContainer()
virtual std::vector< std::string > SgExpression::get_traversalSuccessorNamesContainer () override virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
get_numberOfTraversalSuccessors()
virtual size_t SgExpression::get_numberOfTraversalSuccessors () override virtual
return number of children in the traversal successor list
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
get_traversalSuccessorByIndex()
virtual SgNode * SgExpression::get_traversalSuccessorByIndex (size_t idx) override virtual
index-based access to traversal successors by index number
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
get_childIndex()
virtual size_t SgExpression::get_childIndex (SgNode * child) override virtual
index-based access to traversal successors by child node
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
roseRTI()
virtual RTIReturnType SgExpression::roseRTI () override virtual
return C++ Runtime-Time-Information
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
sage_class_name()
virtual const char * SgExpression::sage_class_name () const override virtual
returns a C style string (char*) representing the class name
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
Referenced by SageInterface::getInitializerOfExpression().
accept()
virtual void SgExpression::accept (ROSE_VisitorPattern & visitor) override virtual
support for the classic visitor pattern done in GoF
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
isInMemoryPool()
virtual bool SgExpression::isInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
checkDataMemberPointersIfInMemoryPool()
virtual void SgExpression::checkDataMemberPointersIfInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
returnDataMemberPointers()
virtual std::vector< std::pair< SgNode *, std::string > > SgExpression::returnDataMemberPointers () const override virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
processDataMemberReferenceToPointers()
virtual void SgExpression::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
getChildIndex()
virtual long SgExpression::getChildIndex (SgNode * childNode) const override virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented from SgLocatedNode.
Reimplemented in SgUnaryOp, SgExpressionRoot, SgMinusOp, SgUnaryAddOp, SgNotOp, SgPointerDerefExp, SgAddressOfOp, SgMinusMinusOp, SgPlusPlusOp, SgBitComplementOp, SgCastExp, SgThrowOp, SgRealPartOp, SgImagPartOp, SgConjugateOp, SgUserDefinedUnaryOp, SgMatrixTransposeOp, SgAbsOp, SgBinaryOp, SgArrowExp, SgDotExp, SgDotStarOp, SgArrowStarOp, SgEqualityOp, SgLessThanOp, SgGreaterThanOp, SgNotEqualOp, SgLessOrEqualOp, SgGreaterOrEqualOp, SgAddOp, SgSubtractOp, SgMultiplyOp, SgDivideOp, SgIntegerDivideOp, SgModOp, SgAndOp, SgOrOp, SgBitXorOp, SgBitAndOp, SgBitOrOp, SgBitEqvOp, SgCommaOpExp, SgLshiftOp, SgRshiftOp, SgPntrArrRefExp, SgScopeOp, SgAssignOp, SgExponentiationOp, SgJavaUnsignedRshiftOp, SgConcatenationOp, SgPointerAssignOp, SgUserDefinedBinaryOp, SgCompoundAssignOp, SgPlusAssignOp, SgMinusAssignOp, SgAndAssignOp, SgIorAssignOp, SgMultAssignOp, SgDivAssignOp, SgModAssignOp, SgXorAssignOp, SgLshiftAssignOp, SgRshiftAssignOp, SgJavaUnsignedRshiftAssignOp, SgIntegerDivideAssignOp, SgExponentiationAssignOp, SgMembershipOp, SgSpaceshipOp, SgNonMembershipOp, SgIsOp, SgIsNotOp, SgDotDotExp, SgElementwiseOp, SgElementwiseMultiplyOp, SgElementwisePowerOp, SgElementwiseLeftDivideOp, SgElementwiseDivideOp, SgElementwiseAddOp, SgElementwiseSubtractOp, SgPowerOp, SgLeftDivideOp, SgRemOp, SgReplicationOp, SgAtOp, SgExprListExp, SgListExp, SgTupleExp, SgMatrixExp, SgVarRefExp, SgClassNameRefExp, SgFunctionRefExp, SgMemberFunctionRefExp, SgValueExp, SgBoolValExp, SgStringVal, SgShortVal, SgCharVal, SgUnsignedCharVal, SgWcharVal, SgUnsignedShortVal, SgIntVal, SgEnumVal, SgUnsignedIntVal, SgLongIntVal, SgLongLongIntVal, SgUnsignedLongLongIntVal, SgUnsignedLongVal, SgFloatVal, SgDoubleVal, SgLongDoubleVal, SgComplexVal, SgUpcThreads, SgUpcMythread, SgTemplateParameterVal, SgNullptrValExp, SgChar16Val, SgChar32Val, SgFloat80Val, SgFloat128Val, SgVoidVal, SgAdaFloatVal, SgCallExpression, SgFunctionCallExp, SgCudaKernelCallExp, SgSizeOfOp, SgUpcLocalsizeofExpression, SgUpcBlocksizeofExpression, SgUpcElemsizeofExpression, SgJavaInstanceOfOp, SgSuperExp, SgTypeIdOp, SgConditionalExp, SgNewExp, SgDeleteExp, SgThisExp, SgRefExp, SgInitializer, SgAggregateInitializer, SgCompoundInitializer, SgConstructorInitializer, SgAssignInitializer, SgDesignatedInitializer, SgBracedInitializer, SgAdaAncestorInitializer, SgVarArgStartOp, SgVarArgOp, SgVarArgEndOp, SgVarArgCopyOp, SgVarArgStartOneOperandOp, SgNullExpression, SgVariantExpression, SgSubscriptExpression, SgColonShapeExp, SgAsteriskShapeExp, SgImpliedDo, SgIOItemExpression, SgStatementExpression, SgAsmOp, SgLabelRefExp, SgActualArgumentExpression, SgUnknownArrayOrFunctionReference, SgPseudoDestructorRefExp, SgCAFCoExpression, SgCudaKernelExecConfig, SgLambdaRefExp, SgDictionaryExp, SgKeyDatumPair, SgComprehension, SgListComprehension, SgSetComprehension, SgDictionaryComprehension, SgNaryOp, SgNaryBooleanOp, SgNaryComparisonOp, SgStringConversion, SgYieldExpression, SgTemplateFunctionRefExp, SgTemplateMemberFunctionRefExp, SgAlignOfOp, SgRangeExp, SgMagicColonExp, SgTypeTraitBuiltinOperator, SgCompoundLiteralExp, SgJavaAnnotation, SgJavaMarkerAnnotation, SgJavaSingleMemberAnnotation, SgJavaNormalAnnotation, SgJavaTypeExpression, SgTypeExpression, SgClassExp, SgFunctionParameterRefExp, SgLambdaExp, SgHereExp, SgAtExp, SgFinishExp, SgNoexceptOp, SgNonrealRefExp, SgAdaTaskRefExp, SgAdaProtectedRefExp, SgFoldExpression, SgAwaitExpression, SgChooseExpression, SgAdaAttributeExp, SgJovialTablePresetExp, SgJovialPresetPositionExp, SgAdaOthersExp, SgAdaRenamingRefExp, and SgAdaUnitRefExp.
addRegExpAttribute()
SgExpression * SgExpression::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
get_need_paren()
SgExpression::get_need_paren (void) const
returns bool value if front-end considers parenthesis to be required.
This function returns a boolean value which is true if parenthesis are required for the proper eveluation of the current expression. The frontend is however overly conservative and introduces parenthesis too often. The value as determined by the frontend is saved in the SAGE III AST because it is sometimes required for more complex expressions and contructor calls with initializers. At present the unparser applies operator precedence rules to eliminate some of the redundent parenthesis within expressions (this makes the output more appealing).
Returns
Returns bool value (true if parenthesis are needed around the expression).
set_need_paren()
SgExpression::set_need_paren (bool need_paren)
This function allows the p_need_paren flag to be set (used internally).
This function is mostly used internally but would required for the construction of specific expression trees where the operator precedence would be insufficent to generate the correct code (which si the purpose of adding parenthesis in source code).
Parameters
need_paren - sets value of internal p_need_paren flag (true if parenthesis are needed around the expression).
Returns
Returns void.
Referenced by SageBuilder::buildAssignInitializer_nfi(), SageInterface::loopTiling(), SageInterface::loopUnrolling(), and SageInterface::replaceExpression().
get_lvalue()
SgExpression::get_lvalue (void) const
Returns a bool value if the current expression is assigned to.
Returns
Returns true if the current expression is assigned to.
Referenced by SageInterface::replaceExpression(), and SageInterface::setLoopLowerBound().
set_lvalue()
SgExpression::set_lvalue (bool lvalue)
This function allows the p_lvalue flag to be set (used internally).
This function is mostly used internally but would required for the construction of specific expression trees. In general it is set by the frontend, but not used elsewhere within SAGE III (will be tested in the future).
Parameters
lvalue - sets value of internal p_lvalue flag (true if the current is to be a left hand side value (lvalue)).
Returns
Returns void.
Referenced by SageBuilder::buildAssignStatement(), SageBuilder::buildAssignStatement_ast_translate(), SageInterface::createTempVariableForExpression(), SageInterface::replaceExpression(), SageInterface::replaceExpressionWithStatement(), and SageInterface::setLoopLowerBound().
Member Data Documentation
p_need_paren
SgExpression::p_need_paren protected
This boolean value marks the current expression as requiring parenthises.
This boolean value marks the current expression as requiring parenthises (the information comes from the frontend's interpretation of the requirement and is almost always overly conservative. The unparser currently backs out more accurate rules based on operator precedence and removed then where they are not truely required. Thus the purpose of this variable is to capture the interpritation of the frontend regarding the use of parenthesis.
Definition at line 475058 of file Cxx_Grammar.h.
p_lvalue
SgExpression::p_lvalue protected
This boolean variable marks the current expression as a left hand side value (lvalue).
Definition at line 475062 of file Cxx_Grammar.h.
p_global_qualified_name
bool SgExpression::p_global_qualified_name protected
Definition at line 475066 of file Cxx_Grammar.h.
p_operatorPosition
Sg_File_Info* SgExpression::p_operatorPosition protected
Definition at line 475070 of file Cxx_Grammar.h.
The documentation for this class was generated from the following files:
Cxx_Grammar.h
SgExpression.docs