ROSE: Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G > Class Template Reference
Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G > Class Template Reference
Description
template<class G>
class Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >
Base class for generating GraphViz output.
The G template parameter is the type of graph for which output is being generated. G must be a Sawyer::Container::Graph type.
Definition at line 141 of file GraphViz.h.
#include <Rose/BinaryAnalysis/Partitioner2/GraphViz.h>
Classes
struct PseudoEdge
Public Types
typedef G Graph
typedef std::vector< Organization > VertexOrganization
Organizational information for vertices.
typedef std::vector< Organization > EdgeOrganization
Organizational information for edges.
typedef Sawyer::Container::Map< std::string, Organization > SubgraphOrganization
Organizational information for subgraphs.
Public Member Functions
BaseEmitter ()
Default constructor.
BaseEmitter (const Graph &g)
Constructor.
void graph (const Graph &g)
Reset the graph.
void selectAll (bool b=true)
Causes all vertices and edges to be selected.
void selectNone ()
Deselects all vertices and edges.
void selectAllVertices (bool b=true)
Causes all vertices to be selected.
void selectAllEdges (bool b=true)
Causes all edges to be selected.
void deselectParallelEdges ()
Deselect all but one parallel edge.
virtual void emit (std::ostream &) const
Dump selected vertices, edges, and subgraphs.
Attributes & defaultGraphAttributes ()
Property: default graph attributes.
const Attributes & defaultGraphAttributes () const
Property: default graph attributes.
Attributes & defaultNodeAttributes ()
Property: default graph node attributes.
const Attributes & defaultNodeAttributes () const
Property: default graph node attributes.
Attributes & defaultEdgeAttributes ()
Property: default graph edge attributes.
const Attributes & defaultEdgeAttributes () const
Property: default graph edge attributes.
const Color::HSV & subgraphColor () const
Property: color to use for function subgraph background.
void subgraphColor (const Color::HSV &bg)
Property: color to use for function subgraph background.
const VertexOrganization & vertexOrganization () const
Property: Controls which vertices are to appear in the output, and how.
VertexOrganization & vertexOrganization ()
Property: Controls which vertices are to appear in the output, and how.
const Organization & vertexOrganization (size_t vertexId) const
Property: Controls which vertices are to appear in the output, and how.
Organization & vertexOrganization (size_t vertexId)
Property: Controls which vertices are to appear in the output, and how.
const Organization & vertexOrganization (const typename G::ConstVertexIterator &vertex) const
Property: Controls which vertices are to appear in the output, and how.
const Organization & vertexOrganization (const typename G::Vertex &vertex) const
Property: Controls which vertices are to appear in the output, and how.
Organization & vertexOrganization (const typename G::ConstVertexIterator &vertex)
Property: Controls which vertices are to appear in the output, and how.
Organization & vertexOrganization (const typename G::Vertex &vertex)
Property: Controls which vertices are to appear in the output, and how.
const EdgeOrganization & edgeOrganization () const
Property: Controls which edges are to appear in the output, and how.
EdgeOrganization & edgeOrganization ()
Property: Controls which edges are to appear in the output, and how.
const Organization & edgeOrganization (size_t edgeId) const
Property: Controls which edges are to appear in the output, and how.
Organization & edgeOrganization (size_t edgeId)
Property: Controls which edges are to appear in the output, and how.
const Organization & edgeOrganization (const typename G::ConstEdgeIterator &edge) const
Property: Controls which edges are to appear in the output, and how.
const Organization & edgeOrganization (const typename G::Edge &edge) const
Property: Controls which edges are to appear in the output, and how.
Organization & edgeOrganization (const typename G::ConstEdgeIterator &edge)
Property: Controls which edges are to appear in the output, and how.
Organization & edgeOrganization (const typename G::Edge &edge)
Property: Controls which edges are to appear in the output, and how.
const SubgraphOrganization & subgraphOrganization () const
Property: Controls which subgraphs appear in the output, and how.
SubgraphOrganization & subgraphOrganization ()
Property: Controls which subgraphs appear in the output, and how.
const Organization & subgraphOrganization (const std::string &name) const
Property: Controls which subgraphs appear in the output, and how.
Organization & subgraphOrganization (const std::string &name)
Property: Controls which subgraphs appear in the output, and how.
Protected Types
typedef Sawyer::Container::Map< size_t, size_t > VMap
Protected Member Functions
size_t emitVertex (std::ostream &, const typename G::ConstVertexIterator &, const Organization &, const VMap &) const
Emit a single vertex if it hasn't been emitted already.
void emitEdge (std::ostream &, const typename G::ConstEdgeIterator &, const Organization &, const VMap &) const
Emit a single edge.
Protected Attributes
Graph graph_
VertexOrganization vertexOrganization_
EdgeOrganization edgeOrganization_
SubgraphOrganization subgraphOrganization_
Attributes defaultGraphAttributes_
Attributes defaultNodeAttributes_
Attributes defaultEdgeAttributes_
std::list< PseudoEdge > pseudoEdges_
Color::HSV subgraphColor_
Member Typedef Documentation
Graph
template<class G > typedef G Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::Graph
Definition at line 143 of file GraphViz.h.
VertexOrganization
template<class G > typedef std::vector<Organization> Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::VertexOrganization
Organizational information for vertices.
Definition at line 146 of file GraphViz.h.
EdgeOrganization
template<class G > typedef std::vector<Organization> Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::EdgeOrganization
Organizational information for edges.
Definition at line 149 of file GraphViz.h.
SubgraphOrganization
template<class G > typedef Sawyer::Container::Map<std::string, Organization> Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::SubgraphOrganization
Organizational information for subgraphs.
Definition at line 152 of file GraphViz.h.
VMap
template<class G > typedef Sawyer::Container::Map<size_t, size_t> Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::VMap protected
Definition at line 164 of file GraphViz.h.
Constructor & Destructor Documentation
BaseEmitter() [1/2]
template<class G > Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::BaseEmitter () inline
Default constructor.
Construct a GraphViz emitter having an empty graph. The graph method can be called to give the emitter a new graph later.
Definition at line 182 of file GraphViz.h.
BaseEmitter() [2/2]
template<class G > Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::BaseEmitter (const Graph & g) inline explicit
Constructor.
Construct a generator for the specified graph. The graph is copied into this generator.
Definition at line 187 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::graph().
Member Function Documentation
graph()
template<class G > void Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::graph (const Graph & g) inline
Reset the graph.
Definition at line 193 of file GraphViz.h.
References Sawyer::Container::Map< K, T, Cmp, Alloc >::clear().
Referenced by Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::BaseEmitter().
defaultGraphAttributes() [1/2]
template<class G > Attributes & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::defaultGraphAttributes () inline
Property: default graph attributes.
Attributes that should apply to the graph as a whole.
Definition at line 208 of file GraphViz.h.
defaultGraphAttributes() [2/2]
template<class G > const Attributes & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::defaultGraphAttributes () const inline
Property: default graph attributes.
Attributes that should apply to the graph as a whole.
Definition at line 211 of file GraphViz.h.
defaultNodeAttributes() [1/2]
template<class G > Attributes & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::defaultNodeAttributes () inline
Property: default graph node attributes.
Attributes that should apply to all graph nodes.
Definition at line 221 of file GraphViz.h.
defaultNodeAttributes() [2/2]
template<class G > const Attributes & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::defaultNodeAttributes () const inline
Property: default graph node attributes.
Attributes that should apply to all graph nodes.
Definition at line 224 of file GraphViz.h.
defaultEdgeAttributes() [1/2]
template<class G > Attributes & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::defaultEdgeAttributes () inline
Property: default graph edge attributes.
Attributes that should apply to all graph edges.
Definition at line 234 of file GraphViz.h.
defaultEdgeAttributes() [2/2]
template<class G > const Attributes & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::defaultEdgeAttributes () const inline
Property: default graph edge attributes.
Attributes that should apply to all graph edges.
Definition at line 237 of file GraphViz.h.
subgraphColor() [1/2]
template<class G > const Color::HSV & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::subgraphColor () const inline
Property: color to use for function subgraph background.
Definition at line 245 of file GraphViz.h.
subgraphColor() [2/2]
template<class G > void Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::subgraphColor (const Color::HSV & bg) inline
Property: color to use for function subgraph background.
Definition at line 246 of file GraphViz.h.
vertexOrganization() [1/8]
template<class G > const VertexOrganization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization () const inline
Property: Controls which vertices are to appear in the output, and how.
Each vertex of the graph has an entry in this table, and the entry describes such things as whether the vertex will be present in the GraphViz file, which subgraph (if any) it will belong to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 259 of file GraphViz.h.
Referenced by Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization(), Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization(), Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization().
vertexOrganization() [2/8]
template<class G > VertexOrganization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization () inline
Property: Controls which vertices are to appear in the output, and how.
Each vertex of the graph has an entry in this table, and the entry describes such things as whether the vertex will be present in the GraphViz file, which subgraph (if any) it will belong to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 262 of file GraphViz.h.
vertexOrganization() [3/8]
template<class G > const Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization (size_t vertexId) const inline
Property: Controls which vertices are to appear in the output, and how.
Each vertex of the graph has an entry in this table, and the entry describes such things as whether the vertex will be present in the GraphViz file, which subgraph (if any) it will belong to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 265 of file GraphViz.h.
vertexOrganization() [4/8]
template<class G > Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization (size_t vertexId) inline
Property: Controls which vertices are to appear in the output, and how.
Each vertex of the graph has an entry in this table, and the entry describes such things as whether the vertex will be present in the GraphViz file, which subgraph (if any) it will belong to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 269 of file GraphViz.h.
vertexOrganization() [5/8]
template<class G > const Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization (const typename G::ConstVertexIterator & vertex) const inline
Property: Controls which vertices are to appear in the output, and how.
Each vertex of the graph has an entry in this table, and the entry describes such things as whether the vertex will be present in the GraphViz file, which subgraph (if any) it will belong to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 273 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization().
vertexOrganization() [6/8]
template<class G > const Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization (const typename G::Vertex & vertex) const inline
Property: Controls which vertices are to appear in the output, and how.
Each vertex of the graph has an entry in this table, and the entry describes such things as whether the vertex will be present in the GraphViz file, which subgraph (if any) it will belong to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 276 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization().
vertexOrganization() [7/8]
template<class G > Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization (const typename G::ConstVertexIterator & vertex) inline
Property: Controls which vertices are to appear in the output, and how.
Each vertex of the graph has an entry in this table, and the entry describes such things as whether the vertex will be present in the GraphViz file, which subgraph (if any) it will belong to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 279 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization().
vertexOrganization() [8/8]
template<class G > Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization (const typename G::Vertex & vertex) inline
Property: Controls which vertices are to appear in the output, and how.
Each vertex of the graph has an entry in this table, and the entry describes such things as whether the vertex will be present in the GraphViz file, which subgraph (if any) it will belong to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 282 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization().
edgeOrganization() [1/8]
template<class G > const EdgeOrganization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization () const inline
Property: Controls which edges are to appear in the output, and how.
Each edge of the CFG has an entry in this table, and the entry describes such things as whether the edge will be present in the GraphViz file, which subgraph (if any) it belongs to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 297 of file GraphViz.h.
Referenced by Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization(), Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization(), Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization().
edgeOrganization() [2/8]
template<class G > EdgeOrganization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization () inline
Property: Controls which edges are to appear in the output, and how.
Each edge of the CFG has an entry in this table, and the entry describes such things as whether the edge will be present in the GraphViz file, which subgraph (if any) it belongs to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 300 of file GraphViz.h.
edgeOrganization() [3/8]
template<class G > const Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization (size_t edgeId) const inline
Property: Controls which edges are to appear in the output, and how.
Each edge of the CFG has an entry in this table, and the entry describes such things as whether the edge will be present in the GraphViz file, which subgraph (if any) it belongs to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 303 of file GraphViz.h.
edgeOrganization() [4/8]
template<class G > Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization (size_t edgeId) inline
Property: Controls which edges are to appear in the output, and how.
Each edge of the CFG has an entry in this table, and the entry describes such things as whether the edge will be present in the GraphViz file, which subgraph (if any) it belongs to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 307 of file GraphViz.h.
edgeOrganization() [5/8]
template<class G > const Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization (const typename G::ConstEdgeIterator & edge) const inline
Property: Controls which edges are to appear in the output, and how.
Each edge of the CFG has an entry in this table, and the entry describes such things as whether the edge will be present in the GraphViz file, which subgraph (if any) it belongs to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 311 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization().
edgeOrganization() [6/8]
template<class G > const Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization (const typename G::Edge & edge) const inline
Property: Controls which edges are to appear in the output, and how.
Each edge of the CFG has an entry in this table, and the entry describes such things as whether the edge will be present in the GraphViz file, which subgraph (if any) it belongs to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 314 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization().
edgeOrganization() [7/8]
template<class G > Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization (const typename G::ConstEdgeIterator & edge) inline
Property: Controls which edges are to appear in the output, and how.
Each edge of the CFG has an entry in this table, and the entry describes such things as whether the edge will be present in the GraphViz file, which subgraph (if any) it belongs to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 317 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization().
edgeOrganization() [8/8]
template<class G > Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization (const typename G::Edge & edge) inline
Property: Controls which edges are to appear in the output, and how.
Each edge of the CFG has an entry in this table, and the entry describes such things as whether the edge will be present in the GraphViz file, which subgraph (if any) it belongs to, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 320 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization().
subgraphOrganization() [1/4]
template<class G > const SubgraphOrganization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::subgraphOrganization () const inline
Property: Controls which subgraphs appear in the output, and how.
Each subgraph has a distinct name consisting of only letters, numbers, and underscores. The table contains information about whether the subgraph is selected for output, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 335 of file GraphViz.h.
subgraphOrganization() [2/4]
template<class G > SubgraphOrganization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::subgraphOrganization () inline
Property: Controls which subgraphs appear in the output, and how.
Each subgraph has a distinct name consisting of only letters, numbers, and underscores. The table contains information about whether the subgraph is selected for output, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 338 of file GraphViz.h.
subgraphOrganization() [3/4]
template<class G > const Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::subgraphOrganization (const std::string & name) const inline
Property: Controls which subgraphs appear in the output, and how.
Each subgraph has a distinct name consisting of only letters, numbers, and underscores. The table contains information about whether the subgraph is selected for output, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 341 of file GraphViz.h.
References Sawyer::Container::Map< K, T, Cmp, Alloc >::getOrDefault().
subgraphOrganization() [4/4]
template<class G > Organization & Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::subgraphOrganization (const std::string & name) inline
Property: Controls which subgraphs appear in the output, and how.
Each subgraph has a distinct name consisting of only letters, numbers, and underscores. The table contains information about whether the subgraph is selected for output, its label, and other attributes.
Most GraphViz-emitting methods modify this information and then call the basic emit method. In general, if the user supplies a label or attribute prior to such calls then that information is used instead of calculating new information.
Definition at line 344 of file GraphViz.h.
References Sawyer::Container::Map< K, T, Cmp, Alloc >::insertMaybeDefault().
selectAll()
template<class G > void Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectAll (bool b = true) inline
Causes all vertices and edges to be selected.
Causes all vertices and edges to be selected as the core part of the graph. If b is false then all vertices and edges are deselected instead.
Definition at line 353 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectAllEdges(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectAllVertices().
selectNone()
template<class G > void Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectNone () inline
Deselects all vertices and edges.
Definition at line 359 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectAllEdges(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectAllVertices().
selectAllVertices()
template<class G > void Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectAllVertices (bool b = true) inline
Causes all vertices to be selected.
Causes all vertices to be selected as the core part of the graph. If b is false then all vertices are deselected instead.
Definition at line 369 of file GraphViz.h.
Referenced by Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectAll(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectNone().
selectAllEdges()
template<class G > void Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectAllEdges (bool b = true) inline
Causes all edges to be selected.
Causes all edges to be selected as the core part of the graph. If b is false then all edges are deselected instead.
Definition at line 378 of file GraphViz.h.
Referenced by Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectAll(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::selectNone().
deselectParallelEdges()
template<class G > void Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::deselectParallelEdges ()
Deselect all but one parallel edge.
For parallel edges between a pair of vertices, all but one is deselected. Which one remains selected is arbitrary.
Definition at line 995 of file GraphViz.h.
emit()
template<class G > void Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emit (std::ostream & out) const virtual
Dump selected vertices, edges, and subgraphs.
This is the most basic emitter that produces an entire GraphViz file. The graph will contain the selected vertices and edges organized into subgraphs according to the vertex, edge, and subgraph organization information.
Definition at line 927 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::escape(), Sawyer::Container::Map< K, T, Cmp, Alloc >::exists(), Sawyer::Container::Map< K, T, Cmp, Alloc >::insert(), Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::isSelected(), Rose::StringUtility::numberToString(), Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::subgraph(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::toString().
emitVertex()
template<class G > size_t Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emitVertex (std::ostream & out, const typename G::ConstVertexIterator & vertex, const Organization & org, const VMap & vmap) const protected
Emit a single vertex if it hasn't been emitted already.
In any case, returns the GraphViz ID number for the vertex.
Definition at line 891 of file GraphViz.h.
References Sawyer::Optional< T >::assignTo(), Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::attributes(), Sawyer::Container::Map< K, T, Cmp, Alloc >::getOptional(), Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::isSelected(), Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::label(), Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::name(), Rose::BinaryAnalysis::Partitioner2::GraphViz::NO_ID, Rose::StringUtility::numberToString(), Sawyer::Container::Map< K, T, Cmp, Alloc >::size(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::toString().
emitEdge()
template<class G > void Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emitEdge (std::ostream & out, const typename G::ConstEdgeIterator & edge, const Organization & org, const VMap & vmap) const protected
Emit a single edge.
The vertices must have been emitted already.
Definition at line 907 of file GraphViz.h.
References Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::attributes(), Sawyer::Container::Map< K, T, Cmp, Alloc >::exists(), Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::label(), Rose::StringUtility::numberToString(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::toString().
Member Data Documentation
graph_
template<class G > Graph Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::graph_ protected
Definition at line 167 of file GraphViz.h.
vertexOrganization_
template<class G > VertexOrganization Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::vertexOrganization_ protected
Definition at line 168 of file GraphViz.h.
edgeOrganization_
template<class G > EdgeOrganization Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::edgeOrganization_ protected
Definition at line 169 of file GraphViz.h.
subgraphOrganization_
template<class G > SubgraphOrganization Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::subgraphOrganization_ protected
Definition at line 170 of file GraphViz.h.
defaultGraphAttributes_
template<class G > Attributes Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::defaultGraphAttributes_ protected
Definition at line 171 of file GraphViz.h.
defaultNodeAttributes_
template<class G > Attributes Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::defaultNodeAttributes_ protected
Definition at line 172 of file GraphViz.h.
defaultEdgeAttributes_
template<class G > Attributes Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::defaultEdgeAttributes_ protected
Definition at line 173 of file GraphViz.h.
pseudoEdges_
template<class G > std::list<PseudoEdge> Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::pseudoEdges_ protected
Definition at line 174 of file GraphViz.h.
subgraphColor_
template<class G > Color::HSV Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::subgraphColor_ protected
Definition at line 175 of file GraphViz.h.
The documentation for this class was generated from the following file:
GraphViz.h