ROSE: Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization Class Reference
Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization Class Reference
Description
Organizational information.
The organization determines which vertices, edges, and subgraphs are selected for output and also gives them labels and attributes. Generally speaking, the GraphViz object will update labels and attributes automatically only when transitioning from an unselected to selected state.
Definition at line 64 of file GraphViz.h.
#include <Rose/BinaryAnalysis/Partitioner2/GraphViz.h>
Public Member Functions
Organization ()
Default constructor.
void select (bool b=true)
Select or deselect object.
bool isSelected () const
Determines whether an object is selected.
const std::string & name () const
Name for object.
void name (const std::string &s)
Name for object.
const std::string & label () const
Label for object.
void label (const std::string &s)
Label for object.
const Attributes & attributes () const
Attributes for object.
Attributes & attributes ()
Attributes for object.
void attributes (const Attributes &a)
Attributes for object.
const std::string & subgraph () const
Subgraph for object.
void subgraph (const std::string &s)
Subgraph for object.
Constructor & Destructor Documentation
Organization()
Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::Organization () inline
Default constructor.
Constructs an organization that selects the object (vertex, edge, or subgraph) and gives it an empty label and no attributes.
Definition at line 76 of file GraphViz.h.
Member Function Documentation
select()
void Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::select (bool b = true) inline
Select or deselect object.
Definition at line 79 of file GraphViz.h.
isSelected()
bool Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::isSelected () const inline
Determines whether an object is selected.
An object that is not selected will not appear in the output, and objects that are selected may appear in the output. Being selected is not sufficient to appear in the output. For instance, a selected edge will only appear if both incident vertices are also selected, and a selected subgraph will appear only if it has at least one selected vertex.
Definition at line 87 of file GraphViz.h.
Referenced by Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emit(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emitVertex().
name() [1/2]
const std::string & Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::name () const inline
Name for object.
This is the name used by GraphViz to denote this object. If the name is empty, then an ID number is used instead.
Definition at line 94 of file GraphViz.h.
Referenced by Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emitVertex().
name() [2/2]
void Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::name (const std::string & s) inline
Name for object.
This is the name used by GraphViz to denote this object. If the name is empty, then an ID number is used instead.
Definition at line 95 of file GraphViz.h.
label() [1/2]
const std::string & Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::label () const inline
Label for object.
The object label should either be empty, or must be a properly delimited and escaped value for the GraphViz language. The accessor will always return a properly-delimited string if the value is empty.
Definition at line 104 of file GraphViz.h.
Referenced by Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emitEdge(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emitVertex().
label() [2/2]
void Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::label (const std::string & s) inline
Label for object.
The object label should either be empty, or must be a properly delimited and escaped value for the GraphViz language. The accessor will always return a properly-delimited string if the value is empty.
Definition at line 108 of file GraphViz.h.
attributes() [1/3]
const Attributes & Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::attributes () const inline
Attributes for object.
Attributes are name/value pairs defined by the GraphViz language.
Definition at line 116 of file GraphViz.h.
Referenced by Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emitEdge(), and Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emitVertex().
attributes() [2/3]
Attributes & Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::attributes () inline
Attributes for object.
Attributes are name/value pairs defined by the GraphViz language.
Definition at line 117 of file GraphViz.h.
attributes() [3/3]
void Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::attributes (const Attributes & a) inline
Attributes for object.
Attributes are name/value pairs defined by the GraphViz language.
Definition at line 118 of file GraphViz.h.
subgraph() [1/2]
const std::string & Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::subgraph () const inline
Subgraph for object.
A vertex may belong to a subgraph. Subgraphs have names that must be valid GraphViz identifiers without the "cluster_" prefix. An empty name means no subgraph.
Definition at line 127 of file GraphViz.h.
Referenced by Rose::BinaryAnalysis::Partitioner2::GraphViz::BaseEmitter< G >::emit().
subgraph() [2/2]
void Rose::BinaryAnalysis::Partitioner2::GraphViz::Organization::subgraph (const std::string & s) inline
Subgraph for object.
A vertex may belong to a subgraph. Subgraphs have names that must be valid GraphViz identifiers without the "cluster_" prefix. An empty name means no subgraph.
Definition at line 128 of file GraphViz.h.
The documentation for this class was generated from the following file:
GraphViz.h