ROSE: Rose::BinaryAnalysis::Partitioner2::Trigger Class Reference
Rose::BinaryAnalysis::Partitioner2::Trigger Class Reference
Description
Trigger based on number of times called.
Definition at line 206 of file BinaryAnalysis/Partitioner2/Utility.h.
#include <Rose/BinaryAnalysis/Partitioner2/Utility.h>
Classes
struct Settings
Public Types
typedef AddressInterval SizeInterval
Public Member Functions
Trigger ()
Trigger armed for single call.
Trigger (const Settings &settings)
Armed for triggering when number of calls falls within when.
Trigger (size_t nSkip, size_t nTimes)
Armed for triggering after nSkip calls but not more than nTimes times.
bool isArmed () const
True if trigger is armed.
bool shouldTrigger ()
Increment calls and return true if triggering.
size_t nCalls () const
Number of times called.
void reset ()
Reset number of calls to zero.
Static Public Member Functions
static Trigger once ()
Armed for one call.
static Trigger always ()
Armed to always trigger.
static Trigger never ()
Armed to never trigger.
static Sawyer::CommandLine::SwitchGroup switches (Settings &)
Command-line switches to initialize settings.
static std::string docString ()
Documentation for command-line switches.
Member Typedef Documentation
SizeInterval
typedef AddressInterval Rose::BinaryAnalysis::Partitioner2::Trigger::SizeInterval
Definition at line 208 of file BinaryAnalysis/Partitioner2/Utility.h.
Constructor & Destructor Documentation
Trigger() [1/3]
Rose::BinaryAnalysis::Partitioner2::Trigger::Trigger () inline
Trigger armed for single call.
Definition at line 218 of file BinaryAnalysis/Partitioner2/Utility.h.
Referenced by always(), never(), and once().
Trigger() [2/3]
Rose::BinaryAnalysis::Partitioner2::Trigger::Trigger (const Settings & settings) inline explicit
Armed for triggering when number of calls falls within when.
Definition at line 221 of file BinaryAnalysis/Partitioner2/Utility.h.
Trigger() [3/3]
Rose::BinaryAnalysis::Partitioner2::Trigger::Trigger (size_t nSkip, size_t nTimes) inline
Armed for triggering after nSkip calls but not more than nTimes times.
Definition at line 224 of file BinaryAnalysis/Partitioner2/Utility.h.
References Sawyer::Container::Interval< Address >::baseSize().
Member Function Documentation
once()
static Trigger Rose::BinaryAnalysis::Partitioner2::Trigger::once () inline static
Armed for one call.
Definition at line 229 of file BinaryAnalysis/Partitioner2/Utility.h.
References Trigger().
always()
static Trigger Rose::BinaryAnalysis::Partitioner2::Trigger::always () inline static
Armed to always trigger.
Definition at line 232 of file BinaryAnalysis/Partitioner2/Utility.h.
References Trigger().
never()
static Trigger Rose::BinaryAnalysis::Partitioner2::Trigger::never () inline static
Armed to never trigger.
Definition at line 235 of file BinaryAnalysis/Partitioner2/Utility.h.
References Trigger().
isArmed()
bool Rose::BinaryAnalysis::Partitioner2::Trigger::isArmed () const inline
True if trigger is armed.
Definition at line 238 of file BinaryAnalysis/Partitioner2/Utility.h.
References Sawyer::Container::Interval< T >::greatest(), and Sawyer::Container::Interval< T >::isEmpty().
shouldTrigger()
bool Rose::BinaryAnalysis::Partitioner2::Trigger::shouldTrigger () inline
Increment calls and return true if triggering.
Definition at line 241 of file BinaryAnalysis/Partitioner2/Utility.h.
References Sawyer::Container::Interval< T >::contains().
nCalls()
size_t Rose::BinaryAnalysis::Partitioner2::Trigger::nCalls () const inline
Number of times called.
Definition at line 244 of file BinaryAnalysis/Partitioner2/Utility.h.
reset()
void Rose::BinaryAnalysis::Partitioner2::Trigger::reset () inline
Reset number of calls to zero.
Definition at line 247 of file BinaryAnalysis/Partitioner2/Utility.h.
The documentation for this class was generated from the following file:
BinaryAnalysis/Partitioner2/Utility.h