ROSE: Sawyer::Container::GraphBimapIndex< VertexOrEdgeKey, VertexOrEdgeConstIterator > Class Template Reference
Sawyer::Container::GraphBimapIndex< VertexOrEdgeKey, VertexOrEdgeConstIterator > Class Template Reference
Description
template<class VertexOrEdgeKey, class VertexOrEdgeConstIterator>
class Sawyer::Container::GraphBimapIndex< VertexOrEdgeKey, VertexOrEdgeConstIterator >
Map based index is the default index type when indexes are present.
This index has O(log N) insert, erase, and lookup times. The key type must have a less-than operator.
The semantics for the methods of this class are documented in the GraphVoidIndex class.
Definition at line 153 of file Graph.h.
#include <Sawyer/Graph.h>
Public Member Functions
void clear ()
Erase all data from this index.
void insert (const VertexOrEdgeKey &key, const VertexOrEdgeConstIterator &iter)
Insert a new element into the map.
void erase (const VertexOrEdgeKey &key)
Erase an element from the map.
Optional< VertexOrEdgeConstIterator > lookup (const VertexOrEdgeKey &key) const
Lookup iterator for vertex or edge key.
Member Function Documentation
clear()
template<class VertexOrEdgeKey , class VertexOrEdgeConstIterator > void Sawyer::Container::GraphBimapIndex< VertexOrEdgeKey, VertexOrEdgeConstIterator >::clear () inline
Erase all data from this index.
See GraphVoidIndex::clear.
Definition at line 159 of file Graph.h.
References Sawyer::Container::Map< K, T, Cmp, Alloc >::clear().
insert()
template<class VertexOrEdgeKey , class VertexOrEdgeConstIterator > void Sawyer::Container::GraphBimapIndex< VertexOrEdgeKey, VertexOrEdgeConstIterator >::insert (const VertexOrEdgeKey & key, const VertexOrEdgeConstIterator & iter) inline
Insert a new element into the map.
See GraphVoidIndex::insert.
Definition at line 166 of file Graph.h.
References Sawyer::Container::Map< K, T, Cmp, Alloc >::insert().
erase()
template<class VertexOrEdgeKey , class VertexOrEdgeConstIterator > void Sawyer::Container::GraphBimapIndex< VertexOrEdgeKey, VertexOrEdgeConstIterator >::erase (const VertexOrEdgeKey & key) inline
Erase an element from the map.
See GraphVoidIndex::erase.
Definition at line 173 of file Graph.h.
References Sawyer::Container::Map< K, T, Cmp, Alloc >::erase().
lookup()
template<class VertexOrEdgeKey , class VertexOrEdgeConstIterator > Optional< VertexOrEdgeConstIterator > Sawyer::Container::GraphBimapIndex< VertexOrEdgeKey, VertexOrEdgeConstIterator >::lookup (const VertexOrEdgeKey & key) const inline
Lookup iterator for vertex or edge key.
See GraphVoidIndex::lookup.
Definition at line 180 of file Graph.h.
References Sawyer::Container::Map< K, T, Cmp, Alloc >::getOptional().
The documentation for this class was generated from the following file:
Graph.h