ROSE: Sawyer::Container::AddressMapConstraints< AddressMap > Class Template Reference
Sawyer::Container::AddressMapConstraints< AddressMap > Class Template Reference
Description
template<typename AddressMap>
class Sawyer::Container::AddressMapConstraints< AddressMap >
Constraints are used to select addresses from a memory map.
Users don't normally see this class since it's almost always created as a temporary. In fact, most of the public methods in this class are also present in the AddressMap class, and that's where they're documented.
The purpose of this class is to curry the arguments that would otherwise need to be passed to the various map I/O methods and which would significantly complicate the API since many of these arguments are optional.
Definition at line 76 of file AddressMap.h.
#include <Sawyer/AddressMap.h>
Public Types
typedef AddressMap::Address Address
typedef AddressMap::Value Value
typedef Sawyer::Container::Interval< Address > AddressInterval
Public Member Functions
AddressMapConstraints (AddressMap *map)
Construct a constraint that matches everything.
operator AddressMapConstraints< const AddressMap > () const
void print (std::ostream &out) const
Print constraints in a human readable form.
AddressMapConstraints require (unsigned bits) const
Require certain access permissions.
AddressMapConstraints prohibit (unsigned bits) const
Prohibit certain access permissions.
AddressMapConstraints access (unsigned bits) const
Require and prohibit certain access permissions.
AddressMapConstraints substr (const std::string &s) const
Require certain segment names.
AddressMapConstraints any () const
No constraints.
AddressMapConstraints none () const
Constraints that match nothing.
AddressMapConstraints at (Address x) const
Anchor at a certain address.
AddressMapConstraints at (const Sawyer::Container::Interval< Address > &x) const
Anchor at a certain interval.
AddressMapConstraints limit (size_t x) const
Limit matching length.
AddressMapConstraints atOrAfter (Address least) const
Limit addresses.
AddressMapConstraints atOrBefore (Address greatest) const
Limit addresses.
AddressMapConstraints within (const Sawyer::Container::Interval< Address > &x) const
Limit addresses.
AddressMapConstraints within (Address lo, Address hi) const
Limit addresses.
AddressMapConstraints baseSize (Address base, Address size) const
Limit addresses.
AddressMapConstraints after (Address x) const
Limit addresses.
AddressMapConstraints before (Address x) const
Limit addreses.
AddressMapConstraints singleSegment () const
Limit matching to single segment.
AddressMapConstraints segmentPredicate (SegmentPredicate< Address, Value > *p) const
Limit segments.
AddressMapConstraints segmentPredicates (const Callbacks< SegmentPredicate< Address, Value > * > &predicates) const
unsigned required () const
Accessibility bits that are required to be set.
unsigned prohibited () const
Accessibility bits that are required to be clear.
const std::string & substr () const
Section name substring.
bool neverMatches () const
Returns true if the constraint is not allowed to match anything.
bool isAnchored () const
Determines whether constraints are anchored to an address.
AddressInterval anchored () const
Returns the anchor points.
size_t limit () const
Size limit.
const Optional< Address > & least () const
Least possible address.
const Optional< Address > & greatest () const
Greatest possible address.
bool isSingleSegment () const
Returns true if the single-segment constraint is set.
const Callbacks< SegmentPredicate< Address, Value > * > segmentPredicates () const
Returns the segment predicates.
AddressMap * map () const
Returns a pointer to the memory map for this constraint object.
bool hasNonAddressConstraints () const
Determines whether non-address constraints are present.
AddressMapConstraints addressConstraints () const
Construct new constraints from existing address constraints.
boost::iterator_range< typename AddressMapTraits< AddressMap >::NodeIterator > nodes (MatchFlags flags=0) const
boost::iterator_range< typename AddressMapTraits< AddressMap >::SegmentIterator > segments (MatchFlags flags=0) const
Optional< typename AddressMap::Address > next (MatchFlags flags=0) const
Sawyer::Container::Interval< Address > available (MatchFlags flags=0) const
bool exists (MatchFlags flags=0) const
AddressMapTraits< AddressMap >::NodeIterator findNode (MatchFlags flags=0) const
template<typename Functor >
void traverse (Functor &functor, MatchFlags flags=0) const
void traverse (typename AddressMap::Visitor &visitor, MatchFlags flags=0) const
Sawyer::Container::Interval< Address > read (typename AddressMap::Value *buf, MatchFlags flags=0) const
Sawyer::Container::Interval< Address > read (std::vector< typename AddressMap::Value > &buf, MatchFlags flags=0) const
Sawyer::Container::Interval< Address > write (const typename AddressMap::Value *buf, MatchFlags flags=0) const
Sawyer::Container::Interval< Address > write (const std::vector< typename AddressMap::Value > &buf, MatchFlags flags=0)
void prune (MatchFlags flags=0) const
void keep (MatchFlags flags=0) const
void changeAccess (unsigned requiredAccess, unsigned prohibitedAccess, MatchFlags flags=0) const
Member Typedef Documentation
Address
template<typename AddressMap > typedef AddressMap::Address Sawyer::Container::AddressMapConstraints< AddressMap >::Address
Definition at line 78 of file AddressMap.h.
Value
template<typename AddressMap > typedef AddressMap::Value Sawyer::Container::AddressMapConstraints< AddressMap >::Value
Definition at line 79 of file AddressMap.h.
AddressInterval
template<typename AddressMap > typedef Sawyer::Container::Interval<Address> Sawyer::Container::AddressMapConstraints< AddressMap >::AddressInterval
Definition at line 80 of file AddressMap.h.
Constructor & Destructor Documentation
AddressMapConstraints()
template<typename AddressMap > Sawyer::Container::AddressMapConstraints< AddressMap >::AddressMapConstraints (AddressMap * map) inline
Construct a constraint that matches everything.
Definition at line 97 of file AddressMap.h.
Member Function Documentation
operator AddressMapConstraints< const AddressMap >()
template<typename AddressMap > Sawyer::Container::AddressMapConstraints< AddressMap >::operator AddressMapConstraints< const AddressMap > () const inline
Definition at line 129 of file AddressMap.h.
print()
template<typename AddressMap > void Sawyer::Container::AddressMapConstraints< AddressMap >::print (std::ostream & out) const inline
Print constraints in a human readable form.
Definition at line 156 of file AddressMap.h.
References Sawyer::Container::BitVector::fromInteger(), Sawyer::Container::Interval< T >::greatest(), Sawyer::Container::Interval< T >::isEmpty(), Sawyer::Container::Interval< T >::least(), Sawyer::Container::AddressMapConstraints< AddressMap >::map(), and Sawyer::Container::BitVector::toHex().
require()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::require (unsigned bits) const inline
Require certain access permissions.
See AddressMap::require.
Definition at line 239 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::map().
Referenced by Sawyer::Container::AddressMapConstraints< AddressMap >::access(), Sawyer::Container::AddressMap< A, T >::require(), and Sawyer::Container::AddressMap< A, T >::require().
prohibit()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::prohibit (unsigned bits) const inline
Prohibit certain access permissions.
See AddressMap::prohibit.
Definition at line 246 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::map().
Referenced by Sawyer::Container::AddressMapConstraints< AddressMap >::access(), Sawyer::Container::AddressMap< A, T >::prohibit(), Sawyer::Container::AddressMap< A, T >::prohibit(), and Sawyer::Container::AddressMap< A, T >::write().
access()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::access (unsigned bits) const inline
Require and prohibit certain access permissions.
See AddressMap::access.
Definition at line 253 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::prohibit(), and Sawyer::Container::AddressMapConstraints< AddressMap >::require().
Referenced by Sawyer::Container::AddressMap< A, T >::access(), and Sawyer::Container::AddressMap< A, T >::access().
substr() [1/2]
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::substr (const std::string & s) const inline
Require certain segment names.
See AddressMap::substr.
Definition at line 258 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::map().
Referenced by Sawyer::Container::AddressMap< A, T >::substr(), and Sawyer::Container::AddressMap< A, T >::substr().
any()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::any () const inline
No constraints.
See AddressMap::any.
Definition at line 266 of file AddressMap.h.
none()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::none () const inline
Constraints that match nothing.
See AddressMap::none.
Definition at line 271 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::map().
Referenced by Sawyer::Container::AddressMapConstraints< AddressMap >::after(), Sawyer::Container::AddressMapConstraints< AddressMap >::baseSize(), Sawyer::Container::AddressMapConstraints< AddressMap >::before(), Sawyer::Container::AddressMap< A, T >::none(), Sawyer::Container::AddressMap< A, T >::none(), Sawyer::Container::AddressMapConstraints< AddressMap >::segmentPredicate(), Sawyer::Container::AddressMapConstraints< AddressMap >::within(), and Sawyer::Container::AddressMapConstraints< AddressMap >::within().
at() [1/2]
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::at (Address x) const inline
Anchor at a certain address.
See AddressMap::at.
Definition at line 278 of file AddressMap.h.
References Sawyer::Container::IntervalMap< I, T, Policy >::isEmpty(), Sawyer::Container::AddressMapConstraints< AddressMap >::map(), and Sawyer::Container::AddressMap< A, T >::none().
Referenced by Sawyer::Container::AddressMap< A, T >::at(), Sawyer::Container::AddressMap< A, T >::at(), Sawyer::Container::AddressMap< A, T >::at(), and Sawyer::Container::AddressMap< A, T >::at().
at() [2/2]
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::at (const Sawyer::Container::Interval< Address > & x) const inline
Anchor at a certain interval.
See AddressMap::at.
Definition at line 285 of file AddressMap.h.
References Sawyer::Container::AddressMap< A, T >::atOrAfter(), Sawyer::Container::Interval< T >::greatest(), Sawyer::Container::IntervalMap< I, T, Policy >::isEmpty(), Sawyer::Container::Interval< T >::least(), Sawyer::Container::AddressMapConstraints< AddressMap >::map(), and Sawyer::Container::AddressMap< A, T >::none().
limit() [1/2]
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::limit (size_t x) const inline
Limit matching length.
See AddressMap::limit.
Definition at line 292 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::map(), and Sawyer::Container::AddressMap< A, T >::none().
Referenced by Sawyer::Container::AddressMap< A, T >::findNode(), Sawyer::Container::AddressMap< A, T >::findNode(), Sawyer::Container::AddressMap< A, T >::limit(), Sawyer::Container::AddressMap< A, T >::limit(), Sawyer::Container::AddressMap< A, T >::next(), Sawyer::Container::AddressMap< A, T >::read(), and Sawyer::Container::AddressMap< A, T >::write().
atOrAfter()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::atOrAfter (Address least) const inline
Limit addresses.
See AddressMap::atOrAfter.
Definition at line 299 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::least(), Sawyer::Container::AddressMapConstraints< AddressMap >::map(), and Sawyer::Container::AddressMap< A, T >::none().
Referenced by Sawyer::Container::AddressMapConstraints< AddressMap >::after(), Sawyer::Container::AddressMap< A, T >::atOrAfter(), Sawyer::Container::AddressMap< A, T >::atOrAfter(), Sawyer::Container::AddressMapConstraints< AddressMap >::baseSize(), and Sawyer::Container::AddressMapConstraints< AddressMap >::within().
atOrBefore()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::atOrBefore (Address greatest) const inline
Limit addresses.
See AddressMap::atOrBefore.
Definition at line 312 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::greatest(), Sawyer::Container::AddressMapConstraints< AddressMap >::map(), and Sawyer::Container::AddressMap< A, T >::none().
Referenced by Sawyer::Container::AddressMap< A, T >::atOrBefore(), Sawyer::Container::AddressMap< A, T >::atOrBefore(), Sawyer::Container::AddressMapConstraints< AddressMap >::baseSize(), Sawyer::Container::AddressMapConstraints< AddressMap >::before(), and Sawyer::Container::AddressMapConstraints< AddressMap >::within().
within() [1/2]
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::within (const Sawyer::Container::Interval< Address > & x) const inline
Limit addresses.
See AddressMap::within.
Definition at line 325 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::atOrAfter(), Sawyer::Container::AddressMapConstraints< AddressMap >::atOrBefore(), Sawyer::Container::Interval< T >::greatest(), Sawyer::Container::Interval< T >::isEmpty(), Sawyer::Container::Interval< T >::least(), and Sawyer::Container::AddressMapConstraints< AddressMap >::none().
Referenced by Sawyer::Container::AddressMapConstraints< AddressMap >::within(), Sawyer::Container::AddressMap< A, T >::within(), Sawyer::Container::AddressMap< A, T >::within(), Sawyer::Container::AddressMap< A, T >::within(), and Sawyer::Container::AddressMap< A, T >::within().
within() [2/2]
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::within (Address lo, Address hi) const inline
Limit addresses.
See AddressMap::within.
Definition at line 330 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::none(), and Sawyer::Container::AddressMapConstraints< AddressMap >::within().
baseSize()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::baseSize (Address base, Address size) const inline
Limit addresses.
See AddressMap::baseSize.
Definition at line 335 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::atOrAfter(), Sawyer::Container::AddressMapConstraints< AddressMap >::atOrBefore(), and Sawyer::Container::AddressMapConstraints< AddressMap >::none().
Referenced by Sawyer::Container::AddressMap< A, T >::baseSize(), and Sawyer::Container::AddressMap< A, T >::baseSize().
after()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::after (Address x) const inline
Limit addresses.
See AddressMap::after.
Definition at line 340 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::atOrAfter(), and Sawyer::Container::AddressMapConstraints< AddressMap >::none().
Referenced by Sawyer::Container::AddressMap< A, T >::after(), and Sawyer::Container::AddressMap< A, T >::after().
before()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::before (Address x) const inline
Limit addreses.
See AddressMap::before.
Definition at line 345 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::atOrBefore(), and Sawyer::Container::AddressMapConstraints< AddressMap >::none().
Referenced by Sawyer::Container::AddressMap< A, T >::before(), and Sawyer::Container::AddressMap< A, T >::before().
singleSegment()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::singleSegment () const inline
Limit matching to single segment.
See AddressMap::singleSegment.
Definition at line 350 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::map().
Referenced by Sawyer::Container::AddressMap< A, T >::singleSegment(), and Sawyer::Container::AddressMap< A, T >::singleSegment().
segmentPredicate()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::segmentPredicate (SegmentPredicate< Address, Value > * p) const inline
Limit segments.
See AddressMap::segmentPredicate.
Definition at line 357 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::map(), and Sawyer::Container::AddressMapConstraints< AddressMap >::none().
Referenced by Sawyer::Container::AddressMap< A, T >::segmentPredicate(), and Sawyer::Container::AddressMap< A, T >::segmentPredicate().
segmentPredicates() [1/2]
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::segmentPredicates (const Callbacks< SegmentPredicate< Address, Value > * > & predicates) const inline
Definition at line 365 of file AddressMap.h.
required()
template<typename AddressMap > unsigned Sawyer::Container::AddressMapConstraints< AddressMap >::required () const inline
Accessibility bits that are required to be set.
Definition at line 375 of file AddressMap.h.
prohibited()
template<typename AddressMap > unsigned Sawyer::Container::AddressMapConstraints< AddressMap >::prohibited () const inline
Accessibility bits that are required to be clear.
Definition at line 380 of file AddressMap.h.
substr() [2/2]
template<typename AddressMap > const std::string & Sawyer::Container::AddressMapConstraints< AddressMap >::substr () const inline
Section name substring.
Returns the string that must be present as a substring in a section name.
Definition at line 385 of file AddressMap.h.
neverMatches()
template<typename AddressMap > bool Sawyer::Container::AddressMapConstraints< AddressMap >::neverMatches () const inline
Returns true if the constraint is not allowed to match anything.
This returns true if the none constraint is set, but it doesn't necessarily return true if a combination of other constraints results in something that cannot match.
Definition at line 392 of file AddressMap.h.
isAnchored()
template<typename AddressMap > bool Sawyer::Container::AddressMapConstraints< AddressMap >::isAnchored () const inline
Determines whether constraints are anchored to an address.
Definition at line 397 of file AddressMap.h.
Referenced by Sawyer::Container::AddressMapConstraints< AddressMap >::anchored().
anchored()
template<typename AddressMap > AddressInterval Sawyer::Container::AddressMapConstraints< AddressMap >::anchored () const inline
Returns the anchor points.
Returns the anchor points as an interval, where the anchor(s) is an endpoint of the returned interval. For instance, if the at method was called, then anchored will return a singleton interval whose value was the at argument. The return value will be an empty interval if mutually exclusive anchors are set. This method should not be called without first calling isAnchored.
Definition at line 405 of file AddressMap.h.
References Sawyer::Container::AddressMapConstraints< AddressMap >::isAnchored().
limit() [2/2]
template<typename AddressMap > size_t Sawyer::Container::AddressMapConstraints< AddressMap >::limit () const inline
Size limit.
Returns the size limit or the maximum possible size_t value if not limit is in effect.
Definition at line 411 of file AddressMap.h.
least()
template<typename AddressMap > const Optional< Address > & Sawyer::Container::AddressMapConstraints< AddressMap >::least () const inline
Least possible address.
Returns the least possible address or nothing. The least address is in effect for the atOrAfter constraint.
Definition at line 417 of file AddressMap.h.
Referenced by Sawyer::Container::AddressMapConstraints< AddressMap >::atOrAfter().
greatest()
template<typename AddressMap > const Optional< Address > & Sawyer::Container::AddressMapConstraints< AddressMap >::greatest () const inline
Greatest possible address.
Returns the greatest possible address or nothing. The greatest address is in effect for the atOrBefore constraint.
Definition at line 423 of file AddressMap.h.
Referenced by Sawyer::Container::AddressMapConstraints< AddressMap >::atOrBefore().
isSingleSegment()
template<typename AddressMap > bool Sawyer::Container::AddressMapConstraints< AddressMap >::isSingleSegment () const inline
Returns true if the single-segment constraint is set.
Definition at line 428 of file AddressMap.h.
segmentPredicates() [2/2]
template<typename AddressMap > const Callbacks< SegmentPredicate< Address, Value > * > Sawyer::Container::AddressMapConstraints< AddressMap >::segmentPredicates () const inline
Returns the segment predicates.
Definition at line 433 of file AddressMap.h.
map()
template<typename AddressMap > AddressMap * Sawyer::Container::AddressMapConstraints< AddressMap >::map () const inline
Returns a pointer to the memory map for this constraint object.
Definition at line 438 of file AddressMap.h.
Referenced by Sawyer::Container::AddressMapConstraints< AddressMap >::at(), Sawyer::Container::AddressMapConstraints< AddressMap >::at(), Sawyer::Container::AddressMapConstraints< AddressMap >::atOrAfter(), Sawyer::Container::AddressMapConstraints< AddressMap >::atOrBefore(), Sawyer::Container::AddressMapConstraints< AddressMap >::limit(), Sawyer::Container::AddressMapConstraints< AddressMap >::none(), Sawyer::Container::AddressMapConstraints< AddressMap >::print(), Sawyer::Container::AddressMapConstraints< AddressMap >::prohibit(), Sawyer::Container::AddressMapConstraints< AddressMap >::require(), Sawyer::Container::AddressMapConstraints< AddressMap >::segmentPredicate(), Sawyer::Container::AddressMapConstraints< AddressMap >::singleSegment(), and Sawyer::Container::AddressMapConstraints< AddressMap >::substr().
hasNonAddressConstraints()
template<typename AddressMap > bool Sawyer::Container::AddressMapConstraints< AddressMap >::hasNonAddressConstraints () const inline
Determines whether non-address constraints are present.
The presence of non-address constraints requires iteration over matching addresses to find applicable regions of the address space.
Definition at line 444 of file AddressMap.h.
addressConstraints()
template<typename AddressMap > AddressMapConstraints Sawyer::Container::AddressMapConstraints< AddressMap >::addressConstraints () const inline
Construct new constraints from existing address constraints.
Constructs a new constraints object from an existing but using only the address constraints of the existing object and none of its non-address constraints.
Definition at line 452 of file AddressMap.h.
Referenced by Sawyer::Container::AddressMap< A, T >::changeAccess(), Sawyer::Container::AddressMap< A, T >::keep(), and Sawyer::Container::AddressMap< A, T >::prune().
nodes()
template<typename AddressMap > boost::iterator_range< typename AddressMapTraits< AddressMap >::NodeIterator > Sawyer::Container::AddressMapConstraints< AddressMap >::nodes (MatchFlags flags = 0) const inline
Definition at line 465 of file AddressMap.h.
segments()
template<typename AddressMap > boost::iterator_range< typename AddressMapTraits< AddressMap >::SegmentIterator > Sawyer::Container::AddressMapConstraints< AddressMap >::segments (MatchFlags flags = 0) const inline
Definition at line 470 of file AddressMap.h.
next()
template<typename AddressMap > Optional< typename AddressMap::Address > Sawyer::Container::AddressMapConstraints< AddressMap >::next (MatchFlags flags = 0) const inline
Definition at line 475 of file AddressMap.h.
available()
template<typename AddressMap > Sawyer::Container::Interval< Address > Sawyer::Container::AddressMapConstraints< AddressMap >::available (MatchFlags flags = 0) const inline
Definition at line 480 of file AddressMap.h.
exists()
template<typename AddressMap > bool Sawyer::Container::AddressMapConstraints< AddressMap >::exists (MatchFlags flags = 0) const inline
Definition at line 485 of file AddressMap.h.
findNode()
template<typename AddressMap > AddressMapTraits< AddressMap >::NodeIterator Sawyer::Container::AddressMapConstraints< AddressMap >::findNode (MatchFlags flags = 0) const inline
Definition at line 490 of file AddressMap.h.
traverse() [1/2]
template<typename AddressMap > template<typename Functor > void Sawyer::Container::AddressMapConstraints< AddressMap >::traverse (Functor & functor, MatchFlags flags = 0) const inline
Definition at line 496 of file AddressMap.h.
traverse() [2/2]
template<typename AddressMap > void Sawyer::Container::AddressMapConstraints< AddressMap >::traverse (typename AddressMap::Visitor & visitor, MatchFlags flags = 0) const inline
Definition at line 500 of file AddressMap.h.
read() [1/2]
template<typename AddressMap > Sawyer::Container::Interval< Address > Sawyer::Container::AddressMapConstraints< AddressMap >::read (typename AddressMap::Value * buf, MatchFlags flags = 0) const inline
Definition at line 505 of file AddressMap.h.
read() [2/2]
template<typename AddressMap > Sawyer::Container::Interval< Address > Sawyer::Container::AddressMapConstraints< AddressMap >::read (std::vector< typename AddressMap::Value > & buf, MatchFlags flags = 0) const inline
Definition at line 510 of file AddressMap.h.
write() [1/2]
template<typename AddressMap > Sawyer::Container::Interval< Address > Sawyer::Container::AddressMapConstraints< AddressMap >::write (const typename AddressMap::Value * buf, MatchFlags flags = 0) const inline
Definition at line 516 of file AddressMap.h.
write() [2/2]
template<typename AddressMap > Sawyer::Container::Interval< Address > Sawyer::Container::AddressMapConstraints< AddressMap >::write (const std::vector< typename AddressMap::Value > & buf, MatchFlags flags = 0) inline
Definition at line 521 of file AddressMap.h.
prune()
template<typename AddressMap > void Sawyer::Container::AddressMapConstraints< AddressMap >::prune (MatchFlags flags = 0) const inline
Definition at line 526 of file AddressMap.h.
keep()
template<typename AddressMap > void Sawyer::Container::AddressMapConstraints< AddressMap >::keep (MatchFlags flags = 0) const inline
Definition at line 531 of file AddressMap.h.
changeAccess()
template<typename AddressMap > void Sawyer::Container::AddressMapConstraints< AddressMap >::changeAccess (unsigned requiredAccess, unsigned prohibitedAccess, MatchFlags flags = 0) const inline
Definition at line 536 of file AddressMap.h.
The documentation for this class was generated from the following file:
AddressMap.h