ROSE: SgInitializedName Class Reference
SgInitializedName Class Reference
Description
This class represents the notion of a declared variable.
Each variable in the program has a SgInitializedName object which represents its definition. A SgVariableDeclaration for example might contain several SgInitializedName objects, while the SgInitializedName contains the declaration for one variable. Each variable use (VarRefExp for example) must have a link to the SgInitializedName object where that specific variable was defined.
What really happens
Currently, each SgVariableDeclaration contains only one SgInitializedName
In order to have a valid SgInitializedName object, this information must be provided :
the variable name which represents the variable that is being declared in this class.
the variable type
the declaration object which contains the SgInitializedName (this might be a SgVariableDeclaration, SgFunctionParameterList, SgClassDeclaration,etc)
See also
Example of creating an SgInitializedName object
Example of using an SgInitializedName object
Definition at line 175008 of file Cxx_Grammar.h.
Public Types
enum preinitialization_enum {
e_unknown_preinitialization = 0 ,
e_virtual_base_class = 1 ,
e_nonvirtual_base_class = 2 ,
e_data_member = 3 ,
e_delegation_constructor = 4 ,
e_last_preinitialization
}
Preinitialization Enum (only one value can be specified)
enum asm_register_name_enum {
e_invalid_register = 0 ,
e_memory_register ,
e_register_a ,
e_register_b ,
e_register_c ,
e_register_d ,
e_register_si ,
e_register_di ,
e_register_bp ,
e_register_sp ,
e_register_r8 ,
e_register_r9 ,
e_register_r10 ,
e_register_r11 ,
e_register_r12 ,
e_register_r13 ,
e_register_r14 ,
e_register_r15 ,
e_register_st0 ,
e_register_st1 ,
e_register_st2 ,
e_register_st3 ,
e_register_st4 ,
e_register_st5 ,
e_register_st6 ,
e_register_st7 ,
e_register_mm0 ,
e_register_mm1 ,
e_register_mm2 ,
e_register_mm3 ,
e_register_mm4 ,
e_register_mm5 ,
e_register_mm6 ,
e_register_mm7 ,
e_register_f0 ,
e_register_f1 ,
e_register_f2 ,
e_register_f3 ,
e_register_f4 ,
e_register_f5 ,
e_register_f6 ,
e_register_f7 ,
e_register_f8 ,
e_register_f9 ,
e_register_f10 ,
e_register_f11 ,
e_register_f12 ,
e_register_f13 ,
e_register_f14 ,
e_register_f15 ,
e_register_flags ,
e_register_fpsr ,
e_register_dirflag ,
e_register_f16 ,
e_register_f17 ,
e_register_f18 ,
e_register_f19 ,
e_register_f20 ,
e_unrecognized_register ,
e_last_register
}
Register names (x86 specific GNU names).
enum gnu_variable_attribute_enum {
e_gnu_attribute__weak__ = 0 ,
e_gnu_attribute__unused__ = 1 ,
e_gnu_attribute__used__ = 2 ,
e_gnu_attribute__deprecated__ = 3 ,
e_gnu_attribute__nocommon__ = 4 ,
e_gnu_attribute__transparent_union__ = 5 ,
e_gnu_attribute__weakref__ = 6 ,
e_gnu_attribute__packed__ = 7 ,
e_gnu_attribute__noreturn__ = 8 ,
e_gnu_attribute__noreorder__ = 9 ,
e_ms_declspec_parameter_appdomain = 10 ,
e_ms_declspec_parameter_deprecated = 11 ,
e_ms_declspec_parameter_dllimport = 12 ,
e_ms_declspec_parameter_dllexport = 13 ,
e_ms_declspec_parameter_novtable = 14 ,
e_ms_declspec_parameter_process = 15 ,
e_ms_declspec_parameter_property = 16 ,
e_ms_declspec_parameter_restrict = 17 ,
e_ms_declspec_parameter_selectany = 18 ,
e_ms_declspec_parameter_thread = 19 ,
e_ms_declspec_parameter_uuid = 20 ,
e_last_gnu_variable_attribute
}
enum excess_specifier_enum {
e_excess_specifier_none = 0 ,
e_excess_specifier_positionals ,
e_excess_specifier_keywords ,
e_excess_specifier_last
}
enum { static_variant = V_SgInitializedName }
static variant value
typedef SgLocatedNodeSupport base_node_type
Public Types inherited from SgLocatedNodeSupport
enum { static_variant = V_SgLocatedNodeSupport }
static variant value
typedef SgLocatedNode base_node_type
Public Types inherited from SgLocatedNode
enum { static_variant = V_SgLocatedNode }
static variant value
typedef SgNode base_node_type
Public Types inherited from SgNode
enum { static_variant = V_SgNode }
static variant value
enum { static_variant = V_SgNode }
static variant value
Public Member Functions
virtual SgNode * copy (SgCopyHelp &help) const override
It clones the current SgInitializedName object recursively or not, depending on the argument.
bool checkBit (unsigned int bit) const
void setBit (unsigned int bit)
void unsetBit (unsigned int bit)
bool isGnuAttributeWeak () const
void setGnuAttributeWeak ()
void unsetGnuAttributeWeak ()
bool isGnuAttributeUnused () const
void setGnuAttributeUnused ()
void unsetGnuAttributeUnused ()
bool isGnuAttributeUsed () const
void setGnuAttributeUsed ()
void unsetGnuAttributeUsed ()
bool isGnuAttributeDeprecated () const
void setGnuAttributeDeprecated ()
void unsetGnuAttributeDeprecated ()
bool isGnuAttributeNoCommon () const
void setGnuAttributeNoCommon ()
void unsetGnuAttributeNoCommon ()
bool isGnuAttributeTransparentUnion () const
void setGnuAttributeTransparentUnion ()
void unsetGnuAttributeTransparentUnion ()
bool isGnuAttributeWeakReference () const
void setGnuAttributeWeakReference ()
void unsetGnuAttributeWeakReference ()
bool isGnuAttributePacked () const
void setGnuAttributePacked ()
void unsetGnuAttributePacked ()
bool isGnuAttributeNoReturn () const
void setGnuAttributeNoReturn ()
void unsetGnuAttributeNoReturn ()
bool isGnuAttributeNoReorder () const
void setGnuAttributeNoReorder ()
void unsetGnuAttributeNoReorder ()
bool is_ms_declspec_parameter_appdomain () const
void set_ms_declspec_parameter_appdomain ()
void unset_ms_declspec_parameter_appdomain ()
bool is_ms_declspec_parameter_deprecated () const
void set_ms_declspec_parameter_deprecated ()
void unset_ms_declspec_parameter_deprecated ()
bool is_ms_declspec_parameter_dllimport () const
void set_ms_declspec_parameter_dllimport ()
void unset_ms_declspec_parameter_dllimport ()
bool is_ms_declspec_parameter_dllexport () const
void set_ms_declspec_parameter_dllexport ()
void unset_ms_declspec_parameter_dllexport ()
bool is_ms_declspec_parameter_novtable () const
void set_ms_declspec_parameter_novtable ()
void unset_ms_declspec_parameter_novtable ()
bool is_ms_declspec_parameter_process () const
void set_ms_declspec_parameter_process ()
void unset_ms_declspec_parameter_process ()
bool is_ms_declspec_parameter_restrict () const
void set_ms_declspec_parameter_restrict ()
void unset_ms_declspec_parameter_restrict ()
bool is_ms_declspec_parameter_selectany () const
void set_ms_declspec_parameter_selectany ()
void unset_ms_declspec_parameter_selectany ()
bool is_ms_declspec_parameter_thread () const
void set_ms_declspec_parameter_thread ()
void unset_ms_declspec_parameter_thread ()
bool is_ms_declspec_parameter_uuid () const
void set_ms_declspec_parameter_uuid ()
void unset_ms_declspec_parameter_uuid ()
void post_construction_initialization () override
Allocates a new storage modifier and sets the storage modifier to default values.
virtual unsigned int cfgIndexForEnd () const override
Determine the CFG index for the end of this construct.
virtual bool cfgIsIndexInteresting (unsigned int index) const override
Determine whether a particular CFG node index is "interesting" for this kind of node.
virtual unsigned int cfgFindChildIndex (SgNode *n) override
Find the index of n in this node's CFG children.
virtual unsigned int cfgFindNextChildIndex (SgNode *n) override
Find the index just after n in this node's CFG children.
virtual std::vector< VirtualCFG::CFGEdge > cfgOutEdges (unsigned int index) override
Find the out edges of a CFG node – internal version.
virtual std::vector< VirtualCFG::CFGEdge > cfgInEdges (unsigned int index) override
Find the in edges of a CFG node – internal version.
SgStorageModifier & get_storageModifier ()
returns a reference to the storage modifier
const SgStorageModifier & get_storageModifier () const
SgInitializedName (const SgName &name, SgType *typeptr, SgInitializer *iptr=0, SgDeclarationStatement *declptr=0, SgInitializedName *prev_decl_item=0)
SgInitializedName (Sg_File_Info *fileInfo, const SgName &name, SgType *typeptr, SgInitializer *iptr, SgDeclarationStatement *declptr, SgScopeStatement *scope, SgInitializedName *prev_itemptr)
This is the constructor.
SgInitializedName (const SgInitializedName &ptr)
This is the copy constructor.
SgInitializedName & operator= (const SgInitializedName &ptr)
assignment operator. It copies everything (including pointers) from the rhs object to the lhs object
bool operator== (const SgInitializedName &) const
Equal operator : it checks if all the data members are the same or point to the same objects.
bool operator< (const SgInitializedName &) const
SgType * get_type () const
void set_type (SgType *t)
SgInitializer * get_initializer () const
void set_initializer (SgInitializer *i)
SgDeclarationStatement * get_declaration () const
Equal operator : it checks if all the data members are the same or point to the same objects.
SgDeclarationStatement * get_definition () const
void set_definition (SgDeclarationStatement *def)
SgName get_qualified_name () const
Returns the name with appropriate qualified names representing nested scopes.
virtual SgName get_mangled_name (void) const
SgSymbol * get_symbol_from_symbol_table () const
Get the associated SgSymbol from the symbol table located in the scope, without considering possible prev_decl_item. Internal use only. Users should use search_for_symbol_from_symbol_table() instead.
SgSymbol * search_for_symbol_from_symbol_table () const
User interface for retrieving the associated symbol. It searches through the possible chain of prev_decl_item.
virtual void fixupCopy_scopes (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_symbols (SgNode *copy, SgCopyHelp &help) const override
virtual void fixupCopy_references (SgNode *copy, SgCopyHelp &help) const override
SgName get_qualified_name_prefix () const
int get_name_qualification_length () const
void set_name_qualification_length (int name_qualification_length_for_type)
bool get_type_elaboration_required () const
void set_type_elaboration_required (bool type_elaboration_required_for_type)
bool get_global_qualification_required () const
void set_global_qualification_required (bool global_qualification_required_for_type)
SgName get_qualified_name_prefix_for_type () const
This function generates the qualified name prefix to be used with the named declaration (only applied to restricted set of declarations where name qualification can be used).
int get_name_qualification_length_for_type () const
void set_name_qualification_length_for_type (int name_qualification_length_for_type)
bool get_type_elaboration_required_for_type () const
void set_type_elaboration_required_for_type (bool type_elaboration_required_for_type)
bool get_global_qualification_required_for_type () const
void set_global_qualification_required_for_type (bool global_qualification_required_for_type)
virtual void addNewAttribute (std::string s, AstAttribute *a) override
Add a new attribute represented by the named string.
virtual AstAttribute * getAttribute (std::string s) const override
Returns attribute of name 's'.
virtual void updateAttribute (std::string s, AstAttribute *a) override
Replace existing attribute of name 's' with new AstAttribute.
virtual void setAttribute (std::string s, AstAttribute *a) override
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
virtual void removeAttribute (std::string s) override
Remove attribute of name 's' if present.
virtual bool attributeExists (std::string s) const override
Tests if attribute of name 's' is present.
virtual int numberOfAttributes () const override
Returns the number of attributes on this IR node.
virtual std::string class_name () const override
returns a string representing the class name
virtual VariantT variantT () const override
returns new style SageIII enum values
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
virtual std::vector< SgNode * > get_traversalSuccessorContainer () override
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
virtual std::vector< std::string > get_traversalSuccessorNamesContainer () override
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
virtual size_t get_numberOfTraversalSuccessors () override
return number of children in the traversal successor list
virtual SgNode * get_traversalSuccessorByIndex (size_t idx) override
index-based access to traversal successors by index number
virtual size_t get_childIndex (SgNode *child) override
index-based access to traversal successors by child node
virtual RTIReturnType roseRTI () override
return C++ Runtime-Time-Information
virtual const char * sage_class_name () const override
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
virtual void accept (ROSE_VisitorPattern &visitor) override
support for the classic visitor pattern done in GoF
virtual bool isInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual void checkDataMemberPointersIfInMemoryPool () override
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
virtual std::vector< std::pair< SgNode *, std::string > > returnDataMemberPointers () const override
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
virtual void processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
virtual long getChildIndex (SgNode *childNode) const override
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
SgInitializedName (const SgInitializedNameStorageClass &source)
IR node constructor to support AST File I/O.
SgInitializedName * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
SgName get_name () const
void set_name (SgName name)
std::string get_microsoft_uuid_string () const
void set_microsoft_uuid_string (std::string microsoft_uuid_string)
SgType * get_typeptr () const
void set_typeptr (SgType *typeptr)
SgInitializer * get_initptr () const
void set_initptr (SgInitializer *initptr)
SgInitializedName * get_prev_decl_item () const
void set_prev_decl_item (SgInitializedName *prev_decl_item)
SgDeclarationStatement * get_declptr () const
void set_declptr (SgDeclarationStatement *declptr)
SgScopeStatement * get_scope () const
void set_scope (SgScopeStatement *scope)
SgInitializedName::preinitialization_enum get_preinitialization () const
void set_preinitialization (SgInitializedName::preinitialization_enum preinitialization)
bool get_isCoArray () const
void set_isCoArray (bool isCoArray)
SgInitializedName::asm_register_name_enum get_register_name_code () const
void set_register_name_code (SgInitializedName::asm_register_name_enum register_name_code)
SgInitializedName::excess_specifier_enum get_excess_specifier () const
void set_excess_specifier (SgInitializedName::excess_specifier_enum excess_specifier)
std::string get_register_name_string () const
void set_register_name_string (std::string register_name_string)
bool get_requiresGlobalNameQualificationOnType () const
void set_requiresGlobalNameQualificationOnType (bool requiresGlobalNameQualificationOnType)
bool get_shapeDeferred () const
void set_shapeDeferred (bool shapeDeferred)
bool get_initializationDeferred () const
void set_initializationDeferred (bool initializationDeferred)
SgBitVector get_gnu_attribute_modifierVector () const
void set_gnu_attribute_modifierVector (SgBitVector gnu_attribute_modifierVector)
unsigned long int get_gnu_attribute_initialization_priority () const
void set_gnu_attribute_initialization_priority (unsigned long int gnu_attribute_initialization_priority)
std::string get_gnu_attribute_named_weak_reference () const
void set_gnu_attribute_named_weak_reference (std::string gnu_attribute_named_weak_reference)
std::string get_gnu_attribute_named_alias () const
void set_gnu_attribute_named_alias (std::string gnu_attribute_named_alias)
std::string get_gnu_attribute_cleanup_function () const
void set_gnu_attribute_cleanup_function (std::string gnu_attribute_cleanup_function)
std::string get_gnu_attribute_section_name () const
void set_gnu_attribute_section_name (std::string gnu_attribute_section_name)
int get_gnu_attribute_alignment () const
void set_gnu_attribute_alignment (int gnu_attribute_alignment)
SgDeclarationModifier::gnu_declaration_visability_enum get_gnu_attribute_visability () const
void set_gnu_attribute_visability (SgDeclarationModifier::gnu_declaration_visability_enum gnu_attribute_visability)
bool get_protected_declaration () const
void set_protected_declaration (bool protected_declaration)
bool get_hasArrayTypeWithEmptyBracketSyntax () const
void set_hasArrayTypeWithEmptyBracketSyntax (bool hasArrayTypeWithEmptyBracketSyntax)
bool get_using_C11_Alignas_keyword () const
void set_using_C11_Alignas_keyword (bool using_C11_Alignas_keyword)
SgNode * get_constant_or_type_argument_for_Alignas_keyword () const
void set_constant_or_type_argument_for_Alignas_keyword (SgNode *constant_or_type_argument_for_Alignas_keyword)
bool get_using_auto_keyword () const
void set_using_auto_keyword (bool using_auto_keyword)
SgType * get_auto_decltype () const
void set_auto_decltype (SgType *auto_decltype)
bool get_using_device_keyword () const
void set_using_device_keyword (bool using_device_keyword)
bool get_is_braced_initialized () const
void set_is_braced_initialized (bool is_braced_initialized)
bool get_using_assignment_copy_constructor_syntax () const
void set_using_assignment_copy_constructor_syntax (bool using_assignment_copy_constructor_syntax)
bool get_needs_definitions () const
void set_needs_definitions (bool needs_definitions)
bool get_is_parameter_pack () const
void set_is_parameter_pack (bool is_parameter_pack)
bool get_is_pack_element () const
void set_is_pack_element (bool is_pack_element)
SgInitializedName (Sg_File_Info *startOfConstruct, SgName name=NULL, SgType *typeptr=NULL)
SgInitializedName (SgName name, SgType *typeptr)
Public Member Functions inherited from SgLocatedNodeSupport
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgLocatedNodeSupport (const SgLocatedNodeSupportStorageClass &source)
IR node constructor to support AST File I/O.
SgLocatedNodeSupport * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
SgLocatedNodeSupport (Sg_File_Info *startOfConstruct)
Public Member Functions inherited from SgLocatedNode
const std::string & getFilenameString () const
void addToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo::RelativePositionType locationInList=PreprocessingInfo::after)
This function adds comment or CPP directives to the current IR node.
void insertToAttachedPreprocessingInfo (PreprocessingInfo *prepInfoPtr, PreprocessingInfo *anchorInfoPtr, bool insertAfter=true)
Insert prepInfo After (or before if last parameter is false) an anchor info ptr in the list of preprocessing info attached to the current node. This is useful to insert things in the middle.
virtual Sg_File_Info * get_file_info () const override
Interface function to implement original SAGE interface to SgFile_Info objects.
virtual void set_file_info (Sg_File_Info *X)
Access function calls set_startingConstruct(Sg_File_Info*) member function.
void setCompilerGenerated ()
Allow IR nodes (mostly SgLocatedNode) to be marked as compiler generated.
void unsetCompilerGenerated ()
bool isCompilerGenerated () const
Simple test for if this is a compiler generated node.
void setTransformation ()
Allow IR nodes (mostly SgLocatedNode) to be marked as a transformation.
void unsetTransformation ()
bool isTransformation () const
Simple test for if this is a part of a transformation.
void setFrontendSpecific ()
Allow IR nodes (mostly SgLocatedNode) to be marked as front-end specific (generated by the front-end to support a specific backend compiler; e.g. GNU gcc and g++).
void unsetFrontendSpecific ()
bool isFrontendSpecific () const
Simple test for if this is a frontend specific IR node.
void setShared ()
Allow IR nodes (mostly SgLocatedNode) to be marked as shared.
void unsetShared ()
bool isShared () const
Simple test for if this is a shared IR node.
void setSourcePositionUnavailableInFrontend ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetSourcePositionUnavailableInFrontend ()
void setOutputInCodeGeneration ()
Allow IR nodes (mostly SgLocatedNode) to be marked as to when the information was unavilable in the front-end (even if it typically is there are special cases).
void unsetOutputInCodeGeneration ()
bool isOutputInCodeGeneration () const
int get_physical_file_id ()
Allow IR nodes (mostly SgLocatedNode) to be queried for there physical file ID.
AttachedPreprocessingInfoType *& getAttachedPreprocessingInfo (void)
Computes the number of nodes in the defined subtree of the AST.
Sg_File_Info * generateMatchingFileInfo ()
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgLocatedNode (const SgLocatedNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgLocatedNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
Sg_File_Info * get_startOfConstruct () const override
New function interface for Sg_File_Info data stores starting location of contruct (typically the opening brace or first letter of keyword).
void set_startOfConstruct (Sg_File_Info *startOfConstruct)
This function sets the current source location position of the start of the current construct.
Sg_File_Info * get_endOfConstruct () const override
New function interface for Sg_File_Info data stores ending location of contruct (typically the closing brace).
void set_endOfConstruct (Sg_File_Info *endOfConstruct)
This function sets the current source location position of the end of the current construct.
AttachedPreprocessingInfoType * get_attachedPreprocessingInfoPtr () const
void set_attachedPreprocessingInfoPtr (AttachedPreprocessingInfoType *attachedPreprocessingInfoPtr)
AstAttributeMechanism * get_attributeMechanism () const override
FOR INTERNAL USE Access function; if an attribute exists then a pointer to it is returned, else error.
void set_attributeMechanism (AstAttributeMechanism *attributeMechanism) override
FOR INTERNAL USE Access function; sets poiner to value AstAttributeMechanism.
bool get_containsTransformationToSurroundingWhitespace () const
void set_containsTransformationToSurroundingWhitespace (bool containsTransformationToSurroundingWhitespace)
virtual ~SgLocatedNode ()
This is the destructor.
SgLocatedNode (Sg_File_Info *startOfConstruct=NULL)
This is the constructor.
Public Member Functions inherited from SgNode
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
int variant () const
Older version function returns enum value "NODE".
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
virtual ~SgNode ()
This is the destructor.
SgNode ()
This is the constructor.
void * operator new (size_t size)
returns pointer to newly allocated IR node
void operator delete (void *pointer, size_t size)
deallocated memory for IR node (returns memory to memory pool for reuse)
void operator delete (void *pointer)
void executeVisitorMemberFunction (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
SgNode (const SgNodeStorageClass &source)
IR node constructor to support AST File I/O.
SgNode * addRegExpAttribute (std::string s, AstRegExAttribute *a)
Support for AST matching using regular expression.
void set_isModified (bool isModified)
All nodes in the AST contain a isModified flag used to track changes to the AST.
void set_containsTransformation (bool containsTransformation)
Many nodes can hide other AST nodes and we need to track when outer nodes contain modified nodes even if they are not themselves modified.
bool get_isModified () const
Acess function for isModified flag.
bool get_containsTransformation () const
Acess function for containsTransformation flag.
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
SgNode * get_raw_parent () const
Access function for direct access to uncomputed value of parent node.
bool isChild (SgNode *node) const
Query function for if the input IR nodes is a child of the current IR node.
virtual std::string unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)
std::string unparseToString () const
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
int variant () const
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
VirtualCFG::CFGNode cfgForBeginning ()
Returns the CFG node for just before this AST node.
VirtualCFG::CFGNode cfgForEnd ()
Returns the CFG node for just after this AST node.
int numberOfNodesInSubtree ()
Computes the number of nodes in the defined subtree of the AST.
int depthOfSubtree ()
Computes the depth of the current defined subtree of the AST.
template<class T >
T * initParentPointer (T *child, SgNode *parent)
Generated for tree edge data member initializations.
SgNode * get_freepointer () const
void set_freepointer (SgNode *freepointer)
void set_parent (SgNode *parent)
All nodes in the AST contain a reference to a parent node.
SgNode * get_parent () const
Access function for parent node.
std::string unparseToCompleteString ()
This function unparses the AST node (including comments and white space)
bool get_isVisited () const
DOCS IN HEADER: Access function for p_isVisited flag used previously by the AST traversals.
void set_isVisited (bool isVisited)
Access function for p_isVisited flag used previously by the AST traversals.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if< std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
template<class T >
std::enable_if<!std::is_pointer< T >::value, void >::type changeChildPointer (T &edge, T const &child)
Set a child edge in a tree to point to a specific child.
Static Public Member Functions
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgInitializedName * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgInitializedName *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgInitializedName *sgnode)
Static Public Member Functions inherited from SgLocatedNodeSupport
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgLocatedNodeSupport * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgLocatedNodeSupport *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgLocatedNodeSupport *sgnode)
Static Public Member Functions inherited from SgLocatedNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgLocatedNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgLocatedNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgLocatedNode *sgnode)
Static Public Member Functions inherited from SgNode
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
static void deleteMemoryPool ()
static size_t numberOfNodes ()
Returns the total number of IR nodes of this type.
static size_t memoryUsage ()
Returns the size in bytes of the total memory allocated for all IR nodes of this type.
static void traverseMemoryPoolNodes (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for visitor pattern over all IR nodes by type of IR node.
static void traverseMemoryPoolVisitorPattern (ROSE_VisitorPattern &visitor)
FOR INTERNAL USE Support for visitor pattern.
static void visitRepresentativeNode (ROSE_VisitTraversal &visit)
FOR INTERNAL USE Support for type-based traversal.
static SgNode * getNodeByNodeId (VariantT variantT, size_t poolIdx, size_t itemIdx)
Find a node by its variant type, pool index, and item index.
static SgNode * getNodeByNodeIdInternal (size_t poolIdx, size_t itemIdx)
FOR INTERNAL USE Find an SgNode from its memory pool and location therin.
static std::string getNodeIdString (SgNode *sgnode)
compute the NodeId for a particular SgNode*.
static std::string getNodeIdStringInternal (SgNode *sgnode)
static std::vector< std::string > buildCommandLineToSubstituteTransformationFile (const std::vector< std::string > &argv, std::string newFileName)
Command line support for this compilation The command line is saved as a static variable so that it will be available to support the rewrite mechanism.
static std::vector< VariantT > getClassHierarchySubTreeFunction (VariantT v)
static void getClassHierarchySubTreeFunction (VariantT v, std::vector< VariantT > &)
static std::map< SgNode *, std::string > & get_globalMangledNameMap ()
Access function for performance optimizing global mangled name map.
static void clearGlobalMangledNameMap ()
Support to clear the performance optimizing global mangled name map.
static std::map< std::string, uint64_t > & get_shortMangledNameCache ()
Access function for lower level optimizing of global mangled name map.
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForNames ()
Access function for name qualification support (for names).
static void set_globalQualifiedNameMapForNames (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTypes ()
Access function for name qualification support (for type).
static void set_globalQualifiedNameMapForTypes (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for type).
static std::map< SgNode *, std::map< SgNode *, std::string > > & get_globalQualifiedNameMapForMapsOfTypes ()
Access function for name qualification support (for maps of types).
static void set_globalQualifiedNameMapForMapsOfTypes (const std::map< SgNode *, std::map< SgNode *, std::string > > &X)
Access function for name qualification support (for maps of types).
static std::map< SgNode *, std::string > & get_globalQualifiedNameMapForTemplateHeaders ()
Access function for name qualification support (for template headers in template declarations).
static void set_globalQualifiedNameMapForTemplateHeaders (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for template headers in template declarations).
static std::map< SgNode *, std::string > & get_globalTypeNameMap ()
Access function for name qualification support (for names of types).
static void set_globalTypeNameMap (const std::map< SgNode *, std::string > &X)
Access function for name qualification support (for names of types).
static SgFunctionTypeTable * get_globalFunctionTypeTable ()
Access function for symbol table specific to function types.
static void set_globalFunctionTypeTable (SgFunctionTypeTable *globalFunctionTypeTable)
Access function for symbol table specific to function types.
static SgTypeTable * get_globalTypeTable ()
Access function for symbol table specific to non-function types.
static void set_globalTypeTable (SgTypeTable *globalTypeTable)
Access function for symbol table specific to non-function types.
static VariantT variantFromPool (SgNode const *n)
template<class T >
static std::enable_if< std::is_base_of< SgNode, T >::value, T * >::type createAndParent (SgNode *parent)
Allocate and return a new node after setting its parent.
Protected Attributes
SgName p_name
The variable that is declared in this declaration.
std::string p_microsoft_uuid_string
SgType * p_typeptr
Pointer to a type object that has been associated with SgInitializedName::p_name.
SgInitializer * p_initptr
Pointer to an initializer for the variable.
SgInitializedName * p_prev_decl_item
Pointer to the initial uses of this variable previous to its redeclaration declaration.
bool p_is_initializer
flag to determine whether the declaration has an initializer.
SgDeclarationStatement * p_declptr
Pointer to the declaration object where this SgInitializedName object belongs to.
SgStorageModifier * p_storageModifier
This is the storage modifier (static, auto, register, mutable, asm, etc.).
SgScopeStatement * p_scope
This pointer is always valid and stores the current scope of the variable.
SgInitializedName::preinitialization_enum p_preinitialization
This data member stores an enum value.
bool p_isCoArray
SgInitializedName::asm_register_name_enum p_register_name_code
Code (following GNU standard) for register name.
SgInitializedName::excess_specifier_enum p_excess_specifier
std::string p_register_name_string
bool p_requiresGlobalNameQualificationOnType
bool p_shapeDeferred
bool p_initializationDeferred
SgBitVector p_gnu_attribute_modifierVector
unsigned long int p_gnu_attribute_initialization_priority
std::string p_gnu_attribute_named_weak_reference
std::string p_gnu_attribute_named_alias
std::string p_gnu_attribute_cleanup_function
std::string p_gnu_attribute_section_name
int p_gnu_attribute_alignment
SgDeclarationModifier::gnu_declaration_visability_enum p_gnu_attribute_visability
bool p_protected_declaration
int p_name_qualification_length
bool p_type_elaboration_required
bool p_global_qualification_required
int p_name_qualification_length_for_type
bool p_type_elaboration_required_for_type
bool p_global_qualification_required_for_type
bool p_hasArrayTypeWithEmptyBracketSyntax
bool p_using_C11_Alignas_keyword
SgNode * p_constant_or_type_argument_for_Alignas_keyword
bool p_using_auto_keyword
SgType * p_auto_decltype
bool p_using_device_keyword
bool p_is_braced_initialized
bool p_using_assignment_copy_constructor_syntax
bool p_needs_definitions
bool p_is_parameter_pack
bool p_is_pack_element
Protected Attributes inherited from SgLocatedNode
Sg_File_Info * p_startOfConstruct
This pointer is always valid and stores the source position of the start of the current construct.
Sg_File_Info * p_endOfConstruct
This pointer is always valid and stores the source position of the end of the current construct.
AttachedPreprocessingInfoType * p_attachedPreprocessingInfoPtr
Holds comments and/or preprocessor directives located before or after the current statement of expression.
AstAttributeMechanism * p_attributeMechanism
bool p_containsTransformationToSurroundingWhitespace
Protected Attributes inherited from SgNode
SgNode * p_parent
This is the pointer to the parent IR node in the AST.
bool p_isModified
Records if IR node has been modified (data members reset).
bool p_containsTransformation
SgNode * p_freepointer
This is the pointer to the chain of previously freed objects.
Additional Inherited Members
Protected Member Functions inherited from SgLocatedNode
void post_construction_initialization () override
Final initialization for constructors This function is called at the end of generated constructors to allow the specification writer to add special initialization functions or tests. Default is to do nothing. Otherwise it should be overridden in the spec file, in NewHeaderCode/NewOutlinedCode.
Protected Member Functions inherited from SgNode
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void destructorHelper ()
This gets called by all Rosebud-generated destructors.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
virtual void debugSerializationBegin (const char *className)
Called by generated serializers.
virtual void debugSerializationEnd (const char *className)
Called by generated serializers.
Static Protected Attributes inherited from SgNode
static std::vector< std::tuple< unsigned char *, unsigned, VariantT > > all_pools
static SgFunctionTypeTable * p_globalFunctionTypeTable
Pointer to symbol table specific to function types.
static SgTypeTable * p_globalTypeTable
static std::map< SgNode *, std::string > p_globalMangledNameMap
Cache of mangled names to avoid regeneration of previously build mangled names or parts of mangled names. This is a performance optimization.
static std::map< std::string, uint64_t > p_shortMangledNameCache
STL map used as a cache to shorten generated mangled names. This is mostly a space optimization ofr mangled names of templates.
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForNames
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTypes
static std::map< SgNode *, std::string > p_globalQualifiedNameMapForTemplateHeaders
static std::map< SgNode *, std::string > p_globalTypeNameMap
static std::map< SgNode *, std::map< SgNode *, std::string > > p_globalQualifiedNameMapForMapsOfTypes
Member Typedef Documentation
base_node_type
typedef SgLocatedNodeSupport SgInitializedName::base_node_type
Definition at line 175846 of file Cxx_Grammar.h.
Member Enumeration Documentation
preinitialization_enum
enum SgInitializedName::preinitialization_enum
Preinitialization Enum (only one value can be specified)
Initialization information which I forget the details of ...
Enumerator
e_unknown_preinitialization
default value
e_virtual_base_class
virtual base class value
e_nonvirtual_base_class
nonvirtual base class value
e_data_member
data member value
e_delegation_constructor
delegation constructor (C++11 feature)
e_last_preinitialization
last value (upper bound on range of values, used in error checking)
Definition at line 175028 of file Cxx_Grammar.h.
asm_register_name_enum
enum SgInitializedName::asm_register_name_enum
Register names (x86 specific GNU names).
Enumerator
e_invalid_register
error value
e_memory_register
memory
e_register_d
eax, ebx, ecx, edx
e_register_sp
esi, edi, ebp, esp
e_register_r11
x86-64 extra integer registers
e_register_st3
80387 floating point stack
e_register_mm3
MMX registers
e_register_f3
SSE/SSE2 registers
e_register_f11
x86-64 extra SSE registers
e_register_dirflag
control registers
e_unrecognized_register
used to represent an unrecognized register.
Definition at line 175043 of file Cxx_Grammar.h.
gnu_variable_attribute_enum
enum SgInitializedName::gnu_variable_attribute_enum
Enumerator
e_gnu_attribute__weak__
GNU specific attribute for (GNU extension)
e_gnu_attribute__unused__
GNU specific attribute for (GNU extension)
e_gnu_attribute__used__
GNU specific attribute for (GNU extension)
e_gnu_attribute__deprecated__
GNU specific attribute for (GNU extension)
e_gnu_attribute__nocommon__
GNU specific attribute for (GNU extension)
e_gnu_attribute__transparent_union__
GNU specific attribute for (GNU extension)
e_gnu_attribute__weakref__
GNU specific attribute for (GNU extension)
e_gnu_attribute__packed__
GNU specific attribute for (GNU extension)
e_gnu_attribute__noreturn__
GNU specific attribute for (GNU extension)
e_gnu_attribute__noreorder__
GNU specific attribute for (GNU extension)
e_ms_declspec_parameter_appdomain
Microsoft declspec() attributes
e_ms_declspec_parameter_deprecated
Microsoft declspec() attributes
e_ms_declspec_parameter_dllimport
Microsoft declspec() attributes
e_ms_declspec_parameter_dllexport
Microsoft declspec() attributes
e_ms_declspec_parameter_novtable
Microsoft declspec() attributes
e_ms_declspec_parameter_process
Microsoft declspec() attributes
e_ms_declspec_parameter_property
Microsoft declspec() attributes
e_ms_declspec_parameter_restrict
Microsoft declspec() attributes
e_ms_declspec_parameter_selectany
Microsoft declspec() attributes
e_ms_declspec_parameter_thread
Microsoft declspec() attributes
e_ms_declspec_parameter_uuid
Microsoft declspec() attributes
e_last_gnu_variable_attribute
last value (upper bound on range of values, used in error checking)
Definition at line 175110 of file Cxx_Grammar.h.
excess_specifier_enum
enum SgInitializedName::excess_specifier_enum
Definition at line 175145 of file Cxx_Grammar.h.
anonymous enum
anonymous enum
static variant value
Definition at line 175467 of file Cxx_Grammar.h.
Constructor & Destructor Documentation
SgInitializedName()
SgInitializedName::SgInitializedName (Sg_File_Info * fileInfo, const SgName & name, SgType * typeptr, SgInitializer * iptr, SgDeclarationStatement * declptr, SgScopeStatement * scope, SgInitializedName * prev_itemptr)
This is the constructor.
Parameters
fileInfo pointer to source position (also used to mark compiler generated or transformed code)
name the variable name
typeptr a pointer to the variable's type object
iptr pointer to the initializer of the variable (if any)
declptr pointer to the declaration statement to which this SgInitializedName belongs to
scope pointer to SgScopeStatement to explicitly represent the scope of the variable (required for ROSE, but mostly useful in C++)
itemptr the next SgInitializedName object in the parent declaration statement
prev_itemptr the previous SgInitializedName object in the parent declaration statement
See also
Example:create an SgInitializedName object
Member Function Documentation
copy()
SgNode * SgInitializedName::copy (SgCopyHelp & help) const override virtual
It clones the current SgInitializedName object recursively or not, depending on the argument.
Parameters
help - If this argument is of type SgTreeCopy, then the SgInitializedName is cloned recursively. If it's of type SgShallowCopy only the first level of SgInitializedName is copied, everything else pointing to the the original SgInitializedName object's data members.
Returns
a pointer to the new clone.
Reimplemented from SgLocatedNodeSupport.
post_construction_initialization()
SgInitializedName::post_construction_initialization () override virtual
Allocates a new storage modifier and sets the storage modifier to default values.
Reimplemented from SgNode.
cfgIndexForEnd()
virtual unsigned int SgInitializedName::cfgIndexForEnd () const override virtual
Determine the CFG index for the end of this construct.
Reimplemented from SgNode.
cfgIsIndexInteresting()
virtual bool SgInitializedName::cfgIsIndexInteresting (unsigned int index) const override virtual
Determine whether a particular CFG node index is "interesting" for this kind of node.
Reimplemented from SgNode.
cfgFindChildIndex()
virtual unsigned int SgInitializedName::cfgFindChildIndex (SgNode * n) override virtual
Find the index of n in this node's CFG children.
Reimplemented from SgNode.
cfgFindNextChildIndex()
virtual unsigned int SgInitializedName::cfgFindNextChildIndex (SgNode * n) override virtual
Find the index just after n in this node's CFG children.
Reimplemented from SgNode.
cfgOutEdges()
virtual std::vector< VirtualCFG::CFGEdge > SgInitializedName::cfgOutEdges (unsigned int index) override virtual
Find the out edges of a CFG node – internal version.
Reimplemented from SgNode.
cfgInEdges()
virtual std::vector< VirtualCFG::CFGEdge > SgInitializedName::cfgInEdges (unsigned int index) override virtual
Find the in edges of a CFG node – internal version.
Reimplemented from SgNode.
operator=()
SgInitializedName & SgInitializedName::operator= (const SgInitializedName & ptr)
assignment operator. It copies everything (including pointers) from the rhs object to the lhs object
It copies all the data members of the rhs SgInitializedName object to the lhs (this) object. The copying is done by value, so all the data member pointers are copied by value. After the assignment operator is executed, both operands share the same data members. Actually there is a note in the source code (Cxx_Grammar.h) that says that this needs to be executed recursively (allocating new data members for the newly assigned object).
operator==()
bool SgInitializedName::operator== (const SgInitializedName &) const
Equal operator : it checks if all the data members are the same or point to the same objects.
What really happens It returns false all the time.
get_declaration()
bool SgInitializedName::get_declaration () const
Equal operator : it checks if all the data members are the same or point to the same objects.
Returns
Pointer to SgDeclarationStatement
Referenced by SageInterface::set_name().
get_symbol_from_symbol_table()
SgInitializedName::get_symbol_from_symbol_table () const
Get the associated SgSymbol from the symbol table located in the scope, without considering possible prev_decl_item. Internal use only. Users should use search_for_symbol_from_symbol_table() instead.
FOR INTERNAL USE Get the associated symbol from the symbol table in the stored scope. Users should use the SgInitializedName::search_for_symbol_from_symbol_table() instead.
Referenced by SageBuilder::buildVarRefExp(), SageInterface::deleteAST(), SageInterface::isCanonicalDoLoop(), SageInterface::isCanonicalForLoop(), SageInterface::loopUnrolling(), SageInterface::mergeAssignmentWithDeclaration(), and SageInterface::mergeDeclarationWithAssignment().
fixupCopy_scopes()
virtual void SgInitializedName::fixupCopy_scopes (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
fixupCopy_symbols()
virtual void SgInitializedName::fixupCopy_symbols (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
fixupCopy_references()
virtual void SgInitializedName::fixupCopy_references (SgNode * copy, SgCopyHelp & help) const override virtual
Reimplemented from SgLocatedNode.
addNewAttribute()
virtual void SgInitializedName::addNewAttribute (std::string s, AstAttribute * a) override virtual
Add a new attribute represented by the named string.
Reimplemented from SgLocatedNode.
getAttribute()
virtual AstAttribute * SgInitializedName::getAttribute (std::string s) const override virtual
Returns attribute of name 's'.
Reimplemented from SgLocatedNode.
updateAttribute()
virtual void SgInitializedName::updateAttribute (std::string s, AstAttribute * a) override virtual
Replace existing attribute of name 's' with new AstAttribute.
Reimplemented from SgLocatedNode.
setAttribute()
virtual void SgInitializedName::setAttribute (std::string s, AstAttribute * a) override virtual
This is a wrapper function with the following semantics: if no attribute of name 's' exists then addNewAttribute(s,a); is called, otherwise updateAttribute(s,a); is called.
Reimplemented from SgLocatedNode.
removeAttribute()
virtual void SgInitializedName::removeAttribute (std::string s) override virtual
Remove attribute of name 's' if present.
Reimplemented from SgLocatedNode.
attributeExists()
virtual bool SgInitializedName::attributeExists (std::string s) const override virtual
Tests if attribute of name 's' is present.
Reimplemented from SgLocatedNode.
numberOfAttributes()
virtual int SgInitializedName::numberOfAttributes () const override virtual
Returns the number of attributes on this IR node.
Reimplemented from SgLocatedNode.
class_name()
virtual std::string SgInitializedName::class_name () const override virtual
returns a string representing the class name
Reimplemented from SgLocatedNodeSupport.
Referenced by SageInterface::outputFileIds().
variantT()
virtual VariantT SgInitializedName::variantT () const override virtual
returns new style SageIII enum values
Reimplemented from SgLocatedNodeSupport.
operator delete()
void SgInitializedName::operator delete (void * pointer) inline
Definition at line 175522 of file Cxx_Grammar.h.
get_traversalSuccessorContainer()
virtual std::vector< SgNode * > SgInitializedName::get_traversalSuccessorContainer () override virtual
container of pointers to AST successor nodes used in the traversal overridden in every class by generated implementation
Reimplemented from SgLocatedNodeSupport.
get_traversalSuccessorNamesContainer()
virtual std::vector< std::string > SgInitializedName::get_traversalSuccessorNamesContainer () override virtual
container of names of variables or container indices used used in the traversal to access AST successor nodes overridden in every class by generated implementation
Reimplemented from SgLocatedNodeSupport.
get_numberOfTraversalSuccessors()
virtual size_t SgInitializedName::get_numberOfTraversalSuccessors () override virtual
return number of children in the traversal successor list
Reimplemented from SgLocatedNodeSupport.
get_traversalSuccessorByIndex()
virtual SgNode * SgInitializedName::get_traversalSuccessorByIndex (size_t idx) override virtual
index-based access to traversal successors by index number
Reimplemented from SgLocatedNodeSupport.
get_childIndex()
virtual size_t SgInitializedName::get_childIndex (SgNode * child) override virtual
index-based access to traversal successors by child node
Reimplemented from SgLocatedNodeSupport.
roseRTI()
virtual RTIReturnType SgInitializedName::roseRTI () override virtual
return C++ Runtime-Time-Information
Reimplemented from SgLocatedNodeSupport.
sage_class_name()
virtual const char * SgInitializedName::sage_class_name () const override virtual
returns a C style string (char*) representing the class name
Reimplemented from SgLocatedNodeSupport.
accept()
virtual void SgInitializedName::accept (ROSE_VisitorPattern & visitor) override virtual
support for the classic visitor pattern done in GoF
Reimplemented from SgLocatedNodeSupport.
isInMemoryPool()
virtual bool SgInitializedName::isInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgLocatedNodeSupport.
checkDataMemberPointersIfInMemoryPool()
virtual void SgInitializedName::checkDataMemberPointersIfInMemoryPool () override virtual
FOR INTERNAL USE This is used in internal tests to verify that all IR nodes are allocated from the heap.
The AST File I/O depends upon the allocation of IR nodes being from the heap, stack based or global IR nodes should not appear in the AST if it will be written out to a file and read back in. To enforce this concept, this function implements a test to verify that the IR node can be found on the heap and is part of a larger test of the whole AST. This test must pass before the AST can be written out to a file. This is part of a compromise in the design of the AST File I/O to support binary streaming of data to files; for performance. It is also rather difficult, but possible, to build a useful AST with IR nodes allocated on the stack or frm global scope, this test filters out such cased from being used with the AST File I/O mechanism.
Reimplemented from SgLocatedNodeSupport.
returnDataMemberPointers()
virtual std::vector< std::pair< SgNode *, std::string > > SgInitializedName::returnDataMemberPointers () const override virtual
FOR INTERNAL USE Returns STL vector of pairs of SgNode* and strings for use in AST tools
This functions is part of general support for many possible tools to operate on the AST. The forms a list of ALL IR node pointers used by each IR node, and is a supperset of the get_traversalSuccessorContainer(). It is (I think) less than the set of pointers used by the AST file I/O. This is part of work implemented by Andreas, and support tools such as the AST graph generation.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Returns
STL vector of pairs of SgNode* and strings
Reimplemented from SgLocatedNodeSupport.
processDataMemberReferenceToPointers()
virtual void SgInitializedName::processDataMemberReferenceToPointers (ReferenceToPointerHandler *) override virtual
FOR INTERNAL USE Processes pairs of references to SgNode* and strings for use in AST tools
This functions similar to returnDataMemberPointers() except that it passes references to a handler object. As a result there is FAR more damage that can be done by using this function, but it is type-safe. This is provided for support of internal tools that operate on the AST, e.g the AST Merge mechanism.
Warning
This function can return unexpected data members and thus the order and the number of elements is unpredicable and subject to change.
Reimplemented from SgLocatedNodeSupport.
getChildIndex()
virtual long SgInitializedName::getChildIndex (SgNode * childNode) const override virtual
FOR INTERNAL USE Returns a unique index value for the childNode in the list of children at this IR node.
This function returns a unique value for the input childNode in set of children at this IR node. Note that a negative value indicates that the input node is not a child. This is the basis for the implementation of the isChild(SgNode*) member function. Data members that are NULL in the IR node are counted internally (so that this function returns value that could be statically defined, and so are not dynamically determined).
Warning
The mapping on children to integer values could change from release to release of ROSE.
Returns
long
Reimplemented from SgLocatedNodeSupport.
addRegExpAttribute()
SgInitializedName * SgInitializedName::addRegExpAttribute (std::string s, AstRegExAttribute * a)
Support for AST matching using regular expression.
This support is incomplete and the subject of current research to define RegEx trees to support inexact matching.
Member Data Documentation
p_name
SgInitializedName::p_name protected
The variable that is declared in this declaration.
variable x
This is a SgName object which represents the variable that is being declared in this SgInitializedName object. For example, if there is a "int x" declaration in the code, "x" is the variable that will be stored in SgInitializedName::p_name as a SgName object.
detailed variable x
Definition at line 176010 of file Cxx_Grammar.h.
p_microsoft_uuid_string
std::string SgInitializedName::p_microsoft_uuid_string protected
Definition at line 176014 of file Cxx_Grammar.h.
p_typeptr
SgInitializedName::p_typeptr protected
Pointer to a type object that has been associated with SgInitializedName::p_name.
This is a pointer that points to an SgType object that represents the type the variable SgInitializedName::p_name declared in this SgInitializedName class (in this declaration). For example, if the variable is of type "int" (as in "int x"), then a SgTypeInt object has to be allocated , and a pointer to this SgTypeInt object has to be stored in SgInitializedName::p_typeptr to represent the type of SgInitializedName::p_name.
Definition at line 176018 of file Cxx_Grammar.h.
p_initptr
SgInitializedName::p_initptr protected
Pointer to an initializer for the variable.
In the case that the declaration contains an initializer for the variable, for example "int x=5" or "int x=y" (in these cases the intializers for the declared variable are "5" and "y"), that initializer has to be stored in SgInitializedName::p_initptr as a pointer that points to the SgInitializer object that the SgInitializedName::p_name variable is initialized with.
Definition at line 176022 of file Cxx_Grammar.h.
p_prev_decl_item
SgInitializedName::p_prev_decl_item protected
Pointer to the initial uses of this variable previous to its redeclaration declaration.
Dan's intuitive explanation This pointer references any initialized name previously built to define a SgVarRefExp, which requires a pointer to a variable declaration (but points to a SgInitializedName since a SgVariableDeclaration could stand for many variables (not just one, e.g. "int x,y,z;"), since uniqueness is required. Although non-intuative, C++ code defined within a class definition can reference variables before they are defined (e.g. "class X { int foo() { return x; } int x; };"), see test2005_67.C (non-static data member) and test2005_68.C (static data member).
It is also used by a SgInitializedName in a static declaration outside the class to refer to the preliminary declaration inside the class. (e.g. "class X { static int a;}; int X::a = 0; };")
Definition at line 176026 of file Cxx_Grammar.h.
p_is_initializer
SgInitializedName::p_is_initializer protected
flag to determine whether the declaration has an initializer.
If the declaration has an initializer, for example "int x=5", then this flag is set to true. The flag is set to false otherwise.
Definition at line 176030 of file Cxx_Grammar.h.
p_declptr
SgInitializedName::p_declptr protected
Pointer to the declaration object where this SgInitializedName object belongs to.
Alin's intuitive explanation
Each SgInitializedName object contains the declaration of one variable. In the case where the code has more declarations in a single statement, for example "int x=5,y=3;", that declaration is composed of two SgInitializedName objects, one for each variable declared in that statment. So, this SgInitializedName::p_declptr points to the statement (actually the declaration - SgDeclaration) that contains it.
What really happens
For the first SgInitializedName, this points to the the SgDeclarationStatement that contains this SgInitializedName. For the second one, it is set to an unknown SgDeclarationStatement that does not show up in the pdf or the dot files (not traversed).
Dan's explaination
This points to the SgVariableDefinition and is the same as get_definition().
Definition at line 176034 of file Cxx_Grammar.h.
p_storageModifier
SgInitializedName::p_storageModifier protected
This is the storage modifier (static, auto, register, mutable, asm, etc.).
This is the storage modifier (static, auto, register, mutable, asm, etc.), see complete list in source code for more details. This is an implementation of the modifier system as outlined in appendix A of Bjarne's book.
Definition at line 176038 of file Cxx_Grammar.h.
p_scope
SgInitializedName::p_scope protected
This pointer is always valid and stores the current scope of the variable.
This is the current scope of the variable (required because variables can be defined separately from their declaration). See test2004_133.C (approx).
Definition at line 176042 of file Cxx_Grammar.h.
p_preinitialization
SgInitializedName::p_preinitialization protected
This data member stores an enum value.
This value is set based on an enum value to indicate the type of use of the initialized name (valid values are: virtual base class, non-virtual base, data member).
Definition at line 176046 of file Cxx_Grammar.h.
p_isCoArray
bool SgInitializedName::p_isCoArray protected
Definition at line 176050 of file Cxx_Grammar.h.
p_register_name_code
SgInitializedName::p_register_name_code protected
Code (following GNU standard) for register name.
This value is set based on an enum value of GNU standard codes mappings to register names.
Definition at line 176054 of file Cxx_Grammar.h.
p_excess_specifier
SgInitializedName::excess_specifier_enum SgInitializedName::p_excess_specifier protected
Definition at line 176058 of file Cxx_Grammar.h.
p_register_name_string
std::string SgInitializedName::p_register_name_string protected
Definition at line 176062 of file Cxx_Grammar.h.
p_requiresGlobalNameQualificationOnType
bool SgInitializedName::p_requiresGlobalNameQualificationOnType protected
Definition at line 176066 of file Cxx_Grammar.h.
p_shapeDeferred
bool SgInitializedName::p_shapeDeferred protected
Definition at line 176070 of file Cxx_Grammar.h.
p_initializationDeferred
bool SgInitializedName::p_initializationDeferred protected
Definition at line 176074 of file Cxx_Grammar.h.
p_gnu_attribute_modifierVector
SgBitVector SgInitializedName::p_gnu_attribute_modifierVector protected
Definition at line 176078 of file Cxx_Grammar.h.
p_gnu_attribute_initialization_priority
unsigned long int SgInitializedName::p_gnu_attribute_initialization_priority protected
Definition at line 176082 of file Cxx_Grammar.h.
p_gnu_attribute_named_weak_reference
std::string SgInitializedName::p_gnu_attribute_named_weak_reference protected
Definition at line 176086 of file Cxx_Grammar.h.
p_gnu_attribute_named_alias
std::string SgInitializedName::p_gnu_attribute_named_alias protected
Definition at line 176090 of file Cxx_Grammar.h.
p_gnu_attribute_cleanup_function
std::string SgInitializedName::p_gnu_attribute_cleanup_function protected
Definition at line 176094 of file Cxx_Grammar.h.
p_gnu_attribute_section_name
std::string SgInitializedName::p_gnu_attribute_section_name protected
Definition at line 176098 of file Cxx_Grammar.h.
p_gnu_attribute_alignment
int SgInitializedName::p_gnu_attribute_alignment protected
Definition at line 176102 of file Cxx_Grammar.h.
p_gnu_attribute_visability
SgDeclarationModifier::gnu_declaration_visability_enum SgInitializedName::p_gnu_attribute_visability protected
Definition at line 176106 of file Cxx_Grammar.h.
p_protected_declaration
bool SgInitializedName::p_protected_declaration protected
Definition at line 176110 of file Cxx_Grammar.h.
p_name_qualification_length
int SgInitializedName::p_name_qualification_length protected
Definition at line 176114 of file Cxx_Grammar.h.
p_type_elaboration_required
bool SgInitializedName::p_type_elaboration_required protected
Definition at line 176118 of file Cxx_Grammar.h.
p_global_qualification_required
bool SgInitializedName::p_global_qualification_required protected
Definition at line 176122 of file Cxx_Grammar.h.
p_name_qualification_length_for_type
int SgInitializedName::p_name_qualification_length_for_type protected
Definition at line 176126 of file Cxx_Grammar.h.
p_type_elaboration_required_for_type
bool SgInitializedName::p_type_elaboration_required_for_type protected
Definition at line 176130 of file Cxx_Grammar.h.
p_global_qualification_required_for_type
bool SgInitializedName::p_global_qualification_required_for_type protected
Definition at line 176134 of file Cxx_Grammar.h.
p_hasArrayTypeWithEmptyBracketSyntax
bool SgInitializedName::p_hasArrayTypeWithEmptyBracketSyntax protected
Definition at line 176138 of file Cxx_Grammar.h.
p_using_C11_Alignas_keyword
bool SgInitializedName::p_using_C11_Alignas_keyword protected
Definition at line 176142 of file Cxx_Grammar.h.
p_constant_or_type_argument_for_Alignas_keyword
SgNode* SgInitializedName::p_constant_or_type_argument_for_Alignas_keyword protected
Definition at line 176146 of file Cxx_Grammar.h.
p_using_auto_keyword
bool SgInitializedName::p_using_auto_keyword protected
Definition at line 176150 of file Cxx_Grammar.h.
p_auto_decltype
SgType* SgInitializedName::p_auto_decltype protected
Definition at line 176154 of file Cxx_Grammar.h.
p_using_device_keyword
bool SgInitializedName::p_using_device_keyword protected
Definition at line 176158 of file Cxx_Grammar.h.
p_is_braced_initialized
bool SgInitializedName::p_is_braced_initialized protected
Definition at line 176162 of file Cxx_Grammar.h.
p_using_assignment_copy_constructor_syntax
bool SgInitializedName::p_using_assignment_copy_constructor_syntax protected
Definition at line 176166 of file Cxx_Grammar.h.
p_needs_definitions
bool SgInitializedName::p_needs_definitions protected
Definition at line 176170 of file Cxx_Grammar.h.
p_is_parameter_pack
bool SgInitializedName::p_is_parameter_pack protected
Definition at line 176174 of file Cxx_Grammar.h.
p_is_pack_element
bool SgInitializedName::p_is_pack_element protected
Definition at line 176178 of file Cxx_Grammar.h.
The documentation for this class was generated from the following files:
Cxx_Grammar.h
SgInitializedName.docs