ROSE: SageInterface::Ada::AggregateInfo Struct Reference
SageInterface::Ada::AggregateInfo Struct Reference
Description
Definition at line 716 of file sageInterfaceAda.h.
Public Types
using base = AggregateInfoBase
Public Member Functions
SgAdaAncestorInitializer * ancestor () const
returns the ancestor initializer iff it exists, otherwise null
SgExpressionPtrList::const_iterator begin () const
returns the remaining range-begin without the ancestor initializer (if it existed)
SgExpressionPtrList::const_iterator end () const
returns the underlying's list end iterator
bool nullRecord () const
returns if the remaining range (w/o the ancestor initializer) indicates a null record.
Member Typedef Documentation
base
using SageInterface::Ada::AggregateInfo::base = AggregateInfoBase
Definition at line 718 of file sageInterfaceAda.h.
Member Function Documentation
ancestor()
SgAdaAncestorInitializer * SageInterface::Ada::AggregateInfo::ancestor () const inline
returns the ancestor initializer iff it exists, otherwise null
Definition at line 722 of file sageInterfaceAda.h.
begin()
SgExpressionPtrList::const_iterator SageInterface::Ada::AggregateInfo::begin () const inline
returns the remaining range-begin without the ancestor initializer (if it existed)
Definition at line 725 of file sageInterfaceAda.h.
Referenced by nullRecord().
end()
SgExpressionPtrList::const_iterator SageInterface::Ada::AggregateInfo::end () const inline
returns the underlying's list end iterator
Definition at line 728 of file sageInterfaceAda.h.
Referenced by nullRecord().
nullRecord()
bool SageInterface::Ada::AggregateInfo::nullRecord () const inline
returns if the remaining range (w/o the ancestor initializer) indicates a null record.
Definition at line 731 of file sageInterfaceAda.h.
References begin(), and end().
The documentation for this struct was generated from the following file:
sageInterfaceAda.h