var MatchOperation_8h =
[
    [ "SingleMatchResult", "structSingleMatchResult.html", "structSingleMatchResult" ],
    [ "MatchStatus", "classMatchStatus.html", "classMatchStatus" ],
    [ "MatchOperation", "classMatchOperation.html", "classMatchOperation" ],
    [ "MatchOpSequence", "classMatchOpSequence.html", "classMatchOpSequence" ],
    [ "MatchOpOr", "classMatchOpOr.html", "classMatchOpOr" ],
    [ "MatchOpVariableAssignment", "classMatchOpVariableAssignment.html", "classMatchOpVariableAssignment" ],
    [ "MatchOpCheckNode", "classMatchOpCheckNode.html", "classMatchOpCheckNode" ],
    [ "MatchOpCheckNodeSet", "classMatchOpCheckNodeSet.html", "classMatchOpCheckNodeSet" ],
    [ "MatchOpArityCheck", "classMatchOpArityCheck.html", "classMatchOpArityCheck" ],
    [ "MatchOpForward", "classMatchOpForward.html", "classMatchOpForward" ],
    [ "MatchOpSkipChildOnForward", "classMatchOpSkipChildOnForward.html", "classMatchOpSkipChildOnForward" ],
    [ "MatchOpMarkNode", "classMatchOpMarkNode.html", "classMatchOpMarkNode" ],
    [ "MatchOpCheckNull", "classMatchOpCheckNull.html", "classMatchOpCheckNull" ],
    [ "MatchOpDotDot", "classMatchOpDotDot.html", "classMatchOpDotDot" ],
    [ "MatchOpBinaryOp", "classMatchOpBinaryOp.html", "classMatchOpBinaryOp" ],
    [ "MatchOpUnaryOp", "classMatchOpUnaryOp.html", "classMatchOpUnaryOp" ],
    [ "MatchOpConstant", "classMatchOpConstant.html", "classMatchOpConstant" ],
    [ "MatchOpAccessVariable", "classMatchOpAccessVariable.html", "classMatchOpAccessVariable" ],
    [ "MatchOpAccessRoseAstAttribute", "classMatchOpAccessRoseAstAttribute.html", "classMatchOpAccessRoseAstAttribute" ],
    [ "MatchOpAccessUserAstAttribute", "classMatchOpAccessUserAstAttribute.html", "classMatchOpAccessUserAstAttribute" ],
    [ "MatchOperationList", "MatchOperation_8h.html#ad5f534adbc66805e3b45bdfba04f2b4a", null ],
    [ "MatchOperationListList", "MatchOperation_8h.html#ade2a99e8abf0d6b0ca048340bbfaed11", null ],
    [ "MatchResult", "MatchOperation_8h.html#a5d2a44f423ba0ee78806f362a15fa847", null ],
    [ "SingleMatchMarkedLocation", "MatchOperation_8h.html#ad0e274dc665b5a3b977aa045c229e5e3", null ],
    [ "SingleMatchMarkedLocations", "MatchOperation_8h.html#aa5dc3feb531dfb6ac893bd9a8f4515fd", null ],
    [ "SingleMatchVarBindings", "MatchOperation_8h.html#a7468331a68b0780f0ef60aa43ca27df2", null ]
];