var searchData=
[
  ['oarifg',['OARIFG',['../classOARIFG.html',1,'']]],
  ['oarifgedgeiterator',['OARIFGEdgeIterator',['../classOARIFGEdgeIterator.html',1,'']]],
  ['oarifgnodeiterator',['OARIFGNodeIterator',['../classOARIFGNodeIterator.html',1,'']]],
  ['object_5fhelper',['object_helper',['../structRose_1_1CodeGen_1_1object__helper.html',1,'Rose::CodeGen']]],
  ['object_5fhelper_3c_20object_3a_3aa_5fclass_20_3e',['object_helper&lt; Object::a_class &gt;',['../structRose_1_1CodeGen_1_1object__helper_3_01Object_1_1a__class_01_4.html',1,'Rose::CodeGen']]],
  ['object_5fhelper_3c_20object_3a_3aa_5ffunction_20_3e',['object_helper&lt; Object::a_function &gt;',['../structRose_1_1CodeGen_1_1object__helper_3_01Object_1_1a__function_01_4.html',1,'Rose::CodeGen']]],
  ['object_5fhelper_3c_20object_3a_3aa_5fnamespace_20_3e',['object_helper&lt; Object::a_namespace &gt;',['../structRose_1_1CodeGen_1_1object__helper_3_01Object_1_1a__namespace_01_4.html',1,'Rose::CodeGen']]],
  ['object_5fhelper_3c_20object_3a_3aa_5ftypedef_20_3e',['object_helper&lt; Object::a_typedef &gt;',['../structRose_1_1CodeGen_1_1object__helper_3_01Object_1_1a__typedef_01_4.html',1,'Rose::CodeGen']]],
  ['object_5fhelper_3c_20object_3a_3aa_5fvariable_20_3e',['object_helper&lt; Object::a_variable &gt;',['../structRose_1_1CodeGen_1_1object__helper_3_01Object_1_1a__variable_01_4.html',1,'Rose::CodeGen']]],
  ['objectsallocatedattr',['ObjectsAllocatedAttr',['../structObjectsAllocatedAttr.html',1,'']]],
  ['objset',['ObjSet',['../classAbstractMemoryObject_1_1ObjSet.html',1,'AbstractMemoryObject']]],
  ['objsetfactory',['ObjSetFactory',['../classAbstractMemoryObject_1_1ObjSetFactory.html',1,'AbstractMemoryObject']]],
  ['observable',['Observable',['../classRoseHPCT_1_1Observable.html',1,'RoseHPCT']]],
  ['observeimpl',['ObserveImpl',['../classCompSlice_1_1ObserveImpl.html',1,'CompSlice::ObserveImpl'],['../classCompSliceNest_1_1ObserveImpl.html',1,'CompSliceNest::ObserveImpl']]],
  ['observeinfo',['ObserveInfo',['../classObserveInfo.html',1,'']]],
  ['observeinfo_3c_20astobserver_20_3e',['ObserveInfo&lt; AstObserver &gt;',['../classObserveInfo.html',1,'']]],
  ['observeinfo_3c_20compslicenestobserver_20_3e',['ObserveInfo&lt; CompSliceNestObserver &gt;',['../classObserveInfo.html',1,'']]],
  ['observeinfo_3c_20compsliceobserver_20_3e',['ObserveInfo&lt; CompSliceObserver &gt;',['../classObserveInfo.html',1,'']]],
  ['observeinfo_3c_20looptreeobserver_20_3e',['ObserveInfo&lt; LoopTreeObserver &gt;',['../classObserveInfo.html',1,'']]],
  ['observeinfo_3c_20multigraphobserver_20_3e',['ObserveInfo&lt; MultiGraphObserver &gt;',['../classObserveInfo.html',1,'']]],
  ['observeobject',['ObserveObject',['../classObserveObject.html',1,'']]],
  ['observeobject_3c_20astobserver_20_3e',['ObserveObject&lt; AstObserver &gt;',['../classObserveObject.html',1,'']]],
  ['observeobject_3c_20compslicenestobserver_20_3e',['ObserveObject&lt; CompSliceNestObserver &gt;',['../classObserveObject.html',1,'']]],
  ['observeobject_3c_20compsliceobserver_20_3e',['ObserveObject&lt; CompSliceObserver &gt;',['../classObserveObject.html',1,'']]],
  ['observeobject_3c_20looptreeobserver_20_3e',['ObserveObject&lt; LoopTreeObserver &gt;',['../classObserveObject.html',1,'']]],
  ['observeobject_3c_20multigraphobserver_20_3e',['ObserveObject&lt; MultiGraphObserver &gt;',['../classObserveObject.html',1,'']]],
  ['observetransform',['ObserveTransform',['../classObserveTransform.html',1,'']]],
  ['ok',['Ok',['../classSawyer_1_1Ok.html',1,'Sawyer']]],
  ['ok_3c_20char_5bn_5d_3e',['Ok&lt; char[N]&gt;',['../classSawyer_1_1Ok_3_01char[N]_4.html',1,'Sawyer']]],
  ['ompattribute',['OmpAttribute',['../classOmpSupport_1_1OmpAttribute.html',1,'OmpSupport']]],
  ['ompattributelist',['OmpAttributeList',['../classOmpSupport_1_1OmpAttributeList.html',1,'OmpSupport']]],
  ['one_5fsymbol',['one_symbol',['../structone__symbol.html',1,'']]],
  ['oneparamater',['OneParamater',['../structOneParamater.html',1,'']]],
  ['onlynoncompilergenerated',['OnlyNonCompilerGenerated',['../structOnlyNonCompilerGenerated.html',1,'']]],
  ['opapplicator',['OPApplicator',['../classOPApplicator.html',1,'']]],
  ['opdescriptortemp',['OPDescriptorTemp',['../classOPDescriptorTemp.html',1,'']]],
  ['opdescriptortemp_3c_20closedescriptor_3c_20symbolicvaldescriptor_2c_20_27_7b_27_2c_20_27_7d_27_3e_20_3e',['OPDescriptorTemp&lt; CloseDescriptor&lt; SymbolicValDescriptor, &apos;{&apos;, &apos;}&apos;&gt; &gt;',['../classOPDescriptorTemp.html',1,'']]],
  ['opdescriptortemp_3c_20collectpair_3c_20closedescriptor_3c_20symbolicvaldescriptor_2c_20_27_28_27_2c_20_27_29_27_3e_2c_20arraydescriptor_2c_200_20_3e_20_3e',['OPDescriptorTemp&lt; CollectPair&lt; CloseDescriptor&lt; SymbolicValDescriptor, &apos;(&apos;, &apos;)&apos;&gt;, ArrayDescriptor, 0 &gt; &gt;',['../classOPDescriptorTemp.html',1,'']]],
  ['opdescriptortemp_3c_20collectpair_3c_20containerdescriptor_3c_20std_3a_3alist_3c_20symbolicvaldescriptor_20_3e_2c_20symbolicvaldescriptor_2c_20_27_2c_27_2c_20_27_28_27_2c_20_27_29_27_3e_2c_20arraydescriptor_2c_200_20_3e_20_3e',['OPDescriptorTemp&lt; CollectPair&lt; ContainerDescriptor&lt; std::list&lt; SymbolicValDescriptor &gt;, SymbolicValDescriptor, &apos;,&apos;, &apos;(&apos;, &apos;)&apos;&gt;, ArrayDescriptor, 0 &gt; &gt;',['../classOPDescriptorTemp.html',1,'']]],
  ['opdescriptortemp_3c_20containerdescriptor_3c_20std_3a_3alist_3c_20restrictvaluedescriptor_20_3e_2c_20restrictvaluedescriptor_2c_20_27_3b_27_2c_20_27_7b_27_2c_20_27_7d_27_3e_20_3e',['OPDescriptorTemp&lt; ContainerDescriptor&lt; std::list&lt; RestrictValueDescriptor &gt;, RestrictValueDescriptor, &apos;;&apos;, &apos;{&apos;, &apos;}&apos;&gt; &gt;',['../classOPDescriptorTemp.html',1,'']]],
  ['opdescriptortemp_3c_20setdescriptor_3c_20symbolicvaldescriptor_2c_20_27_2c_27_2c_27_7b_27_2c_27_7d_27_3e_20_3e',['OPDescriptorTemp&lt; SetDescriptor&lt; SymbolicValDescriptor, &apos;,&apos;,&apos;{&apos;,&apos;}&apos;&gt; &gt;',['../classOPDescriptorTemp.html',1,'']]],
  ['operationcountingtraversal',['OperationCountingTraversal',['../classArithmeticIntensityMeasurement_1_1OperationCountingTraversal.html',1,'ArithmeticIntensityMeasurement']]],
  ['operationexception',['OperationException',['../classSawyer_1_1Yaml_1_1OperationException.html',1,'Sawyer::Yaml']]],
  ['operatoraliasannotation',['OperatorAliasAnnotation',['../classOperatorAliasAnnotation.html',1,'']]],
  ['operatoraliascollection',['OperatorAliasCollection',['../classOperatorAliasCollection.html',1,'']]],
  ['operatorallowaliascollection',['OperatorAllowAliasCollection',['../classOperatorAllowAliasCollection.html',1,'']]],
  ['operatorannotcollection',['OperatorAnnotCollection',['../classOperatorAnnotCollection.html',1,'']]],
  ['operatorannotcollection_3c_20arrayconstructdescriptor_20_3e',['OperatorAnnotCollection&lt; ArrayConstructDescriptor &gt;',['../classOperatorAnnotCollection.html',1,'']]],
  ['operatorannotcollection_3c_20arraymodifydescriptor_20_3e',['OperatorAnnotCollection&lt; ArrayModifyDescriptor &gt;',['../classOperatorAnnotCollection.html',1,'']]],
  ['operatorannotcollection_3c_20operatoraliasdescriptor_20_3e',['OperatorAnnotCollection&lt; OperatorAliasDescriptor &gt;',['../classOperatorAnnotCollection.html',1,'']]],
  ['operatorannotcollection_3c_20operatorinlinedescriptor_20_3e',['OperatorAnnotCollection&lt; OperatorInlineDescriptor &gt;',['../classOperatorAnnotCollection.html',1,'']]],
  ['operatorannotcollection_3c_20operatorsideeffectdescriptor_20_3e',['OperatorAnnotCollection&lt; OperatorSideEffectDescriptor &gt;',['../classOperatorAnnotCollection.html',1,'']]],
  ['operatorannotcollection_3c_20restrictvalueopdescriptor_20_3e',['OperatorAnnotCollection&lt; RestrictValueOpDescriptor &gt;',['../classOperatorAnnotCollection.html',1,'']]],
  ['operatorcallinfocollection',['OperatorCallInfoCollection',['../classOperatorCallInfoCollection.html',1,'']]],
  ['operatorcallsupplement',['OperatorCallSupplement',['../structAda__ROSE__Translation_1_1OperatorCallSupplement.html',1,'Ada_ROSE_Translation::OperatorCallSupplement'],['../structLibadalang__ROSE__Translation_1_1OperatorCallSupplement.html',1,'Libadalang_ROSE_Translation::OperatorCallSupplement']]],
  ['operatordeclaration',['OperatorDeclaration',['../classOperatorDeclaration.html',1,'']]],
  ['operatordesc',['OperatorDesc',['../structAda__ROSE__Translation_1_1OperatorDesc.html',1,'Ada_ROSE_Translation::OperatorDesc'],['../structLibadalang__ROSE__Translation_1_1OperatorDesc.html',1,'Libadalang_ROSE_Translation::OperatorDesc']]],
  ['operatorinlineannotation',['OperatorInlineAnnotation',['../classOperatorInlineAnnotation.html',1,'']]],
  ['operatorinlinedescriptor',['OperatorInlineDescriptor',['../classOperatorInlineDescriptor.html',1,'']]],
  ['operatorinlinerewrite',['OperatorInlineRewrite',['../classOperatorInlineRewrite.html',1,'']]],
  ['operatorkey',['OperatorKey',['../structAda__ROSE__Translation_1_1OperatorKey.html',1,'Ada_ROSE_Translation::OperatorKey'],['../structLibadalang__ROSE__Translation_1_1OperatorKey.html',1,'Libadalang_ROSE_Translation::OperatorKey']]],
  ['operatorkillinfocollection',['OperatorKillInfoCollection',['../classOperatorKillInfoCollection.html',1,'']]],
  ['operatormodinfocollection',['OperatorModInfoCollection',['../classOperatorModInfoCollection.html',1,'']]],
  ['operatorreadinfocollection',['OperatorReadInfoCollection',['../classOperatorReadInfoCollection.html',1,'']]],
  ['operatorscopeinfo',['OperatorScopeInfo',['../structSageInterface_1_1Ada_1_1OperatorScopeInfo.html',1,'SageInterface::Ada']]],
  ['operatorsideeffectannotation',['OperatorSideEffectAnnotation',['../classOperatorSideEffectAnnotation.html',1,'']]],
  ['operatorsideeffectdescriptor',['OperatorSideEffectDescriptor',['../classOperatorSideEffectDescriptor.html',1,'']]],
  ['ophelpvisitor',['OPHelpVisitor',['../classOPHelpVisitor.html',1,'']]],
  ['optimizelooptreeimpl',['OptimizeLoopTreeImpl',['../classOptimizeLoopTreeImpl.html',1,'']]],
  ['optional',['Optional',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20a_20_3e',['Optional&lt; A &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20alignment_20_3e',['Optional&lt; Alignment &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20double_20_3e',['Optional&lt; double &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20enabled_20_3e',['Optional&lt; Enabled &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20importance_20_3e',['Optional&lt; Importance &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20int_20_3e',['Optional&lt; int &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20label_20_3e',['Optional&lt; Label &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20rose_3a_3acolor_3a_3ahsv_20_3e',['Optional&lt; Rose::Color::HSV &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20sawyer_3a_3acontainer_3a_3aalgorithm_3a_3agraphtraversal_3a_3awork_20_3e',['Optional&lt; Sawyer::Container::Algorithm::GraphTraversal::Work &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20sawyer_3a_3acontainer_3a_3ainterval_20_3e',['Optional&lt; Sawyer::Container::Interval &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20sawyer_3a_3aerror_3c_20e_20_3e_20_3e',['Optional&lt; Sawyer::Error&lt; E &gt; &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20size_5ft_20_3e',['Optional&lt; size_t &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20std_3a_3astring_20_3e',['Optional&lt; std::string &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20std_3a_3avector_3c_20std_3a_3astring_20_3e_20_3e',['Optional&lt; std::vector&lt; std::string &gt; &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20theme_20_3e',['Optional&lt; Theme &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20tokenenum_20_3e',['Optional&lt; TokenEnum &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20unsigned_20_3e',['Optional&lt; unsigned &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optional_3c_20value_20_3e',['Optional&lt; Value &gt;',['../classSawyer_1_1Optional.html',1,'Sawyer']]],
  ['optiondeclaration',['OptionDeclaration',['../classOptionDeclaration.html',1,'']]],
  ['options',['Options',['../classRose_1_1Options.html',1,'Rose']]],
  ['options_5fdescription',['options_description',['../structSawyer_1_1CommandLine_1_1Boost_1_1options__description.html',1,'Sawyer::CommandLine::Boost']]],
  ['optregistrytype',['OptRegistryType',['../classLoopTransformOptions_1_1OptRegistryType.html',1,'LoopTransformOptions']]],
  ['optspec',['OptSpec',['../classOptSpec.html',1,'']]],
  ['opvisitor',['OPVisitor',['../classOPVisitor.html',1,'']]],
  ['or_5ft',['or_t',['../structRose_1_1metaprog_1_1details_1_1or__t.html',1,'Rose::metaprog::details::or_t&lt; L, R, bool &gt;'],['../structRose_1_1metaprog_1_1or__t.html',1,'Rose::metaprog::or_t&lt; L, R &gt;']]],
  ['or_5ft_3c_20l_2c_20r_20_3e',['or_t&lt; L, R &gt;',['../structRose_1_1metaprog_1_1details_1_1or__t.html',1,'Rose::metaprog::details']]],
  ['or_5ft_3c_20l_2c_20r_2c_20false_20_3e',['or_t&lt; L, R, false &gt;',['../structRose_1_1metaprog_1_1details_1_1or__t_3_01L_00_01R_00_01false_01_4.html',1,'Rose::metaprog::details']]],
  ['or_5ft_3c_20l_2c_20void_2c_20false_20_3e',['or_t&lt; L, void, false &gt;',['../structRose_1_1metaprog_1_1details_1_1or__t_3_01L_00_01void_00_01false_01_4.html',1,'Rose::metaprog::details']]],
  ['orbits',['OrBits',['../structSawyer_1_1Container_1_1BitVectorSupport_1_1OrBits.html',1,'Sawyer::Container::BitVectorSupport']]],
  ['origloopfusionanal',['OrigLoopFusionAnal',['../classOrigLoopFusionAnal.html',1,'']]],
  ['oropgenerator',['OrOpGenerator',['../classSageInterface_1_1OrOpGenerator.html',1,'SageInterface']]],
  ['osfixup_5ftype',['osfixup_type',['../structSgAsmNERelocEntry_1_1osfixup__type.html',1,'SgAsmNERelocEntry']]],
  ['outdatetracevars',['OutdateTraceVars',['../classOutdateTraceVars.html',1,'']]],
  ['outedgesiterator',['OutEdgesIterator',['../classTree_1_1OutEdgesIterator.html',1,'Tree']]],
  ['outerloopreuseblocking',['OuterLoopReuseBlocking',['../classOuterLoopReuseBlocking.html',1,'']]],
  ['outgoingedgesiterator',['OutgoingEdgesIterator',['../classDGraph_1_1OutgoingEdgesIterator.html',1,'DGraph']]],
  ['outputedges',['OutputEdges',['../classWalrusGraph_1_1OutputEdges.html',1,'WalrusGraph']]],
  ['outputlocalsymboltables',['OutputLocalSymbolTables',['../classSageInterface_1_1OutputLocalSymbolTables.html',1,'SageInterface']]],
  ['outputnodes',['OutputNodes',['../classWalrusGraph_1_1OutputNodes.html',1,'WalrusGraph']]],
  ['outputtarget',['OutputTarget',['../structSgNodeHelper_1_1Pattern_1_1OutputTarget.html',1,'SgNodeHelper::Pattern']]]
];
