var searchData=
[
  ['dag',['DAG',['../classDAG.html',1,'']]],
  ['dag_3c_20dagbasenodeimpl_2c_20dagbaseedgeimpl_20_3e',['DAG&lt; DAGBaseNodeImpl, DAGBaseEdgeImpl &gt;',['../classDAG.html',1,'']]],
  ['dagbaseedgeimpl',['DAGBaseEdgeImpl',['../classDAGBaseEdgeImpl.html',1,'']]],
  ['dagbasegraphimpl',['DAGBaseGraphImpl',['../classDAGBaseGraphImpl.html',1,'']]],
  ['dagbasenodeimpl',['DAGBaseNodeImpl',['../classDAGBaseNodeImpl.html',1,'']]],
  ['dagedge',['DAGEdge',['../classDAGEdge.html',1,'']]],
  ['dagedge_3c_20dagbasenodeimpl_2c_20dagbaseedgeimpl_20_3e',['DAGEdge&lt; DAGBaseNodeImpl, DAGBaseEdgeImpl &gt;',['../classDAGEdge.html',1,'']]],
  ['dagnode',['DAGNode',['../classDAGNode.html',1,'']]],
  ['dagnode_3c_20dagbasenodeimpl_2c_20dagbaseedgeimpl_20_3e',['DAGNode&lt; DAGBaseNodeImpl, DAGBaseEdgeImpl &gt;',['../classDAGNode.html',1,'']]],
  ['dagop',['DAGOP',['../classDAGOP.html',1,'']]],
  ['database_5ferror',['database_error',['../classsqlite3x_1_1database__error.html',1,'sqlite3x']]],
  ['datadependencegraph',['DataDependenceGraph',['../classDataDependenceGraph.html',1,'DataDependenceGraph'],['../classSDG_1_1DataDependenceGraph.html',1,'SDG::DataDependenceGraph']]],
  ['dataentry',['DataEntry',['../structBitVectorReprBase_1_1DataEntry.html',1,'BitVectorReprBase']]],
  ['dataflowanalysis',['DataFlowAnalysis',['../classDataFlowAnalysis.html',1,'']]],
  ['dataflowanalysis_3c_20reachingdefnode_2c_20reachingdefinitions_20_3e',['DataFlowAnalysis&lt; ReachingDefNode, ReachingDefinitions &gt;',['../classDataFlowAnalysis.html',1,'']]],
  ['dataflowcfgfilter',['DataflowCfgFilter',['../structssa__private_1_1DataflowCfgFilter.html',1,'ssa_private']]],
  ['dataflownode',['DataFlowNode',['../classDataFlowNode.html',1,'']]],
  ['dataflownode_3c_20reachingdefinitions_20_3e',['DataFlowNode&lt; ReachingDefinitions &gt;',['../classDataFlowNode.html',1,'']]],
  ['datamemberpointerstoir',['DataMemberPointersToIR',['../classAST__Graph_1_1DataMemberPointersToIR.html',1,'AST_Graph']]],
  ['dde_5fdata',['DDE_data',['../structDDE__data.html',1,'']]],
  ['ddfix',['DDFix',['../classDDFix.html',1,'']]],
  ['ddgedge',['DDGEdge',['../structSDG_1_1DDGEdge.html',1,'SDG']]],
  ['debuglog',['DebugLog',['../classDebugLog.html',1,'']]],
  ['declaration',['Declaration',['../structDeclaration.html',1,'']]],
  ['declaration_5fstruct',['Declaration_Struct',['../structDeclaration__Struct.html',1,'']]],
  ['declarationorcommentlistelement',['DeclarationOrCommentListElement',['../classMidLevelRewrite_1_1PrefixSuffixGenerationTraversal_1_1DeclarationOrCommentListElement.html',1,'MidLevelRewrite::PrefixSuffixGenerationTraversal']]],
  ['declarationsets',['DeclarationSets',['../classSageInterface_1_1DeclarationSets.html',1,'SageInterface']]],
  ['decompression',['Decompression',['../structSawyer_1_1Container_1_1Trace_1_1Decompression.html',1,'Sawyer::Container::Trace']]],
  ['decrement',['Decrement',['../structSawyer_1_1Container_1_1BitVectorSupport_1_1Decrement.html',1,'Sawyer::Container::BitVectorSupport']]],
  ['def',['Def',['../classSSA_1_1Def.html',1,'SSA']]],
  ['defaultallocator',['DefaultAllocator',['../classSawyer_1_1DefaultAllocator.html',1,'Sawyer']]],
  ['defaultbasicdominatortreeisstatementfilter',['DefaultBasicDominatorTreeIsStatementFilter',['../structDominatorTreesAndDominanceFrontiers_1_1DefaultBasicDominatorTreeIsStatementFilter.html',1,'DominatorTreesAndDominanceFrontiers']]],
  ['defaultcfgimpl',['DefaultCFGImpl',['../classDefaultCFGImpl.html',1,'']]],
  ['defaultduchain',['DefaultDUchain',['../classDefaultDUchain.html',1,'']]],
  ['defaultextraedgeinfo',['DefaultExtraEdgeInfo',['../structAstDOTGenerationExtended__Defaults_1_1DefaultExtraEdgeInfo.html',1,'AstDOTGenerationExtended_Defaults']]],
  ['defaultextraedgeoptions',['DefaultExtraEdgeOptions',['../structAstDOTGenerationExtended__Defaults_1_1DefaultExtraEdgeOptions.html',1,'AstDOTGenerationExtended_Defaults']]],
  ['defaultextranodeinfo',['DefaultExtraNodeInfo',['../structAstDOTGenerationExtended__Defaults_1_1DefaultExtraNodeInfo.html',1,'AstDOTGenerationExtended_Defaults']]],
  ['defaultextranodeoptions',['DefaultExtraNodeOptions',['../structAstDOTGenerationExtended__Defaults_1_1DefaultExtraNodeOptions.html',1,'AstDOTGenerationExtended_Defaults']]],
  ['defaultfilter',['DefaultFilter',['../structStaticCFG_1_1DefaultFilter.html',1,'StaticCFG']]],
  ['defaultfilterbinary',['defaultFilterBinary',['../structAST__Graph_1_1defaultFilterBinary.html',1,'AST_Graph']]],
  ['defaultfilterunary',['defaultFilterUnary',['../structAST__Graph_1_1defaultFilterUnary.html',1,'AST_Graph']]],
  ['defaultfunctiongenerator',['DefaultFunctionGenerator',['../classDefaultFunctionGenerator.html',1,'']]],
  ['defaulthandler',['DefaultHandler',['../structsg_1_1DefaultHandler.html',1,'sg']]],
  ['defaulthandler_3c_20const_20sgproject_20_3e',['DefaultHandler&lt; const SgProject &gt;',['../structsg_1_1DefaultHandler.html',1,'sg']]],
  ['defaultnodefunctional',['DefaultNodeFunctional',['../structAstQueryNamespace_1_1DefaultNodeFunctional.html',1,'AstQueryNamespace']]],
  ['defaulttraversalsuccessors',['DefaultTraversalSuccessors',['../structsg_1_1DefaultTraversalSuccessors.html',1,'sg']]],
  ['defblocksiterator',['DefBlocksIterator',['../classCFG_1_1DefBlocksIterator.html',1,'CFG']]],
  ['defect_5ft',['defect_t',['../structRose_1_1AST_1_1Defects_1_1defect__t.html',1,'Rose::AST::Defects']]],
  ['defect_5ft_3c_20kind_3a_3aany_20_3e',['defect_t&lt; Kind::any &gt;',['../structRose_1_1AST_1_1Defects_1_1defect__t_3_01Kind_1_1any_01_4.html',1,'Rose::AST::Defects']]],
  ['defect_5ft_3c_20kind_3a_3aintegrity_5fedges_20_3e',['defect_t&lt; Kind::integrity_edges &gt;',['../structRose_1_1AST_1_1Defects_1_1defect__t_3_01Kind_1_1integrity__edges_01_4.html',1,'Rose::AST::Defects']]],
  ['deferredtransformation',['DeferredTransformation',['../structSageInterface_1_1DeferredTransformation.html',1,'SageInterface']]],
  ['definevariabledescriptor',['DefineVariableDescriptor',['../classDefineVariableDescriptor.html',1,'']]],
  ['defining_5fname_5fstruct',['Defining_Name_Struct',['../structDefining__Name__Struct.html',1,'']]],
  ['definition',['Definition',['../classRosebud_1_1Ast_1_1Definition.html',1,'Rosebud::Ast']]],
  ['definition_5fstruct',['Definition_Struct',['../structDefinition__Struct.html',1,'']]],
  ['defsandusestraversal',['DefsAndUsesTraversal',['../classssa__private_1_1DefsAndUsesTraversal.html',1,'ssa_private::DefsAndUsesTraversal'],['../classVariableRenaming_1_1DefsAndUsesTraversal.html',1,'VariableRenaming::DefsAndUsesTraversal'],['../classssa__unfiltered__cfg_1_1DefsAndUsesTraversal.html',1,'ssa_unfiltered_cfg::DefsAndUsesTraversal']]],
  ['defuseanalysis',['DefUseAnalysis',['../classDefUseAnalysis.html',1,'']]],
  ['defuseanalysisabstract',['DefUseAnalysisAbstract',['../classDefUseAnalysisAbstract.html',1,'']]],
  ['defuseanalysispf',['DefUseAnalysisPF',['../classDefUseAnalysisPF.html',1,'']]],
  ['defusechain',['DefUseChain',['../classDefUseChain.html',1,'']]],
  ['defusechain_3c_20defusechainnode_20_3e',['DefUseChain&lt; DefUseChainNode &gt;',['../classDefUseChain.html',1,'']]],
  ['defusechain_3c_20valuepropagatenode_20_3e',['DefUseChain&lt; ValuePropagateNode &gt;',['../classDefUseChain.html',1,'']]],
  ['defusechainnode',['DefUseChainNode',['../classDefUseChainNode.html',1,'']]],
  ['deleteallnode',['DeleteAllNode',['../structRose_1_1AST_1_1IO_1_1DeleteAllNode.html',1,'Rose::AST::IO']]],
  ['deletedisconnectednode',['DeleteDisconnectedNode',['../structRose_1_1AST_1_1IO_1_1DeleteDisconnectedNode.html',1,'Rose::AST::IO']]],
  ['deleteemptyoperatornodes',['DeleteEmptyOperatorNodes',['../classDeleteEmptyOperatorNodes.html',1,'']]],
  ['deletenodeinfo',['DeleteNodeInfo',['../classDeleteNodeInfo.html',1,'']]],
  ['deletestmtloopinfo',['DeleteStmtLoopInfo',['../classDeleteStmtLoopInfo.html',1,'']]],
  ['deletingrootofnonsingletongraph',['DeletingRootOfNonSingletonGraph',['../classBaseGraph_1_1DeletingRootOfNonSingletonGraph.html',1,'BaseGraph']]],
  ['deletingrootofnonsingletontree',['DeletingRootOfNonSingletonTree',['../classTree_1_1DeletingRootOfNonSingletonTree.html',1,'Tree']]],
  ['denseintegerset',['DenseIntegerSet',['../classSawyer_1_1Container_1_1DenseIntegerSet.html',1,'Sawyer::Container']]],
  ['denseintegerset_3c_20size_5ft_20_3e',['DenseIntegerSet&lt; size_t &gt;',['../classSawyer_1_1Container_1_1DenseIntegerSet.html',1,'Sawyer::Container']]],
  ['depcompastref',['DepCompAstRef',['../structDepCompAstRef.html',1,'']]],
  ['depcompastrefanal',['DepCompAstRefAnal',['../classDepCompAstRefAnal.html',1,'']]],
  ['depcompastrefdag',['DepCompAstRefDAG',['../classDepCompAstRefDAG.html',1,'']]],
  ['depcompastrefgraphcreate',['DepCompAstRefGraphCreate',['../classDepCompAstRefGraphCreate.html',1,'']]],
  ['depcompastrefgraphnode',['DepCompAstRefGraphNode',['../classDepCompAstRefGraphNode.html',1,'']]],
  ['depcompcopyarraycollect',['DepCompCopyArrayCollect',['../classDepCompCopyArrayCollect.html',1,'']]],
  ['depcompcopyarraytobuffer',['DepCompCopyArrayToBuffer',['../classDepCompCopyArrayToBuffer.html',1,'']]],
  ['depcompdistributeloop',['DepCompDistributeLoop',['../classDepCompDistributeLoop.html',1,'']]],
  ['depedd',['DepEDD',['../classDepEDD.html',1,'']]],
  ['depeddrefinfo',['DepEDDRefInfo',['../classDepEDDRefInfo.html',1,'']]],
  ['depeddtypeinfo',['DepEDDTypeInfo',['../classDepEDDTypeInfo.html',1,'']]],
  ['dependenceentry',['DependenceEntry',['../classAstUtilInterface_1_1DependenceEntry.html',1,'AstUtilInterface']]],
  ['dependencegraph',['DependenceGraph',['../classDependenceGraph.html',1,'']]],
  ['dependencehoisting',['DependenceHoisting',['../classDependenceHoisting.html',1,'']]],
  ['dependencenode',['DependenceNode',['../classDependenceNode.html',1,'']]],
  ['dependencetable',['DependenceTable',['../classAstUtilInterface_1_1DependenceTable.html',1,'AstUtilInterface']]],
  ['dependencetesting',['DependenceTesting',['../classDependenceTesting.html',1,'']]],
  ['dependencyinfo',['DependencyInfo',['../classDependencyInfo.html',1,'']]],
  ['depgraphedgecreate',['DepGraphEdgeCreate',['../classDepGraphEdgeCreate.html',1,'']]],
  ['depinfo',['DepInfo',['../classDepInfo.html',1,'']]],
  ['depinfoalignloop',['DepInfoAlignLoop',['../classDepInfoAlignLoop.html',1,'']]],
  ['depinfoanal',['DepInfoAnal',['../classDepInfoAnal.html',1,'']]],
  ['depinfoanalinterface',['DepInfoAnalInterface',['../classDepInfoAnalInterface.html',1,'']]],
  ['depinfoedge',['DepInfoEdge',['../classDepInfoEdge.html',1,'']]],
  ['depinfoedgeconstinfoiterator',['DepInfoEdgeConstInfoIterator',['../classDepInfoEdgeConstInfoIterator.html',1,'']]],
  ['depinfogenerator',['DepInfoGenerator',['../classDepInfoGenerator.html',1,'']]],
  ['depinfographcreate',['DepInfoGraphCreate',['../classDepInfoGraphCreate.html',1,'']]],
  ['depinfographcreate_3c_20compslicedepgraphnode_20_3e',['DepInfoGraphCreate&lt; CompSliceDepGraphNode &gt;',['../classDepInfoGraphCreate.html',1,'']]],
  ['depinfographcreate_3c_20depcompastrefgraphnode_20_3e',['DepInfoGraphCreate&lt; DepCompAstRefGraphNode &gt;',['../classDepInfoGraphCreate.html',1,'']]],
  ['depinfographcreate_3c_20looptreedepgraphnode_20_3e',['DepInfoGraphCreate&lt; LoopTreeDepGraphNode &gt;',['../classDepInfoGraphCreate.html',1,'']]],
  ['depinfoimpl',['DepInfoImpl',['../classDepInfoImpl.html',1,'']]],
  ['depinfoinsertloop',['DepInfoInsertLoop',['../classDepInfoInsertLoop.html',1,'']]],
  ['depinfomergeloop',['DepInfoMergeLoop',['../classDepInfoMergeLoop.html',1,'']]],
  ['depinforemoveloop',['DepInfoRemoveLoop',['../classDepInfoRemoveLoop.html',1,'']]],
  ['depinforestrictdomain',['DepInfoRestrictDomain',['../classDepInfoRestrictDomain.html',1,'']]],
  ['depinfoset',['DepInfoSet',['../classDepInfoSet.html',1,'']]],
  ['depinfosetedge',['DepInfoSetEdge',['../classDepInfoSetEdge.html',1,'']]],
  ['depinfosetgenerator',['DepInfoSetGenerator',['../classDepInfoSetGenerator.html',1,'']]],
  ['depinfosetgraphcreate',['DepInfoSetGraphCreate',['../classDepInfoSetGraphCreate.html',1,'']]],
  ['depinfosetimpl',['DepInfoSetImpl',['../classDepInfoSetImpl.html',1,'']]],
  ['depinfoswaploop',['DepInfoSwapLoop',['../classDepInfoSwapLoop.html',1,'']]],
  ['deprel',['DepRel',['../classDepRel.html',1,'']]],
  ['depteststatistics',['DepTestStatistics',['../classDepTestStatistics.html',1,'']]],
  ['depthattr',['DepthAttr',['../classRoseHPCT_1_1DepthAttr.html',1,'RoseHPCT']]],
  ['depthfirstforwardedgetraversal',['DepthFirstForwardEdgeTraversal',['../classSawyer_1_1Container_1_1Algorithm_1_1DepthFirstForwardEdgeTraversal.html',1,'Sawyer::Container::Algorithm']]],
  ['depthfirstforwardgraphtraversal',['DepthFirstForwardGraphTraversal',['../classSawyer_1_1Container_1_1Algorithm_1_1DepthFirstForwardGraphTraversal.html',1,'Sawyer::Container::Algorithm']]],
  ['depthfirstforwardvertextraversal',['DepthFirstForwardVertexTraversal',['../classSawyer_1_1Container_1_1Algorithm_1_1DepthFirstForwardVertexTraversal.html',1,'Sawyer::Container::Algorithm']]],
  ['depthfirstreverseedgetraversal',['DepthFirstReverseEdgeTraversal',['../classSawyer_1_1Container_1_1Algorithm_1_1DepthFirstReverseEdgeTraversal.html',1,'Sawyer::Container::Algorithm']]],
  ['depthfirstreversegraphtraversal',['DepthFirstReverseGraphTraversal',['../classSawyer_1_1Container_1_1Algorithm_1_1DepthFirstReverseGraphTraversal.html',1,'Sawyer::Container::Algorithm']]],
  ['depthfirstreversevertextraversal',['DepthFirstReverseVertexTraversal',['../classSawyer_1_1Container_1_1Algorithm_1_1DepthFirstReverseVertexTraversal.html',1,'Sawyer::Container::Algorithm']]],
  ['depthfirsttraversaltag',['DepthFirstTraversalTag',['../classSawyer_1_1Container_1_1Algorithm_1_1DepthFirstTraversalTag.html',1,'Sawyer::Container::Algorithm']]],
  ['depthinheritedattribute',['DepthInheritedAttribute',['../classSgNode__depthOfSubtree_1_1DepthInheritedAttribute.html',1,'SgNode_depthOfSubtree']]],
  ['desc_5ft',['desc_t',['../structRose_1_1AST_1_1IO_1_1FunctionLinker_1_1desc__t.html',1,'Rose::AST::IO::FunctionLinker::desc_t'],['../structRose_1_1AST_1_1IO_1_1VariableLinker_1_1desc__t.html',1,'Rose::AST::IO::VariableLinker::desc_t'],['../structRose_1_1AST_1_1IO_1_1ClassLinker_1_1desc__t.html',1,'Rose::AST::IO::ClassLinker::desc_t']]],
  ['describe_5ffield_5ft',['describe_field_t',['../structRose_1_1Traits_1_1generated_1_1describe__field__t.html',1,'Rose::Traits::generated']]],
  ['describe_5ffield_5ft_3c_20nodet_2c_20fieldtypet_2c_20fld_5fptr_20_3e',['describe_field_t&lt; NodeT, FieldTypeT, fld_ptr &gt;',['../structRose_1_1Traits_1_1generated_1_1describe__field__t.html',1,'Rose::Traits::generated']]],
  ['describe_5fnode_5ft',['describe_node_t',['../structRose_1_1Traits_1_1generated_1_1describe__node__t.html',1,'Rose::Traits::generated']]],
  ['describefield',['DescribeField',['../structRose_1_1Traits_1_1DescribeField.html',1,'Rose::Traits']]],
  ['describefield_3c_20nodet_2c_20fieldtypet_20nodet_3a_3a_2a_2c_20fld_5fptr_20_3e',['DescribeField&lt; NodeT, FieldTypeT NodeT::*, fld_ptr &gt;',['../structRose_1_1Traits_1_1DescribeField_3_01NodeT_00_01FieldTypeT_01NodeT_1_1_5_00_01fld__ptr_01_4.html',1,'Rose::Traits']]],
  ['describefield_3c_20void_2c_20decltype_28nullptr_29_2c_20nullptr_20_3e',['DescribeField&lt; void, decltype(nullptr), nullptr &gt;',['../structRose_1_1Traits_1_1DescribeField_3_01void_00_01decltype_07nullptr_08_00_01nullptr_01_4.html',1,'Rose::Traits']]],
  ['describenode',['DescribeNode',['../structRose_1_1Traits_1_1DescribeNode.html',1,'Rose::Traits']]],
  ['describenode_3c_20void_20_3e',['DescribeNode&lt; void &gt;',['../structRose_1_1Traits_1_1DescribeNode_3_01void_01_4.html',1,'Rose::Traits']]],
  ['destination',['Destination',['../classSawyer_1_1Message_1_1Destination.html',1,'Sawyer::Message']]],
  ['detectmacroorincludefileexpansions',['DetectMacroOrIncludeFileExpansions',['../classDetectMacroOrIncludeFileExpansions.html',1,'']]],
  ['detectmacroorincludefileexpansionsinheritedattribute',['DetectMacroOrIncludeFileExpansionsInheritedAttribute',['../classDetectMacroOrIncludeFileExpansionsInheritedAttribute.html',1,'']]],
  ['detectmacroorincludefileexpansionssynthesizedattribute',['DetectMacroOrIncludeFileExpansionsSynthesizedAttribute',['../classDetectMacroOrIncludeFileExpansionsSynthesizedAttribute.html',1,'']]],
  ['detecttransformations',['DetectTransformations',['../classDetectTransformations.html',1,'']]],
  ['dfanalysis',['DFAnalysis',['../classDFAnalysis.html',1,'']]],
  ['dfastattribute',['DFAstAttribute',['../classCodeThorn_1_1DFAstAttribute.html',1,'CodeThorn']]],
  ['dfatodotimpl',['DfaToDotImpl',['../classVirtualCFG_1_1DfaToDotImpl.html',1,'VirtualCFG']]],
  ['dfsiterator',['DFSIterator',['../classCFG_1_1DFSIterator.html',1,'CFG::DFSIterator'],['../classBaseGraph_1_1DFSIterator.html',1,'BaseGraph::DFSIterator'],['../classDGraph_1_1DFSIterator.html',1,'DGraph::DFSIterator'],['../classGraph_1_1DFSIterator.html',1,'Graph::DFSIterator']]],
  ['dfsvisitor',['DFSVisitor',['../structSDG_1_1DFSVisitor.html',1,'SDG::DFSVisitor&lt; VertexT &gt;'],['../structStaticCFG_1_1DFSVisitor.html',1,'StaticCFG::DFSVisitor&lt; VertexT &gt;']]],
  ['dgbaseedgeimpl',['DGBaseEdgeImpl',['../classDGBaseEdgeImpl.html',1,'']]],
  ['dgbasegraphimpl',['DGBaseGraphImpl',['../classDGBaseGraphImpl.html',1,'']]],
  ['dgbasenodeimpl',['DGBaseNodeImpl',['../classDGBaseNodeImpl.html',1,'']]],
  ['dgraph',['DGraph',['../classDGraph.html',1,'']]],
  ['di',['DI',['../classDI.html',1,'']]],
  ['directededgeinterface',['DirectedEdgeInterface',['../classDirectedEdgeInterface.html',1,'']]],
  ['directedgraph',['DirectedGraph',['../classDirectedGraph.html',1,'']]],
  ['directedgraph_3c_20dagbasenodeimpl_2c_20dagbaseedgeimpl_20_3e',['DirectedGraph&lt; DAGBaseNodeImpl, DAGBaseEdgeImpl &gt;',['../classDirectedGraph.html',1,'']]],
  ['directedgraph_3c_20dgbasenodeimpl_2c_20dgbaseedgeimpl_20_3e',['DirectedGraph&lt; DGBaseNodeImpl, DGBaseEdgeImpl &gt;',['../classDirectedGraph.html',1,'']]],
  ['directedgraph_3c_20node_2c_20edge_20_3e',['DirectedGraph&lt; Node, Edge &gt;',['../classDirectedGraph.html',1,'']]],
  ['directedgraphedge',['DirectedGraphEdge',['../classDirectedGraphEdge.html',1,'']]],
  ['directedgraphedge_3c_20dagbasenodeimpl_2c_20dagbaseedgeimpl_20_3e',['DirectedGraphEdge&lt; DAGBaseNodeImpl, DAGBaseEdgeImpl &gt;',['../classDirectedGraphEdge.html',1,'']]],
  ['directedgraphedge_3c_20dgbasenodeimpl_2c_20dgbaseedgeimpl_20_3e',['DirectedGraphEdge&lt; DGBaseNodeImpl, DGBaseEdgeImpl &gt;',['../classDirectedGraphEdge.html',1,'']]],
  ['directedgraphnode',['DirectedGraphNode',['../classDirectedGraphNode.html',1,'']]],
  ['directedgraphnode_3c_20dagbasenodeimpl_2c_20dagbaseedgeimpl_20_3e',['DirectedGraphNode&lt; DAGBaseNodeImpl, DAGBaseEdgeImpl &gt;',['../classDirectedGraphNode.html',1,'']]],
  ['directedgraphnode_3c_20dgbasenodeimpl_2c_20dgbaseedgeimpl_20_3e',['DirectedGraphNode&lt; DGBaseNodeImpl, DGBaseEdgeImpl &gt;',['../classDirectedGraphNode.html',1,'']]],
  ['directive',['Directive',['../structRosebud_1_1Ast_1_1CppStack_1_1Directive.html',1,'Rosebud::Ast::CppStack']]],
  ['disassembler',['Disassembler',['../structDisassembler.html',1,'']]],
  ['disassembleramd64',['DisassemblerAmd64',['../structDisassemblerAmd64.html',1,'']]],
  ['disassemblerarm',['DisassemblerArm',['../structDisassemblerArm.html',1,'']]],
  ['disassemblercoldfire',['DisassemblerColdFire',['../structDisassemblerColdFire.html',1,'']]],
  ['disassembleri386',['DisassemblerI386',['../structDisassemblerI386.html',1,'']]],
  ['disassemblerm68k',['DisassemblerM68k',['../structDisassemblerM68k.html',1,'']]],
  ['disassemblermips',['DisassemblerMips',['../structDisassemblerMips.html',1,'']]],
  ['disassemblerpowerpc',['DisassemblerPowerpc',['../structDisassemblerPowerpc.html',1,'']]],
  ['dispatcher',['Dispatcher',['../structRose_1_1Traits_1_1traversal__details_1_1Dispatcher.html',1,'Rose::Traits::traversal_details']]],
  ['dispatchhandler',['DispatchHandler',['../structsg_1_1DispatchHandler.html',1,'sg']]],
  ['dispatchhandler_3c_20bool_20_3e',['DispatchHandler&lt; bool &gt;',['../structsg_1_1DispatchHandler.html',1,'sg']]],
  ['dispatchhandler_3c_20sagenode_20_2a_3e',['DispatchHandler&lt; SageNode *&gt;',['../structsg_1_1DispatchHandler.html',1,'sg']]],
  ['dispatchhandler_3c_20sgexpression_20_2a_3e',['DispatchHandler&lt; SgExpression *&gt;',['../structsg_1_1DispatchHandler.html',1,'sg']]],
  ['dispatchhandler_3c_20sgnodeptrlist_20_3e',['DispatchHandler&lt; SgNodePtrList &gt;',['../structsg_1_1DispatchHandler.html',1,'sg']]],
  ['dispatchhandler_3c_20sgstatement_20_2a_3e',['DispatchHandler&lt; SgStatement *&gt;',['../structsg_1_1DispatchHandler.html',1,'sg']]],
  ['dispatchhandler_3c_20std_3a_3apair_3c_20sgtype_20_2a_2c_20sgtype_20_2a_3e_20_3e',['DispatchHandler&lt; std::pair&lt; SgType *, SgType *&gt; &gt;',['../structsg_1_1DispatchHandler.html',1,'sg']]],
  ['dispatchhelper',['DispatchHelper',['../structsg_1_1DispatchHelper.html',1,'sg']]],
  ['displaycallgraph',['DisplayCallGraph',['../classDisplayCallGraph.html',1,'']]],
  ['displayedge',['DisplayEdge',['../classDisplayEdge.html',1,'']]],
  ['displaygraph',['DisplayGraph',['../classDisplayGraph.html',1,'']]],
  ['displaygraphnode',['DisplayGraphNode',['../classDisplayGraphNode.html',1,'']]],
  ['displaynode',['DisplayNode',['../classDisplayNode.html',1,'']]],
  ['displaytreegenerator',['DisplayTreeGenerator',['../classDisplayTreeGenerator.html',1,'']]],
  ['displaytreenode',['DisplayTreeNode',['../classDisplayTreeNode.html',1,'']]],
  ['distinctlist',['DistinctList',['../classSawyer_1_1Container_1_1DistinctList.html',1,'Sawyer::Container']]],
  ['distnodeinfo',['DistNodeInfo',['../classDistNodeInfo.html',1,'']]],
  ['distributeddotgraph',['DistributedDotGraph',['../classDistributedDotGraph.html',1,'']]],
  ['distributedmemoryanalysisposttraversal',['DistributedMemoryAnalysisPostTraversal',['../classDistributedMemoryAnalysisPostTraversal.html',1,'']]],
  ['distributedmemoryanalysispretraversal',['DistributedMemoryAnalysisPreTraversal',['../classDistributedMemoryAnalysisPreTraversal.html',1,'']]],
  ['distributedprogramverifier',['DistributedProgramVerifier',['../classDistributedProgramVerifier.html',1,'']]],
  ['distributevisitor',['DistributeVisitor',['../classDistributeVisitor.html',1,'']]],
  ['doesnotexist',['DoesNotExist',['../classSawyer_1_1Attribute_1_1DoesNotExist.html',1,'Sawyer::Attribute']]],
  ['dog',['Dog',['../classDog.html',1,'']]],
  ['domaincond',['DomainCond',['../classDomainCond.html',1,'']]],
  ['domaincondalignloop',['DomainCondAlignLoop',['../classDomainCondAlignLoop.html',1,'']]],
  ['domaincondinsertloop',['DomainCondInsertLoop',['../classDomainCondInsertLoop.html',1,'']]],
  ['domaincondmergeloop',['DomainCondMergeLoop',['../classDomainCondMergeLoop.html',1,'']]],
  ['domaincondremoveloop',['DomainCondRemoveLoop',['../classDomainCondRemoveLoop.html',1,'']]],
  ['domaincondswaploop',['DomainCondSwapLoop',['../classDomainCondSwapLoop.html',1,'']]],
  ['domainerror',['DomainError',['../classSawyer_1_1Exception_1_1DomainError.html',1,'Sawyer::Exception']]],
  ['domaininfo',['DomainInfo',['../classDomainInfo.html',1,'']]],
  ['domaininfoimpl',['DomainInfoImpl',['../classDomainInfoImpl.html',1,'']]],
  ['domainvisitor',['DomainVisitor',['../classqrs_1_1DomainVisitor.html',1,'qrs']]],
  ['domestic',['Domestic',['../classDomestic.html',1,'']]],
  ['domfrontiterator',['DomFrontIterator',['../classDomTree_1_1DomFrontIterator.html',1,'DomTree']]],
  ['dominancefrontier',['DominanceFrontier',['../classDominatorTreesAndDominanceFrontiers_1_1DominanceFrontier.html',1,'DominatorTreesAndDominanceFrontiers']]],
  ['dominantarginfo',['DominantArgInfo',['../structSageInterface_1_1Ada_1_1DominantArgInfo.html',1,'SageInterface::Ada']]],
  ['dominatorforwardbackwardwrapperclass',['DominatorForwardBackwardWrapperClass',['../classDominatorTreesAndDominanceFrontiers_1_1DominatorForwardBackwardWrapperClass.html',1,'DominatorTreesAndDominanceFrontiers']]],
  ['dominatortree',['DominatorTree',['../classDominatorTreesAndDominanceFrontiers_1_1DominatorTree.html',1,'DominatorTreesAndDominanceFrontiers']]],
  ['domtree',['DomTree',['../classDomTree.html',1,'']]],
  ['dopreoneachfunctionvisitor',['DoPreOnEachFunctionVisitor',['../classlegacy_1_1DoPreOnEachFunctionVisitor.html',1,'legacy']]],
  ['dorewriteruledeepvisitor',['DoRewriteRuleDeepVisitor',['../classDoRewriteRuleDeepVisitor.html',1,'']]],
  ['dosextendedheader_5fdisk',['DOSExtendedHeader_disk',['../structSgAsmDOSExtendedHeader_1_1DOSExtendedHeader__disk.html',1,'SgAsmDOSExtendedHeader']]],
  ['dosfileheader_5fdisk',['DOSFileHeader_disk',['../structSgAsmDOSFileHeader_1_1DOSFileHeader__disk.html',1,'SgAsmDOSFileHeader']]],
  ['dosrelocentry_5fdisk',['DOSRelocEntry_disk',['../structSgAsmDOSFileHeader_1_1DOSRelocEntry__disk.html',1,'SgAsmDOSFileHeader']]],
  ['dotgeneration',['DOTGeneration',['../classDOTGeneration.html',1,'']]],
  ['dotgeneration_3c_20sgnode_20_2a_3e',['DOTGeneration&lt; SgNode *&gt;',['../classDOTGeneration.html',1,'']]],
  ['dotgraphedge',['DOTGraphEdge',['../classDOTGraphEdge.html',1,'']]],
  ['dotgraphinterface',['DOTGraphInterface',['../classDOTGraphInterface.html',1,'']]],
  ['dotgraphnode',['DOTGraphNode',['../classDOTGraphNode.html',1,'']]],
  ['dotgraphposttraversal',['DotGraphPostTraversal',['../classDotGraphPostTraversal.html',1,'']]],
  ['dotinheritedattribute',['DOTInheritedAttribute',['../classDOTInheritedAttribute.html',1,'']]],
  ['dotprinter',['DotPrinter',['../structdot_1_1DotPrinter.html',1,'dot']]],
  ['dotrepresentation',['DOTRepresentation',['../classDOTRepresentation.html',1,'']]],
  ['dotrepresentation_3c_20node_20_3e',['DOTRepresentation&lt; Node &gt;',['../classDOTRepresentation.html',1,'']]],
  ['dotrepresentation_3c_20sgnode_20_2a_3e',['DOTRepresentation&lt; SgNode *&gt;',['../classDOTRepresentation.html',1,'']]],
  ['dotrepresentation_3c_20std_3a_3astring_20_3e',['DOTRepresentation&lt; std::string &gt;',['../classDOTRepresentation.html',1,'']]],
  ['dotrepresentation_3c_20vertex_20_2a_20_3e',['DOTRepresentation&lt; vertex * &gt;',['../classDOTRepresentation.html',1,'']]],
  ['dotsubgraphrepresentation',['DOTSubgraphRepresentation',['../classDOTSubgraphRepresentation.html',1,'']]],
  ['dotsubgraphrepresentation_3c_20std_3a_3astring_20_3e',['DOTSubgraphRepresentation&lt; std::string &gt;',['../classDOTSubgraphRepresentation.html',1,'']]],
  ['dotsubgraphrepresentation_3c_20vertex_20_2a_20_3e',['DOTSubgraphRepresentation&lt; vertex * &gt;',['../classDOTSubgraphRepresentation.html',1,'']]],
  ['dotsynthesizedattribute',['DOTSynthesizedAttribute',['../classDOTSynthesizedAttribute.html',1,'']]],
  ['dotvisualizer',['DotVisualizer',['../classDotVisualizer.html',1,'']]],
  ['doublylinkedentrywrap',['DoublyLinkedEntryWrap',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20dagbaseedgeimpl_20_2a_3e',['DoublyLinkedEntryWrap&lt; DAGBaseEdgeImpl *&gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20dagbasenodeimpl_20_2a_3e',['DoublyLinkedEntryWrap&lt; DAGBaseNodeImpl *&gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20dataentry_20_3e',['DoublyLinkedEntryWrap&lt; DataEntry &gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20depcompcopyarraycollect_3a_3acopyarrayunit_20_3e',['DoublyLinkedEntryWrap&lt; DepCompCopyArrayCollect::CopyArrayUnit &gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20depinfo_20_3e',['DoublyLinkedEntryWrap&lt; DepInfo &gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20dgbaseedgeimpl_20_2a_3e',['DoublyLinkedEntryWrap&lt; DGBaseEdgeImpl *&gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20dgbasenodeimpl_20_2a_3e',['DoublyLinkedEntryWrap&lt; DGBaseNodeImpl *&gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20domaincond_20_3e',['DoublyLinkedEntryWrap&lt; DomainCond &gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20edge_20_2a_3e',['DoublyLinkedEntryWrap&lt; Edge *&gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20looptreenode_20_2a_3e',['DoublyLinkedEntryWrap&lt; LoopTreeNode *&gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20node_20_2a_3e',['DoublyLinkedEntryWrap&lt; Node *&gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20nodeimpl_20_2a_3e',['DoublyLinkedEntryWrap&lt; NodeImpl *&gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20symbolicterm_20_3e',['DoublyLinkedEntryWrap&lt; SymbolicTerm &gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedentrywrap_3c_20t_20_2a_3e',['DoublyLinkedEntryWrap&lt; T *&gt;',['../classDoublyLinkedEntryWrap.html',1,'']]],
  ['doublylinkedlistwrap',['DoublyLinkedListWrap',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20dagbaseedgeimpl_20_2a_3e',['DoublyLinkedListWrap&lt; DAGBaseEdgeImpl *&gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20dagbasenodeimpl_20_2a_3e',['DoublyLinkedListWrap&lt; DAGBaseNodeImpl *&gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20dataentry_20_3e',['DoublyLinkedListWrap&lt; DataEntry &gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20depcompcopyarraycollect_3a_3acopyarrayunit_20_3e',['DoublyLinkedListWrap&lt; DepCompCopyArrayCollect::CopyArrayUnit &gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20depinfo_20_3e',['DoublyLinkedListWrap&lt; DepInfo &gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20dgbaseedgeimpl_20_2a_3e',['DoublyLinkedListWrap&lt; DGBaseEdgeImpl *&gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20dgbasenodeimpl_20_2a_3e',['DoublyLinkedListWrap&lt; DGBaseNodeImpl *&gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20domaincond_20_3e',['DoublyLinkedListWrap&lt; DomainCond &gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20edge_20_2a_3e',['DoublyLinkedListWrap&lt; Edge *&gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20looptreenode_20_2a_3e',['DoublyLinkedListWrap&lt; LoopTreeNode *&gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20node_20_2a_3e',['DoublyLinkedListWrap&lt; Node *&gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20nodeimpl_20_2a_3e',['DoublyLinkedListWrap&lt; NodeImpl *&gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20symbolicterm_20_3e',['DoublyLinkedListWrap&lt; SymbolicTerm &gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['doublylinkedlistwrap_3c_20t_20_2a_3e',['DoublyLinkedListWrap&lt; T *&gt;',['../classDoublyLinkedListWrap.html',1,'']]],
  ['driver',['Driver',['../classRose_1_1CodeGen_1_1Driver.html',1,'Rose::CodeGen']]],
  ['driveroptions',['DriverOptions',['../structDriverOptions.html',1,'']]],
  ['ds',['DS',['../classDS.html',1,'']]],
  ['dummyfilter',['dummyFilter',['../structdummyFilter.html',1,'']]],
  ['dummyistestquery1',['DummyISTestQuery1',['../classDummyISTestQuery1.html',1,'']]],
  ['dummyistestquery2',['DummyISTestQuery2',['../classDummyISTestQuery2.html',1,'']]],
  ['dummyistestquery3',['DummyISTestQuery3',['../classDummyISTestQuery3.html',1,'']]],
  ['dummyitestquery1',['DummyITestQuery1',['../classDummyITestQuery1.html',1,'']]],
  ['dummyitestquery2',['DummyITestQuery2',['../classDummyITestQuery2.html',1,'']]],
  ['dummyitestquery3',['DummyITestQuery3',['../classDummyITestQuery3.html',1,'']]],
  ['dummystestquery1',['DummySTestQuery1',['../classDummySTestQuery1.html',1,'']]],
  ['dummystestquery2',['DummySTestQuery2',['../classDummySTestQuery2.html',1,'']]],
  ['dummystestquery3',['DummySTestQuery3',['../classDummySTestQuery3.html',1,'']]],
  ['dummytestquery1',['DummyTestQuery1',['../classDummyTestQuery1.html',1,'']]],
  ['dummytestquery2',['DummyTestQuery2',['../classDummyTestQuery2.html',1,'']]],
  ['dummytestquery3',['DummyTestQuery3',['../classDummyTestQuery3.html',1,'']]],
  ['dumppoolinfo',['DumpPoolInfo',['../structRose_1_1MemPool_1_1DumpPoolInfo.html',1,'Rose::MemPool']]],
  ['dupinfovisitor',['DupInfoVisitor',['../classDupInfoVisitor.html',1,'']]],
  ['duplicateedge',['DuplicateEdge',['../classBaseGraph_1_1DuplicateEdge.html',1,'BaseGraph::DuplicateEdge'],['../classTree_1_1DuplicateEdge.html',1,'Tree::DuplicateEdge']]],
  ['duplicatenode',['DuplicateNode',['../classBaseGraph_1_1DuplicateNode.html',1,'BaseGraph::DuplicateNode'],['../classTree_1_1DuplicateNode.html',1,'Tree::DuplicateNode']]],
  ['durationparser',['DurationParser',['../classRose_1_1CommandLine_1_1DurationParser.html',1,'Rose::CommandLine']]],
  ['dynamiccompslice',['DynamicCompSlice',['../classDynamicCompSlice.html',1,'']]],
  ['dynamiccompsliceimpl',['DynamicCompSliceImpl',['../classDynamicCompSliceImpl.html',1,'']]],
  ['dynamicslicing',['DynamicSlicing',['../classDynamicSlicing.html',1,'']]],
  ['dynamictuning',['DynamicTuning',['../classDynamicTuning.html',1,'']]]
];
